### PR TITLE
Minimize unsafe C functions usage - replace strcat() and strcpy() (and strncat() and strncpy()) with custom safe_strcat() and safe_strcpy() functions. Part one.

### PR DESCRIPTION
**Pull request by Chaloff**
Minimize unsafe C functions usage - replace strcat() and strcpy() with strncat() and strncpy(). Part one.

 ## Description
The MariaDB code base uses strcat() and strcpy() in several
places. These are known to have memory safety issues and their usage is
discouraged. Common security scanners like Flawfinder flags them. In MariaDB we
should start using modern and safer variants on these functions.

Those changes continue the similar memory issues fixes started at
[8298d32](https://github.com/MariaDB/server/pull/2210/commits/8298d32d8ef9b2207f267ff6e308c43450d2a97e) and
[19af189](https://github.com/MariaDB/server/commit/19af1890b56c6c147c296479bb6a4ad00fa59dbb).
Now we are taking care of some of the usage of strcat() and strcpy(). We are
replacing them with the safer options - strncat() and strncpy() but since these
2 functions also have well known disadvantages - it's not guaranteed what new
string will be null-terminated - we are adding '\0' forcefully to make sure the
result string is correct:
```
size_t dest_len = sizeof(g->Message);
strncpy(g->Message, "Null json tree", dest_len); strncat(g->Message, ":",
sizeof(g->Message) - strlen(g->Message)); size_t wrote_sz = strlen(g->Message);
size_t cur_len = wrote_sz >= dest_len ? dest_len - 1 : wrote_sz;
g->Message[cur_len] = '\0';
```

We would like to provide 2-3 smaller size changes to make code review and
merge easier. Next part will follow.

All build stages pass for these commits. For the
commit without the intentional bug, mysql-test-run is properly passing. The
changes do not change the functionality itself they just replace unsafe C
methods with the safe ones.

- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

The changes are fully backward compatible.

All new code of the whole pull request, including one or several files
that are either new files or modified ones, are contributed under the BSD-new
license. I am contributing on behalf of my employer Amazon Web Services,
Inc.

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @Chaloff !

The idea of the PR is sound, however the implementation leaves much to be desired unfortunately.

There are a couple of problems here:
1. The code doesn't actually compile as you can see from the github checks ran through buildbot.mariadb.org.
2. There is a lot of code duplication and the purpose of the code is obscured by a lot of boilerplate checking for lengths, when to override the ending character, etc.
3. Nit: You are also mixing tabs with spaces. Please use only 2 spaces for indentation.

Here is how I suggest you go about this change:

Let's refactor the duplicate code into a set of functions. The prototype I propose at the moment is this:
`const char *safe_strcpy(char *dst, size_t dst_size, char *src, size_t src_len)`
and
`const char *safe_strcat(char *dst, size_t dst_size, char *src, size_t src_len) `

I believe you should be able to place 95% of the logic within these functions and only call these within the codebase. Can you give it a try and see how the resulting patch looks like?

I'm happy to review that and iterate.
Vicențiu

**Comment by ericherman** [comment]
While doing so, it would be good to review the docs for `strlcpy` and `strlcat`, the BSD versions of size-bounded string copying and concatenation ( https://www.freebsd.org/cgi/man.cgi?query=strlcat ) as the docs highlight how even `stncat` and `strncopy` can be easily misused.

**Comment by Chaloff** [comment]
@cvicentiu   @ericherman  Thank you for the comments. What you suggested I basically tried to do in [this PR](https://github.com/MariaDB/server/pull/2233). I tried to adopt `strlcpy()` & `strlcat()` to MariaDB. That change was rejected and I understand why.
Will create new functions as suggested (`*safe_strcpy()` and `*safe_strcat()`) using the same code pattern I use in current PR

**Comment by ericherman** [comment]
@Chaloff I was unaware of PR https://github.com/MariaDB/server/pull/2233 ; I am sorry if I came across as "talking down" when you've obviously already been in a long discussion about the variations on implementations of these operations, including some comments regarding the kernel's own [strscpy]( https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/lib/string.c?h=v6.0.14#n175 ). 

As @cvicentiu suggests, some sort of function with clearly defined usage is in order. Later, as we wrestle with the best way to implement the specifics, at least the internals will be all in one place. I think this is wise.

@cvicentiu in your proposed function signature, the return type is `const char *`, if that is a pointer to `char *dest` on success, then why `const`? Also, I assume on failure the value returned in `NULL`, and the error is assumed to be "too big to fit", is that correct?

**Comment by Chaloff** [comment]
> @Chaloff I was unaware of PR #2233 ; I am sorry if I came across as "talking down" when you've obviously already been in a long discussion about the variations on implementations of these operations, including some comments regarding the kernel's own [strscpy](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/lib/string.c?h=v6.0.14#n175).
> 
> As @cvicentiu suggests, some sort of function with clearly defined usage is in order. Later, as we wrestle with the best way to implement the specifics, at least the internals will be all in one place. I think this is wise.
> 
> @cvicentiu in your proposed function signature, the return type is `const char *`, if that is a pointer to `char *dest` on success, then why `const`? Also, I assume on failure a `NULL` is returned, and the error is assumed to be "too big to fit", is that correct?

@ericherman Thanks! I personally agree with the proposal to have return type `char *` not a `const char *` - exactly as in `strspy/strncpy` and `strcat/strncat`. I would go with it. About returning `nullptr` in case of failure - should we really do it? I would propose the same logic as in `strncpy/strlcpy` and `strncat/strlcat `- just copy/add no more than `dst_size` characters, with only one exception - always add '\0' at the end. In case the size of source is bigger than `dst_size` we can write an warning to `stderr` but still return result. What do you think about it?

**Comment by Chaloff** [comment]
Can somebody review it again, please?

**Comment by ericherman** [comment]
> About returning `nullptr` in case of failure - should we really do it? I would propose the same logic as in `strncpy/strlcpy` and `strncat/strlcat `- just copy/add no more than `dst_size` characters, with only one exception - always add '\0' at the end. In case the size of source is bigger than `dst_size` we can write an warning to `stderr` but still return result. What do you think about it?

In some cases it might be okay to proceed with a truncated string, in other cases this is an error that the caller should act upon. Simply printing an error message to stderr does not provide the caller the ability to check for success or failure.

Given that we pass in `char *dest`, if that is always null-terminated regardless of success or failure (if `dest_size` is greater than 0), means that the pointer we passed in is, indeed, null terminated, and the returned value can be used to determine the success or failure. In my mind, `nullptr` on failure is easy to check for the caller, and the caller can act accordingly. 

I'm not certain what  @cvicentiu had in mind for the return value. Rather than simply returning `dest`, a possible return value would be a pointer to the _end_ of `dest`, where the NULL terminator was written, which would allow the caller to subtract for the number of characters copied, and possibly more easily append additional characters to the buffer.

**Comment by Chaloff** [comment]
> 
> In some cases it might be okay to proceed with a truncated string, in other cases this is an error that the caller should act upon. Simply printing an error message to stderr does not provide the caller the ability to check for success or failure.
> 
> Given that we pass in `char *dest`, if that is always null-terminated regardless of success or failure (if `dest_size` is greater than 0), means that the pointer we passed in is, indeed, null terminated, and the returned value can be used to determine the success or failure. In my mind, `nullptr` on failure is easy to check for the caller, and the caller can act accordingly.
> 
> I'm not certain what @cvicentiu had in mind for the return value. Rather than simply returning `dest`, a possible return value would be a pointer to the _end_ of `dest`, where the NULL terminator was written, which would allow the caller to subtract for the number of characters copied, and possibly more easily append additional characters to the buffer.

@ericherman thank you for the comment. I see your point it definitely have sense. My concern here is - I wanted to do methods with the same interface as `strcpy()` and `strcat()` (also `strncpy()` and `strncat()`) and with almost the same functionality - they should do the same but be safe.
This allows users to use `safe_strcpy()` and `safe_strcat()` the same way they are using old C-functions. In most of the cases it's possible simply replace old C-functions with the new safe_ ones with only one change - 3rd parameter should be the size of destination array.

I agree what writing to `stderr` is not very informative - will remove it.

But despite returning `nullptr` or pointer to `NULL` terminator can be really useful for some cases the problem here that for the many of users this behaviour will be unexpected:
You can't use safely anymore tuples of `strcat()` + `strcpy() `functions like that:
`strcat(strcat(strcpy(dest_str, source1_str), source2_str), source_last_str);`
since if one of this function calls return `nullptr` we'll get undefined behaviour.
And we have a lot of such or similar syntax in MariaDB.
I just assume that user will be confused and rather not willing to use new safe_ function or misused them from time to time creating even more problems here.

I would like to propose instead of it - return NULL terminated string (correct or truncated) - as it is now. In case of an error (destination size is smaller than source) use another parameter `int error_code` and set it to `1`. Also check this parameter in safe_strcpy() and safe_strcat() just not to proceed in the tuples in case of error. So the usage will look like that:
```
char *safe_strcpy(char *dst, const char *src, size_t dst_size, int &error_code){
  if(!error_code) {
  ...
  if(overflow) error_code = 1;
  }
}
//the same for safe_strcat()
...
int my_ec = 0;
size_t sz = sizeof(dest_str);
safe_strcat(safe_strcat(safe_strcpy(dest_str, source1_str, sz, my_ec), source2_str sz, my_ec), source_last_str sz, my_ec);
if(my_ec != 0){
//process the error
}
```
Al this just a suggestion - will implement it shortly and would like to know you opinion

**Comment by vaintroub** [comment]
I'd like to remind of standard safe versions of strcpy etc (strcpy_s, sprintf_s ).  they could be taken into consideration, before jumping into implementing own stuff. They do not offer chaining,  but , they offer return code. They are not implemented in glibc yet, but  effort to implement function with standard signature, is the same  as any NIH version.

**Comment by Chaloff** [comment]
> I'd like to remind of standard safe versions of strcpy etc (strcpy_s, sprintf_s ). they could be taken into consideration, before jumping into implementing own stuff. They do not offer chaining, but , they offer return code. They are not implemented in glibc yet, but effort to implement function with standard signature, is the same as any NIH version.

I'm agree - _s functions must be used instead of all all methods we are using now. The problem here is - we do not know when they are arrive and most probably it's not going to happen soon.

**Comment by ericherman** [comment]
> > Perhaps `strcpy_s` is the interface to use, but that doesn't seem the direction @cvicentiu was leaning.
> 
> @ericherman thanks! This make sense - when `_s` functions arrive we can easily find/replace our custom `safe_` functions with the new ` _s` functions. So I can leave it as it implemented now or re-implement using `strcpy_s, sprintf_s `. What is your opinion - what is a better way to proceed?

Personally, I do not think the `_s` functions will be widely supported as Annex K, where they were introduced, will be likely go away, thus I would place conforming to that interface at high priority. I do not have a strong opinion about the best interface, simply that it should be possible to check the error -- by return value or by an `int *err` param would both work. Personally, I would prioritise a function signature which is the nicest for the calling code to use, and I expect that is the angle @cvicentiu was coming from. And obviously, as long as the code is centralized, the internals can easily change to become whatever makes the most sense over time, even perhaps becoming just a thin wrapper for more standard `_s`-like functions if something like those arrive in the future.

**Comment by cvicentiu** [comment]
Apologies for not replying earlier. 

I have started working on this yesterday and should be ready by the end of the day. Yes, the angle I have is to make the code readable with the functions not being overly verbose. I am now writing a few changes I'd like incorporated. I think that would speed up the process instead of going back and forth. 

I'll come back to you by the end of the day or tomorrow.

**Review by cvicentiu — COMMENTED** [review]
Thank you for this patch. I have taken this code and have modified it to what I believe should be its final form. Below I will explain my reasoning.

# Commit structure
First of all, please make sure you perform a rebase, not a merge with the latest branch. In this PR and subsequent ones you have 2 commits within the pull request. One is the actual patch, while the other is a merge commit, where you merge 10.3 *into* your branch. That is not correct and the merge commit will be meaningless if I am to actually press the "merge" button on github.

Pull requests should be a simple fast-forward of the branch they are intended to land on.

Correct way to rebase (if working on top of 10.3 branch):

```bash
git fetch upstream/10.3  # This assumes upstream is github.com/MariaDB/server
git rebase upstream/10.3
git push --force 10.3-strcat-strcpy_fix
```

Please amend all your other open PRs that have the same issue.

# Unneded changes

- `extra/readline/display.c` -> This change should not be present in this commit at all.
- Storing `sizeof(X)` within a variable (`size_t X_sz`). This change doesn't help readability as it adds an extra variable while only saving 4 characters for each use. sizeof(X) is a compile time constant so this is not a performance optimization. Only store the size if it is a computation of values. For example `size_t buff_sz = strlen(name) + strlen(value) + 2;`

# API decision
- I have benchmarked the safe_strxxx variants that are proposed in my final patch. The safe version is between 1 - 10% slower on inputs of various size (10 bytes, 128 bytes, 1Mb, 10Mb)
- Most of the call sites are not on the hot path so the performance degradation is not important.
- The `strxxx_s` variants of these functions is overly complex, with hooks for callback handlers for various error conditions. Those lead to worse performance then our home brewed version. Nonetheless, the variant that works the best is to actually use that function signature. **As such,  the `safe_strxxx` functions will be of the form `f(dst, dst_size, src)`**
- One other thing to note about the error_code and chaining idea:
- The error_code being both and input and output parameter is "surprising". I also believe it introduces clutter. Chaining of strxxx functions is a bad idea in the current form as `strcat` is completely ridiculous in returning the first argument as a return value. Even cppreference advises *not* to chain strcats. Having an extra parameter for this use case seems unnecesarily verbose and complicates the call sites.
- Furthermore, the code you propose doesn't actually make use of the error_code at all for error handling. This plus the previous point lead me to the conclusion to abandon this idea.

# Functions implementation
First I will discuss general code style aspects, then dive into the implementation details.
## Coding style
- Prefer reducing indent level with the use of early `return` statements (or in special circumstances `goto`). Rather than:
```c++
if (condition)
{
   <logic>
}
return error_code;
```
Use:
```c++
if (!condition)
  return error_code;
<logic>
return success;
```
- For this codebase, an if statement must be of the form:
```c++
if (<condition>)
  single-line-statement
else
  single-line-statement
```
or
```c++
if (<condition>)
{
  multi-line-statement
}
else
{
  multi-line-statement
}
````
- One space after the `if` keyword.
- No space before assignment operator.
```c++
a= 1;  // Correct
a = 1; // Incorrect for the server code,
       // ok for Storage Engines if they use it (aka Connect)
```
- Please do not write conditions like so:
```c++
if (0 == *error_code)
```
This reads **very unnatural**. You will not find this coding style in the codebase. Prefer
```c++
if (*error_code == 0)
// Or even better
if (!*error_code)
```
- Multi-line comments are always written like so:
```c++
/*
  A multi line comment starts on the next line following the opening comment sequence.
  Indent it by two spaces. Close the comment on a new line, no indentation. Ideally, use proper
  punctuation, capital letters, etc. Finish statements with a period.
*/
```
- Single line comments can use `//`, but please put a space after `//`. This improves readability.
- Unless strictly necessary, do not go over 80 characters with your code. There are some exceptions in connect storage engine, but seek to be consistent.
## Function logic
- There is a serious flaw in the function's logic when it encounters the error case, where the src is to be truncated.
```c++
static inline char *safe_strcpy(char *dst, const char *src, size_t dst_size, int *error_code)
{
  if(0 == *error_code)
  {
    size_t wrote_sz;
    size_t cur_len;

    // When strlen(src) >= dst_size, dst is not null terminated!
    strncpy(dst, src, dst_size);
    // This strlen goes over the bounds of dst. It may segfault or return a bad size.
    wrote_sz = strlen(dst);
    // Assuming this if statement does not crash....
    if('\0' != dst[wrote_sz]) {
      if(wrote_sz >= dst_size) {
        cur_len = dst_size - 1;
        *error_code = 1;
      }
      else {
        cur_len = wrote_sz;
      }
      // We are overwriting memory we have no ownership of.
      dst[cur_len] = '\0';
    }
  }

  return dst;
}
```
- The other function has an off-by-one error, which leads to a similar problem.
```c++
//append src to dst - max (dst_size - strlen(dst) are appended, returns NULL terminated string
//in case src is bigger than dst_size - error_code is set to 1
//check if error code is = 0 to prevent rewrite error_code value if safe_ functions called in tuple
static inline char *safe_strcat(char *dst, const char *src, size_t dst_size, int *error_code)
{
  if(0 == *error_code)
  {
    size_t wrote_sz;
    size_t cur_len;

    // If strlen(dst) == 0 and strlen(src) >= dst_size, strncat will write
    // dst_size + 1 bytes, possibly crashing the server. Check cppreference.
    strncat(dst, src, dst_size - strlen(dst));
    wrote_sz = strlen(dst);
    //if dst string not null terminated - add '\0'
    if('\0' != dst[wrote_sz]) {
      if(wrote_sz >= dst_size) {
        cur_len = dst_size - 1;
        *error_code = 1;
      }
      else {
        cur_len = wrote_sz;
      }
      dst[cur_len] = '\0';
    }
  }

  return dst;
}
```
- Here is a simpler version of those two functions that also eliminates the extra `strlen()` call.
```c++
/*
  Copies src into dst and ensures dst is a NULL terminated C string.

  Returns 1 if the src string was truncated due to too small size of dst.
  Returns 0 if src completely fit within dst. Pads the remaining dst with '\0'

  Note: dst_size must be > 0
*/
static inline int safe_strcpy(char *dst, size_t dst_size, const char *src)
{
  memset(dst, '\0', dst_size);
  strncpy(dst, src, dst_size - 1);
  /*
     If the first condition is true, we are guaranteed to have src length
     >= (dst_size - 1), hence safe to access src[dst_size - 1]
  */
  if (dst[dst_size - 2] != '\0' && src[dst_size - 1] != '\0')
    return 1; /* Truncation of src. */
  return 0;
}

/*
  Appends src to dst and ensures dst is a NULL terminated C string.

  Returns 1 if the src string was truncated due to too small size of dst.
  Returns 0 if src completely fit within the remaining dst space. Pads the
            remaining dst with '\0'.

  Note: dst_size must be > 0
*/
static inline int safe_strcat(char *dst, size_t dst_size, const char *src)
{
  size_t init_len= strlen(dst);
  if (likely(init_len < dst_size - 1))
    return safe_strcpy(dst + init_len, dst_size - init_len, src);
  return 1;
}
```
# Other code changes
- In general I am against mechanically changing code to conform to a new interface. Given that the changes you propose are not significantly large, I have gone through each callsite of safe_strxxx and tried to achieve the following:
- Prefer to use `snprintf() ` instead of a series of `safe_strcpy`, `safe_strcat` calls.
- If possible eliminate dynamic construction of strings. This can be achieved in places where all we're doing is concatenating statically allocated string constants. (see connect engine `opmode= "wb"` and such).
I've pushed my changes to [bb-10.3-strcat-strcpy_fix](https://github.com/MariaDB/server/compare/bb-10.3-strcat-strcpy_fix)

The relevant commit (as of writing this review is): https://github.com/MariaDB/server/commit/46a3389403bf476f66d461d34c7563801b7d3965
Have a look at the code I wrote and let me know if you have any questions or if you disagree with anything. I'm happy to make corrections if you spot anything wrong.

Waiting for CI to turn green then I will merge.

**Comment by vaintroub** [comment]
@cvicentiu , while concentrating on  non-essential details of the strcpy_s such as hook handlers, you're missing the essential part  that makes them better than the BSD-family strlcpy and stuff.  If overflow occurs, the result of string operation would be an *empty* string , and this makes the failure apparent. While "castrated" null terminated strings won't do that.

**Comment by cvicentiu** [comment]
@vaintroub The problem with strncat and strncpy is that it is impossible to tell if a string was actually "castrated" leaving you to try and figure out:
a. For strncat, was the string terminated at dest[size(dest) - 1] or did it just fit right.
b. For strncpy, is the string actually null terminated or did we overflow?

You'll notice that I kept identical prototype and similar semantics to strcpy_s and strcat_s however I kept only the parts that are indeed relevant for us. If at a point in the future we want to only use strcpy_s, strcat_s, a simple find and replace will suffice.

Also, call sites where these functions were used actually *benefit* from a truncated string. Most of them are error messages that can come from the OS, messages with lengths where we don't quite know how big they can get and dynamically allocating the message buffer would require too large of a code change. I still think that the maintenance overhead of checking that strcpy_s *is* available on the platform in question is much more cumbersome than the in-house implementation I have provided.

Furthermore, if you would look at the patch, you would see that snprintf is actually the go-to solution for most of the call-sites and the use of these functions is now only done for safety when external input is at play.

**Comment by haidong** [comment]
Hi @cvicentiu , your comments on git practices and coding style is very thoughtful and well-written. Although some may quibble on certain aspects of them, but I think they deserve to be in MariaDB Foundation's documentation.

**Comment by Chaloff** [comment]
@cvicentiu Thank you very much for the changes!

I agree with the changes you did - making safe_ function interface similar to str..._s() functions was one of the way I also inclined to go - this definitely has a perfect sense (you can see that we discussed this option with @ericherman as well)

Have no questions here - feel free to merge changes.

And another thanks for detailed comment - especially for coding style. Some of it seems a bit unnatural for me but still it's your code base and your rules - will use this style in all following PRs

**Comment by ericherman** [comment]
@Chaloff @haidong please look at https://github.com/MariaDB/server/pull/2272 and leave a comment/review if you feel this would be helpful.

**Comment by cvicentiu** [comment]
Merged with https://github.com/MariaDB/server/commit/567b68129943a1cceab1d7b4c68e2a4ba011cdc0

Thank you for all the reviewers involved.

**Pull request closed without merging**
