### PR TITLE
MDEV-15022 - travis: add versioning to test suite

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

passed in https://travis-ci.org/grooverdan/mariadb-server/jobs/330273292

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for you contribution! I added this task to our 10.3 queue: https://jira.mariadb.org/browse/MDEV-15022

**Comment by grooverdan** [comment]
rebased on the the travis functioning 10.3 branch and still passes. Merge-able now?

**Comment by grooverdan** [comment]
32min(gcc) and 23min(clang) is about standard for me https://travis-ci.org/grooverdan/mariadb-server/builds/398514452 which is consistent to what the PR says above.

I just kicked off https://travis-ci.org/grooverdan/mariadb-server/builds/398527670 again too.

If there's a better travis branch feel free add versioning to there instead.

**Comment by shinnok** [comment]
@grooverdan Ok, looks good enough. However, @ottok recommended I remove RocksDB from Travis altogether.

**Comment by ottok** [comment]
We've managed to get to a point last week that the 10.3 actually consistently passes on Travis-CI right now. We will consider adding versioning tests later on.

Right now our biggest priority is to backport these Travis-CI improvements to other main branches (to get all green) and to enforce a culture where core developers actually respect Travis-CI and don't break it again.

image

We are glad @grooverdan that you contribute so much and are the far most frequent pull request maker, but as we want to be diligent that nothing brakes and our overall 'keep the tests green' effort advances, we cannot merge changes to .travis.yml right now unless they fix a clear bug.

**Comment by grooverdan** [comment]
there's a lot of rocksdb test masked, so eventually it might get too long, but until then it works.

**Comment by grooverdan** [comment]
@ottok well done on getting it green. glad i've got you started in the backport with #505

**Comment by shinnok** [comment]
Hi Dan, can you rebase and force push again so we get a fresh run? If that runs under 35 minutes I'm happy to merge it.

**Comment by grooverdan** [comment]
rebased. first push was a bit longer however compared to other fresh PRs all the build times where high. Second time hit the cache. Looking at MTR output the versioning test was ~20 seconds worth

**Comment by shinnok** [comment]
Merged, thanks a bunch!

**Pull request merged**
