### PR TITLE
Fix Travis-CI issues and most notably make the deb build job pass

### PR DESCRIPTION
**Pull request by ottok**
For details see the git commits.
screenshot from 2017-11-17 12-28-41

### CODE REVIEW

**Comment by grooverdan** [comment]
Works for me 👍

**Comment by ottok** [comment]
No regressions on buildbot after 11 hours:
screencapture-buildbot-askmonty-org-buildbot-grid-1510935094290

**Comment by grooverdan** [comment]
could target 10.2 with no major problem. Only percona tests where removed in 10.3.

git diff  10.2:.travis.yml 10.3:.travis.yml

**Comment by cvicentiu** [comment]
I also would like to get this on top of 10.2.

**Pull request merged**
