### PR TITLE
 MDEV-16481, MDEV-16026: refactor Sys_var_vers_asof

### PR DESCRIPTION
**Pull request by FooBarrior**
Two bugs are fixed:
1. MDEV-16026: Global system_versioning_asof must not be used if client sessions can have non-default time zone
2. MDEV-16481: set global system_versioning_asof=sf() crashes in specific case

Two more commits are the refactorings -- see comments below.

Behavior changed:
* system_versioning_asof value is stored as unix timestamp. Temporal values are converted with respect to local time zone.
* "DEFAULT" string is not accepted anymore. DEFAULT sql keyword should be used instead.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @FooBarrior,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-16481

This task was added to 10.3 backlog.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by FooBarrior** [comment]
I am contributing my new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by FooBarrior** [comment]
Note that this pull request depends on fix from MDEV-16026, which is also on review under PR #792

**Comment by vuvova** [comment]
The main problem is that dirty hack that inherits `Sys_var_vers_asof` from `Sys_var_enum`.
 It's not an enum and shouldn't be inherited from it.

This causes numerous evaluations of `var->value`, which can causes undesirable side effects.
There should be only one evaluation of `var->value`, in `Sys_var_vers_asof::check()`.

**Comment by FooBarrior** [comment]
@vuvova agree. Since "ALL" keyword was removed, keywords are no longer needed at all. Anyway, it was incorrect to add DEFAULT to keywords -- instead one could have keywords={"NOW", "ALL"}, and default to "NOW".
Copying from global var to local one was also 100% incorrect design, since it was impossible to "unset" local var without changing the global one.

While making all that pretty and straightforward, I've also noticed, that const literal pointers were erroneously returned as non-const pointers, i.e. discarding const qualifiers in `value_ptr`. This was also true for Sys_var_typelib. So I've refactored whole `sys_var::value_ptr` stack to save const qualification: indeed, all the places use those return values as pointers to constants and never modify them.

Please review is as well. The commit is also in the PR

**Comment by FooBarrior** [comment]
See next: 
https://lists.launchpad.net/maria-developers/msg12419.html
https://lists.launchpad.net/maria-developers/msg12439.html

**Pull request closed without merging**
