### PR TITLE
MDEV-23585: checksum.c: only use clmul if available

### PR DESCRIPTION
**Pull request by kencu**
if the processor does not support PCLMUL, then
crc32_x86.c is not compiled in, and this fails
to link. Only call the functions in crc32_x86.c if
they have been included.

fixes builds on older processors without PCLMUL

see: https://trac.macports.org/ticket/61063

### CODE REVIEW

**Review by dr-m — CHANGES_REQUESTED** [review]
@an3l, can you please file an MDEV for this, so that the MDEV number can be used in the first line of the commit message. It looks like this was broken in dec3f8ca69e5eb19a4be7a175d3834874c4d880b (MDEV-22641).

I think that the commit message is misleading. The `HAVE_CLMUL_INSTRUCTION` should be defined if the compiler toolchain supports the instruction, per `CHECK_C_SOURCE_COMPILES` in `mysys/CMakeLists.txt`. There is a separate run-time check for the processor.

I see that we are unnecessarily excluding 32-bit processors from using `pclmul`. I do not see anything in `crc32_x86.c` that would depend on AMD64. Could we please change the condition
```cmake
IF(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
  #Check for PCLMUL instruction (x86)
```
to the following:
```cmake
IF(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|i[36]86")
```
Would this change happen to fix the build alone? I do agree that the `#if` condition needs to be revised as well. In fact, I would suggest to simplify the condition to
```c
#ifdef HAVE_CLMUL_INSTRUCTION
```

**Comment by kencu** [comment]
Crux of the issue is that the runtime check doesn't exist if crc32_x86.c is never compiled in, so the link fails.

I agree your #ifdef covers it, I wanted to make the patch as minimal as possible but prefer what you put.

**Comment by dr-m** [comment]
@kencu Can you please confirm that my suggested fix works for you? And force-push it to this pull request, so that you will get the credit for the fix?

**Comment by kencu** [comment]
I suspect the real proper fix here is to remove the cmake test for the pclmul instruction entirely, always compile in crc32_x86.c on all intel/amd  systems, and let the runtime check handle whether to use the pclmul instructions...

That would fix the case where the build system does not have pclmul.

**Comment by dr-m** [comment]
> I suspect the real proper fix here is to remove the cmake test for the pclmul instruction entirely, always compile in crc32_x86.c on all intel/amd systems, and let the runtime check handle whether to use the pclmul instructions...

That is basically what my suggested fix does, but I would still need you to confirm the fix, because I do not have access to similar environment.
> That would fix the case where the build system does not have pclmul.

I would guess that in your build environment, `CMAKE_SYSTEM_PROCESSOR` does not match `x86_64` but it would match `amd64` instead. For some reason, http://buildbot.askmonty.org/buildbot/builders/mac-1012-bintar/builds/7781 does not suffer from this issue. http://buildbot.askmonty.org/buildbot/builders/mac-1012-pkg/builds/5395/steps/compile/logs/stdio does fail, but not due to this:
```
-- Performing Test HAVE_CLMUL_INSTRUCTION - Success
```

**Comment by kencu** [comment]
still sleeping (west coast North America). Up now, will report back shortly.

**Comment by kencu** [comment]
> That is basically what my suggested fix does, but I would still need you to confirm the fix, because I do not have access to similar environment.

You are quite right, this works:
```
IF(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|i[36]86")
```
and then the build succeeds.

And changing the #ifdef test to 
```
#ifdef HAVE_CLMUL_INSTRUCTION
```
will prevent the functions in ```crc32_x86.c``` from being called in case the file is not compiled in.

I will update the PR shortly.

**Comment by kencu** [comment]
For now, I left the ```__GNUC__``` test and the ```__x86_64__``` test in ```checksum.c``` as well, until I hear that you don't want them.

**Comment by kencu** [comment]
Re: your macOS build failures; looks like some of. the supporting software is failing. On MacPorts we use some of our own supports, and (with this fix included) mariadb-10.5 builds on MacOSX 10.6 all the way through to macOS 10.15 without issues.

**Comment by dr-m** [comment]
> For now, I left the `__GNUC__` test and the `__x86_64__` test in `checksum.c` as well, until I hear that you don't want them.

I suspect that the `__x86_64__` is unnecessarily preventing the acceleration from being attempted in 32-bit builds. I will check that and revise if needed.

For the record, on my system, `info_macros.cmake` in the build directory will define both `CMAKE_HOST_SYSTEM_PROCESSOR` and `CMAKE_SYSTEM_PROCESSOR` as `x86_64`, no matter if the `-m32` flag is being passed.

[MDEV-22749](https://jira.mariadb.org/browse/MDEV-22749) should address another omission: the acceleration is not available on Microsoft Windows yet.

**Comment by dr-m** [comment]
We never defined the preprocessor symbol that our code change is interested in:
```diff
diff --git a/config.h.cmake b/config.h.cmake
index ff0a039b3ac..0de5c2be3e0 100644
--- a/config.h.cmake
+++ b/config.h.cmake
@@ -102,6 +102,8 @@
 /* Libraries */
 #cmakedefine HAVE_LIBWRAP 1
 #cmakedefine HAVE_SYSTEMD 1
+
+#cmakedefine HAVE_CLMUL_INSTRUCTION 1
 #cmakedefine HAVE_CRC32_VPMSUM 1
 
 /* Support ARMv8 crc + crypto  */
```
Finally, the implementation was unnecessarily being disabled on 32-bit systems. The condition is redundant, because we are only compiling this module if the `CHECK_C_SOURCE_COMPILES` passed and `HAVE_CLMUL_INSTRUCTION` was set in CMake:
```diff
diff --git a/mysys/crc32/crc32_x86.c b/mysys/crc32/crc32_x86.c
index 3f176a6c145..608ba3927c7 100644
--- a/mysys/crc32/crc32_x86.c
+++ b/mysys/crc32/crc32_x86.c
@@ -57,8 +57,6 @@ typedef uint8_t byte;
 
 # define _gcry_bswap32 __builtin_bswap32
 
-#if __GNUC__ >= 4 && defined(__x86_64__)
-
 #if defined(_GCRY_GCC_VERSION) && _GCRY_GCC_VERSION >= 40400 /* 4.4 */
 /* Prevent compiler from issuing SSE instructions between asm blocks. */
 #  pragma GCC target("no-sse")
@@ -542,4 +540,3 @@ unsigned int crc32_pclmul(unsigned int crc32, const void *buf, size_t len)
   crc32_intel_pclmul(&crc32, buf, len);
   return ~crc32;
 }
-#endif
```
The rest of the patch is as we discussed before:
```diff
diff --git a/mysys/CMakeLists.txt b/mysys/CMakeLists.txt
index 14a4ea9e9bb..3122decfde1 100644
--- a/mysys/CMakeLists.txt
+++ b/mysys/CMakeLists.txt
@@ -58,7 +58,7 @@ IF (WIN32)
     my_win_popen.cc)
 ENDIF()
 
-IF(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64")
+IF(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|i[36]86")
   #Check for PCLMUL instruction (x86)
   CHECK_C_SOURCE_COMPILES("
   int main()
diff --git a/mysys/checksum.c b/mysys/checksum.c
index 948b9be6164..6e6633600a9 100644
--- a/mysys/checksum.c
+++ b/mysys/checksum.c
@@ -30,8 +30,7 @@ static unsigned int my_crc32_zlib(unsigned int crc, const void *data,
 my_crc32_t my_checksum= my_crc32_zlib;
 #endif
 
-#if __GNUC__ >= 4 && defined(__x86_64__)
-
+#ifdef HAVE_CLMUL_INSTRUCTION
 extern int crc32_pclmul_enabled();
 extern unsigned int crc32_pclmul(unsigned int, const void *, size_t);
 
```
With this, I will get a non-empty `my_checksum_init()` function. The test suite seems to pass on the 32-bit build, but I will still check in a debugger that an accelerated `crc32_pclmul()` is actually being invoked and it is producing correct results.

**Comment by dr-m** [comment]
During my execution of `./mtr --manual-gdb main.func_math`, the function `crc32_pclmul()` in `mariadbd` was invoked 160 times and the function `crc32_intel_pclmul()` was invoked 318 times. According to the disassembly, `pclmul` and other SIMD instructions were part of the 32-bit code. The test should fail with a result difference if the computations were incorrect.

I believe that this test combined with your validation of the `CMAKE_SYSTEM_PROCESSOR` change guarantees that my fix will work also for you. I will push my version shortly.

**Comment by kencu** [comment]
thanks for being so thorough! Please go ahead and push your fixes and feel free to close this on your timeline when desired. Well done!

**Comment by dr-m** [comment]
@kencu Thank you too!
I hinted to some colleagues that you might be able to help with some trouble that we are currently having on our Mac OS X builders.

**Comment by ottok** [comment]
Hello @kencu!

Currently our Travis-CI Mac OS X build is failing permanently. If the Travis-CI build is not fixed, the MariaDB builds on Mac OS X will eventually regress again. Could you please help rewrite the .travis.yml file in the 10.5 branch so the Mac builds would pass?

Example:
https://travis-ci.org/github/MariaDB/server/builds/722658169
image

Build code:
https://github.com/MariaDB/server/blob/10.5/.travis.yml#L202-L207

**Comment by grooverdan** [comment]
Raised: https://travis-ci.community/t/storing-build-cache-on-osx-exceeded-10-minute-timeout/9789

Attempt at removing Cellar from the build:
https://travis-ci.org/github/grooverdan/mariadb-server/jobs/723046285

^ + 1G ccache (rather than 5G)
https://travis-ci.org/github/grooverdan/mariadb-server/jobs/723050293

**Comment by kencu** [comment]
I'll be happy to take a look.

**Comment by ryandesign** [comment]
> Currently our Travis-CI Mac OS X build is failing permanently.

If the Travis 50 minute limit is part of the problem, consider trying Azure Pipelines which allows much longer builds.

**Comment by grooverdan** [comment]
I've fixed/worked around the stall with #1665 which took [45 mins](https://travis-ci.org/github/MariaDB/server/builds/723075837) so still a little tight on time. Considering other similar builds on other os/arch are 10-20mins it seems likely its the environment more than anything osx specific. Maybe it just hasn't started a build with a ccache. I guess we'll see soon if the build time improves.

If it doesn't improve, afaik we don't have a good plan for how to get a better OSX so Azure certainly might be an option. If you want to show how quick it is that would be good. Azure supporting >50 mins won't be the criteria as much as the Azure builds are just quicker.

**Pull request closed without merging**
