### PR TITLE
MDEV-17703 Add WITH_UBSAN switch to CMake similar to WITH_ASAN

### PR DESCRIPTION
**Pull request by kevgs**
I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.1-MDEV-17703-with-ubsan)

### CODE REVIEW

**Comment by svoj** [comment]
@kevgs could you resolve conflicts?

**Comment by kevgs** [comment]
@svoj For the first time I've tried github's resolver in browser. Seems to work.

**Comment by svoj** [comment]
Yeah, but generated merge commit. :(

**Comment by kevgs** [comment]
Does it cause problems with 'Squash and merge'? I force pushed to this branch to resolve a conflict without merge commit.

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
