### PR TITLE
MDEV-11159 - Porting the proxy protocol code from the latest percona

### PR DESCRIPTION
**Pull request by jkbzh**
The proxy protocol allows a proxy front-end to communicate
the client's IP address to a backend server. See [1,2]
for more information.

The code was ported and adapted from the current Percona
git base, using the original commit [3] as a guide
for identifying the files. No major change was applied
to any of the code at this time.

[1] https://blog.haproxy.com/2017/03/24/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/
[2] http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
[3] https://github.com/percona/percona-server/commit/c464c4de5dc8d07576e154da70745eab8d2b392f

### CODE REVIEW

**Comment by vaintroub** [comment]
It is, in my opinion, on the wrong place in code.  viosocket.  If you want to parse proxy header, the place to do it is whenever server reads first packet from client. It does not need any tricks with MSG_PEEK. it needs to be based upon VIO reads, not socket reads.

**Comment by svoj** [comment]
Hi @jkbzh,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-11159

This task was added to 10.3 backlog, which hasn't been scheduled yet.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by svoj** [comment]
@jkbzh, could you also share your thoughts regarding @vaintroub comment? Do you agree with these suggestions? Will you want to reimplement your patch?

**Comment by svoj** [comment]
@jkbzh, please also note that we'll have to retarget this feature for 10.3.

**Comment by jkbzh** [comment]
@vaintroub,

Thank you for your feedback.

> It is, in my opinion, on the wrong place in code. viosocket. If you want to parse proxy header, the place to do it is whenever server reads first packet from client, sql/net_serv.cc, my_real_read. IT is a big and scary function, but when it is called with new connection, the first time around it reads 4 bytes from client in the while(remain > 0) loop. if this matches proxy protocol header, you can continue proxy parsing. It does not need any tricks with MSG_PEEK. it needs to be based upon VIO reads, not socket reads. 

One thing that must be clear is that the proxy protocol as defined by its spec
is aimed to protocol-agnostic proxies, such as haproxy. The specs refers to
them as dumb proxies,

The proxy protocol allows to tell a backend server behind a proxy front-end the
client's IP address and this information is sent when the connection is
open. There is both a text and a binary version for the protocol header, with
the latter being today more favorably recommended by the author of the spec
(faster and easier to parse, etc). The protocol header is prefixed to the
client data sent on layer 4 (you called it 4.5 on irc).

You told me that you'd like to have a header for MaxScale that would allow to
reuse an existing connection by different clients, without closing it (reuse,
not multiplexing). Here if the proxy is aware of the application protocol, it
is no longer considered a dumb proxy and the proxy protocol, as defined by the
spec, may not be the best choice.

If your proxy has control of the messages that signal the backend that a new
client is reusing an existing connection, you can then send any header right
afterwards or merge that information in that signal header.  If you reuse the
proxy protocol, you could reuse the same header processing code for that part.
I'm not sure, thought, that the proxy protocol would be the best or only choice
for that purpose, For example, you could choose to adapt another another spec
such as RFC7239. We're now talking about layer 7.

Note that this layer 7 approach wouldn't work for haproxy or other dumb proxies
due to lack of knowledge of the application protocol (mysql). Haproxy does have
an exception for HTTP backend servers because haproxy knows how to inject HTTP
headers.

Re: peeking, the proxy protocol spec says that the receiver must not process
the connection before it receives a complete and valid proxy protocol header
and reject connections if they only contain partial proxy protocol headers
(potentially with a small amount of timeout to give a chance to receive
everything).  This is to allow for the detection of connection problems, ease
processing, and abort quickly if an incorrect header arrives.

The proxy protocol is designed to avoid the segmentation of the data it sends,
by making it smaller than the default TCP Maximum Segment Size (MSS) of 536
bytes. In some cases, the header content's length can vary: IPv4 vs IPv6,
binary version with length header, ... This makes it difficult to have an
implementation that doesn't peek, processes the header, and then consummes the
exact number of bytes that correspond to the header's length.  If we read too
much, then we will need to buffer that data somewhere.

All the implementations I saw of this protocol for different servers (apache,
varnish, proposed code in the spec), they all use peek to wait until the proxy
protocol data arrives. The spec insists to not process the header until the
whole header is received. If you think this is not needed, I think it would be
better to bring this topic to the author of the spec.

> Apart from being usable with all, (also other than socket) transports, better abstraction allows in principle to parse proxy protocol header after COM_CHANGE_USER (https://dev.mysql.com/doc/internals/en/com-change-user.html) or after COM_RESET_CONNECTION (https://dev.mysql.com/doc/internals/en/com-reset-connection.html), thus making it more attractive for proxies with connection pools.

For this kind of proxy forwarding of client IP addresses, there are two possible strategies, 
depending on what kind of processing you do with that data: in the first one, you 
replace early on the IP address of the proxy by that of the client. This change is 
transparent to all the functions that use that information (e.g., logs, ACLs). 
This is what the backported percona code originally does. Apache 2.2 also adopted this strategy.

In the second strategy, you add a variable to the structure that stores the
remote IP address to store the client's IP address. If no proxy is used, the
client's IP address is the same as the remote IP address. If an authorized
proxy forwards the client's IP address through a proxy protocol header (or
other), the remote IP address will store the proxy's address while the new
variable will store the client's. You also have to modify the functions that
need the client's IP address to retrieve it from the new variable. This is
typical for the ACL and log functions. This is is the strategy adopted by
apache 2.4, together with its mod_remote_ip module.

Rather than looking at where the code is, I think it's more interesting to see
where in the workflow the proxy protocol header is being processed. Following
the Percona implementation, right now the code is called when a new connection
arrives to the server,

```
sql_connect.cc:handle_one_connection()
->do_handle_one_connection()
 ->thd_prepare_connection()
  ->login_connection()
    ->check_connection()
      ->viosocket.c:vio_peer_addr()
        ->viosocket.c:process_proxy_header().
```

Also:
```
threadpool_unix.cc:tp_add_connection()
->threadpool_common.cc:threadpool_add_connection():
  ->thd_prepare_connection()
```
From what I see in the code, **check_connection()** is the earliest where access
control is done on the IP address so, imo, it makes sense having the call there
for handling the proxy protocol header.  Whether that part of the code is in
vioscoket or in another file, and whether it uses recv or calls a higher level
function, I don't have an issue about that, provided it can do a peek and then
consume the bytes that correspond to the header.

The drawback of moving this code outside of **vio_peer_addr()** is that if the proxy
protocol is used, **vio_peer_addr()** will probably need to be called twice. The
first time to get the IP address of the sender, to see if it's a proxy-protocol
enabled pfe, the 2nd time to initialize it with the updated client IP address
values retrieved after processing the proxy protocol header. This means that
the time, resources, and system calls linked to **vio_peer_addr()** will be doubled
when using the proxy protocol.

Where were you planning to do your support for connection reuse with proxies?
Maybe both could be done in check_connection.

This is an architectural issue that must be evaluated before moving ahead with
code changes. Some of the questions are:

1. Where to do the proxy protocol processing

2. Is it necessary to preserve the proxy's IP address in
   **violite.h:st_vio.remote** or ok to overwrite it with the client's IP address?
   (This is what percona does) Do we want to use another variable for that?
   Change functions to use the new variable or only store the proxy's address
   there and use it for authenticating and authorizing which proxies may
   forward the client's IP addresses?
   
3. If for MaxScale, how will the client IP (and port if needed) be transmitted
   and where will it be processed.

**Comment by jkbzh** [comment]
Hi @svoj 

> Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

The code I backported came originally from the percona repository. It was an original and whole contribution to the percona repository. The percona code doesn't need any copyright assignment.

All new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by jkbzh** [comment]
@svoj 

> Will you want to reimplement your patch?

I'm ok for helping do the changes concerning the proxy protocol handling and
code integration for both 10.1 and 10.2 (I don't think I've the environment to
test 10.3), with some guidance and previous discussion if the code needs to move elsewhere. I don't want to engage myself for taking on the MaxScale related enhancement or processing.

**Comment by vaintroub** [comment]
Ok, here is how I imagine it could work, and what I discussed with MaxScale folks last week. As I mentioned, they would find the whole 

Proxy header can be part of the MariaDB protocol, rather than "transport layer". Normally, all communications in MYSQL protocol are done by exchanging "packets" with 4 byte headers. However we can do special exceptions and allow to have a proxy header in some predefined places

a) Creation of new connection. This is partially covered by Percona's patch (just for sockets, rather than transport independent)
Or,  for connection pooling
b) Together with COM_CHANGE_USER / COM_RESET_CONNECTION.

Proxy header cannot be mistaken with the normal MySQL packet header in any of these places.

The place in code to detect the proxy header is thus not really complicated. Eventually, after reading 4 bytes off the client packet, **my_real_read()**  would detect invalid packet sequence number and jump to packets_out_of_order label https://github.com/MariaDB/server/blob/10.1/sql/net_serv.cc#L1069 . Then , if one looks at the 4 bytes and they match 4 first bytes of proxy protocol header, one could continue reading and parsing the rest of the proxy header. 

My understanding is that reading rest of the proxy header  can be done synchronously, no peeking or consuming required. Does not seem like a big deal to me. Perhaps it does one more syscall for binary header format, so what, the data is there in the socket, it is cheap  to get it from there.

Binary format (v2):
overall there are 3 read() calls - the above mentioned 4 bytes from my_real_read() ("\x0D\x0A\x0D\x0A")  , another 12 bytes to read off the proxy_hdr_v2 header, and finally the address with the size of proxy_hdr_v2::len (/* number of following bytes part of the header */). 

Text format(v1) (if we choose to support it)
the above mentioned 4 bytes from my_real_read() ("PROX"), followed by bytewise read()s until "\r\n".


Once the proxy  header is read and parsed and ip address is resolved (which does not have to be vio_peer_addr all the time, as ip_to_hostname() maintains its own cache), one can update 
thd->main_security_ctx.host and thd->main_security_ctx.ip . That's it I think. After header is parsed, my_real_read()  would be repeated once again, to read the actual MySQL packet header.

Now, to the connection pooling. To me it looks like first the proxy header needs to be sent just **before** 
COM_CHANGE_USER/COM_RESET_CONNECTION, to fix the thd->main_security_ctx members.  Which means whenever proxy header appears on an already existing connection, the next command on the current connection must be one of COM_CHANGE_USER , or COM_RESET_CONNECTION. COM_RESET_CONNECTION, would need a check that this user can connect from the new IP . COM_CHANGE_USER, should do  right thing already, it does full featured authentication in this case.

There are some small details , like check whether this connection(peer) can be used for proxying. This needs to be done only once time, during the first proxy request, and result can be stored somewhere in THD . 

So, this is the server part as I see it. We need to test it in our test suite somehow, i.e we need a sender,  Do you have any idea how to do that?

**Comment by jkbzh** [comment]
@vaintroub , let's deal with each point at a time. Re: peek

> The place in code to detect the proxy header is thus not really complicated. Eventually, after reading 4 bytes off the client connection, my_real_read() would detect invalid packet sequence number and jump to packets_out_of_order label https://github.com/MariaDB/server/blob/10.1/sql/net_serv.cc#L1069 . Then , if one looks at the 4 bytes and they match 4 first bytes of proxy protocol header, one could continue reading and parsing the rest of the proxy header.
> 
> My understanding is that reading rest of the proxy header can be done synchronously, no peeking or consuming required. Does not really seem like big deal. Perhaps it does one more syscall for binary header format, so what, the data is there in the socket, it is cheap to get it from there.
> 
> Binary format (v2):
> overall there are 3 read() calls - the above mentioned 4 bytes from my_real_read() ("\x0D\x0A\x0D\x0A") , another 12 bytes to read off the proxy_hdr_v2 header, and one more read() of proxy_hdr_v2::len bytes (/* number of following bytes part of the header */).

If each my_real_read() call only reads up to 4 bytes at a time, there would be more than 3 calls needed. Here's a decomposition of the data sent in the proxy header. 
``
\# first column is byte number
1
12 signature

13 protocol version
14 transport protocol and address family

15
16 address + extra data length in bytes (len)

\# if using IPV4
17
28   TCP/UDP over IPV4 (len = 12)

\#If using IPV6
17   TCP/UDP over IPV6 (len = 36)
52  
    
\# if using sockets
17
232  Unix sockets

\# If optional extra data was sent    
233-536  Per address length, optional extra data that may be ignored
``
Thus for IPV4 we may receive a minimum of 28 byes (7 calls of my_real_read() )
For IPV6, we may receive a minimum of 52 byes (13 calls to my_real_read() )
For sockets, we may receive a minimum of 232 bytes (58 calls to my_real_read() )
And if extra data is send, we may have a maximum of 536 byes that need to be consumed, even if it needs to be ignored (134 calls to my real_read() )

The implementations of this protocol use peek to wait until 536 bytes are available, then they consume the actual bytes that form the header as declared in bytes 15-16.

I've not tried but yes, you could simulate the peek by doing a partial processing of the header up to bytes 15/16 and then reading the rest. More than 3 calls, though. Couldn't it be possible to expand my_real_read with an extra parameter to say how many bytes we want to read?

Another issue is to to detect and decide what to do if the connection is closed, timeouts, or if the header is malformed.

**Comment by vaintroub** [comment]
I think you might be mixing my_real_read() and vio_read(). my_real_read reads MySQL protocol packets, so it first reads packet header (4 bytes), using vio_read(), and then it detects mismatch of the sequence number,  You can read the rest you need vio_read(), which is more posixly oriented

**Comment by jkbzh** [comment]
@vaintroub  Yes you're right in that I got mixed up with those two functions, but not only that! Let's meet on freenode at some time to clear up things?

**Comment by vaintroub** [comment]
Sure, I'm there know either as wlad or as vvaintroub

**Comment by vaintroub** [comment]
Closing, as we implemented slightly different solution, not based on percona, in the latest 10.3

**Comment by jkbzh** [comment]
Hello Vlad,

Thank you for having taken care of this. I was too busy to be able
to continue my contribution.

I just tested 10.3 against our haproxy proxy protocol setup and it 
works as expected.

Any idea when the support for proxy protocol will be rolled out 
in 10.2 (maybe 10.1 too)?

Cheers,

--josé

**Comment by vaintroub** [comment]
Hi Jose,
At the moment there are no plans for porting it back, as we planned this for 10.3+ , as can be seen in JIRA. We usually do not add new features post-GA. Rule of thumb is that a new feature is for a new version, we only make exceptions for plugins, but  even that is rather seldom.

**Pull request closed without merging**
