### PR TITLE
MDEV-20732 Correctly set the length of the FORMAT() result for float data type as argument.

### PR DESCRIPTION
**Pull request by tntnatbry**

### CODE REVIEW

**Comment by an3l** [comment]
Hi @tntnatbry,
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by robertbindar** [comment]
Hi @tntnatbry, thanks for the patch. I'm currently looking if it's reproducible on earlier versions, once this and the buildbot tests are done, this is good to go.

**Comment by robertbindar** [comment]
Forgot to ask, can you please submit a signed copy of MCA or specify here that this work falls under the bsd-3 new license? Many thanks.

**Comment by tntnatbry** [comment]
Thanks @robertbindar! I am submitting this patch under the BSD-3 new license.

**Comment by robertbindar** [comment]
Done! Excellent, many thanks!

**Pull request merged**
