### PR TITLE
Deb: Use build flag to enforce default charset as utf8mb4

### PR DESCRIPTION
**Pull request by ottok**
Possible now since
https://github.com/mariadb-corporation/mariadb-connector-c/commit/29720950eeae75f1ea7ef1376a6149cabeb79d13

Upstreamed from https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/ca5e93c754209f9c1a729bb057332ab3b0b76363

### CODE REVIEW

**Comment by ottok** [comment]
For the best QA flow, https://github.com/MariaDB/server/pull/1721 should be merged first.

**Comment by ottok** [comment]
# Quality assurance

## Salsa-CI

Debian packaging tests at https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/211523 pass:
image

This includes the custom test added in this PR

## Travis-CI

The tests at https://travis-ci.org/github/MariaDB/server/builds/751470508 passed apart from the often failing ppc64el job, which has been addressed in https://github.com/MariaDB/server/pull/1681

image


## Buildbot 

Buildbot shows a lot of failures at http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-conc-utf8&category=main&category=experimental

image

All of these failures however seem unrelated to this PR. For example the test at http://buildbot.askmonty.org/buildbot/builders/kvm-deb-groovy-amd64/builds/330/steps/minor-upgrade-server/logs/stdio fails due to expired TLS certificate.

**Comment by ottok** [comment]
Rebased on latest 10.5. I can also rebase this on 10.6 if you think this change is better suited to be rolled out in 10.6.

**Comment by grooverdan** [comment]
merged per f26e3259a15cc26dac0a0a77e2488abb87892cf4

Thanks @ottok

**Comment by vuvova** [comment]
I think it can only go to 10.6, we cannot change defaults after GA

**Comment by ottok** [comment]
Hello @grooverdan @vuvova @dr-m! If a PR has issues and needs to be updated, please allow me at least 24h to do it. Do not merge directly and close PR in a non-merged/rejected state (which will show as negative progress on my Github stats).

**Comment by vuvova** [comment]
@ottok, I'm afraid, @grooverdan has already merged it.

@grooverdan what about this approach — you revert this change in 10.5 and when @ottok is ready, it'll go into 10.6 and it'll also modify rpm/bintars to match, as there's no reason why deb packages should behave differently (if we agree that utf8mb4 is the future).

**Comment by grooverdan** [comment]
> Hello @grooverdan @vuvova @dr-m! If a PR has issues and needs to be updated, please allow me at least 24h to do it. Do not merge directly and close PR in a non-merged/rejected state (which will show as negative progress on my Github stats).

Some of the github merge, rebase options confused me. I think I've got it for next time.

> @ottok, I'm afraid, @grooverdan has already merged it.
> 
> @grooverdan what about this approach — you revert this change in 10.5

Already done.

> and when @ottok is ready, it'll go into 10.6 

Too late. Also already done.

> and it'll also modify rpm/bintars to match, as there's no reason why deb packages should behave differently (if we agree that utf8mb4 is the future).

So are @vuvova  are you doing the rpm/bintars? So yes, I agree utf8mb4 is the future.

**Comment by grooverdan** [comment]
MDEV-25485 / b29c5b1e99e09f8fb5e33e7cd78aad1063af34a8

**Pull request closed without merging**
