### PR TITLE
Fix duplicate word

### PR DESCRIPTION
**Pull request by Sp1l**
Rebase had too many merge conflicts, redo on 5.5

### CODE REVIEW

**Comment by an3l** [comment]
Can you please just change commit message `git commit --amend` as you did in previous PR `Fix duplicate word both both -> both`?

**Comment by an3l** [comment]
Pushed with 821a6939087d4 to `5.5`, thanks.

**Comment by Sp1l** [comment]
Does this get merged all the way up to 10.5?

**Comment by an3l** [comment]
Yes it will

**Pull request closed without merging**
