### PR TITLE
MDEV-31888 : galera.galera_wan, galera.galera_vote_rejoin_* fail

### PR DESCRIPTION
**Pull request by janlindstrom**
- [x] *The Jira issue number for this PR is: MDEV-31888*

## Description

Clean up configuration and tests. Add wait conditions to make sure test continues from clean state. Test case changes only.

## Release Notes
TODO: What should the release notes say about this change?
Include any changed system variables, status variables or behaviour. Optionally list any https://mariadb.com/kb/ pages that need changing.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [x ] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by sysprg** [comment]
@janlindstrom Thanks, but it's unclear why the generic galera_4nodes.cnf will now include log-bin for all tests that use it, including versioning_trx_id.test and GCF-360.test. Is this really always necessary when testing a 4-node configuration? The second question is increasing the gcache size to 20M - what is the need for that? I'm concerned that this may mask some bugs in other tests (other than the ones this fix is ​​intended to fix).

**Comment by sysprg** [comment]
I have temporarily re-assigned this pull request back to you - please assign it back to me after you have finalized the configuration change so that it does not affect unrelated tests.

**Comment by janlindstrom** [comment]
@sysprg Ok, I will restrict configuration change to this test only. In general case we should run almost all tests using both log-bin and binlog-off cases but that would make suites slower. I changed suspect and evict timeouts because in these tests starting of servers takes longer than normally.

**Comment by janlindstrom** [comment]
Timeout change is needed for slow machines.

**Comment by sysprg** [comment]
Thanks, the fix has been merged with the head revision: https://github.com/MariaDB/server/commit/7ffa7b6b0193738d011e514b66d875ce29bc11d2

**Pull request closed without merging**
