### PR TITLE
Fix inconsistent definition of PERFORMANCE_SCHEMA.REPLICATION_APPLIER_STATUS.COUNT_TRANSACTIONS_RETRIES column

### PR DESCRIPTION
**Pull request by dlenski**
# Description

This column (`COUNT_TRANSACTIONS_RETRIES`) is defined as `BIGINT UNSIGNED`
(64-bit unsigned integer) in the user-visible SQL definition:
https://github.com/MariaDB/server/blob/182ff21ace34ea4f00fb5b66689b172323d91f99/storage/perfschema/table_replication_applier_status.cc#L66

And its value is internally set/updated using the `set_field_ulonglong`
function:
https://github.com/MariaDB/server/blob/182ff21ace34ea4f00fb5b66689b172323d91f99/storage/perfschema/table_replication_applier_status.cc#L231-L233

… but the structure where it is stored allocates only `ulong` for it:
https://github.com/MariaDB/server/blob/182ff21ace34ea4f00fb5b66689b172323d91f99/storage/perfschema/table_replication_applier_status.h#L62

As a result of this inconsistency:

1. On any platform where `ulong` is `uint32_t` and `ulonglong` is `uint64_t`,
   setting this value would corrupt the 4 bytes of memory *following* the 4
   bytes actually allocated for it.

   Likely this problem was never noticed because this is the final element in
   the structure, and the structure is padded by the compiler to prevent
   memory corruption errors.

2. On any BIG-ENDIAN platform where `ulong` is `uint32_t` and `ulonglong`
   is `uint64_t`, reading back the value of this column will result in
   total garbage.

   Likely this problem was never noticed because MariaDB has not been
   tested on 32-bit big-endian platforms.

In order not to affect the user-visible/SQL definition of this column, the
correct way to fix this issue is to change it to `ulonglong` in the
structure definition.  See
https://github.com/MariaDB/server/pull/2763/files#r1329110832 for the
original identification and discussion of this issue.

## How can this PR be tested?

* [x] Builds with no errors
* [ ] Consider adding at least one big-endian platform to CI
* [ ] Consider adding at least one platform where `ulong` and `ulonglong` are not the same underlying C/C++ data type

## Basing the PR against the correct MariaDB version

* [ ] This is a new feature and the PR is based against the latest MariaDB development branch.
* [x] This is a bug fix and the PR is based against MariaDB **10.6**.

## PR quality check

* [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
* [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

# Copyright

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc

### CODE REVIEW

**Comment by dlenski** [comment]
@grooverdan, you specifically asked me to backport this fix to 10.6 in https://github.com/MariaDB/server/pull/2763#discussion_r1363507893

**Comment by dlenski** [comment]
In https://github.com/MariaDB/server/pull/2763#discussion_r1363507893, @grooverdan wrote:

> can you correct this mistake for 10.6 and put new functionality into 11.4 branch

Per @vuvova's https://github.com/MariaDB/server/pull/2927#issuecomment-1854578097, bugfixes should (**still**) be targeted at **10.4**, rather than **10.6**.

Are you all aligned on this now? Can I rebase this bugfix PR right here to 10.4?

**Comment by LinuxJedi** [comment]
> In [#2763 (comment)](https://github.com/MariaDB/server/pull/2763#discussion_r1363507893), @grooverdan wrote:
> 
> > can you correct this mistake for 10.6 and put new functionality into 11.4 branch
> 
> Per @vuvova's [#2927 (comment)](https://github.com/MariaDB/server/pull/2927#issuecomment-1854578097), bugfixes should (**still**) be targeted at **10.4**, rather than **10.6**.
> 
> Are you all aligned on this now? Can I rebase this bugfix PR right here to 10.4?

I don't know the reason for that specific case, but bug fixes should be against the oldest still supported release that has the feature that is being fixed. So, if a feature is only in 10.6 onwards, it would go in 10.6. I believe in this case this file doesn't exist until 10.5, so it could probably be rebased against that.

**Comment by dlenski** [comment]
Okay, I've rebased this onto 10.5 per @LinuxJedi.

**Comment by dlenski** [comment]
Are you planning to merge this soon, @LinuxJedi?

**Review by LinuxJedi — APPROVED** [review]

**Review by grooverdan — APPROVED** [review]

**Pull request merged**
