### PR TITLE
add Hygon Dhyana support in check-cpu

### PR DESCRIPTION
**Pull request by hygonsoc**
add Hygon CPU vendorID checking in check-cpu and use k8 as initial support

I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @hygonsoc 
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by vaintroub** [comment]
Our build is not using check-cpu, just normal cmake.
This only user of this script, as far as I know, is @montywi .

**Comment by hygonsoc** [comment]
@an3l Already update PR, thanks for notification!

**Comment by cvicentiu** [comment]
The script only uses the cpu_arg to hint GCC how to better optimize the binary for the target CPU. It will not produce any unwanted side effects, given how Hygon Dhyana is an AMD based chip.

**Pull request merged**
