### PR TITLE
Plugins to limit binlog sending/receiving speed.

### PR DESCRIPTION
**Pull request by klaywang**
Contributed by TXSQL on Tencent Cloud.

### CODE REVIEW

**Comment by klaywang** [comment]
I contribute this under MCA.

**Comment by montywi** [comment]
@andrei and I can look at this next week.

The problem with this patch is that it has to be reworked for 10.3 as we are in 10.3 changing semisync to not be a plugin (to get more functionality and more speed) and as part of this we are removing all the semisync and replication hooks.

Andreii or I will comment here as soon as the semisync work is done in 10.3 so that we can then discuss who will do the merge to latest 10.3

**Comment by felixliang** [comment]
@svoj @montywi 

hi svoj & monty

https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#read_binlog_speed_limit

In MariaDB 10.2.3, you already merge our patch of restricting the speed at which a replication slave can read the binlog from the master, do we also need the plugin of the same function?

**Comment by svoj** [comment]
@felixliang I thought this plugin has additional features (I didn't verify though). May be @klaywang could comment?

**Comment by klaywang** [comment]
actually slave side is enough for use, so we don't need master side so much. 

Just close it now. Thanks.

**Pull request closed without merging**
