### PR TITLE
MDEV-20946: Hard FTWRL deadlock under user level locks

### PR DESCRIPTION
**Pull request by i-rinat**
Increase deadlock weight of a lock each time it was selected as a victim, but not unlocked.

### CODE REVIEW

**Comment by i-rinat** [comment]
Request for comments.

This patch does what was suggested in MDEV-20946, that is, prevents FTWRL when any locks are taken. That makes the suggested in MDEV-2046 test to not timeout. However I strongly believe that there is no issue, or I failed to see one despite several attempts. The test makes `mysqltest` to lock itself, while server is fine.

If the suggested test is changed to look like this:
```
CREATE TABLE t1(a INT);
SELECT GET_LOCK("l1", 0);
 
connect(con1,localhost,root,,);
LOCK TABLES t1 WRITE;
 
connection default;
sleep 1;
send FLUSH TABLES WITH READ LOCK;
 
connection con1;
sleep 1;
send SELECT GET_LOCK("l1", 10);
 
connection default;
# <- Here is where "reap" was before.
 
connection con1;
reap;
disconnect con1;
 
connection default;
reap;  # <- Here is where "reap" was moved.
SELECT RELEASE_LOCK("l1");
UNLOCK TABLES;
DROP TABLE t1;
```
then it passes. Note that only change was the order in which "reap" commands are called.

**Review by montywi — CHANGES_REQUESTED** [review]
Patch looks ok
Please do the following changes and I will then commit the code the main branch:
- Fix the few request
- Update the commit message to describe the problem in full detail and why the patch solves it.
  - For this you have already most of the text in the Jira entry and you can reuse that

**Comment by i-rinat** [comment]
Updated the test and the commit description.

**Comment by an3l** [comment]
Pushed with https://github.com/MariaDB/server/commit/fa5f60681fe4ed9d5bb160e551381cb7b1be5850  to  10.6. Thanks

**Pull request closed without merging**
