### PR TITLE
MDEV-22552: Remove mytop as deprecated

### PR DESCRIPTION
**Pull request by ottok**
For historical reasons the sources have carried a copy of the mytop script.
It is not being maintained in MariaDB sources and it was not intended for
distribution, so clarify the situation by completely removing it and let
users install it from the origin themselves.

Most Linux distros such as Debian and Fedora ship mytop as a separate
package which users should use.

### CODE REVIEW

**Comment by ottok** [comment]
CI passed at http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-remove-mytop&category=main&category=experimental

**Comment by ottok** [comment]
buildbot/centos-7 failing without clear error message:
```

Completed: All 1997 tests were successful.
567 tests were skipped, 265 by the test itself.
process killed by signal 13
program finished with exit code -1
elapsedTime=350.796971
```

**Comment by Sp1l** [comment]
The upstream package requires p5-DBD-mysql not p5-DBD-MariaDB.
This leads to conflicts that are not easily resolved in installers and packagers.

**Comment by ottok** [comment]
Closing as per comment https://jira.mariadb.org/browse/MDEV-22552?focusedCommentId=155100&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-155100

**Pull request closed without merging**
