### PR TITLE
Fix resource leak

### PR DESCRIPTION
**Pull request by FaramosCZ**

### CODE REVIEW

**Comment by FaramosCZ** [comment]
Submitted under MCA

--

```
Error: RESOURCE_LEAK (CWE-772):
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5253: alloc_fn: Storage is returned from allocation function "os_file_opendir".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2780:2: alloc_fn: Storage is returned from allocation function "opendir".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2780:2: var_assign: Assigning: "dir" = "opendir(dirname)".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2782:2: cond_false: Condition "dir == NULL", taking false branch.
mariadb-10.3.10/storage/innobase/os/os0file.cc:2784:2: if_end: End of if statement.
mariadb-10.3.10/storage/innobase/os/os0file.cc:2786:2: return_alloc: Returning allocated memory "dir".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5253: var_assign: Assigning: "dbdir" = storage returned from "os_file_opendir(dbpath, false)".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5255: cond_true: Condition "dbdir != NULL", taking true branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5257: noescape: Resource "dbdir" is not freed or pointed-to in "fil_file_readdir_next_file".
mariadb-10.3.10/storage/innobase/fil/fil0fil.cc:3988:16: noescape: "fil_file_readdir_next_file(dberr_t *, char const *, os_file_dir_t, os_file_stat_t *)" does not free or save its parameter "dir".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5259: cond_true: Condition "ret == 0", taking true branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5261: cond_false: Condition "fileinfo.type == OS_FILE_TYPE_DIR", taking false branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5264: if_end: End of if statement.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5266: cond_true: Condition "strlen(fileinfo.name) > suffix_len", taking true branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5266: cond_true: Condition "0 == strcmp(fileinfo.name + strlen(fileinfo.name) - suffix_len, suffix)", taking true branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5273: cond_true: Condition "!(*func)(path, dbinfo.name, fileinfo.name, NULL)", taking true branch.
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5278: leaked_storage: Variable "dbdir" going out of scope leaks the storage it points to.
# 5276|                                                     fileinfo.name, NULL))
# 5277|                                         {
# 5278|->                                               return(FALSE);
# 5279|                                         }
# 5280|                                 }

```

**Comment by FaramosCZ** [comment]
Also

```
Error: RESOURCE_LEAK (CWE-772):
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5233: alloc_fn: Storage is returned from allocation function "os_file_opendir".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2780:2: alloc_fn: Storage is returned from allocation function "opendir".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2780:2: var_assign: Assigning: "dir" = "opendir(dirname)".
mariadb-10.3.10/storage/innobase/os/os0file.cc:2786:2: return_alloc: Returning allocated memory "dir".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5233: var_assign: Assigning: "dir" = storage returned from "os_file_opendir(path, false)".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5240: noescape: Resource "dir" is not freed or pointed-to in "fil_file_readdir_next_file".
mariadb-10.3.10/storage/innobase/fil/fil0fil.cc:3988:16: noescape: "fil_file_readdir_next_file(dberr_t *, char const *, os_file_dir_t, os_file_stat_t *)" does not free or save its parameter "dir".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5290: noescape: Resource "dir" is not freed or pointed-to in "fil_file_readdir_next_file".
mariadb-10.3.10/storage/innobase/fil/fil0fil.cc:3988:16: noescape: "fil_file_readdir_next_file(dberr_t *, char const *, os_file_dir_t, os_file_stat_t *)" does not free or save its parameter "dir".
mariadb-10.3.10/extra/mariabackup/xtrabackup.cc:5278: leaked_storage: Variable "dir" going out of scope leaks the storage it points to.
# 5276|                                                     fileinfo.name, NULL))
# 5277|                                         {
# 5278|->                                               return(FALSE);
# 5279|                                         }
# 5280|                                 }

```

**Comment by FaramosCZ** [comment]
Sure.
I'm making PRs as I dig through the covscan results, that's why it may be fragmented to more PRs.

I have the covscan results only for one specific build I made so I try to stick to 10.3 version as the build originates from it.
I'm fine with opening new PRs once you point me to the correct branch. I hope this system does not make to much aditional work. Tell me if it acceptable or satisfactory workflow to you.

**Comment by dr-m** [comment]
> I'm fine with opening new PRs once you point me to the correct branch. I hope this system does not make to much aditional work. Tell me if it acceptable or satisfactory workflow to you.

The correct branch is the earliest applicable one. Yes, it involves some work to determine it.

I can address these pull requests by aggregating the fixes and pushing them to the earliest branch, but in that case GitHub would misleadingly indicate that the pull requests were closed without merge.

**Comment by dr-m** [comment]
Pull requests #983 and #984 were closed in commit 7372fe4da195f465a2f13984dcd89325ec361c43.

**Pull request closed without merging**
