### PR TITLE
MDEV-10154 - Remove some unnecessary parentheses

### PR DESCRIPTION
**Pull request by Cona19**

### CODE REVIEW

**Comment by svoj** [comment]
Hi Cona19,
 
Thanks for your contribution. 
  
Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
 
The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
 
Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
 
Thanks,
Sergey

**Comment by janlindstrom** [comment]
Hi, is there some compiler warning or other reason to remove unnecessary parenthesis ? Have you tested your change on where ?

**Comment by Cona19** [comment]
I am now studying the redo logging system of xtradb. So, I found that ut_align_down function uses unnecessary parentheses. I think that this function is copied from ut_align function which is written above, so some redundant parentheses are exist.
There was no warning or errors when I compile and build in my laptop.

**Comment by Cona19** [comment]
This code of the whole pull request, including one or several files that are contributed, either new files or modified ones, under the BSD-new license.

**Comment by svoj** [comment]
JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-10154

This task was added to 10.1 backlog, which is planned to be handled between 2016-06-23 and 2016-06-30.

**Pull request merged**
