### PR TITLE
MDEV-11612 - some clang warnings fixed

### PR DESCRIPTION
**Pull request by kevgs**
Hi.

No functional changes.

I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

### CODE REVIEW

**Comment by grooverdan** [comment]
The travis build appears to have caused a segfaulted in the myisam engine where it previously didn't. Can you look closer at the cause here as it appears you have changed some of the engine code.

**Comment by kevgs** [comment]
Silly segfaults have been fixed.

**Comment by grooverdan** [comment]
thanks much better. Consider submitting the PerconaFT (https://github.com/percona/PerconaFT) and tokudb components upstream too .

can you explain the ha_sphinx a bit more too?

Aside, I'm working on getting clang as part of Travis here too. Just need #281 committed first.

**Comment by kevgs** [comment]
FixNulls() is never used. m_sLastMessage is an array, not pointer and thus is never NULL.

**Comment by svoj** [comment]
Hi kevgs,

Thanks for your contribution. JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-11612

This task was added to 10.2.5 backlog, which is planned to be handled between 2017-01-19 and 2017-01-26.

Thanks,
Sergey

**Comment by grooverdan** [comment]
After fixing the minor conflicts - here is how the build will works for clang-3.8, 3.9 and 4.0 - https://travis-ci.org/grooverdan/mariadb-server/builds/212870654

If you are up for fixing more code mgroonga needs some work - https://travis-ci.org/grooverdan/mariadb-server/builds/212870744

**Comment by vuvova** [comment]
@kevgs, why did you close it?

**Comment by kevgs** [comment]
@vuvuva, because it's obsolete. Most of warnings are fixed in 10.2 and other parts of patch are unmergeable now.

**Comment by vuvova** [comment]
I see, thanks.

**Pull request closed without merging**
