### PR TITLE
MDEV-9864 - Implement recursive common table expressions

### PR DESCRIPTION
**Pull request by shagalla**
Please take this implementation of recursive CTE as a contribution for MariaDB server.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Galina,
 
Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-9864 

MCA is on file.

Thanks,
Sergey

**Comment by spetrunia** [comment]
Closing: the code is accepted into https://github.com/MariaDB/server/commits/bb-10.2-mdev9864 branch. It is being finalized there before being pushed into 10.2

**Comment by topillar** [comment]
why this feature is not included into 10.2.1 alpha?

**Comment by vuvova** [comment]
Because "it's being finalized before being pushed into 10.2", that is, it wasn't ready when 10.2.1 was released.

**Comment by SvetlanaM** [comment]
In what state is with recursive implementation? in my sql query does not work

**Comment by spetrunia** [comment]
Recursive CTEs have been pushed into MariaDB-10.2 tree a few days ago.  They will be available in the next  MariaDB release in the 10.2 series, 10.2.2.

**Pull request closed without merging**
