### PR TITLE
MDEV-5725: debian packaging

### PR DESCRIPTION
**Pull request by grooverdan**
Small fixes on the MDEV-6284 merge.

I submit this under the MCA.

### CODE REVIEW

**Comment by ottok** [comment]
LGTM

**Comment by ottok** [comment]
BTW, why add package with name libmariadbd18? Shouldn't the library name be bumped for MariaDB 10.2? @vuvova What is the policy on API version number here, should it be libmariadb19??

**Comment by grooverdan** [comment]
The library version and package name probably should match the ABI more than a major version change. I guess there was a bumping choice at some stage.

**Comment by ottok** [comment]
@grooverdan I still don't understand the .18 -> .19. You mean you adapted this code to a .18 -> .19 change already made somewhere else? The packaging in 10.2 currently has `usr/lib/*/libmysqld.so.18` and it builds fine. Where did you get the error message from? The commit message is void of explanation.

If I get this thing sorted out I will merge this both to the 10.2 branch here and the downstream mariadb-10.0 packaging repo in Debian.

**Comment by ottok** [comment]
I don't understand 07978c0 - what files will the * add? Aren't the extra .so.* files already installed by the libmariadbclient18 package?

**Comment by grooverdan** [comment]
@otto - check the travis output - https://s3.amazonaws.com/archive.travis-ci.org/jobs/173147988/log.txt - the libmysqld libraries definitely 19 created not 18. There are libmysqlclient libraries at version 18 - was that what you where seeing?
<pre>
	strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/libmariadbd-dev/usr/lib/x86_64-linux-gnu/libmysqld.so.19
</pre>

07978c0  /usr/lib/*/libmysqld.so is a symlink. The * was added so the actual shared library libmysqld.so.19 was included. Otherwise only a symlink is included to a non-existent file.
<pre>
-- Installing: /home/travis/build/MariaDB/server/debian/tmp/usr/lib/x86_64-linux-gnu/libmysqld.so.19
-- Installing: /home/travis/build/MariaDB/server/debian/tmp/usr/lib/x86_64-linux-gnu/libmysqld.so
</pre>

**Comment by grooverdan** [comment]
Unfixed: /usr/bin/mysql_config --port is 0 (this is client side config). Couldn't work out why.

**Comment by ottok** [comment]
Ok, thanks for the clarification. Do you want to extend your commit messages a bit and force push them? 

The install files themselves do not allow #-comments or similar, so git commit messages are the most important source of explanation why some line is as it is. I feel we keep coming back again and again to this type of questions, so I encourage the commit messages to be very clear and readable in years from now.

**Comment by grooverdan** [comment]
ack. will amend messages.

**Comment by grooverdan** [comment]
ok mysqld shared libraries are fully in the libmariadbd18 package. The dev package is left with the static library and the mariadb_config executable. I'm assuming this is right.

So just need clarification from @vuvova as to if the package name needs to match the library ABI version.

**Comment by ottok** [comment]
Yes, the package name must match ABI version. Looking at things, I think that Oracle bumped it from 18 to 19 and we inherited that. Note that 18 included already lots of changes, the version bumps by Oracle have been done way too rarely. Our numbers just follow Oracle on this to remain compatible.

**Comment by ottok** [comment]
One last thing: the package name must be libmariadbd19 as it will in 10.2 contain the library .so.19

**Comment by ottok** [comment]
I cherry-picked this downstream: https://github.com/ottok/mariadb-10.0/commit/073548add17a6fab0175f83bcf41a6b50a18cbf9
Other changes are already downstream. The file mariadb_config does not exist in 10.0, so it cannot be downstreamed (it is introduced by MariaDB Connector C included now in 10.2).

**Comment by ottok** [comment]
@grooverdan Can you be super and fine tune PR so that I can merge it without changes? Thanks

**Comment by grooverdan** [comment]
successful build as per https://travis-ci.org/grooverdan/mariadb-server/builds/175858209

Above build failure reported as MDEV-11281

**Comment by ottok** [comment]
@grooverdan Do you plan to do any further changes or shall I finalize this? I wish to merge it soon.

**Comment by grooverdan** [comment]
no further plans. merge away if content.

**Pull request merged**
