### PR TITLE
another test pull request for codership jenkins Bb 10.1 galera

### PR DESCRIPTION
**Pull request by aglarendil**

### CODE REVIEW

**Comment by svoj** [comment]
@aglarendil what's the purpose of these test PR's?

**Comment by aglarendil** [comment]
the purpose is to test codership CI integration and close them after that. should not take more than a couple of such pull requests and you will never see them again

**Comment by svoj** [comment]
Normally we perform such integrations in a private fork. And then just change repo url when ready.

**Comment by aglarendil** [comment]
RIght, this one is (hopefully) the final check before enabling the things.

**Pull request closed without merging**
