### PR TITLE
MDEV-19080 replace pthread_getspecific() with C++11 thread_local

### PR DESCRIPTION
**Pull request by kevgs**
This patch speeds up running tests in debug mode. When I build with -O2 I can
see speedup like 5% in --suite=main

rename dbug.c -> dbug.cc so it's became C++11 file

dbug.cc: introduce g_code_state TLS variable

st_my_thread_var: remove now unneded dbug member

mysql_heartbeat
timer_thread
worker_main
srv_master_thread: remove incorrect DBUG_ENTER() macros

my_thread_var_dbug(): removed as not needed

I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.4-dbug-tls)

### CODE REVIEW

**Comment by kevgs** [comment]
PR is not ready for review yet.

**Comment by svoj** [comment]
FWIW, some nice reading about TLS performance:
http://david-grs.github.io/tls_performance_overhead_cost_linux/
https://software.intel.com/en-us/blogs/2011/05/02/the-hidden-performance-cost-of-accessing-thread-local-variables

Apparently there're 3 modes of operation:
1. fully optimised, no different from local variable access
2. access with resolution (static build?)
3. access with even more complex resolution (dynamic build?)

**Comment by kevgs** [comment]
As @vaintroub mentioned, separating `dbug` from `st_my_thread_var` could break thread pool. I probably need to replace whole `THR_KEY_mysys` with `thread_local` instead.

**Comment by kevgs** [comment]
Closing now. I will rewrite this patch in the future.

**Comment by kevgs** [comment]
I'd better reuse that PR in the future. Trying hard to remember it...

**Pull request closed without merging**
