### PR TITLE
MDEV-8553: Impossible where for a!=a, a<a, a>a

### PR DESCRIPTION
**Pull request by grooverdan**
@igorbabaev, thanks for the review in #1027.

Here's the simpler version with more test cases and a more detailed commit message as requested.

Previously, `new (thd->mem_root) Item_bool(thd, false)` was from the 3 other cases in sql_select.cc where a FALSE condition seemed to be needed.
 
I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
The current behaviour is below. This patch will make columns with NULL allowed gain an Impossible Where optimization.


>     select version();
> 
> <pre>
> | version()                                   |
> | :------------------------------------------ |
> | 10.3.11-MariaDB-1:10.3.11+maria~stretch-log |
> </pre>


>      CREATE TABLE t1 (a TINYINT NOT NULL, KEY(a));
> 
> <pre>
> ✓
> </pre>


>      CREATE TABLE t2 (a TINYINT, KEY(a));
> 
> <pre>
> ✓
> </pre>


>     SHOW CREATE TABLE t1
> 
> <pre>
> Table | Create Table                                                                                                  
> :---- | :-------------------------------------------------------------------------------------------------------------
> t1    | CREATE TABLE `t1` (&lt;br&gt;  `a` tinyint(4) NOT NULL,&lt;br&gt;  KEY `a` (`a`)&lt;br&gt;) ENGINE=InnoDB DEFAULT CHARSET=latin1
> </pre>


>     SHOW CREATE TABLE t2
> 
> <pre>
> Table | Create Table                                                                                                      
> :---- | :-----------------------------------------------------------------------------------------------------------------
> t2    | CREATE TABLE `t2` (&lt;br&gt;  `a` tinyint(4) DEFAULT NULL,&lt;br&gt;  KEY `a` (`a`)&lt;br&gt;) ENGINE=InnoDB DEFAULT CHARSET=latin1
> </pre>


>     INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
> 
> <pre>
> ✓
> </pre>


>     INSERT INTO t2 VALUES (1),(2),(3),(4),(5);
> 
> <pre>
> ✓
> </pre>


>     EXPLAIN SELECT * FROM t1 WHERE a!=a;
> 
> <pre>
> id | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra           
> -: | :---------- | :---- | :--- | :------------ | :--- | :------ | :--- | ---: | :---------------
>  1 | SIMPLE      | <em>null</em>  | <em>null</em> | <em>null</em>          | <em>null</em> | <em>null</em>    | <em>null</em> | <em>null</em> | Impossible WHERE
> </pre>


>     EXPLAIN SELECT * FROM t2 WHERE a!=a;
> 
> <pre>
> id | select_type | table | type  | possible_keys | key | key_len | ref  | rows | Extra                   
> -: | :---------- | :---- | :---- | :------------ | :-- | :------ | :--- | ---: | :-----------------------
>  1 | SIMPLE      | t2    | index | <em>null</em>          | a   | 2       | <em>null</em> |    5 | Using where; Using index
> </pre>


>     EXPLAIN SELECT * FROM t1 WHERE a<a;
> 
> <pre>
> id | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra           
> -: | :---------- | :---- | :--- | :------------ | :--- | :------ | :--- | ---: | :---------------
>  1 | SIMPLE      | <em>null</em>  | <em>null</em> | <em>null</em>          | <em>null</em> | <em>null</em>    | <em>null</em> | <em>null</em> | Impossible WHERE
> </pre>


>     EXPLAIN SELECT * FROM t2 WHERE a<a;
> 
> <pre>
> id | select_type | table | type  | possible_keys | key | key_len | ref  | rows | Extra                   
> -: | :---------- | :---- | :---- | :------------ | :-- | :------ | :--- | ---: | :-----------------------
>  1 | SIMPLE      | t2    | index | <em>null</em>          | a   | 2       | <em>null</em> |    5 | Using where; Using index
> </pre>


>     EXPLAIN SELECT * FROM t1 WHERE a>a;
> 
> <pre>
> id | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra           
> -: | :---------- | :---- | :--- | :------------ | :--- | :------ | :--- | ---: | :---------------
>  1 | SIMPLE      | <em>null</em>  | <em>null</em> | <em>null</em>          | <em>null</em> | <em>null</em>    | <em>null</em> | <em>null</em> | Impossible WHERE
> </pre>


>     EXPLAIN SELECT * FROM t2 WHERE a>a;
> 
> <pre>
> id | select_type | table | type  | possible_keys | key | key_len | ref  | rows | Extra                   
> -: | :---------- | :---- | :---- | :------------ | :-- | :------ | :--- | ---: | :-----------------------
>  1 | SIMPLE      | t2    | index | <em>null</em>          | a   | 2       | <em>null</em> |    5 | Using where; Using index
> </pre>


>     EXPLAIN SELECT COUNT(*) FROM t1 WHERE not (a!=a);
> 
> <pre>
> id | select_type | table | type  | possible_keys | key | key_len | ref  | rows | Extra      
> -: | :---------- | :---- | :---- | :------------ | :-- | :------ | :--- | ---: | :----------
>  1 | SIMPLE      | t1    | index | <em>null</em>          | a   | 1       | <em>null</em> |    5 | Using index
> </pre>


>     EXPLAIN SELECT COUNT(*) FROM t2 WHERE not (a!=a);
> 
> <pre>
> id | select_type | table | type  | possible_keys | key | key_len | ref  | rows | Extra                   
> -: | :---------- | :---- | :---- | :------------ | :-- | :------ | :--- | ---: | :-----------------------
>  1 | SIMPLE      | t2    | index | <em>null</em>          | a   | 2       | <em>null</em> |    5 | Using where; Using index
> </pre>

*db<>fiddle [here](https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=f4b57e5eb6b34bd47d2d71a8f9bde3cf)*

**Comment by grooverdan** [comment]
@igorbabaev this has been changed as requested. Do you want more tests? I could cover other types however the code doesn't look at the types.

**Comment by grooverdan** [comment]
changed behaviour as requested. Is test converge sufficient? Its in a code branch where both sides are equal and there isn't many Item that return `Item::COND_FALSE` so should be quite easy to review.

**Comment by igorbabaev** [comment]
Daniel,
Anel,
The patch is OK.

**Comment by svoj** [comment]
Applied d2fa5f8 to 10.4. Sorry for this delay.

**Pull request closed without merging**
