### PR TITLE
MDEV-14753 Fix build on OSX with 10.13 SDK

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @howard0su !

Sorry for getting back to you so late on this. Thank you for the pull request. This is an issue that we have had for quite a while and I'll get this reviewed asap.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

**Comment by dr-m** [comment]
The patch looks OK to me (once the legal side has been clarified).
In fact, there was a similar pull request (iirc, against 10.2 even though the code was recently added by me in [MDEV-14477 in 10.3](https://jira.mariadb.org/browse/MDEV-14477)). From that pull request, I applied the main idea to 10.3, but did not copy the `const` keyword because I did not realize that it could make a difference.

**Comment by svoj** [comment]
@howard0su could you confirm you contribute this under BSD-new license?

**Comment by grooverdan** [comment]
JIRA issue: MDEV-14753

**Comment by howard0su** [comment]
contribution is under BSD-new license.

**Comment by dr-m** [comment]
Thank you @howard0su! I guess I should have done this as a merge instead of a cherry-pick, so that GitHub would have noticed the change. Included in commit 6fe953cb71241fd5ce583713deb854b4f6170f8c.

**Pull request closed without merging**
