### PR TITLE
MDEV-15048 - storage/innobase: Fix cmake compression library detection

### PR DESCRIPTION
**Pull request by Sp1l**
Applies to 10.2 as well
From FreeBSD port

### CODE REVIEW

**Comment by grooverdan** [comment]
Fails on travis:

<pre>
CMake Error at storage/innobase/lzo.cmake:40 (CHECK_LIBRARY_EXISTS):
  CHECK_LIBRARY_EXISTS Macro invoked with incorrect arguments for macro
  named: CHECK_LIBRARY_EXISTS
Call Stack (most recent call first):
  storage/innobase/innodb.cmake:30 (MYSQL_CHECK_LZO)
  storage/innobase/CMakeLists.txt:21 (INCLUDE)
</pre>

**Comment by janlindstrom** [comment]
Question: Why did you not add similar to lzma and bzip2 ? Can you rebase against 10.1 as it is the first release that supports this page compression. 

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Jan

**Comment by janlindstrom** [comment]
@an3l Can I close this as requested changes have not been done ?

**Comment by an3l** [comment]
Hi @janlindstrom , 
according to my opinion it is ok to close if you (as assignee) are not willing to improve it. 
Also when contributor is willing to improve it we can reopen it again.

**Comment by janlindstrom** [comment]
Closing as no reply.

**Pull request closed without merging**
