### PR TITLE
deb: autobake - add lunar/mantic

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-_____*

## Description
TODO: fill description here

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to
behave as intended. Consult the documentation on
["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).
In many cases, this will be as simple as modifying one `.test` and one `.result`
file in the `mysql-test/` subdirectory. Without _automated_ tests, future regressions
in the expected behavior can't be automatically detected and verified.

If the changes are not amenable to automated testing, please explain why not and
carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*

## Backward compatibility
TODO: fill details here, if applicable, or remove the section

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

### CODE REVIEW

**Comment by illuusio** [comment]
Are Lunar and Mantic based on Debian 11 packages?

**Comment by grooverdan** [comment]
lunar and mantic have a lsb-base consisting of a few `/usr/share/docs` files which I assume are unneeded  - https://packages.ubuntu.com/mantic/all/lsb-base/filelist.

kinetic/jammy have:
* /lib/lsb/init-functions.d/00-verbose
* /lib/lsb/init-functions.d/50-ubuntu-logging

These are important?

Should change should be?

```
diff --git a/debian/autobake-deb.sh b/debian/autobake-deb.sh
index 88b6dabd798..193a208476b 100755
--- a/debian/autobake-deb.sh
+++ b/debian/autobake-deb.sh
@@ -154,8 +154,10 @@ in
     replace_uring_with_aio
     disable_libfmt
     ;&
-  "impish"|"jammy"|"kinetic"|"lunar"|"mantic")
+  "jammy"|"kinetic")
     add_lsb_base_depends
+    ;&
+  "lunar"|"mantic")
     # mariadb-plugin-rocksdb s390x not supported by us (yet)
     # ubuntu doesn't support mips64el yet, so keep this just
     # in case something changes.

```

not: Taking into account impish's eol.

**Comment by illuusio** [comment]
> lunar and mantic have a lsb-base consisting of a few `/usr/share/docs` files which I assume are unneeded - https://packages.ubuntu.com/mantic/all/lsb-base/filelist.
> 
> kinetic/jammy have:
> 
>     * /lib/lsb/init-functions.d/00-verbose
> 
>     * /lib/lsb/init-functions.d/50-ubuntu-logging
> 
> 
> These are important?
> 
> Should change should be?
> 
> ```
> diff --git a/debian/autobake-deb.sh b/debian/autobake-deb.sh
> index 88b6dabd798..193a208476b 100755
> --- a/debian/autobake-deb.sh
> +++ b/debian/autobake-deb.sh
> @@ -154,8 +154,10 @@ in
>      replace_uring_with_aio
>      disable_libfmt
>      ;&
> -  "impish"|"jammy"|"kinetic"|"lunar"|"mantic")
> +  "jammy"|"kinetic")
>      add_lsb_base_depends
> +    ;&
> +  "lunar"|"mantic")
>      # mariadb-plugin-rocksdb s390x not supported by us (yet)
>      # ubuntu doesn't support mips64el yet, so keep this just
>      # in case something changes.
> ```
> 
> note: Taking into account impish's eol.

My opinion is that most correct one to implement this is to use Debian Bullseye/Bookworm approach where if it's  `"impish"|"jammy"|"kinetic"` then add `lsb-base` and if it's not then do not. From Lunar it's same dummy package and LSB SySV-init tools are installed quietly `sysv-utils` which is mandatory.

**Comment by illuusio** [comment]
New version should do the changes requested and in manual testing/bb it does add Lunar and does not prevent building with older Ubuntu version. This is LGTM.

**Pull request merged**
