### PR TITLE
MDEV-9872: New Power8 crc32(ieee) optimized functions

### PR DESCRIPTION
**Pull request by grooverdan**
These are different from the existing crc32 functions which
where really crc32c.

### CODE REVIEW

**Comment by grooverdan** [comment]
I submit this under the MCA

**Comment by svoj** [comment]
@grooverdan, where these implementations come from?

**Comment by svoj** [comment]
Also per my understanding the only difference between those two is polynomial. Can't these implementation share most of the code?

**Comment by svoj** [comment]
Pushed a2c826b6aa38d68e79a80499b0ecdc57ae98f8e0, c82bc561b5a20475a185db4aaae250e83b93af4c, 45ffbda79e22cdfb8841eaec3e81d689fbb5aaf2

**Comment by svoj** [comment]
Thanks for prompt fix!

**Comment by grooverdan** [comment]
The CRC32-IEEE polynomical constants where generated though https://github.com/antonblanchard/crc32-vpmsum/blob/master/crc32_constants.c, the rest was a re-factoring to reduce code sharing.

Thanks for the prompt commit.

**Pull request closed without merging**
