### PR TITLE
MDEV-14578: mysql_install_db install unix_socket plugin when --auth-r…

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
mtr failure:
<pre>
build-mariadb-server-10.2]$ mysql-test/mtr --mem --parallel=10
Logging: /home/dan/repos/mariadb-server-10.2/mysql-test/mysql-test-run.pl  --mem --parallel=10
vardir: /home/dan/repos/build-mariadb-server-10.2/mysql-test/var
Removing old var directory...
Creating var directory '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var'...
 - symlinking 'var' to '/dev/shm/var_auto_eD5E'
Checking supported features...
MariaDB Version 10.2.15-MariaDB
 - SSL connections supported
Using suites: main-,archive-,binlog-,binlog_encryption-,csv-,encryption-,federated-,funcs_1-,funcs_2-,gcol-,handler-,heap-,innodb-,innodb_fts-,innodb_gis-,innodb_zip-,json-,maria-,mariabackup-,multi_source-,optimizer_unfixed_bugs-,parts-,percona-,perfschema-,plugins-,roles-,rpl-,sys_vars-,unit-,vcol-,wsrep-,galera-,connect,mroonga/storage,mroonga/wrapper,rocksdb_rpl,rocksdb_sys_vars,rocksdb,sequence,sql_discovery,tokudb_parts,tokudb_mariadb,tokudb_sys_vars,tokudb_add_index,tokudb_bugs,tokudb_alter_table,tokudb,disks,metadata_lock_info,query_response_time,user_variables
Collecting tests...
Installing system database...
mysql-test-run: *** ERROR: Error executing mysqld --bootstrap
Could not install system database from /home/dan/repos/build-mariadb-server-10.2/mysql-test/var/log/bootstrap.sql
The /home/dan/repos/build-mariadb-server-10.2/mysql-test/var/log/bootstrap.log file contains:
/home/dan/repos/build-mariadb-server-10.2/sql/mysqld --no-defaults --disable-getopt-prefix-matching --bootstrap --basedir=/home/dan/repos/mariadb-server-10.2 --datadir=/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/install.db --plugin-dir=/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/plugins --default-storage-engine=myisam --loose-skip-plugin-aria --loose-skip-plugin-feedback --loose-skip-plugin-innodb --loose-skip-plugin-innodb-buffer-page --loose-skip-plugin-innodb-buffer-page-lru --loose-skip-plugin-innodb-buffer-pool-stats --loose-skip-plugin-innodb-cmp --loose-skip-plugin-innodb-cmp-per-index --loose-skip-plugin-innodb-cmp-per-index-reset --loose-skip-plugin-innodb-cmp-reset --loose-skip-plugin-innodb-cmpmem --loose-skip-plugin-innodb-cmpmem-reset --loose-skip-plugin-innodb-ft-being-deleted --loose-skip-plugin-innodb-ft-config --loose-skip-plugin-innodb-ft-default-stopword --loose-skip-plugin-innodb-ft-deleted --loose-skip-plugin-innodb-ft-index-cache --loose-skip-plugin-innodb-ft-index-table --loose-skip-plugin-innodb-lock-waits --loose-skip-plugin-innodb-locks --loose-skip-plugin-innodb-metrics --loose-skip-plugin-innodb-mutexes --loose-skip-plugin-innodb-sys-columns --loose-skip-plugin-innodb-sys-datafiles --loose-skip-plugin-innodb-sys-fields --loose-skip-plugin-innodb-sys-foreign --loose-skip-plugin-innodb-sys-foreign-cols --loose-skip-plugin-innodb-sys-indexes --loose-skip-plugin-innodb-sys-semaphore-waits --loose-skip-plugin-innodb-sys-tables --loose-skip-plugin-innodb-sys-tablespaces --loose-skip-plugin-innodb-sys-tablestats --loose-skip-plugin-innodb-sys-virtual --loose-skip-plugin-innodb-tablespaces-encryption --loose-skip-plugin-innodb-tablespaces-scrubbing --loose-skip-plugin-innodb-trx --loose-skip-plugin-partition --loose-skip-plugin-sequence --loose-skip-plugin-user-variables --loose-innodb --loose-innodb-log-file-size=5M --disable-sync-frm --tmpdir=/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/tmp/ --core-file --console --lc-messages-dir=/home/dan/repos/build-mariadb-server-10.2/sql/share/ --character-sets-dir=/home/dan/repos/mariadb-server-10.2/sql/share/charsets
2018-05-18 16:14:09 140435135702848 [Note] /home/dan/repos/build-mariadb-server-10.2/sql/mysqld (mysqld 10.2.15-MariaDB) starting as process 18256 ...
2018-05-18 16:14:09 140435135702848 [Warning] Could not increase number of max_open_files to more than 1024 (request: 4182)
2018-05-18 16:14:09 140435135702848 [Warning] Changed limits: max_open_files: 1024  max_connections: 151 (was 151)  table_cache: 421 (was 2000)
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'SEQUENCE' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'partition' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Uses event mutexes
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Using Linux native AIO
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Number of pools: 1
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Using SSE2 crc32 instructions
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Completed initialization of buffer pool
2018-05-18 16:14:09 140434613597952 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: The first innodb_system data file 'ibdata1' did not exist. A new tablespace will be created!
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Setting file './ibdata1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: File './ibdata1' size is now 12 MB.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Setting log file ./ib_logfile101 size to 5242880 bytes
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Setting log file ./ib_logfile1 size to 5242880 bytes
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: New log files created, LSN=45790
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Doublewrite buffer not found: creating new
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Doublewrite buffer created
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Creating foreign key constraint system tables.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Creating tablespace and datafile system tables.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Creating sys_virtual system tables.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: Waiting for purge to start
2018-05-18 16:14:09 140435135702848 [Note] InnoDB: 5.7.22 started; log sequence number 0
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'Aria' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_DATAFILES' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_TABLESTATS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_LOCKS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_MUTEXES' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMPMEM' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMP_PER_INDEX' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMP' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_DELETED' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMP_RESET' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_LOCK_WAITS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_TABLESPACES_ENCRYPTION' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_BUFFER_PAGE_LRU' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_FIELDS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMPMEM_RESET' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_COLUMNS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_INDEX_TABLE' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_CMP_PER_INDEX_RESET' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'user_variables' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_INDEX_CACHE' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_FOREIGN_COLS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_BEING_DELETED' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_BUFFER_POOL_STATS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_TRX' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_FOREIGN' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_TABLES' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_DEFAULT_STOPWORD' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_FT_CONFIG' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_BUFFER_PAGE' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_TABLESPACES' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_METRICS' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_INDEXES' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_VIRTUAL' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_TABLESPACES_SCRUBBING' is disabled.
2018-05-18 16:14:09 140435135702848 [Note] Plugin 'INNODB_SYS_SEMAPHORE_WAITS' is disabled.
ERROR: 1017  Can't find file: '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/tmp/#sql_4750_0.MYI' (errno: 2 "No such file or directory")
2018-05-18 16:14:09 140435135702848 [ERROR] Aborting
</pre>

**Comment by dbjpanda** [comment]
I still get this issue on 10.3. I am trying to install it on alpine docker `mysql_install_db --datadir=/var/lib/mysql --auth-root-socket-user=dev --auth-root-authentication-method=socket`.

> ERROR: 1126  Can't open shared library '/usr/auth_socket.so' (errno: 2, Error loading shared library /usr/auth_socket.so: No such file or directory)
> 2019-01-09 22:38:37 0 [ERROR] Aborting

**Comment by grooverdan** [comment]
Firstly lets not use github PRs as a issue tracker. jira.mariadb.org is for that and alpine also has a issue tracker.

The plugin dir that `mysql_install_db` as you can see from this PR is based on `INSTALL_PLUGIN_DIR` which seems to be set in the alpine packaging https://git.alpinelinux.org/aports/tree/main/mariadb/APKBUILD#n114.

Your bug might be a consequence of the alpine patch https://git.alpinelinux.org/aports/tree/main/mariadb/fix-mysql-install-db-path.patch. I suggest you log an issue with them. Putting `set -x -v` at the top of `mysql_install_db` in the issue might make it easier to diagnose.

**Comment by grooverdan** [comment]
@dbjpanda if you change `mysql` -> `mariadb` in https://github.com/MariaDB/server/blob/10.3/scripts/mysql_install_db.sh#L344 then using `mysql_install_db --basedir=/usr ....` will find the installed auth_socket.

Its definitely alpine's patch of removing `pkgplugindir` that causes it to not be found in the default case.

When I get back to MDEV-14580 hopefully alpine's patch won't be needed anymore.

**Comment by dbjpanda** [comment]
Thanks for providing the hints. However I tried changing from mysql to mariadb but it says `Duplicate entry 'unix_socket' for key 'PRIMARY'`

**Comment by dbjpanda** [comment]
Thanks for the hint. it solves my issue creating a symlink. `ln -snf /usr/lib/mariadb /usr/lib/mysql` However I am not in JIRA. So couldn't file a case there.

**Comment by grooverdan** [comment]
As an alternative https://mariadb.zulipchat.com/login/ has a github credentials for next time.

**Pull request closed without merging**
