### PR TITLE
fix debian typos

### PR DESCRIPTION
**Pull request by musvaage**
debian/additions/innotop/innotop
debian/additions/mariadb-report
debian/mariadb-server.postinst
debian/not-installed
debian/salsa-ci.yml

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]

**Review by ottok — APPROVED** [review]
Thanks, looks good to me!

**Comment by ottok** [comment]
Author of https://github.com/MariaDB/server/pull/2347.patch is `From: musvaage <musvaage@outlook.com>` - I leave it up to MariaDB Foundation staff to decide if they want to accept anonymous contributions. Anyway this is just a spelling fix, so it does not fill the definition of "work" that would be copyright protected, so if there is no copyright then authorship probably does not matter.

**Comment by musvaage** [comment]
CLA signing wasn't anonymous.

Etiquette really informs one should't post user's e-mail addresses; accordingly please delete your previous comment.

**Comment by LinuxJedi** [comment]
> Author of https://github.com/MariaDB/server/pull/2347.patch is `From: musvaage <musvaage@domain>` - I leave it up to MariaDB Foundation staff to decide if they want to accept anonymous contributions. Anyway this is just a spelling fix, so it does not fill the definition of "work" that would be copyright protected, so if there is no copyright then authorship probably does not matter.

There are plenty of contributions via anonymous email addresses, we are fine with this. Only real (minor) issue is that it becomes a little difficult to attribute the person to an organisation (if applicable) for the metric reports when this happens.

**Comment by LinuxJedi** [comment]
> CLA signing wasn't anonymous.
> 
> Etiquette really informs one shouldn't post users' e-mail addresses; accordingly please delete your previous comment.

I have deleted the comment that was edited so that your email address is not showing even when looking at comment edits.

**Comment by illuusio** [comment]
Wording seems to be better than before and typos fixed.

**Comment by musvaage** [comment]
The considerations of the author of the CODEOWNERS file are acknowledged.

The comment in question included a link to the raw patch.

Now a second comment includes, albeit quoted, a link to the raw patch.

My considerations pertain to web indexing; accordingly please delete the cited comments.

**Comment by illuusio** [comment]
Could these fixes be done at some version that is lower than 10.10 like 10.5 or even 10.3?

**Comment by musvaage** [comment]
@an3l 

Care to respond on the previous comment?

https://github.com/MariaDB/server/commit/b9c1c07f83936ac972ace191c77e6f9d8b03302b

10.11 `#2249`
mariadb-10.11.1 …  mariadb-10.3.37
@iangilfillan authored and @grooverdan committed on Sep 20

2 files changed, 4 insertions(+), 4 deletions(-)
Docs/README-wsrep
Docs/myisam.txt

<hr>

There's a sibling PR open regarding header typo fixes.

**Comment by grooverdan** [comment]
seems safe enough for 10.3

**Comment by musvaage** [comment]
@illuusio 

What's the motivation for your comment?

debian/additions/innotop/innotop
debian/additions/mariadb-report

Excluding the above files the changes pertain exclusively to comments.

**Comment by grooverdan** [comment]
```
$  git blame debian/salsa-ci.yml | grep avoitda
ecb1b8721ba6 (Otto Kekäläinen 2020-08-23 23:49:43 +0300 363)     # Run each step separately to avoitda 800+ lines chunk that lacks the
$ git tag --contains ecb1b8721ba6
(10.5)
```

```
$ git blame debian/not-installed | grep -i embeded
d426d0782da3
$ git branch  --contains d426d0782da3
10.9
```

Other changes pushed to 10.3.

**Comment by grooverdan** [comment]
So can you create and new PR (or 2, or rebase) against those two versions?

I've taken care of the 10.3 version.

Can you follow the same process with #2348, apply a fix against the introduced version.

**Comment by musvaage** [comment]
https://github.com/MariaDB/server/pull/2378, https://github.com/MariaDB/server/pull/2379

> same process with `#2348`

I can take care of header typos (10.3, 10.5, 10.9) after the foregoing are merged.

**Comment by musvaage** [comment]
`#2379` failed check buildbot/amd64-ubuntu-2004-debug

**Comment by grooverdan** [comment]
Closed from contributions in other PRs. Thank you.

Occasionally a buildbot worker will fail. If you can't see if its likely to be relevant to your change just leave/note it.

**Pull request closed without merging**
