### PR TITLE
stop covering_keys from being set to the same thing twice

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
@svoy, you like deleting useless code right (especially in used paths)? `covering_keys` is set in the line before this code deletion.

**Comment by svoj** [comment]
@grooverdan I'd gladly merge this, but I'm not sure which lines were correct. I'll try to discuss with @vuvova during the meetup.

**Comment by svoj** [comment]
Approved by @vuvova, now waiting for 10.4 to get unblocked.

**Comment by svoj** [comment]
Unfortunately I messed up this PR by my curiosity: pressed "Update branch" button and got merge revision there. So I cherry-picked your revision instead: 31b65d3dd211826b194a9a2e6894816ccd05b707

**Comment by grooverdan** [comment]
Thanks for the merge.

**Comment by grooverdan** [comment]
you might of been able to `git push -f` to `refs/pull/1035`

**Pull request closed without merging**
