### PR TITLE
MDEV-28191: Stop flooding Lintian with mariadb-test-data-10.6 package

### PR DESCRIPTION
**Pull request by illuusio**
- [x] *The Jira issue number for this PR is: MDEV-28191*

## Description
MariaDB test data package contains result files that are not in-line with Debian Lintian rules. As they are in *correct place* they are just noise (there is ~480 lines which this patch suspends)
Suspeded Lintian Problems are:

 * national-encoding (iso-8859-1 charset) at usr/share/mysql/mysql-test/include/
 * package-contains-documentation-outside-usr-share-doc file that are installed usr/share/mysql/mysql-test
 * repeated-path-segment in several places usr/share/mysql/mysql-test

## How can this PR be tested?
Salsa-CI run: https://salsa.debian.org/illuusio/mariadb-server/-/jobs/2616337/raw

Build manually:
```
debian/autobake-deb.sh
lintian ../*.chages
```
The shouldn't be lines like:
`W: mariadb-test-data: national-encoding usr/share/mysql/mysql-test/include/...`
and
`I: mariadb-test-data: package-contains-documentation-outside-usr-share-doc usr/share/mysql/mysql-test/
Any more

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
Should not affect

### CODE REVIEW

**Comment by ottok** [comment]
Making one commit per Lintian override will clutter the MariaDB git history. Why not make a big comparison of all Lintian overrides downstream vs upstream and fix them in one go?

image

Or use `git am` to import one single commit https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d779a4f4f3c943799097ee29488b77c63729e155 (`git am https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d779a4f4f3c943799097ee29488b77c63729e155.patch`) and get these done in one go, and then focus you energy on fixing the remaining Lintian issues instead of just re-doing something that was already done?

**Comment by illuusio** [comment]
> Making one commit per Lintian override will clutter the MariaDB git history. Why not make a big comparison of all Lintian overrides downstream vs upstream and fix them in one go?
> 
> image
> 
> Or use `git am` to import one single commit https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d779a4f4f3c943799097ee29488b77c63729e155 (`git am https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d779a4f4f3c943799097ee29488b77c63729e155.patch`) and get these done in one go, and then focus you energy on fixing the remaining Lintian issues instead of just re-doing something that was already done?

Those are the stuff that needs little bit investigation that are they false-positives or just errors?

**Comment by illuusio** [comment]
And yes at least this should fix all test packages Lintian problems that drops in a Wont be Fixed category

**Review by ottok — CHANGES_REQUESTED** [review]
I am strongly against adding Lintian overrides to the MariaDB with one commit = one override. At minimum you should squash these two commits.

Even better, copy most of https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d779a4f4f3c943799097ee29488b77c63729e155  over to upstream if you agree with the commit message motivation in that commit.

**Comment by illuusio** [comment]
Ok I'll check 10.6 stuff and update this..

**Comment by illuusio** [comment]
@ottok ok now there is all in one commit solution and added Debian Lintian stuff also in. Let's wait for BB and https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/370756

**Comment by ottok** [comment]
Looking at what you pushed for Salsa-CI to run, the commit ID does not match:
image

So I compared https://github.com/illuusio/server/commit/ee9441cd988b3ab652d39a0f690ccd62e3d48fb0.patch and https://salsa.debian.org/illuusio/mariadb-server/-/commit/8e519d48ce57f860700177ceb308625176643344.patch manually:
image

The other one has "Gitlab" and the end. Weird. How did you end up with that? Would it not be much less work to simply push the exact same commit to both places? What remotes do you have in `git remote -v`? Do you have a habit of running something along `git push -fv github 10.6-MDEV-28191-mariadb-test-data; git push -fv salsa 10.6-MDEV-28191-mariadb-test-data`?

**Review by ottok — APPROVED** [review]
Despite oddities in reviewing Salsa-CI run, the change is good, hence approving now.

**Pull request merged**
