### PR TITLE
improve(test) framework manual is moved

### PR DESCRIPTION
**Pull request by tsasaki609**
Hello,
I was reading the source and found a small problem. 
A few link of some URL written in the comment seems to have moved.
I fixed the link of the URL I wanted to see.
But there seems to be another similar links.
If necessary, I can also fix it. How do you like it?

### CODE REVIEW

**Comment by tsasaki609** [comment]
I didn't know that there was such a page. Thank you.

**Comment by svoj** [comment]
Hi @tsasaki609,

Thanks for your contribution. Could you re-target this patch for 5.5? I can do it myself, but then I can't use this shiny "Rebase and merge" button.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by tsasaki609** [comment]
Hi @svoj , 
I tried to change it from 10.4 on the gui to 5.5, but it is troublesome that various conflicts occur.
I will change it later by cli.

**Comment by svoj** [comment]
@tsasaki609 you need to use both cli and gui. Cherry-pick your patch to 5.5 and then force push into `tsasaki609:10.4-improve-comment`. Then you can use cli to update version.

**Comment by tsasaki609** [comment]
Hi @svoj ,
I re-target to 5.5.
I submit my code of the whole pull request under the BSD-new license.

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
