### PR TITLE
galera configuration not just [mysqld]

### PR DESCRIPTION
**Pull request by grooverdan**
Corrects d48ac8b414d6ada00fb3f9b904266954de9cf6de and 7e8ed15b95b64af2068a3515fe97f2c245311323 which erroneously assumed that the `[mysqld$suffix]` section of the configuration file had precedence for `innodb-data-home-dir`.

parse_cnf though the setting of `$MY_PRINT_DEFAULTS` already accounts the various --defaults* options passed to mysqld so any attempted probing of mysqld  options should use `parse_cnf --mysqld`

Also corrects original mariabackup sst script (3d8aacba861044843417b710fff208b8bd6a53c4)

mtr tests copy off the existing test, changing the  section details in the .cnf file, and return the same results.

I submit this under the MCA. Backports at your discretion.

### CODE REVIEW

**Comment by janlindstrom** [comment]
Hi,

All tests do not pass as it is:

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
SELECT VARIABLE_VALUE LIKE '%[::1]%' FROM INFORMATION_SCHEMA.GLOBAL_STATUS WHERE VARIABLE_NAME = 'wsrep_incoming_addresses';
VARIABLE_VALUE LIKE '%[::1]%'
1
SELECT VARIABLE_VALUE = 3 FROM INFORMATION_SCHEMA.GLOBAL_STATUS WHERE VARIABLE_NAME = 'wsrep_cluster_size';
VARIABLE_VALUE = 3
1
SET GLOBAL wsrep_provider_options='gmcast.isolate=1';
CREATE TABLE t1 (f1 INTEGER) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
SET GLOBAL wsrep_provider_options='gmcast.isolate=0';
SELECT COUNT(*) = 1 FROM t1;
COUNT(*) = 1
1
DROP TABLE t1;
include/assert_grep.inc [Streaming the backup to joiner at \[::1\]]
include/assert_grep.inc [async IST sender starting to serve tcp://\[::1\]:]
galera_3nodes.galera_ipv6_mariabackup_section 'xtradb' [ fail ]
        Test ended at 2019-03-06 13:54:47

CURRENT_TEST: galera_3nodes.galera_ipv6_mariabackup_section
mysqltest: In included file "./include/show_rpl_debug_info.inc": 
included from ./include/assert_grep.inc at line 134:
included from /home/jan/mysql/10.1-galera/mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup_section.test at line 54:
At line 52: Cannot perform inc/dec on a non-numeric value

**Comment by janlindstrom** [comment]
Hi, actually this looks fine. In 10.1 using Galera 3 just expected output is different compared to 10.4 using Galera 4.

**Comment by janlindstrom** [comment]
Merged changes to 10.1

commit b31d025c97cf49ea9d0da26e5948f693e8af60dc (HEAD -> 10.1, origin/bb-10.1-galera, origin/10.1, bb-10.1-galera)
Author: Jan Lindström <jan.lindstrom@mariadb.com>
Date:   Fri Mar 8 10:13:14 2019 +0200

    Decrease the time required to run test by removing unnecessary sleeps.
    
    modified:   suite/galera/t/galera_autoinc_sst_mariabackup.test

commit 9fb84a166ac3f4389d400439d13d2a790c18de1b
Author: Jan Lindström <jan.lindstrom@mariadb.com>
Date:   Thu Mar 7 08:06:50 2019 +0200

    remove WSREP_SST_OPT_SUFFIX_VALUE, checking [mysqld] is covered in the parse_cnf --mysqld case also in wsrep_sst_xtrabackup-v2

commit a05ca1a99a821eb8c9e117e681d37327f265fc92
Author: Jan Lindström <jan.lindstrom@mariadb.com>
Date:   Wed Mar 6 16:41:40 2019 +0200

    Galera 3 versions of the result files recorded.

commit e8541c7565c2b44460007ec03c01a4f171247c1a
Author: Daniel Black <daniel@linux.ibm.com>
Date:   Tue Mar 5 15:29:24 2019 +1100

    galera: test cases for non [mysqld] section for configuration

commit 85a18526bc210e05c8a6feeb053c08f6e8cc867f
Author: Daniel Black <daniel@linux.ibm.com>
Date:   Tue Mar 5 14:01:02 2019 +1100

    wsrep_sst: remove WSREP_SST_OPT_SUFFIX_VALUE, checking [mysqld] is covered in the parse_cnf --mysqld case

**Comment by janlindstrom** [comment]
This has now being merged all the way up to 10.4.

**Comment by grooverdan** [comment]
Thanks Jan

**Pull request closed without merging**
