### PR TITLE
MDEV-9158: disable IPv6 tests on travis

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by svoj** [comment]
Why didn't include/check_ipv6.inc work? Probably it is better to fix it?

**Comment by grooverdan** [comment]
I can't see where the processing of --source is done at the moment. Added --verbose to hope to see it. Yes include/check_ipv6.inc (3febb3ce,3889b19f) should be fixed.

This adds a useful enough exclude framework for the time being.

**Comment by svoj** [comment]
@ottok, could you handle this PR?

**Comment by grooverdan** [comment]
fix in #223

**Pull request closed without merging**
