### PR TITLE
Further tweaking the alloca handling in Hashicorp plugin

### PR DESCRIPTION
**Pull request by brad0**
Adding my_global.h to be able to pull in HAVE_ALLOCA_H, but also simplify the headers a bit.

### CODE REVIEW

**Comment by brad0** [comment]
I just noticed my_global.h already does try to include the alloca.h header so simplify things even further.

**Comment by brad0** [comment]
The only failure is with a test that does not appear to have any to do with this PR.

**Comment by dr-m** [comment]
> The only failure is with a test that does not appear to have any to do with this PR.

Right, according to the [server error log](https://ci.mariadb.org/29214/logs/amd64-ubuntu-2004-debug/mysqld.1.err.4) it looks like a hung shutdown in an unrelated test.
```
CURRENT_TEST: main.statistics_upgrade_not_done
2022-10-16  2:27:56 324 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
2022-10-16  2:27:56 324 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2022-10-16  2:27:56 324 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
2022-10-16  2:27:56 324 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2022-10-16  2:27:56 0 [Note] /home/buildbot/amd64-ubuntu-2004-debug/build/sql/mariadbd (initiated by: root[root] @ localhost []): Normal shutdown
221016  2:28:56 [ERROR] mysqld got signal 6 ;
```
There is a 60-second timeout in server shutdown. After the initial signal, SIGABRT will be sent. Unfortunately, no core dump will be generated and stack traces of all threads will not be output.

The likely culprit for this hang could be one of the preceding tests that are listed as `CURRENT_TEST:` between the server startup and this test:
```
Version: '10.9.4-MariaDB-debug-log'  socket: '/home/buildbot/amd64-ubuntu-2004-debug/build/mysql-test/var/tmp/4/mysqld.1.sock'  port: 16400  Source distribution
CURRENT_TEST: main.index_intersect_innodb
…
CURRENT_TEST: main.statistics_upgrade_not_done
```

**Comment by brad0** [comment]
Is this Ok? Can it go in?

**Review by grooverdan — APPROVED** [review]

**Pull request merged**
