### PR TITLE
Deb: Misc fixes for 10.11 series

### PR DESCRIPTION
**Pull request by ottok**
## Description

Misc fixes for 10.11 series while polishing its Debian packaging:

- Prefer Breaks+Replaces over Conflicts+Replaces in debian/control.

- Clean away conflict/break/replace with self as it either has no effect or harmfully prevents upgrades to self (packages from this source version).

- Remove references to mariadb-server-10.11 as the package names no longer have versions and thus such references are unnecessary cruft.

- Apply 'wrap-and-sort -av' and minor typo fixing.

- Extend Salsa-CI to test for upgrades from 10.9 and 10.10 to 10.11.

- Add minimal required new Lintian overrides so Salsa-CI would not fail on Lintian.

## How can this PR be tested?

Salsa-CI provides best test coverage.

Before:
https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/475866
image

After:
https://salsa.debian.org/otto/mariadb-server/-/pipelines/476266
image

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility

Any changes on 10.11 should be fine for now as it is not released yet.

### CODE REVIEW

**Comment by grooverdan** [comment]
I'm confused over "Prefer Breaks+Replaces over Conflicts+Replaces in debian/control."

From https://www.debian.org/doc/debian-policy/ch-relationships.html#s-conflicts
"Conflicts should be used ... when two packages provide the same file and will continue to do so,"

So isn't (for example) mariadb-server-core (`${source:Version}`) always providing the same files, and hence conflicting with `mariadb-server-core (<< ${source:Version})`?

In https://github.com/MariaDB/server/pull/2390/commits/44666cbf737b4eb1d73b39a28c9df64226f55a0b#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0 it was possible to just Conflicts (but it was a simplier case)

**Comment by ottok** [comment]
> I'm confused over "Prefer Breaks+Replaces over Conflicts+Replaces in debian/control."
> 
> From https://www.debian.org/doc/debian-policy/ch-relationships.html#s-conflicts "Conflicts should be used ... when two packages provide the same file and will continue to do so,"

Using `Conflicts` will make apt in some cases uninstall the previous package first, and then install the new one. This leads occasionally to odd cases, like server pre-install script trying to run `mariadb` binary from client package that was removed from filesystem during the dpkg run and will come back only once dpkg proceeds.

Using `Breaks` is kind of softer, and allows packages to be unpacked on top of each other.

That said, exact behavior is difficult to predict as the apt resolver might end up doing various things in various situations and in particular with the `debian/control` file in MariaDB the scenarios are too complex for humans to predict outcome on.

In my testing the above creates the smoothest upgrade experience, so I am vetting for it.

What comes to https://github.com/MariaDB/server/commit/44666cbf737b4eb1d73b39a28c9df64226f55a0b#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0 I suggest you keep it as a draft until we have proper Salsa-CI on upstream 11.0 branch AND I have finished doing the 10.11 packaging and got it into Debian official with all corner cases solved.

**Comment by grooverdan** [comment]
Can you please allow editing on PRs so "Rebase and merge" can happen. I'm blocked by doing so:

image

**Comment by ottok** [comment]
Rebases on latest 10.11 and allowed edits by maintainers.

**Comment by illuusio** [comment]
> Using `Breaks` is kind of softer, and allows packages to be unpacked on top of each other.

I just read also about this and is it so that `breaks` tells dpkg to ignore problems as they are solved when all packages are installed. I could understand that wrongly.

**Pull request merged**
