### PR TITLE
Deb: libcurl4 in bionic+/buster+

### PR DESCRIPTION
**Pull request by grooverdan**
I came across that libcurl is version 4 in bionic+/buster+. May as well use this and fall back to libcurl3.

I submit this under the MCA.

### CODE REVIEW

**Comment by cvicentiu** [comment]
Running this through old buildbot then merging.

**Comment by ottok** [comment]
@grooverdan Do you want to expand this by also updating libcurl3 -> libcurl4 in the .travis-ci.yml file and other potential locations (RPM stuff?) so that the latest curl library version is used everywhere in the 10.5 code base?

**Comment by ottok** [comment]
..and rebase on latest 10.5.

**Comment by grooverdan** [comment]
I don't want to touch .travis.yml since most branches there are xenial and therefore don't have curl4. RHEL8 is sane enough not to include two version and builds dependencies on what's compiled, similar to Debian. No other references exist. Rebase isn't required as it still merges cleanly despite your efforts. :-)

**Comment by ottok** [comment]
Right. We should maybe update the 10.5 branch Travis to run off bionic by default, it would most likely make sense as new 10.5 installs are not likely to target xenial that much anymore.

**Comment by grooverdan** [comment]
Right. But that can be done as a separate commit.

**Comment by cvicentiu** [comment]
Ok, I investigated this a bit more. Buildbot produced green output, but there is a catch!

Turns out libcurl4 has had an API change compared to libcurl3, however the server only uses a set that has remained stable between libcurl3 and libcurl4 (namely the easy_ prefix of functions).

Sadly this code is not really tested properly, because the server compiles just fine without libcurl4-dev available at all. CMake magic takes care of it. One needs to be very careful when making such library version changes and double check things locally.

**Comment by cvicentiu** [comment]
In the future we'll get code-coverage working again and hopefully we'll be able to get a feel for where things get tested today and what's lacking.

**Comment by ottok** [comment]
I am a bit late to this one now, but I noticed that there is actually no libcurl4-dev package in Debian. These are the options, we should pick one:
```
libcurl4-gnutls-dev
libcurl4-nss-dev
libcurl4-openssl-dev 
```
https://tracker.debian.org/pkg/curl

libcurl4-dev only exists as a virtual pacakge

**Comment by ottok** [comment]
Final tweak done in https://github.com/MariaDB/server/commit/b541defea09b658e6714e0c8b08d10741185b2ed

**Pull request merged**
