### PR TITLE
MDEV-17508 Fix bug for spider when using "not like"

### PR DESCRIPTION
**Pull request by willhan123**
query "select * from t1 where name not like 'x%' " would get a  wrong result.

test case:
t1 is a spider engine table;
  CREATE TABLE `t1` (
  `id` int(11) NOT NULL DEFAULT '0',
  `name` char(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=SPIDER

query: "select * from t1 where name  not like 'x%' " would dispatch "select xxx name name like 'x%' " to remote mysql,  would get a wrong result.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @willhan123 

Thanks for your contribution.
Corresponding JIRA task **MDEV-17508** is added.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by an3l** [comment]
Please update your PR with test and result file so we could track easier.
To learn more about I encourage you to see how to write a good test case:
https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server/

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
1

**Comment by willhan123** [comment]
1

> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

- 

- @an3l

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by willhan123** [comment]
123

**Comment by willhan123** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

Hi anel,
     Thanks for your reply.
     I' am willhan,the member of Tencent Games.  And Tencent Game has become gold sponsor of Mariadb Foundation. (https://mariadb.org/tag/tencent-games/).
     I have signatured  under the BSD-new license too.

**Comment by felixliang** [comment]
> Hi @willhan123
> 
> Thanks for your contribution.
> Corresponding JIRA task **MDEV-17508** is added.
> 
> Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
> 
> The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
> 
> Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
> 
> Thanks,
> Anel

############
@an3l hi anel, i and will are workmate of Tencent Game DBA Team, and our team is signed MCA two years ago at 2016.10.17, should willhan contribute the bug fix under MCA, it is the most easier way for us to summit code to Spider.

[MCA.pdf](https://github.com/MariaDB/server/files/2517250/MCA.pdf)

**Comment by willhan123** [comment]
> Hi @felixliang and @willhan123 ,
> Thank you for clarifying the patch's licensing terms. We will review this as soon as possible.
> If possible for you, please add a test case for this patch. It helps both reviewer now and for maintenance later.

I have add a test case for this patch. The case was named spider_bug_fix.test ,  and We would submit more bug fixes later.

**Comment by Kentoku** [comment]
Please change test/result file name from "spider_bug_fix" to "pushdown_not_like", then ok to push.

**Comment by willhan123** [comment]
> Please change test/result file name from "spider_bug_fix" to "pushdown_not_like", then ok to push.

done

**Comment by an3l** [comment]
Hi @willhan123 can you please rebase everything in single commit and with commit message "MDEV-17508 Fix bug for spider when using "not like" ?

**Comment by willhan123** [comment]
> Hi @willhan123 can you please rebase everything in single commit and with commit message "MDEV-17508 Fix bug for spider when using "not like" ?

done

**Pull request merged**
