### PR TITLE
MDEV-23143 Add support for json_equals

### PR DESCRIPTION
**Pull request by ericherman**
- [x] *The Jira issue number for this PR is: MDEV-23143*

## Description
This adds the "JSON_EQUALS(a, b)" function

## How can this PR be tested?
The tests included in `mysql-test/main/json_equals.test` show some ways in which to test the function.

Most tests are of the form `select json_equals('{"foo":"bar"}', '{"foo":"bar"}')`

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
Should not have backward-compatibility issues, unless an installation has a function defined with the same name.

## Thanks:
Also a big thank you to @cvicentiu for all of his help and pair-programming, especially in the Item space.

### CODE REVIEW

**Comment by ericherman** [comment]
I am happy to squash the commit history down if that would be desired.

Also a big thank you to @cvicentiu for all of his help and pair-programming, especially in the Item space.

**Comment by ericherman** [comment]
https://jira.mariadb.org/browse/MDEV-23143

**Comment by cvicentiu** [comment]
@holyfoot @vuvova your review of this would be greatly appreciated. :)

**Comment by ericherman** [comment]
An obvious follow-on patch would be to expose "json_normalize".

I'd rather that be a separate work because exposing the current internal representation would invite future backwards compatibility issues.

The number formatting is not sufficiently defined in the [expired draaft JSON Canonical Form](https://datatracker.ietf.org/doc/html/draft-staykov-hu-json-canonical-form-00), which invites the task of comparing to other databases and implementations.

Additionally, exposing the sort order of the keys would require sorting of keys to become unicode code-point aware, rather than simple sorting.

**Comment by vuvova** [comment]
I think that `JSON_EQUAL` has a very limited usage. For example, one can, indeed, hack together some application that uses `JSON_EQUAL` to see if all JSON documents in a table are different. You know, like,
```sql
IF (SELECT COUNT(*) FROM t1 WHERE JSON_EQUAL(json_column, @new_json_data)) = 0
THEN
  INSERT INTO t1 (json_column) VALUES (@new_json_data);
END IF
```
but that's *not* how people normally maintain uniqueness of a data in a column in SQL (not mentioning that it's a full table scan, so O(N²) on the number of inserted rows).

With `JSON_NORMALIZE` you can do proper UNIQUE constraints, GROUP BY and DISTINCT. And you can compare for equality too, like `json_normalize(a) = json_normalize(b)`. So `JSON_NORMALIZE`, I'd say, is the main functionality here, while `JSON_EQUAL` is secondary to it.

If your internal normalization doesn't properly handle unicode you have a problem anyway, no matter how the function is called. On comparison you'll treat some keys or values different, when unicode tells they're identical. Like `ț` and `ț` — these values are equal, but not bytewise identical.

As for "not sufficiently defined" and "comparing to other databases and implementations" — I'd think it'd be enough to have stable and comparable results _within MariaDB_ and they don't necessarily have to be comparable over different JSON implementations. That, indeed, would be a task for another day, if at all.

**Comment by ericherman** [comment]
@cvicentiu informs of a discussion with @vuvova regarding string normalization, and this highlights what is for me a clear deficiency in the current code:

`021B LATIN SMALL LETTER T WITH COMMA BELOW`

Compared to two characters 

`0074 LATIN SMALL LETTER T` and `0326 COMBINING COMMA BELOW`

This is a real-world deficiency which reviewers should strongly consider.

**Comment by ericherman** [comment]
We need to decide on 'Normal Form Composed' vs. 'Normal Form Decomposed'.

It would be good to consider "NFKC" and "NFKD" regarding "compatibility" codepoints, like `U+2160 ROMAN NUMERAL ONE` and `U+0049 LATIN CAPITAL LETTER I` ....

**Comment by ericherman** [comment]
[Unicode® Standard Annex #15 Unicode Normalization Forms](https://unicode.org/reports/tr15/)

**Comment by vaintroub** [comment]
there is apparently an opinion that JSON should not necessarily be canonicalized in Unicode Normalization form meaning of it
https://github.com/gibson042/canonicaljson-spec/issues/8

**Comment by ericherman** [comment]
> there is apparently an opinion that JSON should not necessarily be canonicalized in Unicode Normalization form meaning of it
> [gibson042/canonicaljson-spec#8](https://github.com/gibson042/canonicaljson-spec/issues/8)

I guess I can see that argument also: how is the code supposed to know under what situations U+2160 ROMAN NUMERAL ONE and U+0049 LATIN CAPITAL LETTER I are the same and different?

Also, that repo references an old version of the JSON spec. Is that repo endorsed by anyone? Or was it someone on their own trying to take a good stab at advancing the now expired draft normalization spec?

**Comment by ericherman** [comment]
The issue of unicode string comparison is deeper than JSON. Consider the following:

```
create table t1 (a varchar(200) character set utf8mb4) default charset utf8mb4 collate utf8mb4_bin;
create table t2 (a varchar(200) character set utf8mb4) default charset utf8mb4 collate utf8mb4_bin;
insert into t1 values (UNHEX('2261cc8822'));
insert into t2 values (UNHEX('22c3a422'));
```

We now have a from of `"ä"` in both tables, however they are not equal:

```
select  t1.a = t2.a from t1, t2;
t1.a = t2.a
0
```

And while they each contain themselves:

```
select json_contains(t1.a, t1.a), json_contains(t2.a, t2.a) from t1,t2;
json_contains(t1.a, t1.a)	json_contains(t2.a, t2.a)
1	1
```

They do not contain each other:

```
select json_contains(t1.a, t2.a), json_contains(t2.a, t1.a) from t1,t2;
json_contains(t1.a, t2.a)	json_contains(t2.a, t1.a)
0	0
```

Do we want `json_equals` to be different than string `=` and `json_contains`?

**Comment by vaintroub** [comment]
I think, it is not practical to address the normalization forms, until we do full featured ICU integration corresponding to the latest Unicode standard.  Thus, I'd just ignore that, especially because it is not an issue normally. Unicode data is usually precomposed  For example, I've never seen a decomposed "ä" except in Unicode database and Unicode consortium examples.

There is no standard for JSON normalization, that I'd know of, endorsed by respectable standardization bodies,  and the RFC had been abandoned AFAIK. So you might to roll out your own normalization as well, and decide what to ignore, e.g Unicode normalization.

With that, maybe we should take a closer look at normalization of numeric literals, there are some well-known, and relatively easy to understand and implement "canonicalization" for that , e.g the XML Schema datatypes https://www.w3.org/TR/xmlschema-2/#double

**Comment by ericherman** [comment]
If the server codebase already has a better library function for double-to-string than `my_gcvt`, please point me to it. Writing new code for printing numbers strikes me as quite out-of-scope for [MDEV-23143 missing a JSON_EQUALS function, created 2020-07-10](https://jira.mariadb.org/browse/MDEV-23143).

I suggest that a natural follow-on to this work would be an MDEV about providing a json_normalize function, given all the doors which json_normalize would open. Inside of that new MDEV, interested parties could discuss and lay out what the formats and options should be, perhaps including parameters for unicode normal forms. I expect we might see add-on MDEVs for unicode string equality with regards to different forms, also. Regardless, if we already have this MDEV-23143 work in place, additional work to satisfy a new MDEV for json_normalize should be reduced.

**Comment by vaintroub** [comment]
JSON is text, and naturally numbers are given as text. Normalization of number is a text to text lossless conversion.  converting string to IEEE double and to back is not lossless, and, rather surprisingly, sometimes suffers portability problems.

**Comment by ericherman** [comment]
> Normalization of number is a text to text lossless conversion

There is no "text to text lossless conversion" code in the server codebase that I know of (nor in this patch), but it is certainly true that it _could_ be done that way ... and while it would be tedious, is a suggestion worthy of strong consideration. Thank you.

**Comment by ericherman** [comment]
@vaintroub number normalization is now text-to-text lossless.

@vuvova json_normalize is now exposed as an SQL function

Reviewers should note that this does normalization only; canonicalization (e.g.: multiple representation of `ä` as a single code point or two) is not a part of this work.

**Review by holyfoot — COMMENTED** [review]
Hi.
Two first comments.
The DYNAMIC_STRING is used in the json_normalize(). But in the Item::val_str() we have the String result to fill.
So you have to copy the DYNAMIC_STRIN into the String result. I'd propose to use the String in the json_normalize() then we don't have to do the extra copying. And which can be even more important we don't have to do that many memory allocations - as any new DYNAMIC_STRING in the ::val_str() is at least one malloc while that String buffer can be reused.

Then i see the mess with the character sets. The normalized JSON should be in UTF8, but the Item_func_json_normalize::fix_length_and_dec() declares the resulting charset to be same as the argument's. I think it should always be UTF8-MB4. Then the ::val_str() doesn't take the argument's charset in the account at all. And if it's not compatible with the argument's we'd get the wrong result. I think the argument's charset has to be verified and converted into UTF8 if necessary.

**Comment by ericherman** [comment]
> I'm curious why the 'enum json_value_types' from the json_lib.h was not enouth so you added the json_temp_type?

The "json_temp_type" only existed momentarily while all the code was still inside the unit test file, durring which time I was sketching out how the basic functionality would work. You should see that it became evident that `enum json_value_types` was perfectly suitable and that is what is used in the code before it was extracted out of the unit test and into the `strings/json_normalize.c` file.

As stated above, I can squash the commit history if that would be desired.

**Comment by holyfoot** [comment]
> The "json_temp_type" only existed momentarily
right. I was sort of lost a bit.
So changed my comment but you were faster to read it :)

**Comment by ericherman** [comment]
> > > The "json_temp_type" only existed momentarily
> 
> right. I was sort of lost a bit.
> So changed my comment but you were faster to read it :)

No problem at all. I appreciate the time review takes. Thank you!

**Comment by ericherman** [comment]
> The DYNAMIC_STRING is used in the json_normalize(). But in the Item::val_str() we have the String result to fill.
> So you have to copy the DYNAMIC_STRIN into the String result. I'd propose to use the String in the json_normalize() then we don't have to do the extra copying. And which can be even more important we don't have to do that many memory allocations - as any new DYNAMIC_STRING in the ::val_str() is at least one malloc while that String buffer can be reused.

The extra memcpy is not ideal, however it seemed like the better trade-off given that `strings/json_lib.c` is plain C and thus can not use class String, and that `strings/json_lib.c` includes `include/json_lib.h`, using `class String` in `json_normalize` would be problematic. At the moment, making `json_normalize` fit in with the rest of `json_lib`, in exchange for some memory/cpu waste seemed like least worse choice.

> Then i see the mess with the character sets. The normalized JSON should be in UTF8, but the Item_func_json_normalize::fix_length_and_dec() declares the resulting charset to be same as the argument's. I think it should always be UTF8-MB4. Then the ::val_str() doesn't take the argument's charset in the account at all. And if it's not compatible with the argument's we'd get the wrong result. I think the argument's charset has to be verified and converted into UTF8 if necessary.

I'd appreciate some help writing a test which would demonstrate the wrong result. @cvicentiu may I please lean on you for some more time, please?

**Comment by ericherman** [comment]
@holyfoot Item_func_json_normalize now always sets to utf8mb4.

**Comment by ericherman** [comment]
see: https://github.com/MariaDB/server/pull/1863

**Pull request closed without merging**
