### PR TITLE
WIP: Remove Gitlab-CI and Salsa-CI from short-lived MariaDB versions 10.7-10.10

### PR DESCRIPTION
**Pull request by ottok**
**DRAFT - Request for comments**

Doing this change might mess up future merges as the intermediate branches would be missing the file.

-------

Maintaining the Gitlab-CI and Salsa-CI on the short-lived releases of
MariaDB 10.7 to 10.10 does not make sense at this point anymore, as they
would not contain any changes that are not on 10.6 or 10.11, and thus
any regression in code (no matter which branch) would be detected in the
CI runs of 10.6 or 10.11 due to how MariaDB does merges across branches.

From this point onward, only maintain Gitlab-CI and Salsa-CI on the long-
term version and the latest version in development.

NOTE TO MERGERS: This removal commit should be merged only on 10.7/8/9/10.
Do not merge this change on 10.11 or upward.

### CODE REVIEW

**Comment by illuusio** [comment]
Should it be removed from every version and let it live only in Debian git?

**Comment by ottok** [comment]
> Should it be removed from every version and let it live only in Debian git?

No, absolutely not. That would mean that there would be zero Debian packaging tests (Salsa-CI) for upstream branches. We need testing, but perhaps only on branches that are actually maintained (e.g. 10.6, 10.11, 11.0). This helps weed out regressions from changes like eg. #2390, #2382, #2392, #2273 and so forth. If they are tested only after release in when package is imported into Debian proper it would be too late to fix well.

**Comment by grooverdan** [comment]
With this merged
* its going to mean any 10.6 salsa changes would mean a new PR on 10.11 to cover potentially the same content.
* all 10.6 salsa merge ups would be a conflict (that will trivial to resolve)

Would any 10.6 changes cleanly merge all the way though to 10.11? If so its probably rather harmless to keep this in place.

So I'm in favour of this removal if the 10.6 merge ups are likely to be complex.

**Comment by illuusio** [comment]
I go with @grooverdan as 10.6 merging up would we much more difficult. Should we just remove Salsa-CI from upstream altogether and start keep it up-to-date on Debian Salsa? I would need some rebasing etc but wouldn't pollute upstream which does not need it.

**Comment by ottok** [comment]
> I go with @grooverdan as 10.6 merging up would we much more difficult. Should we just remove Salsa-CI from upstream altogether and start keep it up-to-date on Debian Salsa? I would need some rebasing etc but wouldn't pollute upstream which does not need it.

Sure, if upstream stops publishing .deb packages then doing tests for .deb package installs/upgrades and general quality assurance of `debian/*` contents upstream becomes irrelevant. But if it continues to have it, then testing that it actually works makes sense.

Anyway, those short-lived MariaDB versions will soon be out of support so merges in future will be from 10.6 directly to 10.8 and it is probably simplest to just keep the files so that merges don't get weird situations about files being deleted on some branches and on others not.

**Pull request closed without merging**
