### PR TITLE
MDEV-8379: example config file for multi-instance (from openSUSE)

### PR DESCRIPTION
**Pull request by grooverdan**
From https://github.com/openSUSE/mysql-packaging/blob/master/patches/mysql-patches/mysql-community-server-5.1.45-multi-configuration.patch

### CODE REVIEW

**Comment by svoj** [comment]
.oO(didn't @grooverdan remove all examples in 7fee164faf8fce7be4ebe322d2178efd3d075eae)

**Comment by grooverdan** [comment]
Yes. There'll be merge conflicts when it gets to 10.3. The other where removed to their datedness and generally better defaults. This provides a functional example use of mysqld_multi.

**Comment by grooverdan** [comment]
BSD-new license approved by openSUSE: https://bugzilla.opensuse.org/show_bug.cgi?id=1080891#c4

**Comment by an3l** [comment]
@grooverdan should this patch  be retarget to 10.2 at least ?

**Comment by grooverdan** [comment]
suggested enhancements:
- reference https://mariadb.com/kb/en/systemd/#interacting-with-multiple-mariadb-server-processes as alternate
- note galera replication, IST, SST and cluster address needing to be unique

**Comment by LinuxJedi** [comment]
Whilst cleaning up some older PRs I'm looking at this one and my personal opinion is as follows:

Whilst it could be a useful sample configuration file, it appears the typical way we recommend people do this now is using systemd with multiple configuration files. This is more in-line with how other daemons manage this kind of thing.

With that in mind I'm going to close this one for now, but if people feel it is really useful then I can help guide it into the latest development release. I recommend updating the KB at the same time if we are going to do this, to point to the example in the codebase.

**Pull request closed without merging**
