### PR TITLE
MDEV-8923: port innodb_buffer_pool_dump_pct from MySQL

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by janlindstrom** [comment]
Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
Hi Daniel,

Thanks for your contribution.

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Do you think this patch would be beneficial to be applied to 10.0 or is this 10.1 better ?

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. JIRA task just for the record: https://mariadb.atlassian.net/browse/MDEV-8923.

Target version and contribution review will be set later depending on outcome of your discussion with Jan.

Thanks,
Sergey

**Comment by grooverdan** [comment]
@janlindstrom if you're happy with 10.0 that sounds good to me. Its certainly a feature with a few votes and dumping multiple G buffer pools begins to take a while even on decent hardware for not much benefit. The IO throttling also sounds worth while. I contribute the code to the extent written by me under the BSD-new license. All the rest of the code from upstream MySQL as credited.

**Comment by grooverdan** [comment]
Thanks @janlindstrom

**Pull request merged**
