### PR TITLE
MDEV-16213: Improvements and adjustments to Travis config

### PR DESCRIPTION
**Pull request by shinnok**
Several improvements have been made so that builds run
faster and with fewer canceled jobs:

* Set ccache max size to 1GB. Was 512MB for Linux
(too low for MariaDB) and 5GB on macOS with defaults;

* Don't install libasan in Travis if not necessary.
Sicne ASAN is disabled for the time being, save
time/resources for other steps;

* Decrease number of parallel processes. To prevent
resource exhaustion leading to poor performance. According
to Travis docs, a max of 4 concurrent processses should be
run per job:
https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

* Reconsider tests exec order and split huge main and rocksdb
test suites into their own job, decreasing the chance of going
over the Travis job execution limit and getting killed;

* Increase Travis testcase-timeout to 4 minutes. Occasionally
on Ubuntu target and frequently on macOS, many tests in main,
rpl, binlog suites take longer than 2 minutes, resulting in
many jobs failing, when in reality the failing tests didn't
get a chance to complete. From my testing, along with the other
speedups, i.e. increasing ccache size, a timeout of 4 minutes
should be Ok.  Revert to 3 minutes of necessary.

* Build with GCC and Clang version 5,6 only.

* Rename GCC_VERSION to CC_VERSION for clarity. We are using
two compilers after all, GCC and Clang.

* Stop using somewhat obsolete Clang4 in Travis. Also, was the
reason for the failing test suites in MDEV-15430.

### CODE REVIEW

**Comment by grooverdan** [comment]
Nice.

Need to be careful of 1G ccache. I've seen some jobs timeout fail during upload of it.

Could use gcc-7/gcc-8 too https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test (maybe next update).

Any reason not to target 10.2?

**Comment by shinnok** [comment]
@grooverdan Regarding ccache size, I'm currently working on slimming down build disk usage with tricks you can see here:
https://github.com/shinnok/server/commits/tm-10.3-macfixes
More specifically:
https://github.com/shinnok/server/commit/33261cfa22d3669cb04f3a67ef9e0e42f9a5ca2d
Here's a sample build with only changes in this PR (all green for Linux):
https://travis-ci.org/shinnok/server/builds/385532975
Still working on getting macOS targets green.

Regarding GCC version bumps, I think we can only replace, not add new matrix chains at this point due to Travis constraints. I can try it out on my instance though and see how it fares.

Regarding 10.2, not sure, if you think is fit for that I can rebase.

**Comment by svoj** [comment]
I wonder if anybody evaluated ccache performance? I stopped using it long ago because it was _much_ slower.

One of the problems was that I had ~5-10Gb cache, which didn't fit all major versions/build  configurations I'm using. Thus cache misses were quite common.

Second reason is: we update header files quite often, which invalidates big part of the cache. Causing many cache misses again.

**Comment by svoj** [comment]
Stats for exactly this build: https://travis-ci.org/MariaDB/server/jobs/385532998
```
$ ccache --show-stats
cache directory                     /home/travis/.ccache
cache hit (direct)                  1120
cache hit (preprocessed)             578
cache miss                          3698
called for link                     1506
called for preprocessing              62
compile failed                       102
preprocessor error                   122
bad compiler arguments                 8
unsupported source language            4
autoconf compile/link                 98
unsupported compiler option          296
no input file                         38
files in cache                      3226
cache size                         901.0 Mbytes
max cache size                    1000.0 Mbytes
```

3698 misses vs 1120 hits.

**Comment by grooverdan** [comment]
> Regarding 10.2, not sure, if you think is fit for that I can rebase.

Yes, having 10.2 pull requests show up green would be good too. Might mean a few OSX patches need to target 10.2.

> Regarding GCC version bumps, I think we can only replace, not add new matrix chains at this point due to Travis constraints. I can try it out on my instance though and see how it fares

I'm fine with a replace.  ```CC_VERSION``` are duplicated.

AFAIK settings the ```compiler:``` values sets the ```$CC``` explicitly so you can use ```gcc-7``` there for instance. I haven't checked if this propagates to ```$CXX```.

There might be other components from #505 you want to pull in.

I seem to recall testing with pulling in later ccache versions into travis (even a raw pull of a more recent distro version (didn't' conflict on libraries) and cpio extract to work around the sudo: false limit) and that had a better hit ration. Forget when I put that commit.

Agree that cache dirs locally are a pain. I'm working often now with a ```git worktree``` per branch which I think avoids invalidating caches as much by not switching between directories on the same code.

Might also try ```env MTR_MEM=/run``` again, still has 64M limit (https://github.com/travis-ci/worker/pull/299/files)  (unsure if we hit this) but has needed exec perms. Need to check mounts on osx so it might be linux only.

**Comment by shinnok** [comment]
@svoj Here's a summary from my macOS dev machine for comparison (`ccache -C` ran quite recently):

```
ccache --version
ccache version 3.4.2

cache hit (direct)                  5772
cache hit (preprocessed)            2597
cache miss                          3062
cache hit rate                     73.21 %
called for link                        5
called for preprocessing              23
compile failed                        16
preprocessor error                     2
autoconf compile/link                 58
cleanups performed                     0
files in cache                      8686
cache size                           1.2 GB
max cache size                       2.0 GB
```

Subsequent clean rebuilds of the 10.3  source tree (using git worktree also) result in a decrease to 3-5m from approx. 30m without ccache (both with -j7). On Travis I do agree with @grooverdan that we need to fine-tune the configuration and environment a little bit as the cache is unique among individual builds (not jobs), but even with the current state I see a good improvement per job, unless we hit one of those peculiar Travis moments when it decides to cap everything from vcpu rate and time to memory and disk.

**Comment by shinnok** [comment]
More stats after dozen more builds in my Travis instance:
```
ccache --show-stats
cache directory                     /home/travis/.ccache
cache hit (direct)                 22847
cache hit (preprocessed)            4606
cache miss                         14643
called for link                    11843
called for preprocessing             474
compile failed                       785
preprocessor error                   957
bad compiler arguments                60
unsupported source language           30
autoconf compile/link                735
unsupported compiler option         1628
no input file                        291
files in cache                      4552
cache size                           1.1 Gbytes
max cache size                       1.2 Gbytes
```
https://api.travis-ci.org/v3/job/387661983/log.txt

Latest green build (featuring exclusion of modules seen [here](https://github.com/shinnok/server/blob/ccbbd45d43a3fbc5bc9a590ef1ec374f5937bc46/.travis.compiler.sh#L8)):
https://travis-ci.org/shinnok/server/builds/387661982

**Comment by svoj** [comment]
Do you have information of which revisions were built using this cache? tm-10.3-macfixes? I can only see some travis experiments being built by travis, no surprise they give decent hit rate. :)

**Comment by shinnok** [comment]
@svoj tm-10.3-macfixes is based on 10.3. The current build is rebased on origin/10.3. As I used git push -f quite a lot you're not likely to find all revisions. I didn't push any other branches. Also from Travis doc:

> Travis CI can cache content that does not often change, to speed up your build process. To use the caching feature, in your repository settings, set Build branch updates to ON.
Travis CI fetches the cache for every build, including branches and pull requests. If a branch does not have its own cache, Travis CI fetches the cache of the repository’s default branch. There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc. Only modifications made to the cached directories from normal pushes are stored.

https://docs.travis-ci.com/user/caching/

**Comment by svoj** [comment]
Ok, let's hope caching works well.

**Comment by ottok** [comment]
I restarted the builds on Travis-CI to pass. Currently it seem Debian package creation cannot pass and consistently fails with `grep: write error: No space left on device`. This is a regression – it did pass previously without issues.

**Comment by shinnok** [comment]
@ottok Not sure what happened there. ccache size is not adjusted for the *DebPackages* job. You can check on that by grepping for `ccache --show-stats`, you'll see cache size still being 512. As I see it, this job is particularly special in regards to disk usage since it does lots of `apt-get install` and then `make install`.

**Comment by shinnok** [comment]
Let's see if https://github.com/MariaDB/server/pull/779/commits/ac0083cefeb50cadfdc7066eaf848b861c0c1ce9 tips the scale in our favor.

**Comment by grooverdan** [comment]
the correct disable mechanism is ```-DPLUGIN_{name}=NO``` (wasn't in 5.5 and forget which 10.X it was standardised). Some of the ``-DWITHOUT_``` options aren't defined in cmake/plugin.cmake or the CMakeList.txt in the respective directories.

**Pull request merged**
