### PR TITLE
mtr: use env for perl

### PR DESCRIPTION
**Pull request by grooverdan**
On FreeBSD, perl isn't in /usr/bin, its in /usr/local/bin or
elsewhere in the path.

Like storage/{maria/unittest/,}ma_test_* , we use /usr/bin/env to
find perl and run it.

I submit this under the MCA.

### CODE REVIEW

**Comment by an3l** [comment]
I have tested this on 10.4, FreeBSD 12, perl 5.30.2, debug build and cannot see any effect of change, `perl mtr view_grant` (ok), `./mtr view_grant`(not found)
Can you please confirm?

**Comment by grooverdan** [comment]
```
$ uname -a
FreeBSD freebsd 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
$ ls -la /usr/bin/perl /usr/local/bin/perl
ls: /usr/bin/perl: No such file or directory
-rwxr-xr-x  1 root  wheel  15440 Sep 24  2019 /usr/local/bin/perl
$ ls -la /usr/bin/env 
-r-xr-xr-x  1 root  wheel  23720 Dec  7  2018 /usr/bin/env
$ perl --version

This is perl 5, version 30, subversion 0 (v5.30.0) built for amd64-freebsd-thread-multi
$ patch --version
patch 2.0-12u11 FreeBSD
```
With patch:
```
$ cd mysql-test/
$ ./mtr view_grant
...   [ pass ] 
```

without patch:
```
$ more mysql-test/mysql-test-run
#!/usr/bin/perl
# Call mtr in out-of-source build

$ mysql-test/mtr view_grant
-sh: mysql-test/mtr: not found
$ perl mysql-test/mtr view_grant
... [ pass ]
```

Keep in mind cmake generates the mysql-test{mtr,mysql-test-run} in the build directory, not make/ninja.

Admittedly I need to update my FreeBSD version.

Patch version was included because I also get:
```
$ patch --version
patch 2.0-12u11 FreeBSD

$ perl mysql-test/mtr --mem --parallel=3 innodb.table_flags
...
patch: unrecognized option `--binary'
usage: patch [-bCcEeflNnRstuv] [-B backup-prefix] [-D symbol] [-d directory]
             [-F max-fuzz] [-i patchfile] [-o out-file] [-p strip-count]
             [-r rej-name] [-V t | nil | never | none] [-x number]
             [-z backup-ext] [--posix] [origfile [patchfile]]
$ patch --binary
patch: unrecognized option `--binary'
```

Does the binary option exist in your FreeBSD-12.1 patch version? I've tested MTR and it works without that option on FreeBSD.

**Comment by an3l** [comment]
Thanks @grooverdan for confirming, I have setup instance on VM and really it still don't work. There is no binary option in this version.
Also I have tested your patch for PR #1481 and it make sense, but cannot find a proc.
image

**Comment by grooverdan** [comment]
note sure what purpose you're using VMware tools. If you're after file sharing to a VM:

```
mariadb-server-10.5]$ sshfs dan@192.168.122.205:/home/dan /home/dan/repos/freebsd/ -o reconnect,idmap=user
mariadb-server-10.5]$ git worktree add /home/dan/repos/freebsd/mariadb-server-10.5 origin/10.5
cd  /home/dan/repos/freebsd/mariadb-server-10.5
git submodule init --recursive --update
```
After which you have a host based git repository that you can edit/pull etc, that directly maps to a source in the VM that can be built.

**Comment by an3l** [comment]
The purpose is to have multi terminal support (now working in one), mouse support, copy-paste between host and guest (I have sent you an image, no text), full screen option.

**Comment by an3l** [comment]
Hi @grooverdan, can you please change each occurrence of `/usr/bin/perl` to `/usr/bin/env perl`? 
It didn't work with out of source build, it needs change in `mtr.out-of-source`.

**Comment by an3l** [comment]
Hi @grooverdan any update on this?
We can also update this PR for all other places in {{mysql-test}} and {[scripts}}.
Also we need rebase on {{10.1}}.

**Comment by grooverdan** [comment]
scripts are already covered by:
```IF(CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
  SET (PERL_PATH "/usr/local/bin/perl")
ELSE()
  SET (PERL_PATH "/usr/bin/perl")
ENDIF()
```

**Comment by an3l** [comment]
Thanks Daniel!

**Comment by grooverdan** [comment]
Thanks for the review/merge @an3l .

**Comment by ottok** [comment]
@grooverdan Are you sure this is how FreeBSD still works? In Debian there is a strong policy to move away from /usr/bin/env and I assume it is strong only because it is a pretty much universal rule applying at least to all Linux distros, but maybe to software in general as well: https://www.debian.org/doc/debian-policy/ch-files.html#scripts

**Comment by ottok** [comment]
In other words, can you find a Perl policy that recommends using legacy `env` over the modern`#!/usr/bin/perl`?

**Pull request merged**
