### PR TITLE
MDEV-29889 mariadb-dump --tab --header is slow

### PR DESCRIPTION
**Pull request by grooverdan**
--header applied and ORDER BY to ensure that the header row was the first row in the output given UNION ALL doesn't in the standard enforce the order.

We change that now only add the ORDER BY if --order-by-primary is used.

### CODE REVIEW

**Comment by vuvova** [comment]
No, this is technically wrong. Without `ORDER BY` there is no guarantee that the header row will be first.

Although, practically, because of the specifics of `UNION ALL` implementation it _might_ be the case. But it needs the analysis of the `UNION ALL` code. And still will be rather fragile, as the implementation can change in the future.

**Comment by grooverdan** [comment]
My rational was if the implementation changes in future, this test case will fail, and the changes of `UNION ALL` or the implementation here could be re-examined as its making an obvious assumption. The `DERIVED` header query would seem to be a obvious choice in query execution to push though to the result buffer quickly.

Alternate implementations considered included:
* the original implementation, that had an explicit header/non-header column (downside of forcing a sort),
* `SELECT INTO OUTFILE` twice to different files (header and data), but then you're copying the entire data file (`splice`/`copy_file_range` are potential Linux FS optimizations), to append the data to the header file to create the result consuming additional storage and IO to do so.
* If there was a `SELECT INTO APPEND OUTFILE` that would be an ideal solution two perform header/data queries separately.
* Temporary tables also have IO/space overhead.
* CSV engine doesn't support the fields/row separation and quotes as option
* CONNECT engine might support this, but it may not be available. 
* making mariadb-dump write the header to the file and not use `INTO OUTFILE`, fetching the data and perform all the quoting and escaping within mariadb-dump, and write to file (felt like a lot of duplicating functionality)

**Comment by LinuxJedi** [comment]
I do like the `SELECT INTO APPEND OUTFILE` solution, but there is another option. Have `mysqldump` itself generate the files. This has the added advantage of working with remote servers. This may require a new option to maintain compatibility with the behaviour of previous versions.

**Comment by vuvova** [comment]
I agree that the easiest approach would be to drop the ORDER BY. And it's not that difficult to check in the code that current UNION ALL implementation works the way you assume.

But I don't understand what kind of tests you can add to make sure the order won't change in the future. Perhaps, an EXPLAIN on the query that mysqldump is issuing — that'll show that there's no filesort, no temp table, just direct sending results to the client. Technically it doesn't prove much, of course.

How to do an EXPLAIN on exact query that mysqldump is using? I see two ways — enable general log and extract the query from there. Or stop it mid-flight and run SHOW EXPLAIN.

**Comment by grooverdan** [comment]
Isn't the `mysql-test/main/mysqldump-header.result` file that lists the header before the data rows in a number of test cases sufficient to detect the implementation has changed sufficiently for the user result to be impacted?

A manual optimizer trace showing `select_id` 2 before 3:
```
MariaDB [test]> select * from INFORMATION_SCHEMA.OPTIMIZER_TRACE \G
*************************** 1. row ***************************
                            QUERY: SELECT /*!40001 SQL_NO_CACHE */ `i` INTO OUTFILE '/tmp/t/t.txt' /*!50138 CHARACTER SET latin1 */ FROM ( SELECT 'i' UNION ALL SELECT `i` FROM `t`)  s
                            TRACE: {
  "steps": [
    {
      "join_preparation": {
        "select_id": 1,
        "steps": [
          {
            "derived": {
              "table": "s",
              "select_id": 2,
              "algorithm": "materialized"
            }
          },
          {
            "join_preparation": {
              "select_id": 2,
              "steps": [
                {
                  "expanded_query": "/* select#2 */ select 'i' AS i"
                }
              ]
            }
          },
          {
            "join_preparation": {
              "select_id": 3,
              "steps": [
                {
                  "expanded_query": "/* select#3 */ select t.i AS i from t"
                }
              ]
            }
          },
          {
            "expanded_query": "/* select#1 */ select sql_no_cache s.i AS i from (/* select#2 */ select 'i' AS i union all /* select#3 */ select t.i AS i from t) s"
          }
...
    {
      "join_execution": {
        "select_id": 1,
        "steps": [
          {
            "join_execution": {
              "select_id": 2,
              "steps": []
            }
          },
          {
            "join_execution": {
              "select_id": 3,
              "steps": []
            }
          }
        ]
      }
    }
```

**Comment by grooverdan** [comment]
@vuvova, is the existing test case sufficient as it will have a result change if the order changes?

**Comment by vuvova** [comment]
It just occurred to me, that `ORDER BY pk` will be an index scan, at least in InnoDB, that is, filesort will still be a performance regression. I don't see an easy solution for this, so for now let's say it's the price of using `--header` with `--order-by-primary`, assuming it's not used much. If it is, it'll justify a complex solution, like, modifying `INTO OUTFILE`

**Review by vuvova — APPROVED** [review]
ok

**Pull request merged**
