### PR TITLE
MDEV-8743: mysql_tmpfile

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-8743

This task was added to 10.0 backlog.

Thanks,
Sergey

**Comment by grooverdan** [comment]
the open flag O_TMPFILE (since Linux 3.11) might be able to be used here as an alternative to my_register_filename.

**Comment by grooverdan** [comment]
I'd like to test this last commit some more before merging please.

**Comment by grooverdan** [comment]
cherry-picked and improved:

https://github.com/MariaDB/server/commit/e01789ad9b
https://github.com/MariaDB/server/commit/b19ab6be1c571f

**Pull request closed without merging**
