### PR TITLE
Fix FSF addresses

### PR DESCRIPTION
**Pull request by FaramosCZ**
Done with:

```
find ./ -type f -exec sed -i -e 's/Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA.*02111-1307.*USA/Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02111-1301 USA/g' {} \; \
-exec sed -i -e 's/Foundation, Inc., 59 Temple/Foundation, Inc., 51 Franklin/g' {} \; \
-exec sed -i -e 's/Place, Suite 330, Boston, MA.*02111-1307.*USA/Street, Fifth Floor, Boston, MA 02111-1301 USA/g' {} \; \

find ./ -type f -exec sed -i -e 's/MA.*02111-1307/MA 02111-1301/g' {} \;
```

### CODE REVIEW

**Comment by FaramosCZ** [comment]
I forgot about the last part (postal code ??) changed too.
Fixed in second commit.

**Comment by FaramosCZ** [comment]
Typo in my script. Fixing 'MA MA' -> 'MA'

`find ./ -type f -exec sed -i -e 's/MA.*MA.*02110-1335/MA 02110-1335/g' {} \;`

**Comment by FaramosCZ** [comment]
Using FSF address from:
https://www.fsf.org/about/contact/

**Comment by grooverdan** [comment]
dup of #598 that hasn't been merged. I haven't looked at difference but I imagine they are  pretty close.

**Comment by cvicentiu** [comment]
I will be using your script to update all of 5.5, 10.1, 10.2, 10.4 repositories. There is no excuse for us not having the correct FSF address.

**Comment by cvicentiu** [comment]
Turns out there are quite a few miss-matches between addresses all around the code base. Your initial script is very useful.

Here is the commit that pushed the changes to 5.5. It will be run for all versions during merge windows.
17b4f99928eb222dcc7c7b0404ccbcd1063af026

Thank you!

**Comment by FaramosCZ** [comment]
> Your initial script is very useful.
I'm always glad to see my code helped someone :)

Maybe, you can use it in the buildbot as a test when making a tarball of a new release of anything.

**Pull request closed without merging**
