### PR TITLE
fix header typos

### PR DESCRIPTION
**Pull request by musvaage**
include/heap.h
include/json_lib.h
include/lf.h
include/m_ctype.h
include/ma_dyncol.h
include/my_base.h
include/my_compare.h
include/my_decimal_limits.h
include/my_dir.h
include/my_global.h
include/my_rdtsc.h
include/my_sys.h
include/myisam.h
include/myisammrg.h
include/mysql.h
include/mysql/plugin_ftparser.h
include/mysql/psi/mysql_thread.h
include/mysql/psi/psi.h
include/mysql/service_base64.h
include/mysql/service_my_snprintf.h
include/mysql/service_sql.h
include/mysql/service_thd_timezone.h
include/queues.h
include/waiting_threads.h

### CODE REVIEW

**Comment by musvaage** [comment]
@LinuxJedi

I think this can be merged.

**Comment by grooverdan** [comment]
Request for when you split these up. Assume the fixes in the earlier version will be merged to the later version. i.e. no need to duplicate the fixes in different branches. They will be merged and all fixed. Lowest maintained version is 10.3.

**Comment by musvaage** [comment]
10.4 version

include/my_compare.h

```diff
-   1=CHECK_POS  - The filter is statisfied. Current index tuple should be
+   1=CHECK_POS  - The filter is satisfied. Current index tuple should be
```

include/my_rdtsc.h

```diff
-   guarenteed to be active.
+   guaranteed to be active.
```

```
sed -i "s/statisfied/satisfied/g" server/include/my_compare.h
sed -i "s/guarenteed/guaranteed/g" server/include/my_rdtsc.h
```

10.5 version

include/mysql/psi/psi.h

```diff
-   Set the statement text for a prepared statment event.
+   Set the statement text for a prepared statement event.
```

```
sed -i "s/statment/statement/g" include/mysql/psi/psi.h
```

10.7 version

include/mysql/service_sql.h

```diff
- /* The rest of the function declarations mest be taken from the mysql.h */
+ /* The rest of the function declarations must be taken from the mysql.h */
```

```
sed -i "s/mest/must/g" include/mysql/service_sql.h
```

**Comment by musvaage** [comment]
_cf:_ [comment](https://jira.mariadb.org/browse/MDEV-29275?focusedCommentId=231714&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231714)

@grooverdan


The spelling forceintervall/intervall/intervalls (.c, .h and .result files) and uppdated/uppdates (.c and .test files) is likely due to incorrect translation from Swedish.

On a final note would eventual corrections forceinterval/interval/intervals be authorised?

```
$ grep -nr uppdate server/{mysql-test,storage}
server/mysql-test/suite/parts/t/partition_repair_myisam.test:153:# 5 - (Not used) after mi_state_info_write (fully uppdated/closed index file)
server/storage/maria/ma_locking.c:285:  Every isam-function that uppdates the isam-database MUST end with this
server/storage/myisam/mi_locking.c:511:  Every isam-function that uppdates the isam-database MUST end with this
$ 
```

Obviously changing the spelling of `intervall` would affect code.

```
$ grep -nr intervall server/{mysql-test,include,storage}
server/mysql-test/suite/maria/aria_pack_mdev14183.result:13:pre-space:   0  end-space:         0  intervall-fields:   0  zero:         2
server/include/maria.h:227:  uchar *intervalls;
server/include/myisam.h:215:  uchar      *intervalls;
server/storage/heap/hp_test2.c:610:     /* Generate a random value in intervall 0 <=x <= n */
server/storage/maria/ma_open.c:999:            intervalls.
server/storage/maria/maria_pack.c:200:static my_off_t intervall_length;
server/storage/maria/maria_pack.c:1413:    /* Test if intervall-field is better */
server/storage/maria/maria_pack.c:1419:      DBUG_EXECUTE_IF("forceintervall",
server/storage/maria/maria_pack.c:1451:                      "intervall-fields: %3d  zero:       %3d",
server/storage/maria/maria_pack.c:1460:                "intervall-fields: %3d  zero:       %3d\n",
server/storage/maria/maria_pack.c:1945: continue;                       /* Don't join intervall */
server/storage/maria/maria_pack.c:2112:  int4store(buff+20,intervall_length);
server/storage/maria/maria_pack.c:2226:  intervall_length=0;
server/storage/maria/maria_pack.c:2285:      intervall_length+=int_length;
server/storage/maria/maria_pack.c:2504:  uint intervall,field_length,max_pack_length,pack_blob_length, null_bytes;
server/storage/maria/maria_pack.c:2746:   intervall=(uint) (pos - count->tree_buff)/field_length;
server/storage/maria/maria_pack.c:2749:                                intervall, hexdigits(tree->code[intervall]),
server/storage/maria/maria_pack.c:2750:                                (uint) tree->code_len[intervall]));
server/storage/maria/maria_pack.c:2751:   write_bits(tree->code[intervall],(uint) tree->code_len[intervall]);
server/storage/maria/ma_packrec.c:57:                       uint16 **decode_table,uchar **intervall_buff,
server/storage/maria/ma_packrec.c:100:static void uf_intervall(MARIA_COLUMNDEF *rec,MARIA_BIT_BUFF *bit_buff,
server/storage/maria/ma_packrec.c:175:  ulong elements,intervall_length;
server/storage/maria/ma_packrec.c:177:  uchar *intervall_buff;
server/storage/maria/ma_packrec.c:207:  intervall_length=uint4korr(header+20);
server/storage/maria/ma_packrec.c:220:  DBUG_PRINT("info", ("distinct values bytes: %lu", intervall_length));
server/storage/maria/ma_packrec.c:233:                    intervall_length*sizeof(uchar)),
server/storage/maria/ma_packrec.c:236:  intervall_buff=(uchar*) (share->decode_trees+trees);
server/storage/maria/ma_packrec.c:291:                        &intervall_buff,tmp_buff))
server/storage/maria/ma_packrec.c:353:      intervall_buff    IN/OUT  Address of a pointer to the next unused values.
server/storage/maria/ma_packrec.c:363:                      uint16 **decode_table, uchar **intervall_buff,
server/storage/maria/ma_packrec.c:366:  uint min_chr,elements,char_bits,offset_bits,size,intervall_length,table_bits,
server/storage/maria/ma_packrec.c:378:    intervall_length=0;
server/storage/maria/ma_packrec.c:398:    intervall_length=get_bits(bit_buff,16);
server/storage/maria/ma_packrec.c:405:    DBUG_PRINT("info", ("value buffer length:   %u", intervall_length));
server/storage/maria/ma_packrec.c:431:  decode_tree->intervalls= *intervall_buff;
server/storage/maria/ma_packrec.c:432:  if (! intervall_length)
server/storage/maria/ma_packrec.c:459:    memcpy(*intervall_buff,bit_buff->pos,(size_t) intervall_length);
server/storage/maria/ma_packrec.c:460:    (*intervall_buff)+=intervall_length;
server/storage/maria/ma_packrec.c:461:    bit_buff->pos+=intervall_length;
server/storage/maria/ma_packrec.c:842:    return &uf_intervall;
server/storage/maria/ma_packrec.c:1062:  memcpy(to,rec->huff_tree->intervalls,(size_t) (end-to));
server/storage/maria/ma_packrec.c:1065:static void uf_intervall(MARIA_COLUMNDEF *rec, MARIA_BIT_BUFF *bit_buff,
server/storage/maria/ma_packrec.c:1070:  memcpy(to,rec->huff_tree->intervalls+field_length*decode_pos(bit_buff,
server/storage/myisam/mi_packrec.c:52:                      uint16 **decode_table,uchar **intervall_buff,
server/storage/myisam/mi_packrec.c:92:static void uf_intervall(MI_COLUMNDEF *rec,MI_BIT_BUFF *bit_buff,
server/storage/myisam/mi_packrec.c:140:  ulong elements,intervall_length;
server/storage/myisam/mi_packrec.c:142:  uchar *intervall_buff;
server/storage/myisam/mi_packrec.c:172:  intervall_length=uint4korr(header+20);
server/storage/myisam/mi_packrec.c:188:  DBUG_PRINT("info", ("distinct values bytes: %lu", intervall_length));
server/storage/myisam/mi_packrec.c:200:                   intervall_length*sizeof(uchar)),
server/storage/myisam/mi_packrec.c:203:  intervall_buff=(uchar*) (share->decode_trees+trees);
server/storage/myisam/mi_packrec.c:258:                        &intervall_buff,tmp_buff))
server/storage/myisam/mi_packrec.c:320:      intervall_buff    IN/OUT  Address of a pointer to the next unused values.
server/storage/myisam/mi_packrec.c:330:                     uint16 **decode_table, uchar **intervall_buff,
server/storage/myisam/mi_packrec.c:333:  uint min_chr,elements,char_bits,offset_bits,size,intervall_length,table_bits,
server/storage/myisam/mi_packrec.c:345:    intervall_length=0;
server/storage/myisam/mi_packrec.c:364:    intervall_length=get_bits(bit_buff,16);
server/storage/myisam/mi_packrec.c:371:    DBUG_PRINT("info", ("value buffer length:   %u", intervall_length));
server/storage/myisam/mi_packrec.c:397:  decode_tree->intervalls= *intervall_buff;
server/storage/myisam/mi_packrec.c:398:  if (! intervall_length)
server/storage/myisam/mi_packrec.c:425:    memcpy(*intervall_buff,bit_buff->pos,(size_t) intervall_length);
server/storage/myisam/mi_packrec.c:426:    (*intervall_buff)+=intervall_length;
server/storage/myisam/mi_packrec.c:427:    bit_buff->pos+=intervall_length;
server/storage/myisam/mi_packrec.c:802:    return &uf_intervall;
server/storage/myisam/mi_packrec.c:1018:  memcpy(to,rec->huff_tree->intervalls,(size_t) (end-to));
server/storage/myisam/mi_packrec.c:1021:static void uf_intervall(MI_COLUMNDEF *rec, MI_BIT_BUFF *bit_buff, uchar *to,
server/storage/myisam/mi_packrec.c:1025:  memcpy(to,rec->huff_tree->intervalls+field_length*decode_pos(bit_buff,
server/storage/myisam/myisampack.c:195:static my_off_t intervall_length;
server/storage/myisam/myisampack.c:1346:    /* Test if intervall-field is better */
server/storage/myisam/myisampack.c:1352:      DBUG_EXECUTE_IF("forceintervall",
server/storage/myisam/myisampack.c:1384:                      "intervall-fields: %3d  zero:       %3d",
server/storage/myisam/myisampack.c:1393:                "intervall-fields: %3d  zero:       %3d\n",
server/storage/myisam/myisampack.c:1877:        continue;                       /* Don't join intervall */
server/storage/myisam/myisampack.c:2045:  int4store(buff+20,intervall_length);
server/storage/myisam/myisampack.c:2160:  intervall_length=0;
server/storage/myisam/myisampack.c:2219:      intervall_length+=int_length;
server/storage/myisam/myisampack.c:2439:    intervall,field_length,max_pack_length,pack_blob_length;
server/storage/myisam/myisampack.c:2670:          intervall=(uint) (pos - count->tree_buff)/field_length;
server/storage/myisam/myisampack.c:2673:                                intervall, hexdigits(tree->code[intervall]),
server/storage/myisam/myisampack.c:2674:                                (uint) tree->code_len[intervall]));
server/storage/myisam/myisampack.c:2675:          write_bits(tree->code[intervall],(uint) tree->code_len[intervall]);
$ 
```

**Comment by grooverdan** [comment]
Thanks for the split up, that helped a lot.

Although code fixing can be done, its harder especially if a missed change occurs on a later version resulting in a compile failure which causes more pain than the existing misspelling. My current feeling is I'd rather these be left as is.

We've got a backlog of [beginner friendly tasks](https://jira.mariadb.org/issues/?jql=labels%20%3D%20beginner-friendly%20and%20status%20%3D%20open), or if you're after something less code related, some proof reading of manual (`man/*`) pages or KB pages (that get generated into the `HELP sql` SQL statement) would be appreciated.

**Comment by musvaage** [comment]
As follows is mostly for my own notes.

_cf_: [comment](https://jira.mariadb.org/browse/MDEV-29275?focusedCommentId=245738&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-245738)

https://github.com/MariaDB/server/commit/f4adf3547420cced027d26ee8b8190be8a2bdea2

The above patch included a typo fix.

`- Fix typo in Lintian overrides`

debian/source/lintian-overrides

```diff
- # Machine formated HTML
+ # Machine formatted HTML
```

My sympathies presently are to typo fix solely the following.

mysql-test/suite/parts/t/partition_repair_myisam.test

```diff
- # 5 - (Not used) after mi_state_info_write (fully uppdated/closed index file)
+ # 5 - (Not used) after mi_state_info_write (fully updated/closed index file)
```
storage/maria/ma_locking.c

```diff
  /*
-   Every isam-function that uppdates the isam-database MUST end with this
+   Every isam-function that updates the isam-database MUST end with this
    request
    NOTES
      my_errno is not changed if this succeeds!
  */
```
storage/myisam/mi_locking.c

```diff
  /*
-   Every isam-function that uppdates the isam-database MUST end with this
+   Every isam-function that updates the isam-database MUST end with this
    request
  */
```

**Comment by musvaage** [comment]
https://github.com/MariaDB/server/pull/2389

corrects (formated, uppdated, uppdates)

<hr>

> proof reading of manual (`man/*`) pages 

Perhaps next year I will take a look at those.

**Comment by grooverdan** [comment]
Thanks for your contributions this year.

**Comment by musvaage** [comment]
> backlog

MDEV-18311
Change default PAM service name to mariadb
2019-01-19

I wrote to the Slackware community about the cited ticket.

May 18th of 2020, PAM got added to the Slackware-current core.

MCOL-4266
Clean away Windows carriage return (line ending) characters
2020-08-23

Is there any basis for consideration of .gitattributes content for certain storage/columnstore file types?

`*.bat text eol=crlf`

That could factually be subdirectory specific, but I haven't looked into which would be a relevant repository to add that.

<hr>

> proof reading of manual (`man/*`) pages or KB pages (that get generated into the `HELP sql` SQL statement)

It would be expedient to address typos the user might be exposed to over those thus far revealed in the .c files. 

number of headers and man pages installed

```
$ find /usr/include/mysql -type f | wc -l
438
$ grep -E 'man1|man8' /var/log/packages/mariadb-10.5.18-x86_64-1_slack15.0 \
> | expr $(wc -l) - 2
100
$ 
```

**Pull request closed without merging**
