### PR TITLE
MDEV-25343 log read secret size in error log

### PR DESCRIPTION
**Pull request by dingweiqings**
- [x] *The Jira issue number for this PR is: MDEV-25343*

## Description
Add how much file key plugin bytes readed in error log.

## How can this PR be tested?
As usual , CI test is enough.
## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
No

### CODE REVIEW

**Comment by grooverdan** [comment]
Why does this need to be logged?

**Comment by dingweiqings** [comment]
I am very glad to  receive this commets.  This issue describes that the error log message is not clearly for too large openssl secret  length . So I think it is helpful that  print real size mariadb error log

**Comment by dingweiqings** [comment]
And it is ok about checking the secret length and print length too large to error log .

**Comment by dingweiqings** [comment]
I change to key length check implmention

**Pull request merged**
