### PR TITLE
MDEV-10829 (10.1) add innodb_numa_interleave

### PR DESCRIPTION
**Pull request by grooverdan**
Numa interleave was already in innodb/xtradb code. It just needed cmake (and test) components to activate it (hence targeting 10.1).

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-10829

This task was added to 10.1.19 backlog, which is planned to be handled between 2016-10-13 and 2016-10-20.

Nice, I wasn't aware that InnoDB supports libnuma. Some day we should consider adding numa support to various server components.

Thanks,
Sergey

**Comment by svoj** [comment]
Note that we reluctantly add new library dependencies to GA versions. This may have to be retargetted for 10.2 upon @vuvova and @janlindstrom decision.

**Comment by vuvova** [comment]
I think numa checks in cmake files can be added in 10.1.
New dependency (on libnuma) cannot be added to 10.1 packages. So either we disable numa in 10.1 or we force static libnuma in 10.1 and dynamic in 10.2

**Comment by janlindstrom** [comment]
If I correctly understand current version introduces new dependency for libnuma and that cannot be added to 10.1 packages.

**Comment by grooverdan** [comment]
sounds easier if I just do a pull request against 10.2

**Pull request closed without merging**
