### PR TITLE
MDEV-31369 Disable TLS v1.0 and 1.1 for MariaDB

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-31369*

## Description

Remove TLSv1.1 from the default tls_version system variable.

Output a warning if TLSv1.0 or TLSv1.1 are selected.

Thanks Tingyao Nian for the feature request.

## How can this PR be tested?

Covered by existing tests.

## Basing the PR against the correct MariaDB version
- [ X ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ X ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by PhysicsTing** [comment]
Thanks @grooverdan for addressing this! Code change looks good to me especially the addition of the warning message.

I still believe it will be very beneficial if this can be merged to 10.4. Impact to backward compatibility will be very minimum because it only breaks if the client program explicitly uses only TLSv1.1 (TLSv1.0 is already disabled before). Even then, users can still re-enable TLSv1.1 easily.

**Review by LinuxJedi — APPROVED** [review]

**Comment by fraser-nds** [comment]
Hi @PhysicsTing & @grooverdan, we are currently on 10.4 and experiencing this issue in production with one of our third-party applications. It would be good to re-enable TLSv1.1 (as you suggest) to fix our problem while we work with the third party to update their application to use latest TLS.

Do you have brief instructions on how to re-enable TLSv1.1?

Thanks,
Fraser

**Comment by vuvova** [comment]
it's `--tls-version` server option. The commit has only changed its default value, you can still use `--tls-version=TLSv1.1,TLSv1.2,TLSv1.3`

**Comment by fraser-nds** [comment]
Thanks @vuvova 

Do you have any advice on how to apply this change? In particular we're using an AWS RDS managed database so we might not have full control over server functionality. For example, could it be applied with a query?

e.g.
```SET tls_version='TLSv1.1,TLSv1.2,TLSv1.3';```

**Comment by grooverdan** [comment]
Docs show that [tls_version](https://mariadb.com/kb/en/ssltls-system-variables/#tls_version) isn't Dynamic, and therefor cannot be set at runtime.

On the [AWS RDS page](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MariaDB.Concepts.FeatureSupport.html), tls_version is a parameter from 10.4 upwards so I assume is configurable somewhere in their interfaces;

**Comment by PhysicsTing** [comment]
Hi Fraser,

You can config parameter 'tls_version' by creating a customized RDS
parameter group and associate it to your instance. However due to security
requirements RDS stops allowing using 'tls_version' TLSv1.0 and TLSv1.1
from MariaDB 10.4.32 and above. If you have to use TLSv1.1, please use
MariaDB 10.4.31 or lower.

Working with parameter group:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithDBInstanceParamGroups.html

Tingyao,

**Comment by fraser-nds** [comment]
Thanks @grooverdan and @PhysicsTing 

It looks like RDS doesn't allow you to set the TLS back to 1.1 due to security requirements on their side. And AWS already upgraded us to 10.4.32 so it's not possible to go back a version with RDS. I've raised a support ticket with AWS to see if there is anything they can do.

**Pull request merged**
