### PR TITLE
MDEV-15437 - power crc32 c implementation

### PR DESCRIPTION
**Pull request by grooverdan**
Now tested on BE.

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan, thanks for your contribution!

**Comment by grooverdan** [comment]
@dr-m sorry didn't get to this today. I'll get to these tests Monday. Along with a merge of conflicts (and some bigger buffers in the mtr tets).

**Comment by grooverdan** [comment]
test 1: create on x86_64

<pre>
$ sql/mysqld --skip-networking --datadir=${HOME}/repos/p88/datadir-mariadb-10.3 --log-bin=mysqlbin  --socket /tmp/s.sock --lc-messages-dir=${PWD}/sql/share --verbose
2018-05-07 17:14:11 0 [Note] sql/mysqld (mysqld 10.3.7-MariaDB-log) starting as process 29898 ...
2018-05-07 17:14:11 0 [Warning] Could not increase number of max_open_files to more than 2048 (request: 4182)
2018-05-07 17:14:11 0 [Warning] Changed limits: max_open_files: 2048  max_connections: 151 (was 151)  table_cache: 933 (was 2000)
2018-05-07 17:14:11 0 [Note] InnoDB: Using Linux native AIO
2018-05-07 17:14:11 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-07 17:14:11 0 [Note] InnoDB: Uses event mutexes
2018-05-07 17:14:11 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-07 17:14:11 0 [Note] InnoDB: Number of pools: 1
2018-05-07 17:14:11 0 [Note] InnoDB: Using SSE2 crc32 instructions
2018-05-07 17:14:11 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-07 17:14:11 0 [Note] InnoDB: Completed initialization of buffer pool
2018-05-07 17:14:11 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-07 17:14:12 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-07 17:14:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-07 17:14:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-07 17:14:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-07 17:14:12 0 [Note] InnoDB: Waiting for purge to start
2018-05-07 17:14:12 0 [Note] InnoDB: 5.7.21 started; log sequence number 1630968; transaction id 21
2018-05-07 17:14:12 0 [Note] InnoDB: Loading buffer pool(s) from /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:14:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-07 17:14:12 0 [Note] InnoDB: Buffer pool(s) load completed at 180507 17:14:12
2018-05-07 17:14:12 0 [Note] Reading of all Master_info entries succeded
2018-05-07 17:14:12 0 [Note] Added new Master_info '' to hash table
2018-05-07 17:14:12 0 [Note] sql/mysqld: ready for connections.
Version: '10.3.7-MariaDB-log'  socket: '/tmp/s.sock'  port: 0  Source distribution
2018-05-07 17:17:00 0 [Note] sql/mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2018-05-07 17:17:00 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-07 17:17:01 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-07 17:17:01 0 [Note] InnoDB: Starting shutdown...
2018-05-07 17:17:01 0 [Note] InnoDB: Dumping buffer pool(s) to /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:17:01 0 [Note] InnoDB: Buffer pool(s) dump completed at 180507 17:17:01
2018-05-07 17:17:08 0 [Note] InnoDB: Shutdown completed; log sequence number 2781426; transaction id 125
2018-05-07 17:17:08 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:17:08 0 [Note] sql/mysqld: Shutdown complete
</pre>

load data:
<pre>
(cd $HOME/repos/p88/mariadb-10.3-crc32-c/; cat ./mysql-test/include/world_schema.inc; cat ./mysql-test/include/world.inc) | client/mysql -S  /tmp/s.sock -u root test 
Table	Op	Msg_type	Msg_text
test.Country	analyze	status	OK
test.City	analyze	status	OK
test.CountryLanguage	analyze	status	OK
client/mysql -S  /tmp/s.sock -u root -e 'shutdown'  test 
</pre>

test 2: read/write/recover from ppc64le

<pre>
$  sql/mysqld --skip-networking --datadir=${HOME}/datadir-mariadb-10.3 --log-bin=mysqlbin  --socket /tmp/s.sock --lc-messages-dir=${PWD}/sql/share --pid-file=/tmp/mysqld.pid --verbose
2018-05-07 17:18:36 0 [Note] sql/mysqld (mysqld 10.3.7-MariaDB-log) starting as process 14066 ...
sql/mysqld: One can only use the --user switch if running as root
^C2018-05-07 17:18:43 0 [Note] InnoDB: Using Linux native AIO
2018-05-07 17:18:43 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-07 17:18:43 0 [Note] InnoDB: Uses event mutexes
2018-05-07 17:18:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-05-07 17:18:43 0 [Note] InnoDB: Number of pools: 1
2018-05-07 17:18:43 0 [Note] InnoDB: Using POWER8 crc32 instructions
2018-05-07 17:18:43 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-07 17:18:43 0 [Note] InnoDB: Completed initialization of buffer pool
2018-05-07 17:18:43 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-07 17:18:44 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-07 17:18:44 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:18:44 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-07 17:18:44 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-07 17:18:44 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-07 17:18:44 0 [Note] InnoDB: Waiting for purge to start
2018-05-07 17:18:44 0 [Note] InnoDB: 5.7.21 started; log sequence number 2781426; transaction id 127
2018-05-07 17:18:44 0 [Note] InnoDB: Loading buffer pool(s) from /home/danielgb/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:18:44 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-07 17:18:44 0 [Note] Recovering after a crash using mysqlbin
2018-05-07 17:18:44 0 [Note] Starting crash recovery...
2018-05-07 17:18:44 0 [Note] Crash recovery finished.
2018-05-07 17:18:44 0 [Note] InnoDB: Buffer pool(s) load completed at 180507 17:18:44
2018-05-07 17:18:44 0 [Note] Reading of all Master_info entries succeded
2018-05-07 17:18:44 0 [Note] Added new Master_info '' to hash table
2018-05-07 17:18:44 0 [Note] sql/mysqld: ready for connections.
Version: '10.3.7-MariaDB-log'  socket: '/tmp/s.sock'  port: 0  Source distribution
2018-05-07 17:20:50 0 [Note] sql/mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2018-05-07 17:20:50 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-07 17:20:50 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-07 17:20:50 0 [Note] InnoDB: Starting shutdown...
2018-05-07 17:20:50 0 [Note] InnoDB: Dumping buffer pool(s) to /home/danielgb/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:20:50 0 [Note] InnoDB: Buffer pool(s) dump completed at 180507 17:20:50
2018-05-07 17:20:52 0 [Note] InnoDB: Shutdown completed; log sequence number 2781722; transaction id 131
2018-05-07 17:20:52 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:20:52 0 [Note] sql/mysqld: Shutdown complete
</pre>

<pre>
MariaDB [test]> select count(*) from City;  select count(*) from Country;select count(*) from CountryLanguage;
+----------+
| count(*) |
+----------+
|     4079 |
+----------+
1 row in set (0.002 sec)

+----------+
| count(*) |
+----------+
|      239 |
+----------+
1 row in set (0.000 sec)

+----------+
| count(*) |
+----------+
|      984 |
+----------+
1 row in set (0.001 sec)

MariaDB [test]> shutdown;
Query OK, 0 rows affected (0.000 sec)
</pre>

test 3: read/write/modify from ppc64 (big endian)

<pre>$  sql/mysqld --skip-networking --datadir=${HOME}/p88/datadir-mariadb-10.3 --log-bin=mysqlbin  --socket /tmp/s.sock --lc-messages-dir=${PWD}/sql/share --pid-file=/tmp/mysqld.pid --verbose
2018-05-07 17:22:38 0 [Note] sql/mysqld (mysqld 10.3.7-MariaDB-log) starting as process 1616 ...
2018-05-07 17:22:38 0 [Warning] Could not increase number of max_open_files to more than 1024 (request: 4182)
2018-05-07 17:22:38 0 [Warning] Changed limits: max_open_files: 1024  max_connections: 151 (was 151)  table_cache: 421 (was 2000)
2018-05-07 17:22:38 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-07 17:22:38 0 [Note] InnoDB: Uses event mutexes
2018-05-07 17:22:38 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-07 17:22:38 0 [Note] InnoDB: Number of pools: 1
2018-05-07 17:22:38 0 [Note] InnoDB: Using POWER8 crc32 instructions
2018-05-07 17:22:38 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-07 17:22:38 0 [Note] InnoDB: Completed initialization of buffer pool
2018-05-07 17:22:38 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-07 17:22:38 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-07 17:22:38 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-07 17:22:38 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-07 17:22:38 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-07 17:22:38 0 [Note] InnoDB: 5.7.21 started; log sequence number 2781722; transaction id 127
2018-05-07 17:22:38 0 [Note] InnoDB: Loading buffer pool(s) from /home/ozlabs/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:22:38 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-07 17:22:38 0 [Note] InnoDB: Buffer pool(s) load completed at 180507 17:22:38
2018-05-07 17:22:38 0 [Note] Reading of all Master_info entries succeded
2018-05-07 17:22:38 0 [Note] Added new Master_info '' to hash table
2018-05-07 17:22:38 0 [Note] sql/mysqld: ready for connections.
Version: '10.3.7-MariaDB-log'  socket: '/tmp/s.sock'  port: 0  Source distribution
2018-05-07 17:25:23 0 [Note] sql/mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2018-05-07 17:25:23 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-07 17:25:23 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-07 17:25:23 0 [Note] InnoDB: Starting shutdown...
2018-05-07 17:25:23 0 [Note] InnoDB: Dumping buffer pool(s) to /home/ozlabs/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:25:23 0 [Note] InnoDB: Buffer pool(s) dump completed at 180507 17:25:23
2018-05-07 17:25:25 0 [Note] InnoDB: Shutdown completed; log sequence number 3339753; transaction id 164
2018-05-07 17:25:25 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:25:25 0 [Note] sql/mysqld: Shutdown complete
</pre>

<pre>
MariaDB [test]>  select count(*) from City;  select count(*) from Country;select count(*) from CountryLanguage;
+----------+
| count(*) |
+----------+
|     4079 |
+----------+
1 row in set (0.003 sec)

+----------+
| count(*) |
+----------+
|      239 |
+----------+
1 row in set (0.000 sec)

+----------+
| count(*) |
+----------+
|      984 |
+----------+
1 row in set (0.001 sec)
MariaDB [test]> alter table City modify `Name` char(35) CHARACTER SET utf8mb4  NOT NULL DEFAULT '', modify  `Country` char(3) CHARACTER SET utf8mb4 NOT NULL DEFAULT '', DEFAULT CHARSET=utf8mb4;
Query OK, 4079 rows affected (0.793 sec)               
Records: 4079  Duplicates: 0  Warnings: 0

MariaDB [test]> shutdown;
Query OK, 0 rows affected (0.000 sec)
</pre>

test 4: read from ppc64le

<pre>
$ sql/mysqld --skip-networking --datadir=${HOME}/repos/p88/datadir-mariadb-10.3 --log-bin=mysqlbin  --socket /tmp/s.sock --lc-messages-dir=${PWD}/sql/share --verbose
2018-05-07 17:14:11 0 [Note] sql/mysqld (mysqld 10.3.7-MariaDB-log) starting as process 29898 ...
2018-05-07 17:14:11 0 [Warning] Could not increase number of max_open_files to more than 2048 (request: 4182)
2018-05-07 17:14:11 0 [Warning] Changed limits: max_open_files: 2048  max_connections: 151 (was 151)  table_cache: 933 (was 2000)
2018-05-07 17:14:11 0 [Note] InnoDB: Using Linux native AIO
2018-05-07 17:14:11 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-07 17:14:11 0 [Note] InnoDB: Uses event mutexes
2018-05-07 17:14:11 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-07 17:14:11 0 [Note] InnoDB: Number of pools: 1
2018-05-07 17:14:11 0 [Note] InnoDB: Using SSE2 crc32 instructions
2018-05-07 17:14:11 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-07 17:14:11 0 [Note] InnoDB: Completed initialization of buffer pool
2018-05-07 17:14:11 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-07 17:14:12 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-07 17:14:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-07 17:14:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-07 17:14:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-07 17:14:12 0 [Note] InnoDB: Waiting for purge to start
2018-05-07 17:14:12 0 [Note] InnoDB: 5.7.21 started; log sequence number 1630968; transaction id 21
2018-05-07 17:14:12 0 [Note] InnoDB: Loading buffer pool(s) from /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:14:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-07 17:14:12 0 [Note] InnoDB: Buffer pool(s) load completed at 180507 17:14:12
2018-05-07 17:14:12 0 [Note] Reading of all Master_info entries succeded
2018-05-07 17:14:12 0 [Note] Added new Master_info '' to hash table
2018-05-07 17:14:12 0 [Note] sql/mysqld: ready for connections.
Version: '10.3.7-MariaDB-log'  socket: '/tmp/s.sock'  port: 0  Source distribution
2018-05-07 17:17:00 0 [Note] sql/mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2018-05-07 17:17:00 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-07 17:17:01 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-07 17:17:01 0 [Note] InnoDB: Starting shutdown...
2018-05-07 17:17:01 0 [Note] InnoDB: Dumping buffer pool(s) to /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:17:01 0 [Note] InnoDB: Buffer pool(s) dump completed at 180507 17:17:01
2018-05-07 17:17:08 0 [Note] InnoDB: Shutdown completed; log sequence number 2781426; transaction id 125
2018-05-07 17:17:08 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:17:08 0 [Note] sql/mysqld: Shutdown complete
</pre>

<pre>
MariaDB [test]>  select count(*) from City;  select count(*) from Country;select count(*) from CountryLanguage;
+----------+
| count(*) |
+----------+
|     4079 |
+----------+
1 row in set (0.002 sec)

+----------+
| count(*) |
+----------+
|      239 |
+----------+
1 row in set (0.000 sec)

+----------+
| count(*) |
+----------+
|      984 |
+----------+
1 row in set (0.001 sec)
MariaDB [test]> update Country set SurfaceArea=SurfaceArea*1.3;
Query OK, 239 rows affected (0.087 sec)
Rows matched: 239  Changed: 239  Warnings: 0

MariaDB [test]> shutdown;
Query OK, 0 rows affected (0.000 sec)
</pre>

test 6: read from x86_64

<pre>
$ sql/mysqld --skip-networking --datadir=${HOME}/repos/p88/datadir-mariadb-10.3 --log-bin=mysqlbin  --socket /tmp/s.sock --lc-messages-dir=${PWD}/sql/share --verbose
2018-05-07 17:14:11 0 [Note] sql/mysqld (mysqld 10.3.7-MariaDB-log) starting as process 29898 ...
2018-05-07 17:14:11 0 [Warning] Could not increase number of max_open_files to more than 2048 (request: 4182)
2018-05-07 17:14:11 0 [Warning] Changed limits: max_open_files: 2048  max_connections: 151 (was 151)  table_cache: 933 (was 2000)
2018-05-07 17:14:11 0 [Note] InnoDB: Using Linux native AIO
2018-05-07 17:14:11 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-07 17:14:11 0 [Note] InnoDB: Uses event mutexes
2018-05-07 17:14:11 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-07 17:14:11 0 [Note] InnoDB: Number of pools: 1
2018-05-07 17:14:11 0 [Note] InnoDB: Using SSE2 crc32 instructions
2018-05-07 17:14:11 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-05-07 17:14:11 0 [Note] InnoDB: Completed initialization of buffer pool
2018-05-07 17:14:11 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-05-07 17:14:12 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-05-07 17:14:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-05-07 17:14:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-05-07 17:14:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-05-07 17:14:12 0 [Note] InnoDB: Waiting for purge to start
2018-05-07 17:14:12 0 [Note] InnoDB: 5.7.21 started; log sequence number 1630968; transaction id 21
2018-05-07 17:14:12 0 [Note] InnoDB: Loading buffer pool(s) from /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:14:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-07 17:14:12 0 [Note] InnoDB: Buffer pool(s) load completed at 180507 17:14:12
2018-05-07 17:14:12 0 [Note] Reading of all Master_info entries succeded
2018-05-07 17:14:12 0 [Note] Added new Master_info '' to hash table
2018-05-07 17:14:12 0 [Note] sql/mysqld: ready for connections.
Version: '10.3.7-MariaDB-log'  socket: '/tmp/s.sock'  port: 0  Source distribution
2018-05-07 17:17:00 0 [Note] sql/mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2018-05-07 17:17:00 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-07 17:17:01 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-07 17:17:01 0 [Note] InnoDB: Starting shutdown...
2018-05-07 17:17:01 0 [Note] InnoDB: Dumping buffer pool(s) to /home/dan/repos/p88/datadir-mariadb-10.3/ib_buffer_pool
2018-05-07 17:17:01 0 [Note] InnoDB: Buffer pool(s) dump completed at 180507 17:17:01
2018-05-07 17:17:08 0 [Note] InnoDB: Shutdown completed; log sequence number 2781426; transaction id 125
2018-05-07 17:17:08 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-05-07 17:17:08 0 [Note] sql/mysqld: Shutdown complete
</pre>

<pre>

MariaDB [test]> select count(*) from City;  select count(*) from Country;select count(*) from CountryLanguage;
+----------+
| count(*) |
+----------+
|     4079 |
+----------+
1 row in set (0.001 sec)

+----------+
| count(*) |
+----------+
|      239 |
+----------+
1 row in set (0.000 sec)

+----------+
| count(*) |
+----------+
|      984 |
+----------+
1 row in set (0.000 sec)
</pre>

**Comment by grooverdan** [comment]
<pre>
$ ls -la  ${HOME}/p88/datadir-mariadb-10.3/mysqlbin.000002
-rw-rw----. 1 ozlabs 1003 171340 May  7 17:17 /home/ozlabs/p88/datadir-mariadb-10.3/mysqlbin.000002

For each arch:
$ client/mysqlbinlog  ${HOME}/p88/datadir-mariadb-10.3/mysqlbin.000002 >   ${HOME}/p88/binlog-$(uname -m}.log
</pre>

<pre>
# at 256
#180507 17:14:12 server id 1  end_log_pos 299 CRC32 0xf5b9399d 	Gtid list [0-1-43]
# at 299
#180507 17:14:12 server id 1  end_log_pos 341 CRC32 0x1eb41c04 	Binlog checkpoint mysqlbin.000002
# at 341
#180507 17:16:31 server id 1  end_log_pos 383 CRC32 0x536080fa 	GTID 0-1-44 ddl
/*!100101 SET @@session.skip_parallel_replication=0*//*!*/;
/*!100001 SET @@session.gtid_domain_id=0*//*!*/;
/*!100001 SET @@session.server_id=1*//*!*/;
/*!100001 SET @@session.gtid_seq_no=44*//*!*/;
# at 383
#180507 17:16:31 server id 1  end_log_pos 718 CRC32 0x2919e628 	Query	thread_id=9	exec_time=1	error_code=0
<pre>

All identical on decode:
<pre>
danielgb@p88:~$ diff -u binlog-ppc64.log  binlog-x86_64.log
danielgb@p88:~$ diff -u binlog-ppc64le.log  binlog-x86_64.log
danielgb@p88:~$ ls -la binlog*
-rw-rw-r-- 1 danielgb danielgb 181020 May  7 17:46 binlog-ppc64le.log
-rw-rw-r-- 1 danielgb danielgb 181020 May  7 17:43 binlog-ppc64.log
-rw-rw-r-- 1 danielgb danielgb 181020 May  7 17:45 binlog-x86_64.log
<pre>

**Comment by dr-m** [comment]
I did a test push of this to [bb-10.3-marko](https://github.com/MariaDB/server/commit/e79443d861e7be6cfbbbf5f905bfaed1e24e98ce). Unfortunately, it fails to link on all 3 POWER platforms that I tested (there are a couple more which are only part of pushes to the main branches):
http://buildbot.askmonty.org/buildbot/builders/kvm-rpm-centos73-ppc64/builds/4661/steps/compile/logs/stdio
```
/home/buildbot/buildbot/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX/mariadb-10.3.7/storage/innobase/ut/ut0crc32.cc:124: undefined reference to `crc32c_vpmsum'
collect2: error: ld returned 1 exit status
```
http://buildbot.askmonty.org/buildbot/builders/kvm-rpm-centos73-ppc64le/builds/4764/steps/compile/logs/stdio
```
libmariadbd.a(ut0crc32.cc.o): In function `ut_crc32_power8(unsigned char const*, unsigned long)':
/home/buildbot/buildbot/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX/mariadb-10.3.7/storage/innobase/ut/ut0crc32.cc:124: undefined reference to `crc32c_vpmsum'
```
http://buildbot.askmonty.org/buildbot/builders/kvm-deb-trusty-ppc64le/builds/4869/steps/compile/logs/stdio
```
libmariadbd.a(ut0crc32.cc.o): In function `ut_crc32_power8':
/home/buildbot/buildbot/build/mariadb-10.3.7/storage/innobase/ut/ut0crc32.cc:124: undefined reference to `crc32c_vpmsum'
```
@grooverdan Can you help fix this? I have little experience in CMake configuration, and the POWER machines on our buildbot are overloaded.

The patch itself looks OK to me. Once the code builds and the tests (including innodb.log_corruption) pass on our buildbot, I am happy to merge this.

**Comment by grooverdan** [comment]
fixed as per last commit and #749  for convenience. I'm assuming your right resolving innodb.log_corruption

**Comment by dr-m** [comment]
Thanks! It built and tested fine with the linking fix.

**Comment by grooverdan** [comment]
Great, thanks for merging.

**Comment by dr-m** [comment]
@grooverdan Sorry, but with the wider platform coverage in our main branch, it turns out that something needs to be fixed [for SuSE 12](http://buildbot.askmonty.org/buildbot/builders/p8-suse12-rpm/builds/4756/steps/compile/logs/stdio):
```
cd /home/buildbot/maria-slave/power8-vlp05-rpm/build/extra/crc32-vpmsum && /usr/bin/cc  -DCRC32_CONSTANTS_HEADER=\"crc32c_constants.h\" -DCRC32_FUNCTION=crc32c_vpmsum -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing  -Wno-uninitialized   -fPIC -maltivec -mvsx -mpower8-vector -mcrypto -mpower8-vector -o CMakeFiles/crc32c.dir/vec_crc32.c.o   -c /home/buildbot/maria-slave/power8-vlp05-rpm/build/extra/crc32-vpmsum/vec_crc32.c
/home/buildbot/maria-slave/power8-vlp05-rpm/build/extra/crc32-vpmsum/vec_crc32.c: In function ‘__crc32_vpmsum’:
/home/buildbot/maria-slave/power8-vlp05-rpm/build/extra/crc32-vpmsum/vec_crc32.c:217:3: error: invalid parameter combination for AltiVec intrinsic
   vdata0 = vec_xor(vdata0, vcrc);
```
There is a large number of such errors, for both `vec_xor()` and `vec_and()`. Perhaps the compiler is too old?
>-- The C compiler identification is GNU 4.8.3

**Comment by grooverdan** [comment]
Compiler might be too old despite being only a few minor versions behind RHEL7. I'll see what can be done on Monday.

**Comment by grooverdan** [comment]
So I took a look in the SLE-SERVER/12/ppc64le/update/ppc64le/ directory on a SLES mirror and saw these packages:
<pre>
gcc48-4.8.3+r212056-11.2.ppc64le.rpm                 2014-Nov-13 09:35      6.8M
gcc48-4.8.3+r212056-6.3_11.2.ppc64le.drpm            2014-Nov-13 09:38      1.4M
gcc48-4.8.5-18.1.ppc64le.rpm                         2015-Jul-31 10:01      6.7M
gcc48-4.8.5-18.1_24.1.ppc64le.drpm                   2015-Oct-27 12:00      1.5M
gcc48-4.8.5-24.1.ppc64le.rpm                         2015-Oct-27 11:56      6.7M
gcc48-4.8.5-24.1_27.1.ppc64le.drpm                   2016-Jun-15 08:30      1.9M
gcc48-4.8.5-27.1.ppc64le.rpm                         2016-Jun-15 08:27      6.7M
gcc48-c++-4.8.3+r212056-11.2.ppc64le.rpm             2014-Nov-13 09:35      6.4M
gcc48-c++-4.8.3+r212056-6.3_11.2.ppc64le.drpm        2014-Nov-13 09:38      1.6M
gcc48-c++-4.8.5-18.1.ppc64le.rpm                     2015-Jul-31 10:01      6.3M
gcc48-c++-4.8.5-18.1_24.1.ppc64le.drpm               2015-Oct-27 12:00      1.6M
gcc48-c++-4.8.5-24.1.ppc64le.rpm                     2015-Oct-27 11:56      6.2M
gcc48-c++-4.8.5-24.1_27.1.ppc64le.drpm               2016-Jun-15 08:30      2.2M
gcc48-c++-4.8.5-27.1.ppc64le.rpm                     2016-Jun-15 08:27      6.3M
</pre>

Given a gcc 4.8.5 upgrade compiler package came out first in 2015-Jul-31 can we do an update on the build server? This is on the base SLE-SERVER without going to the 3 service packs (SP1, SP2 and SP3) released for version 12.

I did manage to compile on a SLE-SERVER/12-SP3 gcc(4.8.5-31) but ran out of time/skill to do the downgrade properly.

**Comment by dr-m** [comment]
Thanks! Upgrading sounds reasonable to me. @dbart can we do that on p8-suse12?

**Comment by dbart** [comment]
In case you didn't see my update to MDEV-16160, gcc has been updated to 4.8.5 on the p8-suse12-rpm builder

**Pull request merged**
