### PR TITLE
Misc Debian build improvements

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by ottok** [comment]
This is ready for review now, but #1467 needs to go in 10.5 first.

After this PR is merged, the https://jira.mariadb.org/browse/MDEV-21965 (TLS 1.0 not supported on Ubuntu Focal) will be the only remaining issue regarding Debian builds for 10.5 in buildbot.

**Comment by ottok** [comment]
This is now ready for review and merging.

**Comment by ottok** [comment]
Travis-CI passing:
image

http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5&category=main&category=experimental is passing to the degree it can pass..

**Comment by cvicentiu** [comment]
Hi @ottok !

Preliminary look to me seems ok. I will test myself tomorrow and see if I catch anything, then we can merge.

**Comment by ottok** [comment]
Ok, good to know your schedule. I'll do some extra tests now when @rasmushoj's rename changes have landed in master and perhaps add some final polish.

**Comment by ottok** [comment]
Merging now. Will continue on the topic in #1478

**Pull request merged**
