### PR TITLE
MDEV-10697 GOTO statement

### PR DESCRIPTION
**Pull request by halfspawn**

### CODE REVIEW

**Comment by svoj** [comment]
Hi halfspawn,

Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-10697

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by abarkov** [comment]
Hi halfspawn,
the pull request seems to have some merges and reverts:
https://github.com/MariaDB/server/pull/310
Would it be possible to do the following:
- Clone again the latest bb-10.2-comptibility. "git pull" may not works well, because we rebase bb-10.2-compatibility on top of 10.2 from time to  time
- Apply the patch and commit it again
- Create a new pull request with one commit
Thanks!

**Comment by svoj** [comment]
No need to create new pull request. It should be possible to make these updates within current PR.

**Comment by halfspawn** [comment]
Hi Sergey,
I sent the MCA yesterday and you have register it (Jérôme Brauge).
Perhaps my git account (halfspawn) is misleading.

Best regards,
Jérôme.

**Comment by svoj** [comment]
@halfspawn, alright, it works. Thanks for identifying yourself.

**Pull request closed without merging**
