### PR TITLE
MDEV-9001 - Fix DB name quoting in mysqldump --routine

### PR DESCRIPTION
**Pull request by FGasper**
MariaDB fix for: https://bugs.mysql.com/bug.php?id=78932

(code is original, not copied from MySQL)

### CODE REVIEW

**Comment by FGasper** [comment]
It would be great to get a backport of this to as many versions are supported … the breakage from this is pretty debilitating when you want a full backup of everything.

**Comment by svoj** [comment]
Hi FGasper,

thanks for you contribution. JIRA task has been created to track this pull request: https://mariadb.atlassian.net/browse/MDEV-9001

Thanks,
Sergey

**Comment by svoj** [comment]
This task was added to 5.5.47 backlog, which is supposed to be handled between 2015-12-01 and 2015-12-08.

**Comment by svoj** [comment]
Filipe,

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by FGasper** [comment]
I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

Sent from my android device.

-----Original Message-----

**Comment by svoj** [comment]
Felipe,

- it won't work with e.g. --compatible=ansi, where quote character is double quote (instead of back tick)
- it doesn't escape string, which is needed for the following statement issued by dump_routines_for_db(): "SHOW %s STATUS WHERE Db = '%s'"
- the following statement issued by switch_db_collation()/restore_db_collation() will suffer from double quoting: "ALTER DATABASE %s CHARACTER SET %s COLLATE %s %s"
- same for the following statement issued by fetch_db_collation(): "use %s"

The correct fix is to use escaped string for string literals and original string for identifiers (which are quoted later), like in this patch: http://lists.askmonty.org/pipermail/commits/2015-December/008694.html

**Comment by svoj** [comment]
Fix pushed to 5.5: https://github.com/MariaDB/server/commit/9f07c6b383d776d430510de1256b3e4e8680bc60

**Pull request closed without merging**
