### PR TITLE
CRC32 on AIX

### PR DESCRIPTION
**Pull request by EGuesnet**
CRC32 support has been written for Linux and FreeBSD only. This PR adds AIX.

AIX 7.1+ has altivec / vec crypto / vsx support for all machine on POWER 8+. As MariaDB does not support POWER 7, it is available on all AIX.
CMAKE_SYSTEM_PROCESSOR returns "powerpc" and not "powerpc64" on AIX. It is the expected behavior [according documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html#variable:CMAKE_HOST_SYSTEM_PROCESSOR): same result than ``uname -p``.

### CODE REVIEW

**Comment by grooverdan** [comment]
@EGuesnet if you can see anything obvious to fix this CI environment https://buildbot.mariadb.org/#/builders/121/builds/12/steps/5/logs/stdio can you please let me know.

**Comment by EGuesnet** [comment]
> @EGuesnet if you can see anything obvious to fix this CI environment https://buildbot.mariadb.org/#/builders/121/builds/12/steps/5/logs/stdio can you please let me know.

line 1067: getopt.h is missing.
You can get it at http://www.bullfreeware.com/pkg?id=6649 .

Moreover, I suspect you use gnu-ar. If binutils is installed, you must force ar to be /usr/bin/ar (I imagine ``AR=/usr/bin/ar`` is OK with cmake but I never tried). gnu-ar is not fully ported on AIX.
``rpm -qa`` will give you information about what is installed on the machine.

If it does not work, I think it will be easier to give me access to the machine to investigate.

**Comment by grooverdan** [comment]
Thanks @EGuesnet  - that put me on the right track was obviously however the compat-getopt-devel package. The AR fix was spot on too.

On this PR I've pushed this commit into 10.5. Along with an ALIGN 5dbea46cfdc83f2455c7f4a43a4cc932192cfac6 fix.

In 10.6 @montywi has this commit 924b6b1ec9bdff49c03148e68b14887f42f02564 that is work in progress.

It fails to compile on AIX - https://buildbot.mariadb.org/#/builders/121/builds/9/steps/5/logs/stdio

Do you know what would the the right AIX fix?

Fixing the signal warnings is a common problem we've solved elsewhere so I'll get those in the right location.

**Comment by EGuesnet** [comment]
I have checked build log, and there is different trouble:

- fork: Resource temporarily unavailable
- a getopt error

About fork error, you probably use ``-jN`` with a large `N`. I have the same trouble with `N` larger than 16.

About `getopt` remaining error, my mistakes: the devel package is also needed http://www.bullfreeware.com/pkg?id=6650 .

I have tried 924b6b1 commit, and I have a warning, but it works
```
[  2%] Building C object mysys/CMakeFiles/mysys.dir/my_addr_resolve.c.o
/opt/freeware/src/packages/BUILD/mariadb-10.5.9/mysys/my_addr_resolve.c: In function 'my_addr_resolve':
/opt/freeware/src/packages/BUILD/mariadb-10.5.9/mysys/my_addr_resolve.c:324:9: warning: assignment to 'void *' from 'char' makes pointer from integer without a cast [-Wint-conversion]
   offset= info.dli_fbase;
         ^
```

**Comment by grooverdan** [comment]
Mistakenly had `-j$(getconf _NPROCESSORS_ONLN)` with `getconf` being a linux thing and failing, output nothing. But slowly getting there.

Today blind tested 8213543c501808df026e33a8845c0f78081e209e and `CHECK_FUNCTION_EXISTS (getgroupsbyname HAVE_GETGROUPSBYNAME)` failed. Will look next week . Committed 4ca4d606ac96cabe013eb5c9e4eda92233cf1697 today.

In other good AIX news - https://gitlab.kitware.com/cmake/cmake/-/issues/21090 got fixed.

**Comment by EGuesnet** [comment]
About PAM, I do not build it. I confirm a symbol error when I try
> ld: 0711-317 ERROR: Undefined symbol: .getgrouplist

`getgrouplist` and ``getgroupsbyname`` do not exist on AIX. I will check the right way to do this.

For your information, I have the list of plugin or functionalities not yet ported:

- embedded (missing symbols since 10.5.4);
- connect plugin (data corruption during test);
- disks, galera, mroonga, rocksdb, wsrep (labelled as "Linux only" according my very old comments; I think wsrep works now, but it needs Boost and we prefer to avoid this huge dependency);
- all plugin labelled Gamma, Beta, Alpha or Experimental in [this page](https://mariadb.com/kb/en/list-of-plugins) are ignored if they do work as is. handlersocket works, all other are inactivated.

If you think some of them are mandatory, I can port them.

**Comment by grooverdan** [comment]
"getgroupsbyname do not exist on AIX."  - doh, was looking z/OS man pages.

**Comment by grooverdan** [comment]
Don't stress on pam support - b58b289827af4a4905a8afeee9c381f3b593c293 is sufficient for AIX not to recognize getgrouplist doesn't exist.

Also happy to accommodate whatever functions are ready, and I'll ping if something is particularly important.

In the mean time I'm just keen on all the CMake checks being right so a default AIX build doesn't have to guess at what is/isn't going to compile (or work).

**Pull request closed without merging**
