### PR TITLE
MDEV-9303 - SphinxSE: add support for json filtering

### PR DESCRIPTION
**Pull request by ohwgiles**
The filter command did not accept characters . [ ] which are valid
in an attribute name for a sphinx query with json filtering.

+ test case added

### CODE REVIEW

**Comment by svoj** [comment]
Hi Oliver,

Thanks for your contribution. JIRA task has been created to track this pull request: https://mariadb.atlassian.net/browse/MDEV-9303

Since MariaDB team doesn't handle SphinxSE code base, this was also reported upstream: http://sphinxsearch.com/bugs/view.php?id=2388

Thanks,
Sergey

**Comment by svoj** [comment]
Oliver,

Wlad volunteered to handle your patch on the MariaDB side. Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
 
The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
 
Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by ohwgiles** [comment]
I hereby submit this pull request, including all new code and modifications under the BSD-new license

**Comment by vaintroub** [comment]
merged into 10.1.12. Thank you  for contribution!

**Pull request closed without merging**
