### PR TITLE
MEV-26312: Record iteration methods in JOIN_CACHE_BNL public

### PR DESCRIPTION
**Pull request by eberroca**
This commit creates new public methods to iterate the join
cache. This is useful for engine condition pushdown in
remote storage engines. In addition to push the condition,
we can also push data to match rows during JOIN.
This avoids full table scan and hence full table read
over the network.

Signed-off-by: Eduardo Berrocal <eduardo.berrocal@intel.com>

- [x] *The Jira issue number for this PR is: MDEV-26312*

## Description
See commit message.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by spetrunia** [comment]
Q1: is it actually necessary to expose  `skip_next_candidate_for_match(uchar *rec_ptr)` ?

Q2:
The functions are declared protected in class JOIN_CACHE, and then this patch makes them public in the inherited class JOIN_CACHE_BNL. This is technically legal but is not a good practice.

We want to allow iteration only for JOIN_CACHE_BNL (and not for other JOIN_CACHE_XXX classes) . Let's make this explicit and introduce these public inline functions in JOIN_CACHE_BNL:

```
bool iterator_init() { return prepare_look_for_matches(false); }
uchar* iterator_get_next() { return get_next_candidate_for_match();}
void iterator_unpack_current(uchar *) { return read_next_candidate_for_match(); }
```

Please also add a comment mentioning that iteration over the contents of the join buffer is used by a 3rd party storage engine.

**Comment by eberroca** [comment]
@spetrunia I added the changes you suggested. In addition to the functions you suggested, I also added a couple extra needed in order to access more information. For example, Field information (to know what fields are stored in the cache). These 2 new methods are:
```
- CACHE_FIELD *get_field_descr()
- CACHE FIELD **get_blob_ptr()
```
Let me know, thanks.

**Comment by an3l** [comment]
Hi @eberroca can you please create MDEV for this PR ?
Also, can you please rebase to a single commit?

**Comment by eberroca** [comment]
Hi @an3l , sorry for being too new here. How do I create a MDEV?

**Comment by eberroca** [comment]
@an3l : I need access to the jenkins server, right? Can you point me to where I can create an MDEV?

**Comment by an3l** [comment]
You can create an MDEV in our [JIRA system](https://jira.mariadb.org/projects/MDEV/issues/MDEV-19275?filter=allopenissues) :).
That way you can use MDEV number in your commit message too.
I will create this one and you can update description :).

**Comment by eberroca** [comment]
@an3l I already did created one. Please, remove yours :-). Sorry for the confusion. I also did rebase my commits. Let me know what else has to be done.

**Pull request closed without merging**
