### PR TITLE
MDEV-6262 Add travis-ci configuration

### PR DESCRIPTION
**Pull request by grooverdan**
In adding travis-ci integration pull requests get the chance to run though most of the test suite, including big test, (except a couple as listed in MDEV-7429).

Using Coverity scans can be set up http://docs.travis-ci.com/user/coverity-scan/ and these will apply to coverity* branches as per commented parts of .travis.yml

Code coverage information with coveralls.org is almost ready (waiting on https://github.com/travis-ci/apt-package-whitelist/pull/14)

Having a sftp server to upload build failures and packages would be useful. Like the last bit of after_failure this can be restricted to non-pull requests and specific branches.

10.0/10.1 may need a couple of small changes.

### CODE REVIEW

**Comment by grooverdan** [comment]
@ChasonTang - can you give me some tips on OSX compiling of mariadb (after #79 is fixed), travis has OS X Mavericks that I might be able to get going.

I'm guessing some variation of https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mariadb.rb

**Comment by ChasonTang** [comment]
um. I compile & install mariadb manually,so i don't have some issue in homebrew.what i think the issue of mariadb is tokudb. after fix #79 ,i haven't meet other bug up to now.Btw,you can have a try to compile mariadb via gcc, it could avoid the error of struct __toku_db_lsn

**Comment by ChasonTang** [comment]
homebrew have a script to disable tokudb.but it just little issue in the tokudb,disable the tokudb is not a good idea.

**Comment by ottok** [comment]
@grooverdan You seem to have multiple travis.yml versions in multiple repos. Is openquery:travis-5.5_clean still the best version?

**Comment by grooverdan** [comment]
yes

**Comment by ottok** [comment]
The build result https://travis-ci.org/openquery/mariadb-server does not seem to be active? Because the travis.yml now points to mariadb/server Travis-CI account (which does not exist)? I will set one up now.

**Comment by grooverdan** [comment]
there's been no builds on https://travis-ci.org/openquery/mariadb-server  since nothing has been merged or pushed to a branch with .travis.yml recently.

> Travis-CI account (which does not exist)? I will set one up now.

Great

Can you set up a coveralls.io account too.

I was going to put the rpm/deb builds on their own instance not shared with other test env builds. Sorry haven't got to that yet.

**Comment by ottok** [comment]
I've merged your travis file on my own branch ok-debpkg-10.1 and then I've heavily refactored it and have ran test builds at https://travis-ci.org/ottok/mariadb

I am still working to find the most elegant solution.

**Comment by grooverdan** [comment]
in your search for elegance let me enlighten you on a few aspects:
* non container builds are slow - this is why your builds are taking 35min rather than ~10 on a container. Its partially that container builds have more ram and handle parallel connections better. Its probably lower overhead in switching
* Good to see you trying trusty, it certainly does simplify depends, be nice once its containerized
* Non-debug builds skip heaps of tests, but getting a working deb build as a test is a good goal, should be parallelised as separate worker however.
* You can ask travis support for the extra build time on the repo

Once trusty containers are available on travis, I expect the build could be done in 1-2 hrs.

For a full test suite adding the env matrix back in for separate workers will utilise the test for the debug build and the big-tests (excluding the far too big ones).

Thanks for taking a look @ottok

**Comment by ottok** [comment]
I have now in branch https://github.com/ottok/mariadb/tree/ok-travis-ci-10.1 a simple Travis-CI implementation that runs the Debian build and a small testsuite that just passed in 46 minutes within the Travis-CI.org 50 minute limit.

I like this simple one because it will be easier to maintain in the long run (no manually defined cmake commands, no manual fetching and building binutils etc).

**Comment by svoj** [comment]
I merged Otto's PR to 10.2. Let's continue further development from that point.

**Pull request closed without merging**
