### PR TITLE
MDEV-12157 - spelling fixes

### PR DESCRIPTION
**Pull request by ka7**
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.

Please note:
Checked the full source, and found overall ~ 2.5k potential ones in about 1k files. ( the script is sometimes just stupid and creates false-positives, or rename variables.. I'm after the # comments, readme, .. - stuff that don't break your project. ).
Anyway, that's a bunch of changes - so here this is a first try to check your reaction. Maybe you want to keep sources if possible similar to mysql, the changes will take some time to review, ... also maybe just 1 big patch or 10 smaller ones; a GH-pull-request or a mail with .patch
For testing I do "make; make test" to changed source in a docker environment. So should not introduce issues.

### CODE REVIEW

**Comment by ka7** [comment]
.. there is now also a travis-based auto-test-builds available: 
- https://travis-ci.org/ka7/server/builds/205594481 ( original sources )
- https://github.com/ka7/server/blob/feature/travis/.travis.yml

I know, you run in background your own Jenkins environment. But the green check-mark for a github pull-request let me sleep well.

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-12157

This task was added to 10.1.22 backlog, which is planned to be handled between 2017-03-03 and 2017-03-10.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by svoj** [comment]
@ka7, we're running 10.1 sprint currently. If we won't get license confirmation, we'll have to postpone this task for the next sprint.

**Comment by ka7** [comment]
this patch is published under the "BSD-new license".

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
