### PR TITLE
MDEV-30502: Change lsb-base to sysvinit-utils

### PR DESCRIPTION
**Pull request by illuusio**
- [x] *The Jira issue number for this PR is: MDEV-30502*

## Description
As Debian 12 deprecates lsb-base change lsb-base to sysvinit-utils. Reasoning to this is that LSB init scripts are changes to that package and 10.10 will be LTS and provided by Debian 12 (Bookworm).

Make also changes to  `debian/autobake-debs.sh` to make sure that there is backward compatibility. Version that are still using lsb-base are Debian **10** and **11** also to Ubuntu **18.04,** **20.04**, **22.04** and **22.10**
## How can this PR be tested?
Run `debian/autobake-debs.sh` with Debian 11 and see if `debian/control` has `lsb-base` and it compiles ok.

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*

## Backward compatibility
This has negative compatibility as after this as without using  `debian/autobake-debs.sh` it does not make packages that works with Sysvinit below Debian 12

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

### CODE REVIEW

**Review by grooverdan — APPROVED** [review]

**Comment by ottok** [comment]
As I commented in https://github.com/MariaDB/server/pull/2467#issuecomment-1409941202, you could simply remove `lsb-base (>= 3.0-10)` from the debian/control file, and add it back in old distros to avoid having changes in them.

**Comment by illuusio** [comment]
> As I commented in [#2467 (comment)](https://github.com/MariaDB/server/pull/2467#issuecomment-1409941202), you could simply remove `lsb-base (>= 3.0-10)` from the debian/control file, and add it back in old distros to avoid having changes in them.

And again I'll point that SysV-init script requires `lsb-functions.h`. I we don't care about SysV-init (which is wanted by Debian if i'm correct) otherwise we just have to remove that or move it own package

**Comment by illuusio** [comment]
Ok now `lsb-base` and `sysvinit-utils` dependency is removed and added error message in SysV init script that mentions that youll need `sysvinit-utils` if you like to continue. Tuned `autobake-debs.sh` also to be backward compatible.

**Review by ottok — APPROVED** [review]
LGTM!

**Comment by ottok** [comment]
Note that sysvinit-utils is `Essential: yes` meaning it exists on all Debian systems by default, so having a dependency on it is kind of moot. Or did you come across a system somewhere that did not have it? A Docker container perhaps?

```
± apt show sysvinit-utils
Package: sysvinit-utils
Version: 2.88dsf-59.10ubuntu1
Priority: required
Essential: yes
Section: admin
Source: sysvinit
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian sysvinit maintainers <pkg-sysvinit-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 61,4 kB
Depends: libc6 (>= 2.14), init-system-helpers (>= 1.25~), util-linux (>> 2.28-2~)
Breaks: systemd (<< 215)
Replaces: initscripts (<< 2.88dsf-59.5)
Homepage: http://savannah.nongnu.org/projects/sysvinit
Task: minimal
Supported: 5y
Download-Size: 18,6 kB
APT-Manual-Installed: yes
APT-Sources: http://ca.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
Description: System-V-like utilities
 This package contains the important System-V-like utilities.
 .
 Specifically, this package includes:
 killall5, pidof
```

**Comment by illuusio** [comment]
I've made assumption that `sysvinit-utils` is installed and user can remove it.

**Comment by ottok** [comment]
> I've made assumption that `sysvinit-utils` is installed and user can remove it.

Seems unlikely. If you try to do it you get this message:
```
 apt remove sysvinit-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  sysvinit-utils
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  sysvinit-utils
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 102 kB disk space will be freed.
E: Removing essential system-critical packages is not permitted. This might break the system.
```

As I stated in [my first comment](https://github.com/MariaDB/server/pull/2501#issuecomment-1449483523), simply removing lsb-base should be enough.

**Comment by illuusio** [comment]
No it's like first comment there is no `lsb-base` but `autobake-debs.sh` is updated to add it to distros that need it.

**Review by ottok — APPROVED** [review]
LGTM! :+1:

**Comment by ottok** [comment]
This has been approved by both me and Daniel, so I will go ahead and merge this.

**Pull request merged**
