### PR TITLE
MDEV-26891 Server crashes in Field::register_field_in_read_map upon INSERT DELAYED with virtual columns

### PR DESCRIPTION
**Pull request by kohei-matsuyama**
- [x] *The Jira issue number for this PR is: MDEV-26891*

## Description
This patch is trying to fix a reported server crushing bug.
This was occurring because vcol_item is null in register_field_in_read_map() at field.cc:11292.
I fixed it by adding vcol_info->expr in if() like this:
-if (vcol_info)
+if (vcol_info && vcol_info->expr)

## How can this PR be tested?
Please try: ./mysql-test/mysql-test-run.pl innodb.MDEV-26891
Thank you,

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by ottok** [comment]
Why did you close this? You can change branch on the PR, and you can locally rebase on any branch and force push here. No need to close this PR and open a new one.

**Comment by grooverdan** [comment]
@kohei-matsuyama thanks for the patch. I've tested it and it looks fine.

If you could open this PR, and on the right hand side enable 'Allow edits and access to secrets by maintainers' I can push a version here that is cleaned up.

If I could also get a email address for the commit that would be much appreciated.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
 
The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
 
Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

**Comment by grooverdan** [comment]
I had a bit of a closer look. While this patch obviously prevents the crash, the reason that `vcol_info->expr` is null is potentially the deeper issue that needs to be addressed.

**Comment by kohei-matsuyama** [comment]
Daniel, sorry for my late reply and thank you for your review. @grooverdan

**Pull request closed without merging**
