### PR TITLE
MDEV-27663 Spider: remove #ifdef SPIDER_USE_CONST_ITEM_FOR_STRING_INT_REAL_DECIMAL_DATE_ITEM

### PR DESCRIPTION
**Pull request by TakeKiyo**
## Description
Dead code and #ifdef related to
SPIDER_USE_CONST_ITEM_FOR_STRING_INT_REAL_DECIMAL_DATE_ITEM have been removed.

- [x] *The Jira issue number for this PR is: MDEV-27663*

## How can this PR be tested?
No modification of test cases.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by nayuta-yanagisawa** [comment]
@TakeKiyo Thank you for your contribution. The patch itself looks good to me. Could you rebase your branch to 10.9 HEAD?

**Comment by TakeKiyo** [comment]
@nayuta-yanagisawa 
I accidentally merge the 10.9 HEAD commit...
please give me some time to fix that.

**Comment by nayuta-yanagisawa** [comment]
@TakeKiyo You can recreate your branch from the fresh 10.9 HEAD and then cherry-pick your commit to the branch.

**Comment by TakeKiyo** [comment]
@nayuta-yanagisawa 
Is it OK to recreate the pull request??

**Comment by TakeKiyo** [comment]
@nayuta-yanagisawa 
I craeted another pull request and will close this pull request.
Sorry for the inconvenience.

**Comment by nayuta-yanagisawa** [comment]
@TakeKiyo OK, but why ddid't you force push to the branch. It would have been enough.

**Comment by TakeKiyo** [comment]
@nayuta-yanagisawa 
I had no idea how to refresh the branch while storing the previous commit...
I will learn more about git as well.

**Pull request closed without merging**
