### PR TITLE
MDEV-30483 Add fix for migration from MySQL 5.7 to MariaDB 10.6

### PR DESCRIPTION
**Pull request by christian7007**
- [x] *The Jira issue number for this PR is: MDEV-30483, MDEV-30809

## Description

As described in [MDEV-30483](https://jira.mariadb.org/browse/MDEV-30483) and [MDEV-30809](https://jira.mariadb.org/browse/MDEV-30809) the migration path from MySQL 5.7 to MariaDB 10.6 is broken because the `PRTYPE` of `last_update` column for tables `mysql.innodb_table_stats` and `mysql.innodb_index_stats` is not being properly updated after running the corresponding alter table command.

This PR adds logic into the `scripts/mysql_system_tables_fix.sql` script to force the tables rebuild when the alter table does not update the `PRTYPE` properly by using the `force` flag, after the table rebuild the `PRTYPE` is properly updated.

**NOTE**: This changes should be temporal to ensure migration path keeps working until the underlying issue preventing the first `alter table` statement to upgrade the `PRTYPE` is fixed.

## How can this PR be tested?
- Deploy a fresh MySQL 5.7 server.
- Upgrade to MariaDB 10.6.
- Run `mysql_upgrade` tool.
- Run the following queries and check that the `PRTYPE` field for `last_update` column is right (expected value is: `526087`)

```
SELECT a.name AS `Table`, b.TABLE_ID,b.NAME,b.POS,b.MTYPE,b.PRTYPE,b.LEN from innodb_sys_tables a, innodb_sys_columns b where a.name like 'mysql/innodb_table_stats' and a.table_id=b.table_id order by b.table_id,b.pos;

SELECT a.name AS `Table`, b.TABLE_ID,b.NAME,b.POS,b.MTYPE,b.PRTYPE,b.LEN from innodb_sys_tables a, innodb_sys_columns b where a.name like 'mysql/innodb_index_stats' and a.table_id=b.table_id order by b.table_id,b.pos;
```

## Basing the PR against the correct MariaDB version
- [X] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Copyright
All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by ottok** [comment]
I backported this to 10.11 and tested running the full MTR (including --big-test) on [amd64/arm64/ppc64el/s390x](https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/debian-mariadb/+builds?build_text=&build_state=all), and I also included this in a package for which I ran extensive [install/upgrade testing on Debian](https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/512904). I did not come across any issues introduced by this change, so all this testing is in favor of merging this.

**Comment by christian7007** [comment]
Hi @dr-m, yes, the goal of the PR is to at least ensure the behaviour defined in `scripts/mysql_system_tables_fix.sql` for `mysql.innodb_table_stats` and `mysql.innodb_index_stats` tables is enforced until the real cause is located and fixed. I tried to deep dive and find the issue with the information shared in [MDEV-30483](https://jira.mariadb.org/browse/MDEV-30483) but I wasn't able to find the root cause.

**Comment by ottok** [comment]
This was cherry-picked to the official Debian/Ubuntu package of MariaDB 10.11.2 in https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/8b7a0cc6f1bf861b692554830e3b124ef033c26e

**Comment by ottok** [comment]
This is a workaround to a regression in MariaDB 10.6.11. Permanent fix is tracked in https://jira.mariadb.org/browse/MDEV-30483.

**Comment by LinuxJedi** [comment]
@dr-m are you saying we should reject the workaround? Or should we include the workaround until a proper fix can be developed?

**Comment by ottok** [comment]
This PR might fix these related potenrially duplicates issues:
* [MDEV-30809: mysql_upgrade is not upgrading the type of last_update column for innodb_index_stats and innodb_table_stats tables](https://jira.mariadb.org/browse/MDEV-30809)
* [MDEV-30483: After upgrade to 10.6 from Mysql 5.7 seeing "InnoDB: Column last_update in table mysql.innodb_table_stats is BINARY(4) NOT NULL but should be INT UNSIGNED NOT NULL"](https://jira.mariadb.org/browse/MDEV-30483)
* [MDEV-29128: Possible table (mysql.innodb_table_stats) structure mismatch in internals](https://jira.mariadb.org/browse/MDEV-29128)
* [MDEV-27044: Test main.mysql_upgrade seems unstable](https://jira.mariadb.org/browse/MDEV-27044)

**Comment by christian7007** [comment]
Closing this PR as the final fix should be already addressed by: https://github.com/MariaDB/server/commit/9edb1a5ce3d56ffc4ce7be1e698d55fecac0fe09

**Pull request closed without merging**
