### PR TITLE
MDEV-7773 - Aggregate functions

### PR DESCRIPTION
**Pull request by varunraiko**
This contains the progress I made during my GSOC project on Aggregate stored functions. Here is the link to the issue:
https://jira.mariadb.org/browse/MDEV-7773

### CODE REVIEW

**Comment by svoj** [comment]
Hi varunraiko,

Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by varunraiko** [comment]
I am contributing the whole code of the pull request, including one or several files that are either new files or modified ones, under the BSD-new license

**Comment by grooverdan** [comment]
fyi: i did a merge of 10.2 and corrected the conflicts and other compile/test errors.

There is one assertion remaining https://github.com/varunraiko/aggregate-functions/pull/1 and the tests probably should be written with ONLY_FULL_GROUP_BY in mind so they have predictable outcomes.

I wasn't intending to do much more than resolving the conflicts so I'm leaving this for anyone else to carry on with. Its always good to get work competed and merged.

**Comment by cvicentiu** [comment]
This pull request was refactored in:
https://github.com/MariaDB/server/compare/b213f57dc3f9da93ce444805f7581d982bde9f75...60c446584c614f19f9adc9cc38a31954359009d5

It is now pushed. Thanks to everyone involved for their help!

**Pull request closed without merging**
