### PR TITLE
Tests: some sql_sequence tests require wsrep plugin

### PR DESCRIPTION
**Pull request by midenok**
Please, merge.

### CODE REVIEW

**Comment by svoj** [comment]
Thanks for your contribution! Could you explain how exactly these tests require wsrep? What happens if it is unavailable?

**Comment by midenok** [comment]
Results fail like this:
```diff
--- ./mysql-test/suite/sql_sequence/gtid.result	2017-11-14 13:23:16.441066303 +0300
+++ ./mysql-test/suite/sql_sequence/gtid.reject	2017-11-15 09:32:27.389983116 +0300
@@ -603,7 +603,6 @@
 show  session variables like '%binlog_format%';
 Variable_name	Value
 binlog_format	STATEMENT
-wsrep_forced_binlog_format	NONE
 create sequence s1 cache 2;
 select next value for s1;
 ERROR HY000: Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging.
--- ./mysql-test/suite/sql_sequence/replication.result	2017-11-14 13:23:16.442066349 +0300
+++ ./mysql-test/suite/sql_sequence/replication.reject	2017-11-15 09:32:30.206828339 +0300
@@ -699,7 +699,6 @@
 show  session variables like '%binlog_format%';
 Variable_name	Value
 binlog_format	STATEMENT
-wsrep_forced_binlog_format	NONE
 create sequence s1 cache 2;
 select next value for s1;
 ERROR HY000: Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging.
@@ -722,7 +721,6 @@
 show  session variables like '%binlog_format%';
 Variable_name	Value
 binlog_format	MIXED
-wsrep_forced_binlog_format	NONE
 create sequence s1 cache 2;
 select next value for s1;
 next value for s1
```

**Comment by midenok** [comment]
Fixed to `include/have_wsrep.inc` instead of `include/have_wsrep_enabled.inc`.

**Comment by svoj** [comment]
If that's the only problem, just replace
```
show  session variables like '%binlog_format%';
```
with
```
show  session variables like 'binlog_format';
```

Monty confirmed that ```wsrep_forced_binlog_format``` doesn't make much sense here.

**Comment by midenok** [comment]
Fixed.

**Comment by svoj** [comment]
Looks good, thanks!

**Pull request merged**
