### PR TITLE
MDEV-16210 FK constraints on versioned tables use historical rows, which may cause constraint violation

### PR DESCRIPTION
**Pull request by midenok**
This code is submitted under the BSD-new license.

Will be merged with that message:

Constraint check is done on secondary index update. F. ex. DELETE does row_upd_sec_index_entry() and checks constraints in row_upd_check_references_constraints(). UPDATE is optimized for the case when order is not changed (node->cmpl_info & UPD_NODE_NO_ORD_CHANGE) and doesn't do row_upd_sec_index_entry(), so it doesn't check constraints. Since for versioned DELETE we do UPDATE actually, but expect behaviour of DELETE in terms of constraints, we should deny this optimization to get constraints checked.

### CODE REVIEW

**Comment by midenok** [comment]
@dr-m Please review second commit.

**Comment by vuvova** [comment]
I don't understand what this InnoDB change is doing. Could someone elaborate, please?

**Comment by midenok** [comment]
Added to commit message:

On DELETE all secondary indexes are updated with
row_upd_sec_index_entry() which checks foreign key constraint. This
doesn't happen for UPDATE when order is not changed (node->cmpl_info &
UPD_NODE_NO_ORD_CHANGE).

Since this code point was meant for plain UPDATE now for versioned
DELETE we need to use UPD_NODE_UPDATE_ALL_SEC to force update all the
secondary index records.

**Comment by dr-m** [comment]
OK to push. Sorry that this was in limbo so long.

**Comment by midenok** [comment]
Will be pushed from `bb-10.3-midenok`.

**Pull request closed without merging**
