### PR TITLE
Rename all Debian packaging files 10.2 -> 10.3 in the new 10.3 branch

### PR DESCRIPTION
**Pull request by ottok**
Currently we have massive failure on http://buildbot.askmonty.org/buildbot/grid?branch=10.3&category=main&category=experimental because the VERSION file was bumped but the debian/* files were sill at 10.2.

I reviewed debian/* and updated filenames and references to have 10.2 where needed, and update 10.1 to 10.2 in the control file when when the current-1 version is references etc changes.

Local test build passed, final verdict will soon come out from http://buildbot.askmonty.org/buildbot/grid?branch=ok-debpkg-10.3&category=main&category=experimental

### CODE REVIEW

**Comment by ottok** [comment]
No builtbot job passes fully, but at least they now proceed from the step where they were failing previously.

Additional build on Launchpad passed OK on most platforms, but 386 fails due to mroonga build issue and amrhf due to the lack of libnuma on that platform: https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.3/+builds?build_text=&build_state=all

Not being able to build on armhf at all is a bad thing as it might render the package incompatible with official Debian inclusion..

**Comment by svoj** [comment]
@ottok, I believe your editor broke debian/po files. Could you fix that?

It should be possible to build without NUMA, I guess it is only a matter of fixing scripts.

**Comment by ottok** [comment]
@svoj: OK, I see, the utf-8 characters got mangled. I'll try to fix that.

**Comment by svoj** [comment]
Should've been fixed by 75b8fe4f18c6e15196acd6f45b38bdce56ced919

**Pull request closed without merging**
