### PR TITLE
Cleanup the alloca.h header handling to further reduce hardcoded OS l…

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by LinuxJedi — APPROVED** [review]

**Comment by LinuxJedi** [comment]
Nice cleanup, many thanks!

**Comment by grooverdan** [comment]
Causes AIX error:

https://buildbot.mariadb.org/#/builders/121/builds/9094/steps/5/logs/stdio
```
In file included from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/services.h:24,
                 from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/plugin.h:53,
                 from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/plugin_auth.h:28,
                 from /home/buildbot/aix/build/mariadb-10.6.11/plugin/auth_gssapi/server_plugin.cc:40:
/home/buildbot/aix/build/mariadb-10.6.11/include/mysql/service_encryption.h: In function 'int encryption_crypt(const unsigned char*, unsigned int, unsigned char*, unsigned int*, const unsigned char*, unsigned int, const unsigned char*, unsigned int, int, unsigned int, unsigned int)':
/home/buildbot/aix/build/mariadb-10.6.11/include/mysql/service_encryption.h:115:14: error: 'alloca' was not declared in this scope; did you mean 'valloc'?
  115 |   void *ctx= alloca(encryption_ctx_size(key_id, key_version));
      |              ^~~~~~
      |              valloc
```

Ultimate cause, global.h/config.h needs to be included to define HAVE_ALLOCA_H. This could occur at top of plugin/auth_gssapi/server_plugin.cc

I'm tempted to revert or come up with a *BSD compile time define check to avoid the alloc.h include.

@LinuxJedi  suggestions?

**Comment by grooverdan** [comment]
revert https://github.com/MariaDB/buildbot/commit/3c88cd8ae34787cd91baad2e3dac94b53ae9a109 on fix merged up.

**Comment by grooverdan** [comment]
```
In file included from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/services.h:24,
                 from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/plugin.h:53,
                 from /home/buildbot/aix/build/mariadb-10.6.11/include/mysql/plugin_data_type.h:28,
                 from /home/buildbot/aix/build/mariadb-10.6.11/plugin/type_mysql_json/type.cc:17:
/home/buildbot/aix/build/mariadb-10.6.11/include/mysql/service_encryption.h: In function 'int encryption_crypt(const unsigned char*, unsigned int, unsigned char*, unsigned int*, const unsigned char*, unsigned int, const unsigned char*, unsigned int, int, unsigned int, unsigned int)':
/home/buildbot/aix/build/mariadb-10.6.11/include/mysql/service_encryption.h:115:14: error: 'alloca' was not declared in this scope
  115 |   void *ctx= alloca(encryption_ctx_size(key_id, key_version));
      |              ^~~~~~
/home/buildbot/aix/build/mariadb-10.6.11/include/mysql/service_encryption.h:115:14: note: the macro 'alloca' had not yet been defined
In file included from /home/buildbot/aix/build/mariadb-10.6.11/include/my_global.h:330,
                 from /home/buildbot/aix/build/mariadb-10.6.11/plugin/type_mysql_json/type.cc:18:
/usr/include/alloca.h:30: note: it was later defined here
   30 | #define alloca(size)   __builtin_alloca (size)
   ```
   too.

**Comment by brad0** [comment]
Provided a PR here for 10.3.. https://github.com/MariaDB/server/pull/2321

**Comment by brad0** [comment]
Looks like type_mysql_json was added in 10.5. I can send a PR for 10.5 for that after that is merged.

**Pull request merged**
