### PR TITLE
MDEV-27448: MTR returns success (zero) upon invalid option

### PR DESCRIPTION
**Pull request by Shunpoco**
- [x] *The Jira issue number for this PR is: MDEV-27448*

## Description
This issue is caused by a function `usage()` in mariadb-test-run.pl.
When we try to run `perl ./mtr` with the wrong option (in the example, `perl ./mtr --ps--protocol`), a function `usage()` in mariadb-test-run.pl is called with the wrong option as its argument. In this case, because the function call `exit;` in a first if statement, we get exit status `0`. However, the expected status is `1`.

## How can this PR be tested?
Call these commands on a terminal
```bash
$ perl ./mtr --ps--protocol
$ echo $?
```
The expected output is as follows:
```bash
$ perl ./mtr --ps--protocol
Logging: ./mtr  --ps--protocol
VS config: 
Invalid option "--ps--protocol"
For full list of options, use ./mtr --help
$ echo $?
1
```
## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by Shunpoco** [comment]
For version 10.6 and 10.7, they use `mariadb-test-run.pl`.
But for 10.5 or former versions, they use [`mysql-test-run.pl`](https://github.com/MariaDB/server/blob/10.5/mysql-test/mysql-test-run.pl) instead of `mariadb-test-run.pl`.
Is it better to create another PR for 10.5 or former?

**Comment by an3l** [comment]
Hi @Shunpoco , thanks for the patch.
Can you please change the base to {{10.2}} on this PR, as the earliest branch to which patch should be applied?
No need to create new PR for other versions.

**Comment by Shunpoco** [comment]
Hi @an3l , thank you for your suggestion!
I changed the base branch to 10.2, but I have a lot of changes (over 5000) now.
Can I close this PR and recreate a new PR from 10.2?

**Comment by Shunpoco** [comment]
Now I fixed :pray:

**Comment by grooverdan** [comment]
Thanks for the bug fix. I got caught out by this the other day, so good timing.

**Pull request merged**
