### PR TITLE
Bug fix for has_higher_priority

### PR DESCRIPTION
**Pull request by sensssz**
Remove the victim preference since VATS is not enabled in replication.
Consider lock wit mode first.

### CODE REVIEW

**Comment by sensssz** [comment]
@janlindstrom Hi, Jan. This is the fix for 10.2.

**Comment by svoj** [comment]
Hi Jiamin,

Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by svoj** [comment]
@sensssz it would be nice if you could resolve conflicts, thanks!

**Comment by janlindstrom** [comment]
commit 9ea5de30963dd16cec7190b8b2f77858f4a82545
Merge: 3371904 7f504c7
Author: Jan Lindström <jan.lindstrom@mariadb.com>
Date:   Wed Dec 7 09:19:27 2016 +0200

    Merge branch 'sensssz-10.2-vats' into 10.2

commit 7f504c72467ae2a93966b15aa2013aaf13745530
Merge: 3371904 02c8852
Author: Jan Lindström <jan.lindstrom@mariadb.com>
Date:   Wed Dec 7 09:18:41 2016 +0200

    Merge branch '10.2-vats' of https://github.com/sensssz/server into sensssz-10.2-vats

**Comment by sensssz** [comment]
Hi, Sergey,

I am contributing my new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

Hi, Jan,

Thanks for merging the branch!

**Pull request merged**
