### PR TITLE
MDEV-15128: wsrep_sst_common.sh to properly handle compressor with arguments

### PR DESCRIPTION
**Pull request by bmalynovytch**
https://jira.mariadb.org/browse/MDEV-15128

### CODE REVIEW

**Comment by grooverdan** [comment]
Thanks for your contribution.

Note this minorly conflicts with 95e5fe6732d939bd4b43f3a02fe004d530653093 in the 10.0-galera branch.

I totally agree with the fix however. Do you think you can do a fix against the 10.0-galera branch as it will be easier to merge forwards and also provide a fix for the users of earlier versions.

At some point I was considering running shellcheck over all our scripts resolving all the flaky aspects of sst scripts like the one you discovered here.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

**Comment by bmalynovytch** [comment]
I completely agree to contribute this pull request as well as new ones under the BSD-new license. 
@grooverdan I checked the code from 95e5fe6. It seem to be really different from what's in 10.2+, which means that we would need to have at least 2 fixes and 2 pull requests. Is that what you expect ?

**Comment by grooverdan** [comment]
As 10.1, 10.2 and 10.3 releases happen the fixes from the earlier versions are merged before release. So only one fix/pr is required against 10.0-galera.

**Comment by bmalynovytch** [comment]
@grooverdan I reworked all the shell scripts based on 10.0-galera, trying to catch every cases where unsafe variables could cause troubles.
10.2 and 10.3 will need the same refactoring as they introduced new cases.
Don't forget to change the milestone if required.

**Comment by bmalynovytch** [comment]
I'm preparing more changes to protect more variables

**Comment by grooverdan** [comment]
wow. Throughout. Thanks.

**Comment by SachinSetiya** [comment]
I do not think If we are using [[ , we need "" to surround variable.
http://mywiki.wooledge.org/BashGuide/TestsAndConditionals#Conditional_Blocks_.28if.2C_test_and_.5B.5B.29
 There is some other issue I think , _debugging the script_

**Comment by bmalynovytch** [comment]
@SachinSetiya I won't have time during the next weeks to debug the scripts, but I should have enough to fix the variable inclusions. Should I continue or leave them alone ?

**Comment by SachinSetiya** [comment]
right @grooverdan , For the time I think we will go for #617 , If time permits I will work on your pull request.

**Comment by bmalynovytch** [comment]
Let's for for the minor fix then 🙄

**Pull request closed without merging**
