### PR TITLE
MDEV-18750: Failed to get the result using mysqlbinlog flashback option on big binlog file

### PR DESCRIPTION
**Pull request by hzc989**
fix the problem that Failed to get the result using mysqlbinlog flashback option on big binlog file.(MDEV-18750)

### CODE REVIEW

**Comment by SteamedFish** [comment]
You shouldn't delete the test file

**Comment by hzc989** [comment]
It encountered a 'Can't read data from IO_CACHE: Success' error when using mysqlbinlog to flashback a large binlog file. 
it should be the problem of  a function in 'mysys/my_read.c' called 'my_read', as followed:
`
if (readbytes != Count)
{
   ...
   if (readbytes != (size_t) -1 && (MyFlags & MY_FULL_IO))
  {
  Buffer+= readbytes;
  Count-= readbytes;
  continue;
  }
}
`

By adding the MY_FULL_IO to the iocache's tags in the reinit_io_cache() func could fix.

**Comment by hzc989** [comment]
It encountered a 'Can't read data from IO_CACHE: Success' error when using mysqlbinlog to flashback a large binlog file.
it should be the problem of a function in 'mysys/my_read.c' called 'my_read', just take a look in the for loop , each time the read() operation can only read  2147479552( which is related to the maximum read_buffer_size, I guess? Did't try hard to figure it why and what limits it)
 because  (MyFlags & MY_FULL_IO)) returns false it is unable to continue reading over the io_cache and exited.

Therefore by adding the MY_FULL_IO to the iocache's tags in the reinit_io_cache() func could fix.

**Comment by hzc989** [comment]
It encountered a `Can't read data from IO_CACHE: Success` error when using mysqlbinlog to flashback a large binlog file.
it should be the problem of a function in `mysys/my_read.c` called `my_read`- just take a look in the for loop , each time the `read()` operation can only read `2147479552`( which is related to the maximum read_buffer_size, I guess? Did't try hard to figure it why and what limits it).
and because `(MyFlags & MY_FULL_IO))` returns false it is unable to continue reading through the io_cache and exited.

Therefore by adding the `MY_FULL_IO` FLAG in the `reinit_io_cache()` func could fix.

**Comment by an3l** [comment]
Hi @hzc989 ,
thank you for your contribution.
Can you please add result file as well:  `./mtr flashback.largebinlog.test --record` ?

**Comment by hzc989** [comment]
Hi @an3l , already made it. Thanks a lot for your advice, it took me quite a while since I am a absolute beginner~

> Hi @hzc989 ,
> thank you for your contribution.
> Is it possible to add result file as well: `./mtr flashback.largebinlog.test --record` ?

**Comment by hzc989** [comment]
update at 2018.03.08: 
Actually, I later realized that this bug was already fixed in release 10.3.11 , but since it is not yet applied to branch 10.2, I still made this pull request , plus adding the required mtr test and result file. please check.

**Comment by hzc989** [comment]
squash done. But sadly, I've got no idea on how to  write an  io_cache unit test for its entire functionality.[smile with cry]

**Pull request merged**
