### PR TITLE
SQL: optimized build fix on view/derived

### PR DESCRIPTION
**Pull request by midenok**
@dr-m Please, merge.

### CODE REVIEW

**Comment by dr-m** [comment]
Merged. For me, a debug build on AMD64 still fails to bootstrap when trying to update the unique index `ID_IND` of `SYS_TABLES`.
My warning-removal commit 53083bda252484ca50fdb89e5dda9d67e93ed08f which apparently should have removed the failing assertion altogether (`thr` is declared `__attribute__((nonnull))`),
Looking at commit 84e59cfb90e728e646620f472b0b28eb889c7ae8, I think that you should always create a dummy `thr` and not relax assertions. An example can be found in `ha_innobase_inplace_ctx::ha_innobase_inplace_ctx()`.
I removed the bogus assertion in commit 244259155369fa04187f6724aac0b438e20de437.

**Comment by midenok** [comment]
At commit phase there is no table-specific `handler`, only `handlerton`. So no `prebuilt` ever possible (and unable to `pars_complete_graph_for_exec()`). I remember, that I've never seen `thr` used except for getting `trx` at these call paths. Are there any async operations at low level?

**Comment by dr-m** [comment]
I see that at commit, a call to the new function `vers_notify_vtq()` has been added. I believe that it could be cleaner design to move this call above the storage engine layer, so that the VTQ table would be updated via the `handler` interface. Then there would be `thr` and `prebuilt` objects created.

One other challenge with the InnoDB commit is that it is not prepared to return errors. I think that the correct handling of a failure to update the VTQ table at commit would be to roll back the transaction and to return an error. This error handling ought to be easier to implement outside the storage engine code, perhaps in `ha_commit_trans()`.

**Comment by midenok** [comment]
> I believe that it could be cleaner design to move this call above the storage engine layer, so that the VTQ table would be updated via the handler interface. Then there would be thr and prebuilt objects created.

That fits the design of global transaction table, I see. But should we do it now? It means we are going away from InnoDB transparent versioning in favour of SQL versioning. I'm not an enemy of this, but now there are some important feature tasks.

> One other challenge with the InnoDB commit is that it is not prepared to return errors. I think that the correct handling of a failure to update the VTQ table at commit would be to roll back the transaction and to return an error. This error handling ought to be easier to implement outside the storage engine code, perhaps in ha_commit_trans().

Hmm... This doesn't quite fit the idiom of COMMIT to be fast and failsafe. I guess, commit should proceed even if it failed to store historical data properly. Maximum it should do is to bring a warning about it.

**Pull request merged**
