### PR TITLE
Tests: innodb_encryption detect table count

### PR DESCRIPTION
**Pull request by midenok**
Please, review and merge.

### CODE REVIEW

**Comment by svoj** [comment]
It'd be nice to explain in commit message why it was needed.

**Comment by midenok** [comment]
I thought this is self-explanatory: if table count changes, no need to find out what's wrong with test. The test is quite unfriendly on this matter: if table count is different it just hangs.

**Comment by svoj** [comment]
@janlindstrom what this wait was supposed to do? What are those 3 tables it is waiting for?

**Comment by midenok** [comment]
I will add explanation to commit message as requested and add more fixed cases.

**Comment by midenok** [comment]
Reopened at #534

**Pull request closed without merging**
