### PR TITLE
MDEV-27791 Create a new MyRocks parameter rocksdb_log_dir

### PR DESCRIPTION
**Pull request by XYHong18**
Parameter rocksdb_log_dir specifies the path of MyRocks error logs.

By default, the error logs are stored in the same folder with MyRocks
redo logs. Being able to put human readable logs in one place and
machine logs in another place improves usability.

All new code of the whole pull request, including one or several files
that are either new files or modified ones, are contributed under the
BSD-new license. I am contributing on behalf of my employer Amazon 
Web Services, Inc.

### CODE REVIEW

**Comment by grooverdan** [comment]
Nice idea thanks @XYHong18. I added a rework of the test. I see you've just copied the rocksdb_datadir.test previously. The use of BOOTSTRAP like it did is a little messy.

Do you think the commit I appended is still accurate? I'm hoping its a little easier to read.

Looking forward to your and your employer's contributions to RocksDB. There are a some long outstanding of bugs and improvements to make.

**Comment by XYHong18** [comment]
@grooverdan Thanks for your comments. Yes, your commit for rocksdb_log_dir.test makes it easier to read. I double-checked it by rerunning the test with your commit, and it passed and the rocksdb error log appeared under the directory mariadb/mysql-test/var/tmp. So it is accurate. 

Yes, I created the rocksdb_log_dir_basic.test by copying the same logic of rocksdb_wal_dir_basic.test because I think the two parameters are equivalent. Do you suggest I remove this rocksdb_log_dir_basic.test? Or do you suggest I add more testing to rocksdb_log_dir_basic.test?

Thanks!

**Comment by grooverdan** [comment]
Thanks for confirming the test changes.

`rocksdb_log_dir_basic.test` looks fine to me and with `sys_var=ROCKSDB_LOG_DIR` it's testing a different variable to `rocksdb_wal_dir_basic.test`. I'm glad at least it served as a good test template.

I don't see anything more meaningful to test in the log_dir variable that is read only. Nothing more is required.

I'm just going to check the target branch with @spetrunia sometime in the near future.

**Comment by XYHong18** [comment]
Hi @grooverdan, I force-pushed a new version with the two commits combined.

**Review by grooverdan — APPROVED** [review]
Looks good. A rebase to 10.9 at some stage will be required. I'm happy to take care of this at the time its ready to be merged.

**Comment by XYHong18** [comment]
I’ve rebased this on latest 10.9. Please review @spetrunia , thanks!

**Comment by XYHong18** [comment]
Rebased the commit on the latest 10.9.

**Review by spetrunia — APPROVED** [review]
Looks good to me

**Comment by XYHong18** [comment]
@spetrunia Thank you! Do you think it can be merged?

**Comment by grooverdan** [comment]
Thank you @XYHong18. Sorry it took so long. We'll endeavor to do better next time.

**Pull request merged**
