### PR TITLE
MDEV-28145: columnstore still enabled in i386 builds

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-28145*

## Description

This cannot work due to undefined int128 types in 32 builds.

As such we take from the RocksDB and explicitly disable when the
feature isn't there.

## How can this PR be tested?

see if bb fails on i386 builds.

Also pay attention to non-amd64/arm64 builds to see if they previously built and now don't

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ X ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility

Check if ppc64le, or other non-amd64/arm64 builds fail.

### CODE REVIEW

**Comment by illuusio** [comment]
If it's not Aarch64 or AMD64 then don't build Columnstore. Looks clear to me..

**Comment by vuvova** [comment]
What does this fix? How is it "still enabled" ?

**Comment by grooverdan** [comment]
> What does this fix?

It was partially a guess based on the rocksdb CMakeFiles.txt, so I'm hoping on a result of BB to confirm it or not.

> How is it "still enabled" ?

I suspect the MYSQL_ADD_PLUGIN that most other plugins use somehow disables it.

I never quite works it out however.

**Comment by vuvova** [comment]
See my comment in the MDEV

**Pull request closed without merging**
