### PR TITLE
MDEV-29179 Condition pushdown from HAVING into WHERE is not shown in optimizer trace

### PR DESCRIPTION
**Pull request by mariadb-RexJohnston**
Pull request created in: https://jira.mariadb.org/browse/MDEV-29179

### CODE REVIEW

**Comment by spetrunia** [comment]
What would be wrong with
```
diff --git a/sql/sql_select.cc b/sql/sql_select.cc
index eb54484fa51..f64e198b85a 100644
--- a/sql/sql_select.cc
+++ b/sql/sql_select.cc
@@ -2118,6 +2118,10 @@ JOIN::optimize_inner()
                                                   select_lex->attach_to_conds,
                                                   &cond_value);
       sel->attach_to_conds.empty();
+      Json_writer_object wrapper(thd);
+      Json_writer_object pushd(thd, "condition_pushdown_from_having");
+      pushd.add("conds", conds);
+      pushd.add("having", having);
     }
   }
 
```
produces
```json
            "condition_processing": {
              "condition": "WHERE",
              "original_condition": "t1.b <> 'p' or t1.a = 4",
              ...
            }
          },
          {
            "condition_processing": {
              "condition": "HAVING",
              "original_condition": "t1.a <= 7",
              ...
            }
          },
          {
            "condition_pushdown_from_having": {
              "conds": "(t1.b <> 'p' or multiple equal(4, t1.a)) and t1.a <= 7",
              "having": null
            }
          },
```
(Perhaps, the names should be "resulting_where" and "resulting_having" to match other printouts)

**Comment by rex-johnston** [comment]
> What would be wrong with
> 
> ```
> diff --git a/sql/sql_select.cc b/sql/sql_select.cc
> index eb54484fa51..f64e198b85a 100644
> --- a/sql/sql_select.cc
> +++ b/sql/sql_select.cc
> @@ -2118,6 +2118,10 @@ JOIN::optimize_inner()
>                                                    select_lex->attach_to_conds,
>                                                    &cond_value);
>        sel->attach_to_conds.empty();
> +      Json_writer_object wrapper(thd);
> +      Json_writer_object pushd(thd, "condition_pushdown_from_having");
> +      pushd.add("conds", conds);
> +      pushd.add("having", having);
>      }
>    }
>  
> ```
> 
> produces
> 
> ```json
>             "condition_processing": {
>               "condition": "WHERE",
>               "original_condition": "t1.b <> 'p' or t1.a = 4",
>               ...
>             }
>           },
>           {
>             "condition_processing": {
>               "condition": "HAVING",
>               "original_condition": "t1.a <= 7",
>               ...
>             }
>           },
>           {
>             "condition_pushdown_from_having": {
>               "conds": "(t1.b <> 'p' or multiple equal(4, t1.a)) and t1.a <= 7",
>               "having": null
>             }
>           },
> ```
> 
> (Perhaps, the names should be "resulting_where" and "resulting_having" to match other printouts)

because then

`json_detailed(json_extract(trace, '$**.steps[*].join_optimization.steps[*].condition_processing') )`

would only produce

```
[
    {
        "condition": "WHERE",
        "original_condition": "t1.b <> 'p' or t1.a = 4",
        "steps": 
        [
            {
                "transformation": "equality_propagation",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            },
            {
                "transformation": "constant_propagation",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            },
            {
                "transformation": "trivial_condition_removal",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            }
        ]
    },
    {
        "condition": "HAVING",
        "original_condition": "t1.a <= 7",
        "steps": 
        [
            {
                "transformation": "equality_propagation",
                "resulting_condition": "t1.a <= 7"
            },
            {
                "transformation": "constant_propagation",
                "resulting_condition": "t1.a <= 7"
            },
            {
                "transformation": "trivial_condition_removal",
                "resulting_condition": "t1.a <= 7"
            }
        ]
    }
]
```

instead of

```
[
    {
        "condition": "WHERE",
        "original_condition": "t1.b <> 'p' or t1.a = 4",
        "steps": 
        [
            {
                "transformation": "equality_propagation",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            },
            {
                "transformation": "constant_propagation",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            },
            {
                "transformation": "trivial_condition_removal",
                "resulting_condition": "t1.b <> 'p' or multiple equal(4, t1.a)"
            },
            {
                "transformation": "having_to_where_pushdown",
                "resulting_condition": "(t1.b <> 'p' or multiple equal(4, t1.a)) and t1.a <= 7"
            }
        ]
    },
    {
        "condition": "HAVING",
        "original_condition": "t1.a <= 7",
        "steps": 
        [
            {
                "transformation": "equality_propagation",
                "resulting_condition": "t1.a <= 7"
            },
            {
                "transformation": "constant_propagation",
                "resulting_condition": "t1.a <= 7"
            },
            {
                "transformation": "trivial_condition_removal",
                "resulting_condition": "t1.a <= 7"
            },
            {
                "transformation": "having_to_where_pushdown",
                "resulting_condition": null
            }
        ]
    }
]
```

**Comment by spetrunia** [comment]
I see the logic. 
However, consider this example:

```
CREATE TABLE t2 (a INT, b INT, KEY (a), KEY(b,a)) ENGINE=InnoDB;
INSERT INTO t2 VALUES (4,444),(1,111),(NULL,9999);
SELECT b, a FROM t2 WHERE b <> 33333 OR a = 4 GROUP BY b, a HAVING a <= 7 and b=a;
```

It will cause the processing to be logged in backwards fashion:

```
        "steps": [
          {
            "condition_processing": {
              "condition": "WHERE",
              "original_condition": "t2.b <> 33333 or t2.a = 4",
              "steps": [
                {
                  "transformation": "equality_propagation",
                  "resulting_condition": "t2.b <> 33333 or multiple equal(4, t2.a)"
                },
                {
                  "transformation": "constant_propagation",
                  "resulting_condition": "t2.b <> 33333 or multiple equal(4, t2.a)"
                },
                {
                  "transformation": "trivial_condition_removal",
                  "resulting_condition": "t2.b <> 33333 or multiple equal(4, t2.a)"
                },
                {
                  "transformation": "having_to_where_pushdown",
                  "resulting_condition": "(t2.b <> 33333 or multiple equal(4, t2.a, t2.b)) and t2.a <= 7 and multiple equal(t2.a, t2.b)"
### note that "multiple equal(t2.a, t2.b)" is appears here.
### While it is constructed only below there:
                }
              ]
            }
          },
          {
            "condition_processing": {
              "condition": "HAVING",
              "original_condition": "t2.a <= 7 and t2.b = t2.a",
              "steps": [
                {
                  "transformation": "equality_propagation",
                  "resulting_condition": "t2.a <= 7 and multiple equal(t2.b, t2.a)"
####  Here.
                },
                {
                  "transformation": "constant_propagation",
                  "resulting_condition": "t2.a <= 7 and multiple equal(t2.b, t2.a)"
                },
                {
                  "transformation": "trivial_condition_removal",
                  "resulting_condition": "t2.a <= 7 and multiple equal(t2.b, t2.a)"
                },
                {
                  "transformation": "having_to_where_pushdown",
                  "resulting_condition": null
                }
              ]
            }
          },
```

which is not good. 
Please use the approach requested.

Yes, it will cause  `having_to_where_pushdown` to be logged outside `condition_processing` ...  Which is ok, because that's how the optimizer does it.   Pushdown actually does happen outside of `condition_processing` ...

**Review by spetrunia — CHANGES_REQUESTED** [review]
Please change according to the input provided.

**Review by spetrunia — APPROVED** [review]
Ok to push.

**Pull request closed without merging**
