### PR TITLE
Enabling Travis builds for s390x

### PR DESCRIPTION
**Pull request by namrata-ibm**
As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same with below changes:
* Separated common packages to be installed for Linux 
* Added matrix for amd64 and s390x jobs with remaining dependencies. 
* Added a job for env: DebPackages for s390x

### CODE REVIEW

**Comment by namrata-ibm** [comment]
I am contributing my PR under the BSD-new licence

**Comment by namrata-ibm** [comment]
@vladbogo Could you please have a look?

**Comment by vladbogo** [comment]
Hi,

Sorry for the late reply. I think that there needs to be done some refactoring for the packages before merging. The packages list from line 99 and 150 is almost duplicate, so I would suggest some refactoring to it.

Cheers!

**Comment by namrata-ibm** [comment]
@vladbogo , could you please review the changes?

**Comment by namrata-ibm** [comment]
Thanks @grooverdan.. I tried running jobs by increasing parallel threads to 8 and observed faster build times for few jobs:
https://travis-ci.com/linux-on-ibm-z/server/builds/149382070
vs 
https://travis-ci.com/linux-on-ibm-z/server/builds/148181565 (my earlier run)
Is there any optimum value we should consider?

**Comment by grooverdan** [comment]
Its hard to estimate an optimum value without knowing hardware was allocated to each travis Z worker node. On 256G Power machines I use a figure anywhere of about 80 without any real concern. On travis I've found the disk/temp filesystem space allocated on the container/VM may be limiting thing. I tried `watch  du -chs /dev/shm/var_auto_FjOn` during a `--parallel=16` and the largest number I saw was 1.7G. I'd try this (16) to see if it passes but wouldn't spend too much time optimizing this. Existence of test failures https://travis-ci.org/MariaDB/server/branches show it isn't being as actively watched/maintained as their other CI systems.

**Comment by vladbogo** [comment]
Everything looks good. Good job!

**Comment by namrata-ibm** [comment]
Thanks @vladbogo and @grooverdan :)

**Pull request merged**
