### PR TITLE
MDEV-12933: Sort out the compression library chaos

### PR DESCRIPTION
**Pull request by KartikSoneji**
This patch removes the compile-time dependency on compression libraries, and loads them during run time instead.
- The first commit creates a new switch for `mariadbd`/`mysqld` called `--use-compression=`, which allows the user to specify the libraries to be loaded on startup.  
- The next 6 commits add one service each. 
  In order: `LZMA`, `LZO`, `Snappy`, `BZip2`, `ZStd` and `LZ4`.  
- The next few commits contain workarounds that need to be fixed before merging.
  RocksDB has deeper integration with libraries than the other storage engines, so it needs access to more functions.
  The extra functions needed for RocksDB are in separate commits so that they can be removed easily if required.  
- The next commit adds tests.
- Finally, the last commit adds `sql/compression/README.md` that contains instructions to create a new compression service.

### CODE REVIEW

**Comment by ottok** [comment]
Hello @KartikSoneji! Seems you deleted the branch 3 days ago. Was that intentional? You need to reopen this PR if it is still relevant.

**Comment by KartikSoneji** [comment]
Hi @ottok
Sorry about the confusion, I accidently deleted the branch while trying to sync my fork with the main repo.
I have restored the branch and rebased onto `10.6`.

**Comment by KartikSoneji** [comment]
I could not re-open the same PR, so I have created a new one (rebased onto `10.6`): #1748
Thanks for taking a look.

**Comment by janlindstrom** [comment]
Hi, do we really need all these compression libraries? At least on InnoDB point of view many of them are not any good, I must say I made error when I introduced them to main branches, for InnoDB lz4 is the only one really good one.  In 10.6 if would be better to deprecate most of these and then later remove them.

**Pull request closed without merging**
