### PR TITLE
MDEV-25152 "mysqldump --extended-insert" could insert linebreaks between rows

### PR DESCRIPTION
**Pull request by rmfalves**
- [x] *The Jira issue number for this PR is: MDEV-25152*

## Description
Currently, *mysqldump --extended-insert* outputs all rows on a single line, which makes it difficult to use with various Unix command-line utilities such as `grep`. This is a small improvement that makes mysqldump emit a linebreak between each row, so that it becomes easier to work with the dumped file. This change has no significant impact on the performance of dumping and restoring and it does not affect compatibility.

## How can this PR be tested?
The test consists on dumping a database with two tables - students and courses - where each table may have one of four scenarios:

**a)** The table is empty - in that case, data dumping has no INSERT clauses
**b)** The table has one single row - in that case, data dumping has one INSERT clause terminated by semicolon;
**c)** The table has 10 rows - in that case, data dumping has one INSERT clause spanned through several lines where the first line has the INSERT keyword and ends by comma;
**d)** The table has 20000 rows - in that case, data dumping has more than one INSERT clause (likely two), each of them spanned through several lines where the first line has the INSERT keyword and ends by comma;

The test combines the four possible scenarios for each one of the two tables so that it generates 16 different databases. Each one of these databases is exported and every INSERT clause in the resulting output is checked against the expected behavior for its table scenario. The database is then imported again to confirm that the generated output is correct.

Attached is a ZIP file with the following files:
`test_issue_25152.py` - Python script to generate the creation script of a database with x students and y courses, where x and y are given as command line parameters.
`test_issue_25152.sh` - Bash script that uses the above Python script to automatize testing for different scenarios
`test_issue_25152.log` - Output log of the test

**NB:** The test scripts are set for a database with no root password (they were based on a local database with completely fictitious data).

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
Not changed

[mdev-25152.zip](https://github.com/MariaDB/server/files/6697699/mdev-25152.zip)

### CODE REVIEW

**Comment by grooverdan** [comment]
Thanks @rmfalves for writing a very simple fix to the code to achieve this MDEV. I do however have a few requests that I'd like before merging this:

Can I request you use a `fputs` rather than two consecutive `fputc` to acheive the result.

 You'll notice there are test failures here due to the changing output.

Are you able use `mysql-test/mtr --record {testname}` and commit the test case changes?

Can you rebase your original commit onto the latest 10.6 without the merge commits?

Can you identify in the main.mysql test case why the number of rows changes from 41 to 42? It seem unlike that the change here would cause it but its also unlikely to be a flakey test.

Can you put the MDEV-25152 into the subject line of the commit.

After these please rebase to the latest 10.6 and git force push to the same branch and this PR will update.

**Comment by rmfalves** [comment]
Thank you for your feedback, @grooverdan, and my apologies for the late reply.
Now that I got the time to get back to this matter, I started by checking what caused the test failures of rows changing from 41 to 42 in main.mysql. From what I have seen, the problem is related to this kind of instructions:

--let $ldli = load data local infile '$MYSQLTEST_VARDIR/tmp/bug.sql' into table test.t1;

This loads all the lines from the file "bug.sql" into the table "t1". The point is that the "bug.sql" file is generated by a previous mysqldump command issued when the database had one table with two rows (values 1 and 2, for instance). With the new mysqldump output, the dumping of the two rows of "t1" takes two lines, instead of just one single line as before. So, further in the test, the "load data" instruction feeds the table t1 with one extra row, making it 42 rows. However, the "select count(*)" statements are still expected to count the 41 lines from the old output.

Thus it seems to be yet another issue of changed output that must be solved by updating the .result file. Do you agree?

**Comment by grooverdan** [comment]
> Thank you for your feedback, @grooverdan, and my apologies for the late reply.
> Now that I got the time to get back to this matter, I started by checking what caused the test failures of rows changing from 41 to 42 in main.mysql. From what I have seen, the problem is related to this kind of instructions:

Yes, from looking at the bug.sql there is one insert that becomes two lines and the load data is reading line by line.

> --let $ldli = load data local infile '$MYSQLTEST_VARDIR/tmp/bug.sql' into table test.t1;
> 
> This loads all the lines from the file "bug.sql" into the table "t1". The point is that the "bug.sql" file is generated by a previous mysqldump command issued when the database had one table with two rows (values 1 and 2, for instance). With the new mysqldump output, the dumping of the two rows of "t1" takes two lines, instead of just one single line as before. So, further in the test, the "load data" instruction feeds the table t1 with one extra row, making it 42 rows. However, the "select count(*)" statements are still expected to count the 41 lines from the old output.
> 
> Thus it seems to be yet another issue of changed output that must be solved by updating the .result file. Do you agree?

Yes. `mysql-test/mtr --record {testname}` will do that based the test output.

**Comment by rmfalves** [comment]
Hi @grooverdan 
I have already done the changes requested.

> Thanks @rmfalves for writing a very simple fix to the code to achieve this MDEV. I do however have a few requests that I'd like before merging this:
> 
> Can I request you use a `fputs` rather than two consecutive `fputc` to acheive the result.
> 

Done

> You'll notice there are test failures here due to the changing output.
> 
> Are you able use `mysql-test/mtr --record {testname}` and commit the test case changes?
> 

Done

> Can you rebase your original commit onto the latest 10.6 without the merge commits?
> 

Done

> Can you identify in the main.mysql test case why the number of rows changes from 41 to 42? It seem unlike that the change here would cause it but its also unlikely to be a flakey test.
> 

As pointed in an earlier comment, it was also a matter of modified output like in the other tests.

> Can you put the MDEV-25152 into the subject line of the commit.
> 

Since I had already pushed the first commit, I did this on a second commit. I hope it causes no trouble.

> After these please rebase to the latest 10.6 and git force push to the same branch and this PR will update.

Done

I think the pull request is all right now, but if there are any more issues to solve please let me know.

**Pull request closed without merging**
