### PR TITLE
MDEV-16804 SYSTEM VERSIONING columns not showing as GENERATED

### PR DESCRIPTION
**Pull request by midenok**
This code is submitted under the BSD-new license.

### CODE REVIEW

**Comment by vuvova** [comment]
please, add a stored and a virtual generated column to your table in the test.

and add `select * from information_schema.columns where table_name = ...` too.

**Comment by midenok** [comment]
Fixed. There was already a query from `information_schema.columns`.

**Comment by vuvova** [comment]
looks ok, but I think `ROW START GENERATED` is somewhat strange. The syntax is
```
   col TIMESTAMP(6) GENERATED ALWAYS AS ROW START
```
compare with
```
  col TIMESTAMP(6) GENERATED ALWAYS AS CURRENT_TIMESTAMP + 1 MONTH
```
the second column is not reported as "CURRENT_TIMESTAMP + 1 MONTH GENERATED", is it?

That is, the generating expression is never printed in "Extra" column, and "ROW START" should not be either. I suggest to print "STORED GENERATED" like other stored generated columns.

**Comment by vuvova** [comment]
oh, and I've had to move the test case, because versioning.create is now run for MEMORY engine too, and it doesn't support generated columns.

**Pull request closed without merging**
