### PR TITLE
Deb: Track libmariadb3 ABI explicitly to detect future symbol changes

### PR DESCRIPTION
**Pull request by ottok**
When this file exists, Debian builds will automatically compare the built
ABI and symbols to the ones defined in the list. If there is a mismatch,
developers need to update the libmariadb3.symbols file, otherwise the build
fails.

This ensures there are no accidental symbol changes. This also helps track
what symbols changed and in what versions.

Also add a README embedded in the sources to facilitate correct use of this
new file.

Related: MDEV-21732

### CODE REVIEW

**Comment by ottok** [comment]
Travis-CI failed with `Failing test(s): main.select_pkeycache main.select main.select_jcl6 main.type_float main.func_group main.func_str main.type_timestamp_hires main.type_time_hires` – those cannot possibly have anything to do with the changes in this PR.

**Comment by ottok** [comment]
In Travis-CI there are error messages about non-existent directory `/usr/local/Cellar` that was added to cache directories in eecce3d7c8a6374342ed7d0cd8844420d8957682 – should not be related to this PR.

**Comment by ottok** [comment]
Transient Travis-CI errors are now gone after restarting builds. The permanent failure is on all recent 10.2 builds:
image

**Comment by ottok** [comment]
Thanks @cvicentiu for looking at this, but I really think that those who develop the client library should be the ones reviewing this and committing to track the ABI compatibility with this. Technically there isn't much to review, this is mostly a policy/workflow question.

The two commits to fix Travis-CI are already on 10.3+ branches, I added theme here only to get Travis-CI pass.

**Comment by ottok** [comment]
CI: Test failures in buildbot.mariadb.org are unrelated to this PR.

buildbot/aarch64-centos-7
```
/buildbot/aarch64-centos-7/build/storage/innobase/row/row0log.cc: In function 'dberr_t _ZL17row_log_apply_opsPK5trx_tP12dict_index_tP15row_merge_dup_tP16ut_stage_alter_t.isra.86(const trx_t*, dict_index_t*, row_merge_dup_t*)':
/buildbot/aarch64-centos-7/build/storage/innobase/row/row0log.cc:3733:1: error: could not split insn
 }
 ^
```

buildbot/aarch64-rhel-7
```
[ 78%] Building CXX object storage/rocksdb/CMakeFiles/rocksdblib.dir/rocksdb/utilities/persistent_cache/persistent_cache_tier.cc.o
/buildbot/aarch64-rhel-7/build/storage/rocksdb/rocksdb/utilities/blob_db/blob_db_impl.cc: In member function 'virtual rocksdb::Status rocksdb::blob_db::BlobDBImpl::CompactFiles(const rocksdb::CompactionOptions&, const std::vector<std::basic_string<char> >&, int, int, std::vector<std::basic_string<char> >*, rocksdb::CompactionJobInfo*)':
/buildbot/aarch64-rhel-7/build/storage/rocksdb/rocksdb/utilities/blob_db/blob_db_impl.cc:1120:26: warning: missing initializer for member 'rocksdb::CompactionJobInfo::cf_id' [-Wmissing-field-initializers]
   CompactionJobInfo info{};
                          ^
```

**Comment by ottok** [comment]
Do you want me to rebase this on a newer branch, say 10.6? So we star tracking ABI breakage automatically from 10.6 onwards?

**Comment by ottok** [comment]
This is now 16 months old without any comments from @9E0R9 or is it @9EOR9 ... Maybe put this in 10.6 then?

**Comment by robertbindar** [comment]
Hi @ottok, I looked over the PR and read your observations here and the conversations from the Jira MDEV, from my perspective, it's fine. I pinged Georg and hopefully he can quickly take a look and give his ok from workflow/policy perspective.

**Comment by illuusio** [comment]
@robertbindar and @ottok this has slip through my eyes as Debian stuff but this is LGTM stage but should be tested that those symbols are correct and as they seem to be this is very good thing to get in as soon as possible. I test building this and comment..

**Review by robertbindar — APPROVED** [review]

**Pull request merged**
