### PR TITLE
Fixed some typos in mysql.cc

### PR DESCRIPTION
**Pull request by hashirsarwar**

### CODE REVIEW

**Comment by an3l** [comment]
Hi @hashirsarwar 
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by hashirsarwar** [comment]
@an3l I have filled out the contribution agreement and sent it.

**Comment by an3l** [comment]
Hi @hashirsarwar 
can you please send it again to foundation@mariadb.org ?
Easiest way is just to indicate in a new comment.

**Comment by hashirsarwar** [comment]
@an3l can I just type the information and send it to above email? Or I need to scan a document?

**Comment by hashirsarwar** [comment]
Hi @an3l 
Can I submit my code under BSD license?

**Comment by an3l** [comment]
The easiest way is that you write here in comment about submitting your patch under BSD-new license. 
Yes sure, you can.
For MCA, please follow the link https://mariadb.com/kb/en/library/mca/ , scan and send to mail above.
Thanks.

**Comment by hashirsarwar** [comment]
@an3l Okay I submit my code under BSD-new license.

**Comment by an3l** [comment]
Hi @hashirsarwar ,
pushed on `5.5` with d8ace23d26003.
Thanks

**Pull request closed without merging**
