### PR TITLE
Update 10.4 man pages

### PR DESCRIPTION
**Pull request by iangilfillan**

### CODE REVIEW

**Comment by svoj** [comment]
@iangilfillan why some man pages didn't get version update? I think there're 4.

**Comment by iangilfillan** [comment]
The 4 aria* man pages are formatted differently, and don't contain the same version information in the header, so there's nothing to change there.

**Comment by svoj** [comment]
I meant mariabackup, mbstream, mysql_ldb, wsrep_sst_rsync_swan.

**Comment by iangilfillan** [comment]
Thanks, fixed - I'll look at fixing them on earlier releases too.

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
