### PR TITLE
[MDEV-22683] Ensure system tables are correctly upgraded in MariaDB 10.4

### PR DESCRIPTION
**Pull request by lornacluo**
- [x] *The Jira issue number for this PR is: MDEV-22683*

## Description
[MDEV-22683](https://jira.mariadb.org/browse/MDEV-22683) describes that some changes to 'mysql' schema are missing from the mysql_upgrade script of some versions, which results in the difference between the schema installed by running mysql_install_db of a new build and the schema created on an early version and upgraded to the current version. 

This PR is to fix:
- On 5.5 version, the `general_log` table was created as `CREATE TABLE IF NOT EXISTS general_log (..., thread_id INTEGER NOT NULL, ...)`, and starting from 10.0+, the table is created as `CREATE TABLE IF NOT EXISTS general_log (..., thread_id BIGINT(21) UNSIGNED NOT NULL, ...)`, but mysql_upgrade is not properly upgrading the table. It modifies the `thread_id` twice in one query, which could leave the table not modified and lead to other potential error. To fix the problem, the redundant modification is removed.

- On versions 10.0 and 10.1, the `servers` table was created as `CREATE TABLE IF NOT EXISTS servers (..., Host char(64) NOT NULL DEFAULT '', ..., Owner char(64) NOT NULL DEFAULT '', ...)`, and starting from 10.2, the table is created as `CREATE TABLE IF NOT EXISTS servers (..., Host varchar(2048) NOT NULL DEFAULT '', ..., Owner varchar(512) NOT NULL DEFAULT '', ...)`. To align with the table installed on a new build, modifications are added to the table to account for possible upgrade from 10.0 and 10.1.

## How can this PR be tested?
The issue described in [MDEV-22683](https://jira.mariadb.org/browse/MDEV-22683) can be reproduced by upgrading a 5.5 build to 10.4. After the upgrade, invoke `mysql_upgrade` to upgrade the `MySQL` database, and run `mysql_install_db` to install a fresh version of `MySQL` database in a different data directory. The databases can then be compared with queries `SHOW CREATE TABLE general_log` and `SHOW CREATE TABLE servers`, and the command `diff -u <upgraded_table> <newly_created_table>` to reproduce the differences.

The updated script was tested by running it on the upgraded database and again comparing the upgraded tables with the newly created ones, after which the differences didn't repeat.

## Basing the PR against the correct MariaDB version
- [x] This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced and bug fixes are still being accepted.

## Copyright
All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

### CODE REVIEW

**Comment by grooverdan** [comment]
Nice!

Ignoring the `main.func_math` test failures above, it seems the other upgrade tests affected by this need their result re-recording. From your build directory `mysql-test/mtr --record {testname}`. After that `git add ` (the `.result` file, `git commit --amend` and then `git push --force` to update this PR).

Additionally for could you please add a 5.5 (or 5.7 test if equalivant) like mysql-test/main/system_mysql_db_fix50117.test that includes the mysql schema from that version.

**Comment by grooverdan** [comment]
With regard to latin1 on the mysql.user view - a [SET STATEMENT ... FOR CREATE ... VIEW](https://mariadb.com/kb/en/set-statement/) in scripts/mysql_system_tables.sql might be sufficient to resolve that part of the ticket.

Are you also willing to do a 10.5 fix for help_relation described in the ticket?

**Comment by lornacluo** [comment]
> Are you also willing to do a 10.5 fix for help_relation described in the ticket?

Hi! Of course I was willing to fix that too but I think it's been resolved, possibly by a merge between 10.4 and 10.5.

**Comment by lornacluo** [comment]
> With regard to latin1 on the mysql.user view - a [SET STATEMENT ... FOR CREATE ... VIEW](https://mariadb.com/kb/en/set-statement/) in scripts/mysql_system_tables.sql might be sufficient to resolve that part of the ticket.

Since the ticket describes it as a difference but not a miss, I'm not sure if the difference is intentional and if we should fix it - it could result in many tests that need re-recording.

**Comment by lornacluo** [comment]
> Nice!
Thanks!

> Ignoring the `main.func_math` test failures above, it seems the other upgrade tests affected by this need their result re-recording. From your build directory `mysql-test/mtr --record {testname}`. After that `git add ` (the `.result` file, `git commit --amend` and then `git push --force` to update this PR).
> 'system_mysql_db_fix50117.result' and 'system_mysql_db_fix50030.result' have been re-recorded.

> Additionally for could you please add a 5.5 (or 5.7 test if equalivant) like mysql-test/main/system_mysql_db_fix50117.test that includes the mysql schema from that version.
A test for 5.5.68 ('system_mysql_db_fix50568.test' and 'system_mysql_db_fix50568.result' have been added.

**Comment by grooverdan** [comment]
> > With regard to latin1 on the mysql.user view - a [SET STATEMENT ... FOR CREATE ... VIEW](https://mariadb.com/kb/en/set-statement/) in scripts/mysql_system_tables.sql might be sufficient to resolve that part of the ticket.
> 
> Since the ticket describes it as a difference but not a miss, I'm not sure if the difference is intentional and if we should fix it - it could result in many tests that need re-recording.

Ack. Happy to leave it.

Don't worry about 10.5 conflicts, they should be easy to resolve.

**Comment by lornacluo** [comment]
> Don't worry about 10.5 conflicts, they should be easy to resolve.
I double checked and can confirm that 10.4 and 10.5 now have identical 'mysql_system_tables.sql', am I missing anything? If there is a conflict I'd be happy to fix it too:)

**Comment by grooverdan** [comment]
`help_relation` needs an addition key `help_topic_id` (if not exists) in 10.5 making a different result.

Ah, found my stalled #2437 that has all the necessary bits, and will just need to re-record your test case when merged up. I'll take care of it.

**Pull request merged**
