### PR TITLE
MDEV-11613 - Travis: Revert to optional MYSQL_BUILD_{CC,CXX}

### PR DESCRIPTION
**Pull request by grooverdan**
As noted by @ottok in MDEV-10752 e14bdcb81c88156ce5e413865f7fe124321120eb no longer influences the compiler used during the build due to other changes in the build system. An environment variable CC/CXX didn't propagate to the build so a variant of the previous MYSQL_BUILD_CC/MYSQL_BUILD_CXX was introduced to use the non Debian default compilers.

I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
Note: next updated of libmariadb submodule will require reworking the debian build due to https://github.com/MariaDB/mariadb-connector-c/commit/e34a595ce2bff180518df42023dad0b6188b6233 After this this commit "Libraries will be installed in lib/x86_64-linux-gnu" rather than "Libraries will be installed in /usr/lib/mariadb" which has implications for the libmariadb.so.3 install location (debian/rules).

**Comment by svoj** [comment]
I'd merge this if there were no debian changes. I'll assign this to @ottok for review.

**Comment by grooverdan** [comment]
Ack. The 4 options to cmake are only added if the 3 environment variables are set and these where chosen in name to be unlikely to conflict.

**Comment by grooverdan** [comment]
Alternate implementation done. CMAKE_{LANG}_LAUNCHER didn't appear to cmake-3.4 and I couldn't do a backport easily.

The debian/rules falls back to the makefile defined CC/CXX if MYSQL_BUILD_(CC,CXX} isn't defined. As per the Travis results there is cache defined.

**Comment by ottok** [comment]
The commit that downloads ccache from zeisty does not have any explanation why it does so. Commit messages should always have an explanation. If ccache is not working, it could be a bug in Travis, have you checked if any from https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ccache apply on our situation?

**Comment by grooverdan** [comment]
Regarding ccache - updated commit message. I'm yet to decide if I should request travis updates this - its probably more maintenance cost than benefit to them. If I change to container based travis (packages are whitelisted - just need #284) I'll need to drop this ccache version anyway (as I can't sudo in a container build).

@ottok, do you have any objection to d9f9463366b91a324e846e1845c02f2d2accad1e in the way that it provides two environment variables that can override the CC, CXX specified in the Makefile?

**Comment by grooverdan** [comment]
The proof of correction can seen in the travis output about line 875, at the beginning of the cmake invocation, where the following appears and the version number changes corresponding to the GCC_VERSION in the build.

<pre>
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/lib/ccache/gcc-4.8
-- Check for working C compiler: /usr/lib/ccache/gcc-4.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/g++-4.8
-- Check for working CXX compiler: /usr/lib/ccache/g++-4.8 -- works
</pre>

**Comment by ottok** [comment]
Having the GCC version as a variable looks good.

I am not sure about the usefulness of updating the ccache version compared to the complexity (sudo etc) it adds. Also in my tests ccache does not actually work, the Travis-CI build times are not faster. In my own systems where I've been using ccache for years, MariaDB builds 2x-10x faster with ccache. I suspect something with ccache is in general broken with Travis-CI..

**Comment by grooverdan** [comment]
Agree about complexity of updating ccache - dropping it.

Other improvements in travis world that make a sudo: false almost possible, except for:
* Almost all dependencies are now whitelisted (https://github.com/grooverdan/mariadb-server/commit/bf0e4ed50ec5ef5d85e0ce1021eeb1be21aef404), but not whitlelisted libsystemd-daemon-dev (not essential)
* because of differences in shm mounts in travis environment set on config #289 (with MTR_MEM set like /tmp), https://github.com/travis-ci/travis-ci/issues/7062 fixed, or adding --mem=/tmp (https://github.com/MariaDB/server/blob/10.2/debian/rules#L110)
* main.mysqlhotcopy_myisam failing in container builds however its working on non-container builds (https://travis-ci.org/grooverdan/mariadb-server/jobs/193566267 - see rawlogs) - needs fixing (or ignoring).

Also clang whitelisted so https://travis-ci.org/grooverdan/mariadb-server/builds/193566265 type builds are possible.

**Comment by svoj** [comment]
Thanks!

**Comment by grooverdan** [comment]
thanks @svoj

**Pull request merged**
