### PR TITLE
MDEV-13336: mysqldump --ignore-database

### PR DESCRIPTION
**Pull request by grooverdan**
Addressed review comments of #432. Added test case.

I submit new additions and fixes under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for your contribution! This task was added to our 10.3 queue.

**Comment by svoj** [comment]
Pushed 784e9391c98b799550bd901ce9db1d0e6f276a0b and c9839cb0b34014bb463aa790548a39a1975d9c16.

**Comment by grooverdan** [comment]
in hindsight the test case was rather detrimental.

**Comment by svoj** [comment]
Anything specific? I'd do less intrusive test indeed, but this one worked pretty well and I decided to take it.

**Pull request closed without merging**
