### PR TITLE
MDEV-24292  support semi-independent versioning for sub-packages

### PR DESCRIPTION
**Pull request by vuvova**
Sometimes it is convenient to allow certain sub-packages to be versioned semi-independently from the server.

Currently, for example, a package with the plugin "foobar" in the server release A.B.C will always have a version A.B.C, like MariaDB-foobar-engine-A.B.C-1.distro.arch.rpm or mariadb-plugin-foobar_A.B.C+maria~distro_arch.deb.

This tightly binds sub-package release schedule to server release schedule. If, for example, one wants to fix a really critical bug in the plugin foobar or the plugin is just being developed on a more agile schedule than the server — either way, it impossible to release the new version of plugin without releasing everything, the server, clients libraries, all other plugins.

But if the package version of the plugin version K.L.M would be A.B.C-K.L.M (e.g. MariaDB-foobar-engine-A.B.C_K.L.M-1.distro.arch.rpm) that would make it possible to release plugins independently, between server releases. Both a new intermediate plugin release and a full server release (that includes the plugin) would be considered an upgrade from the package manager point of view, which is exactly what's needed.

### CODE REVIEW

**Comment by vuvova** [comment]
@ottok, you can only review the commit "3. Embed plugin version into the DEB package version"

**Comment by vuvova** [comment]
by the way, please **do not merge it**, only review. columnstore changes might be not final yet (columnstore commit related to this MDEV is all right, but updating a submodule brings other commits too, and they might be not final)

**Comment by ottok** [comment]
I will need to take more time to review this better at a later time, but I skimmed through this quickly now.

This PR adds a lot of complexity into the packaging in an attempt to serve a use case that is fundamentally flawed.

> This tightly binds sub-package release schedule to server release schedule. If, for example, one wants to fix a really
> critical bug in the plugin foobar or the plugin is just being developed on a more agile schedule than the server — either way,
> it impossible to release the new version of plugin without releasing everything, the server, clients libraries, all other plugins.

This is how it is supposed to work and this reflects exactly the release policy of MariaDB Server itself. Yes, if there is a security bug that needs a one line code change to fix it, the whole server needs a new release and there will be a lot of builds and upgrades following it, but it is correct from a release engineering point of view since the MariaDB Server has only one version number thus when that is bumped there is a whole new release.

> make it possible to release plugins independently

The goal is to de-couple the release of ColumnStore from the Server. However ColumnStore needs the server sources to even build. Yes, it has it's own versioning scheme already (and release notes, e.g. https://mariadb.com/docs/release-notes/mariadb-columnstore-1-5-2-release-notes/). The release notes do not link to an actual ColumnStore release (=something to download) but I was able to find downloadable .tar.gz packages at https://github.com/mariadb-corporation/mariadb-columnstore-engine/tags. The version scheme here however differs from the release notes. The latest one is "columnstore-5.4.3-1".

Here ColumnStore flipped the version numbers: https://github.com/mariadb-corporation/mariadb-columnstore-engine/commit/8c67a06fe37029963352af1ee6f09208a27acdc3

But there is no commit message explaining why. There is also no explanation what the extra revision numbers (-1 and -2) in ColumnStore are supposed to mean.

Firstly, ColumnStore should get their release engineering sorted out first, it is a mess so far.

Secondly, the goal "possible to release plugins independently" is a wrong goal within the scope of this repository. This repository (MariaDB Server) should at any time build and provide the packages it contains. Trying to twist it into something that builds all the packages but only ships a subset of them or ships new builds with the same old version numbers partially and only has a few new packages with updated version numbers is an anti-pattern that will just cause much more problems later on.

The code in this PR can only be useful if applied to the repository https://github.com/mariadb-corporation/mariadb-columnstore-engine/ so that repository can build and ship one package, and have it's own version numbers (e.g. 10.5.8-5.4.3) to reach the goal of "making it possible to release plugins independently".

I will review the code from that point of view at a later when I have more time.

**Review by ottok — CHANGES_REQUESTED** [review]
This version should not be merged. Will review this more at a later time.

**Comment by vuvova** [comment]
> This PR adds a lot of complexity into the packaging

Could you elaborate on this, please?

---

As for the rationale, it's not really about columnstore. MariaDB server includes many components that are packaged independently and are developed independently. There is no logical reason why they should have the same version number. Historically they did, which caused following problems:
* if a component had to be changed and re-released, the whole server and all components had to be re-released. All users were forced to upgrade, even though the upgrade only changed the version number, nothing else. This is a huge overhead if you take into account the number of users. Especially if the problem was in a comparatively rarely used component, like, for example, columnstore.
* It was never clear what component version (as every such component has a separate version number internally) is included in what server version. Ian routinely maintains version tables in the KB (see e.g. https://mariadb.com/kb/en/connect/) but few users read the manual.

Think of components as of independent projects — there is no need to release a new Debian version, for example, when a new version of openssh is released.

**Comment by ottok** [comment]
> There is no logical reason why they should have the same version number.

Yes there is. You are releasing just one tar.gz package when there are new
MariaDB Server releases. Whatever sources are inside that package will
share the version. This is how all 50000+ existing open source projects /
releases work.

You are now treating binary releases as if they are independent of the
source release. If you split the project into components and start
releasing multiple tar.gz packages each with it's own component version
schemes, then the packaging part would be easy. But you are now trying to
introduce a policy that disregards the "real" project versioning and
releases and forcefully introduces an overly complex binary-only subrelease
thing.

**Comment by vuvova** [comment]
You're right. Source packages, good point, I didn't think of that.

Practically we've never yet had a reason to re-release only one component package. So I don't think it will be happening often, perhaps never. But if it will ever happen — I could append the date to the end of the source package of such an "intermediate" release, this way it'll be a distinct intermediate source package for an intermediate release.

But for me the main reason to have this {main}-{component} version scheme is documentation. To be able to see immediately what plugin version and what C/C version comes with what server release.

**Comment by vuvova** [comment]
@ottok, could you, please, confirm that it won't break Debian builds (or specify what I need to change, if it does)? ColumnStore, basically, doesn't compile anymore, so they cannot continue development until it is pushed.

**Comment by ottok** [comment]
Please hold on a bit.

**Comment by ottok** [comment]
I have not forgotten about this. Currently looking into ColumnStore repo and running it's CI via PR at https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/1700 trying to come up with a setup that could work better without "polluting" the whole MariaDB Server build with hard to maintain quirks.

**Comment by vuvova** [comment]
I don't understand why you're even looking at columnstore, much less at its CI. Debian-relevant commits are
```
commit 3aa999480bf
Author: Sergei Golubchik <serg@mariadb.com>
Date:   Fri Nov 27 14:36:10 2020 +0100

    MDEV-24292 support semi-independent versioning for sub-packages
    
    3. Embed plugin version into the DEB package version
    
    this assumes that -DDEB is only used from within autobake-deb.sh

commit 5fb725b8ce2
Author: Sergei Golubchik <serg@mariadb.com>
Date:   Fri Nov 27 15:05:17 2020 +0100

    deb: use ${server:Version} for the version of the server package
    
    and not ${binary:Version}, which is the version of the current
    package, whatever it is.
```
(commit hashes might change if I rebase again, so I quoted complete commit messages). And I would greatly prefer if they wouldn't break native builds.

So, do they break native builds? What do I need to change to fix that?

**Comment by ottok** [comment]
> You're right. Source packages, good point, I didn't think of that.
> 
> Practically we've never yet had a reason to re-release only one component package. So I don't think it will be happening often, perhaps never. But if it will ever happen — I could append the date to the end of the source package of such an "intermediate" release, this way it'll be a distinct intermediate source package for an intermediate release.

If you want to release a new version of just one package, say mariadb-plugin-columnstore, then there should be a build that produces only that. I did a demo in https://github.com/ottok/mariadb/tree/10.6-columnstore-only

When built, it produces:
```
mariadb-columnstore_10.6.0+maria~sid_amd64.buildinfo
mariadb-columnstore_10.6.0+maria~sid_amd64.changes
mariadb-plugin-columnstore_10.6.0+maria~sid_amd64.deb
```

And nothing else. These can then be sent to a repository for binary distribution.

ColumnStore already has its own `debian/` directory. It could be expanded to have whatever contents it needs, and it could freely define the source and binary package names, the version number (via debian/changelog and debian/control contents) etc. It also allows a quick re-build of only the needed files (helps development and CI) and it automatically verifies that the chain on build dependencies etc is correct.

This demo is not complete. It does **not** yet read the columnstore VERSION file and apply these version numbers on the package:
```
COLUMNSTORE_VERSION_MAJOR=6
COLUMNSTORE_VERSION_MINOR=1
COLUMNSTORE_VERSION_PATCH=1
COLUMNSTORE_VERSION_RELEASE=1
```

There are probably also other things that need to be customized during the CS development cycles. Whatever they end up being can then later be imported "downstream" in MariaDB Server sources manually just like the relation to Mroonga, RocksDB etc is.

**Comment by vuvova** [comment]
@ottok, please forget ColumnStore, it's not touched by those two commits that I listed above and it's not included in native builds. The question is, how those two commits (that don't include ColumnStore) affect native builds (that does not include ColumnStore).

**Comment by ottok** [comment]
This change is made to accommodate ColumnStore, we can't just "forget" it. I am trying to persuade you out of it by showing that there are better ways to serve the needs of ColumnStore than by polluting the MariaDB Server packaging with this over-engineered versioning (that is probably not going to work fully anyway).

Tested building this. While the complete build failed due to missing files in the ColumnStore build, I did observe the version numbers generated in the test:
```
$ cat debian/substvars
server:Version=1:10.5.9+maria~sid

$ cat debian/mariadb-plugin-columnstore.changelog
mariadb-10.5 (1:10.5.9-5.5.1+maria~sid) sid; urgency=medium

  * Automatic build with MariaDB build.

 -- Vicentiu Ciorbaru <vicentiu@mariadb.org>  Sun, 27 Dec 2020 18:12:30 +0000
```

Both in Debian and Fedora world the dashes are reserved for packaging/distro revisions and not intended to use for package versions.Also note that you missed out the ColumnStore VERSION file last component `COLUMNSTORE_VERSION_RELEASE=1`.

**Comment by ottok** [comment]
The native build of this does not work, since it relies on `debian/substvars` file to exist, which is only created by autobake-deb.sh, and thus isn't there in native builds. A native build will fail on error message `dpkg-gencontrol: warning: Depends field of package mariadb-server-10.5: substitution variable ${server:Version} used, but is not defined`.

**Comment by ottok** [comment]
> ColumnStore, basically, doesn't compile anymore, so they cannot continue development until it is pushed.

In my testing and looking at the Drone CI of ColumnStore it does compile and is not broken at the moment.

> Think of components as of independent projects — there is no need to release a new Debian version, for example, when a new version of openssh is released.

That is why the OpenSSH has it's own source package, own versioning scheme and produces its own binary packages. If everything is stuffed into one single source package (as MariaDB Server now is) then there is no (sensible) way around this.

If the components are independent, they should each have their own `debian/` directory in their own repo and depend on libmariadb-dev (and perhaps libmariadbd-dev) and build independently and produce their own xyz.deb.

**Comment by ottok** [comment]
Related:
- https://jira.mariadb.org/browse/MCOL-4471
- https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/1701

**Comment by vuvova** [comment]
`debian/substvars` — right, that's understandable. I've fixed that now, please take another look.

Compiling ColumnStore without the server — don't bother, it's was a hack to save some compiling time in CI that shouldn't have been done in the first place. It'll never work reliably, plugins must be built from within the server tree by the server build system. But it is nothing you need to waste your time on as native builds do not include ColumnStore.

How do you run native builds, by the way? I can test them myself, if I'd knew how.

**Comment by ottok** [comment]
> It'll never work reliably, plugins must be built from within the server tree by the server build system.

I understand that ColumnStore needs the server tree (source code) and at least libmariadb.so, maybe some other parts of the server as well, but surely not everything? The current ColumnStore build includes building the mariadb-plugin-s3 and many other plugins, surely they are excessive? It annoys me that there is a lot of guesswork here as the ColumnStore build dependencies or build products are not documented properly (or at least I did not find).

**Comment by ottok** [comment]
Native builds (unmodified source + entrypoint dpkg-buildpackage) works now:
```
$ ls -w 1 buildout/*.deb
buildout/libmariadb3_10.5.0_amd64.deb
buildout/libmariadb3-compat_10.5.0_amd64.deb
buildout/libmariadbclient18_10.5.0_amd64.deb
buildout/libmariadbd19_10.5.0_amd64.deb
buildout/libmariadbd-dev_10.5.0_amd64.deb
buildout/libmariadb-dev_10.5.0_amd64.deb
buildout/libmariadb-dev-compat_10.5.0_amd64.deb
buildout/libmysqlclient18_10.5.0_amd64.deb
buildout/mariadb-backup_10.5.0_amd64.deb
buildout/mariadb-client_10.5.0_all.deb
buildout/mariadb-client-10.5_10.5.0_amd64.deb
buildout/mariadb-client-core-10.5_10.5.0_amd64.deb
buildout/mariadb-common_10.5.0_all.deb
buildout/mariadb-plugin-connect_10.5.0_amd64.deb
buildout/mariadb-plugin-cracklib-password-check_10.5.0_amd64.deb
buildout/mariadb-plugin-gssapi-client_10.5.0_amd64.deb
buildout/mariadb-plugin-gssapi-server_10.5.0_amd64.deb
buildout/mariadb-plugin-mroonga_10.5.0_amd64.deb
buildout/mariadb-plugin-oqgraph_10.5.0_amd64.deb
buildout/mariadb-plugin-rocksdb_10.5.0_amd64.deb
buildout/mariadb-plugin-s3_10.5.0_amd64.deb
buildout/mariadb-plugin-spider_10.5.0_amd64.deb
buildout/mariadb-server_10.5.0_all.deb
buildout/mariadb-server-10.5_10.5.0_amd64.deb
buildout/mariadb-server-core-10.5_10.5.0_amd64.deb
buildout/mariadb-test_10.5.0_amd64.deb
buildout/mariadb-test-data_10.5.0_all.deb
buildout/mysql-common_10.5.0_all.deb
```

**Comment by vuvova** [comment]
Is that right? It looks suspicious that the version is 10.5.0, not 10.5.9

**Comment by ottok** [comment]
> Is that right? It looks suspicious that the version is 10.5.0, not 10.5.9

Yes it is right. The version is inherited from `debian/changelog` which in pristine sources show this version. It does not matter. Main thing that it builds.

About case Connect (https://mariadb.com/kb/en/connect/) - what is the actual dependency of it on the MariaDB Server itself? Is it dynamially linked, would it suffice for it to have a libmariadbd.so available? Does Connect use different symbols for each MariaDB Server? Could a mariadb-plugin-connect connect.so built for MariaDB Server 10.5.8 be installed and run on MariaDB Server 10.6.0? I am trying to understand what the dependency actually is (both build-time and run-time).

**Comment by ottok** [comment]
Result from autobake-deb.sh:
```
$ ls -w 1 buildout/*.deb
buildout/libmariadb3_10.5.9+maria~sid_amd64.deb
buildout/libmariadb3-compat_10.5.9+maria~sid_amd64.deb
buildout/libmariadbclient18_10.5.9+maria~sid_amd64.deb
buildout/libmariadbd19_10.5.9+maria~sid_amd64.deb
buildout/libmariadbd-dev_10.5.9+maria~sid_amd64.deb
buildout/libmariadb-dev_10.5.9+maria~sid_amd64.deb
buildout/libmariadb-dev-compat_10.5.9+maria~sid_amd64.deb
buildout/libmysqlclient18_10.5.9+maria~sid_amd64.deb
buildout/mariadb-backup_10.5.9+maria~sid_amd64.deb
buildout/mariadb-client-10.5_10.5.9+maria~sid_amd64.deb
buildout/mariadb-client_10.5.9+maria~sid_all.deb
buildout/mariadb-client-core-10.5_10.5.9+maria~sid_amd64.deb
buildout/mariadb-common_10.5.9+maria~sid_all.deb
buildout/mariadb-plugin-columnstore_10.5.9-5.5.1+maria~sid_amd64.deb
buildout/mariadb-plugin-connect_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-cracklib-password-check_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-gssapi-client_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-gssapi-server_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-mroonga_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-oqgraph_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-rocksdb_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-s3_10.5.9+maria~sid_amd64.deb
buildout/mariadb-plugin-spider_10.5.9+maria~sid_amd64.deb
buildout/mariadb-server-10.5_10.5.9+maria~sid_amd64.deb
buildout/mariadb-server_10.5.9+maria~sid_all.deb
buildout/mariadb-server-core-10.5_10.5.9+maria~sid_amd64.deb
buildout/mariadb-test_10.5.9+maria~sid_amd64.deb
buildout/mariadb-test-data_10.5.9+maria~sid_all.deb
buildout/mysql-common_10.5.9+maria~sid_all.deb
```

**Comment by vuvova** [comment]
No, a storage engine plugin will only work with the server of the **exactly** the same version it was built for. This limitation is specific for storage engines though. For RPM packages, storage engine plugins have `Requires: MariaDB-server = %{version}-%{release}` and all other plugins have `Requires: MariaDB-server`.

I've pushed (to this PR) a new commit that fix DEB dependencies similarly

**Comment by ottok** [comment]
How do I run the build so that `SET(ver " = ${ver}-%{release}")` is triggered and the end result would use this new scheme and differ from the binary packages we have today?

**Comment by vuvova** [comment]
This `SET` is for RPM builds, DEB builds use a `debian/control` file and it cannot be be modified from cmake. For the new scheme see 8fabfdc

**Pull request merged**
