### PR TITLE
MDEV-26319: Ensure MariaDB Connector C uses correct layout with CMake 2.x

### PR DESCRIPTION
**Pull request by ottok**
In CMake 2.x doing a STREQUAL comparison needs two strict strings. Without
this change CONC_INSTALL_LAYOUT always ended up with the value "DEFAULT".

This fixes weird RPM layout issues on CentOS 7 (builds with CMake 2.8).

The PR targets branch 10.5 as that is the oldest branch that checks in libmariadb builds
for both RPM and DEB in INSTALL_LAYOUT.

### CODE REVIEW

**Comment by vuvova** [comment]
this looks wrong. cmake manual explicitly says
> ``if(<variable|string> STREQUAL <variable|string>)``
> True if the given string or variable's value is lexicographically equal
> to the string or variable on the right.

so `IF(INSTALL_LAYOUT STREQUAL "RPM")` is perfectly valid and should work.

**Comment by ottok** [comment]
In my research https://jira.mariadb.org/browse/MDEV-26319 I found out that this format is needed for it to work with CMake 2.8. Either `IF("${INSTALL_LAYOUT}" STREQUAL "RPM")` or `IF(${INSTALL_LAYOUT} STREQUAL "RPM")`. Current `IF(INSTALL_LAYOUT STREQUAL "RPM")` did not evaluate true in CMake 2.8.

You are right that this is against CMake docs though. One option is to just decide that we don't care about CentOS 7 (it is supported only 2 years more to 2024) and leave MDEV-26319 unfixed, not a big deal.

**Comment by vuvova** [comment]
This is very strange. Because interpreting a bare word as a variable is the **old** CMake behavior. The new recommended one is to use values, like you did. For example in the old CMake you could even do
```cmake
SET(var1 foo)
SET(var2 var1)
IF(${var2} STREQUAL foo)
```
and it'd be true, because cmake would replace `${var2}` with "var1" and then use it as a bareword, so meaning a variable name. This no longer works since CMake 3.1.

That is, I find it rather questionable that the old historical CMake behavior would work in a recent cmake 3.14.0 but would not work in the old cmake 2.8

**Comment by ottok** [comment]
This is my experience in testing it. This patch is the only way to get it to work. However, maybe an adaptation for an old CMake version is not that relevant and if nobody else cares about this issue, I am fine that we just let it be an close the issue.

**Comment by ottok** [comment]
This was referenced from a94144be4c8e4669b60374f0c3564318ce4db82e but that never got on mainline 10.2..

**Comment by ottok** [comment]
Since CMake 2.x use is getting very rare I will just close https://github.com/MariaDB/server/pull/1897, in particular since nobody else reported running into this issue in https://jira.mariadb.org/browse/MDEV-26319.

**Pull request closed without merging**
