### PR TITLE
typo fixed. HAVE_mi_uint8korr

### PR DESCRIPTION
**Pull request by howz97**
- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
TODO: fill description here

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by grooverdan** [comment]
Well spotted. Been there since 076aa182c2d2 (10.2).

Can you rebase this to 10.4 by:
```
git fetch git@github.com:MariaDB/server.git 10.4
git rebase --onto FETCH_HEAD HEAD^
git push -f
```
Then edit the title of this PR where it has 11.3 as the version and change that to 10.4

Can you either sign the CLA using the link above or write a statement here like "I contribute this change under the BSD-new license". Thank you.

**Comment by howz97** [comment]
> Well spotted. Been there since [076aa18](https://github.com/MariaDB/server/commit/076aa182c2d2ee67c233d0e79c900dfba6f593c1) (10.2).
> 
> Can you rebase this to 10.4 by:
> 
> ```
> git fetch git@github.com:MariaDB/server.git 10.4
> git rebase --onto FETCH_HEAD HEAD^
> git push -f
> ```
> 
> Then edit the title of this PR where it has 11.3 as the version and change that to 10.4
> 
> Can you either sign the CLA using the link above or write a statement here like "I contribute this change under the BSD-new license". Thank you.


Am I done now?

**Comment by grooverdan** [comment]
Yes, Thank you very much for the fix.

**Review by grooverdan — APPROVED** [review]

**Review by LinuxJedi — APPROVED** [review]
Nice catch! Many thanks for the contribution.

**Pull request merged**
