### PR TITLE
MDEV-15505 Fix wsrep XID seqno byte order

### PR DESCRIPTION
**Pull request by temeo**
The problem is that the seqno part of wsrep XID is always
stored in host byte order. This may cause issues when a physical
backup is restored on a host with different architecture, the
seqno part with XID may have incorrect value.

In order to fix this, wsrep XID seqno is always written into
XID data buffer in little endian byte order using int8store()
and read from data buffer using sint8korr(). For backwards
compatibility the seqno is read from TRX_SYS page in host
byte order during upgrade.

This patch implements byte ordering in wsrep_xid_init(),
wsrep_xid_seqno(), and exposes functions to read wsrep
XID uuid and seqno in wsrep_service_st. Backwards compatibility
for upgrade is provided in trx_rseg_init_wsrep_xid().

I submit this patch under BSD-new license.

### CODE REVIEW

**Comment by temeo** [comment]
@dr-m I update the patch in the following way:
1) The old XID format will be unchanged so that the reads from old style XID will be backwards compatible. Introduced a new XID format which will be detected when reading the XID seqno. All newly generated XIDs will have a new format from now on.
2) Included wsrep_api.h from service_wsrep.h for wsrep type definitions
3) Removed the wsrep XID code from mariabackup and included service_wsrep.h

I tested an upgrade from 10.2 and 10.3 on little endian machine and didn't observe any issues. However, I don't currently have access to big endian hardware and compiling/testing upgrade in virtual machine will take some time.

**Comment by temeo** [comment]
@dr-m I was finally able to run upgrade manual tests between big-endian (BE) and little-endian (LE) platforms. The tests were done by starting mysqld with lower version, doing CREATE TABLE/INSERT to advance wsrep position in InnoDB pages, then running --wsrep-recover with upgraded version to verify that the recovery process returns correct wsrep position. The complete results are 

10.2 LE -> MDEV-15505 LE: OK
10.3 LE -> MDEV-15505 LE: OK
10.2 BE -> MDEV-15505 BE: OK
10.3 BE -> MDEV-15505 BE: OK 

10.2 BE -> MDEV-15505 LE: Fail
10.3 BE -> MEDV-15505 LE: Fail
10.2 LE -> MDEV-15505 BE: Fail
10.3 LE -> MDEV-15505 BE: Fail

MDEV-15505 BE -> MDEV-15505 LE: OK
MDEV-15505 LE -> MDEV-15505 BE: OK

So it works as expected: Upgrades between the same byte order architectures work from 10.2, 10.3 -> MDEV-15505. Upgrades from 10.2, 10.3 -> MDEV-15505 fail if the source and target platforms have different endiannes. Fixed MDEV-15505 data dir can be recovered on the platform with different byte order.

**Comment by dr-m** [comment]
This fails to build across the whole buildbot:
> libmariadbd.a(sql_plugin.cc.o):(.data.rel+0x680): undefined reference to `wsrep_xid_seqno'
> libmariadbd.a(sql_plugin.cc.o):(.data.rel+0x688): undefined reference to `wsrep_xid_uuid'
> collect2: error: ld returned 1 exit status

Maybe some `#ifdef WITH_WSREP` is missing? On WIndows, it fails already at compilation time:
> D:\win32-debug\build\src\include\mysql/service_wsrep.h(25): fatal error C1083: Cannot open include file: 'wsrep_api.h': No such file or directory [D:\win32-debug\build\sql\sql_sequence.vcxproj]

**Comment by temeo** [comment]
@dr-m Pushed a commit to fix compilation issues, tested that the build passes with the following cmake options:
* -DBUILD_CONFIG=mysql_release -DWITH_READLINE=1 -DWITH_WSREP:BOOL=OFF
* -DBUILD_CONFIG=mysql_release -DWITH_READLINE=1 -DWITH_WSREP:BOOL=ON
* -DCMAKE_BUILD_TYPE=Debug -DWITH_READLINE=1 -DWITH_WSREP:BOOL=OFF
* -DCMAKE_BUILD_TYPE=Debug -DWITH_READLINE=1 -DWITH_WSREP:BOOL=ON

**Pull request merged**
