### PR TITLE
MDEV-12525 - Use CPACK_RPM_FILE_NAME="RPM-DEFAULT"

### PR DESCRIPTION
**Pull request by grooverdan**
This has been implemented in for cmake-3.6 to match distro version of what the filename should look like.

Thanks to Domen Vranka for the suggestion from https://gitlab.kitware.com/cmake/cmake/issues/16715

example on FC25:
<pre>
ls -la *rpm
-rw-rw-r-- 1 dan dan  4577938 Mar 26 15:57 MariaDB-client-5.5.55-1.fc25.x86_64.rpm
-rw-rw-r-- 1 dan dan    27170 Mar 26 15:57 MariaDB-common-5.5.55-1.fc25.x86_64.rpm
-rw-rw-r-- 1 dan dan  1391514 Mar 26 15:57 MariaDB-devel-5.5.55-1.fc25.x86_64.rpm
-rw-rw-r-- 1 dan dan 14906590 Mar 26 15:57 MariaDB-server-5.5.55-1.fc25.x86_64.rpm
-rw-rw-r-- 1 dan dan  1038230 Mar 26 15:57 MariaDB-shared-5.5.55-1.fc25.x86_64.rpm
-rw-rw-r-- 1 dan dan 20347734 Mar 26 15:57 MariaDB-test-5.5.55-1.fc25.x86_64.rpm
</pre>

### CODE REVIEW

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-12525

This task was added to 5.5 backlog, which hasn't been scheduled yet.

Thanks,
Sergey

**Comment by vuvova** [comment]
What could be the reason for doing it?

**Comment by grooverdan** [comment]
This keeps the RPM filename of the same format that users of the distro expect. It also keeps the debuginfo packages (MDEV-4646 / #334) of the same filename form. (The alternate to this is a cmake-3.9 feature https://cmake.org/cmake/help/v3.9/module/CPackRPM.html#variable:CPACK_RPM_DEBUGINFO_FILE_NAME).

Seems easier to to use RPM-DEFAULT and let rpmbuild create rpm filenames of the same from as the existing distro rpm filenames.

**Comment by vuvova** [comment]
pushed, thanks

**Comment by grooverdan** [comment]
Thanks @vuvova

**Pull request closed without merging**
