### PR TITLE
extend perror to know about server errors

### PR DESCRIPTION
**Pull request by alpes214**
This commit is for suggested development task https://mariadb.com/kb/en/mariadb/suggested-development/ 

There could be the following issues with code:
- it would be good to add different languages in command line parameters
- error names are not stored in the errmsg.sys file and this is why I removed them from the message. This could be an issue for somebody.
- to apply this patch to newer versions (10.2 etc.) some additional modification will be required

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @alpes214:

Thank you for the contribution! There is one more detail before we can review & accept your patch.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Regards,
Vicențiu

**Comment by alpes214** [comment]
Hi Vicențiu,

I am contributing my new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license. 

Hope this comment will be enough for now. I will also fill out the contribution agreement and will send it to MariaDB Foundation.

Thank you,
Valentin

**Comment by alpes214** [comment]
Hi @cvicentiu !

Before continuing with fixes I would like clarify the goal of this task.

> In additionally, I don't see any difference in output between perror with your patch and without. Can you provide an example where the previous version would not print the same message?

I am following suggested developments on this page https://mariadb.com/kb/en/mariadb/suggested-development/ . There is no enough information on this page and I do not know the reason for such change. 

I was following my assumptions.My understanding of this task is, that the error messages for English language should not be changed. But the perror have to read error messages from errmsg.sys file instead of including them from mysqld_errname.h. I guess in the future the perror will be able to print translated messages for other supported languages.

Please let me know what is a goal of the suggested development described on the link above? Are there more details for this task? 

Thank you,
Valentin

**Comment by vuvova** [comment]
this task was created before `perror` knew how to print server messages, it simply reported "unknown error". Now it does know them, so this task is not very relevant anymore. Sorry.

If you'd like I can suggest you some up-to-date tasks from https://jira.mariadb.org

**Comment by alpes214** [comment]
Hi @vuvova ,

thank you for response. I do not know much about mysql or mariadb internals but I would like to learn. I've choosen perror task because it seemed very simple to me so I can learn source code structure, build system etc.

yes, please suggest me a task that I can work on. 

Thank you,
Valentin

**Comment by cvicentiu** [comment]
Hi @alpes214 !

I'm closing this issue as the commit itself is not useful for us. One of the open tasks that we have that could be interesting is:

https://jira.mariadb.org/browse/MDEV-12298

**Comment by alpes214** [comment]
Hi Vicențiu,

I will be busy with other thing next several months and will not be able to work on this ticket. I hope I will be able to return to Mariadb project in the future.

Thank you, Valentin

**Pull request closed without merging**
