### PR TITLE
Added regression test for MDEV-5871

### PR DESCRIPTION
**Pull request by pastcompute**
This is a regression test for MDEV-5871 that I never got merged into BZR
I had to untangle it whilst dealing with the fork/push for MDEV-6282

### CODE REVIEW

**Comment by pastcompute** [comment]
Note, this will cause an easily resolved merge conflict when applied on top of 

https://github.com/pastcompute/server/tree/10.1-oqgraph-6282-6345-6784-cherrypick-test

which is the expected result of forward porting https://github.com/MariaDB/server/pull/17 from 10.0 to 10.1

**Comment by grooverdan** [comment]
typo x 2 - supoprts -> supports

**Comment by pastcompute** [comment]
Fixed typos

**Comment by grooverdan** [comment]
so although MDEV-6282 MDEV-5871 seems part of these tests aren't merged. Is that right? Do they still need to be?

**Comment by pastcompute** [comment]
um it been a while...
the unit tests should probably be merged, I added them to regression test those bugs

**Comment by svoj** [comment]
Pushed https://github.com/MariaDB/server/commit/59b6b99ce3635077d06a3c0edb05c5ac52ca6e34

**Pull request closed without merging**
