### PR TITLE
MDEV-9872: crc32-ieee optimization for Power8

### PR DESCRIPTION
**Pull request by grooverdan**
Like https://github.com/mysql/mysql-server/pull/68, this moves the CRC implementation to the mysys library for common use.

An optimized version of CRC32(-IEEE) for power is added (existing one is CRC32C) and binary log and sql CRC32 function are modified to use this.

Links to completing a x86 optimized implementation are in the mysql-server pull request.

### CODE REVIEW

**Comment by janlindstrom** [comment]
InnoDB changes are fine, someone should review the server changes.

**Comment by svoj** [comment]
Can we avoid bundling crc32-vpmsum (is there crc32-vpmsum packages available)? Or why don't you prefer to patch zlib package instead?

We generally store third party libraries in extra/ (those that are not were put in mistakenly). I'd prefer to have this library in extra/crc32-vpmsum, also compile it as a static library instead of adding sources directly.

innodb stuff (ut0crc32*) should stay inside InnoDB, we shouldn't need it in the server.

We shouldn't really call crc32 implementation via a pointer for performance reasons. What is the purpose of PPC_FEATURE2_ARCH_2_07? When it's on and when it's off?

**Comment by grooverdan** [comment]
We haven't made crc32-vpmsum packages. A generic optimised package of crc32 functions would be ideal no existing product has been identified. zlib has patches submitted https://github.com/madler/zlib/pull/125 (needs to be improved) however they have been quite slow to add anything.

Happy to move to a static library in extra.

utcrc32c functions probably should of been fully renamed. Main reason for moving out of innodb was commonality, using a common slice8 init routine, and potentially reusing an optimised crc32c in future when linking with galera.

PPC_FEATURE2_ARCH_2_07 defines the Power7 version when VSX instructions where added. As only POWER8+ are supported perhaps we can remove runtime checks in favour of a compile time check.

Are you happy to drop the runtime checks for sse2 hardware on x86 too? is so then I can remove function pointers and have a direct compile time selection of optimum implementation.

If you want to keep a runtime check I can make a shared crc32 library and use ifunc indirection call which uses the loader to dynamical plug the write function in at load time (ref: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#ifunc).

**Comment by svoj** [comment]
Ok, so since there's no package containing crc32-vpmsum it should be alright to bundle it as described above.

According to storage/xtradb/CMakeLists.txt crc32-vpmsum is only enabled for ppc64le, which is Power8 or newer (please correct me if I'm wrong!). This makes runtime checks redundant.

According to my rough benchmark empty function call via a pointer is 18% slower and "ifunc" call is 36% slower than a normal function call. So we optimize crc32 algorithm and then immediately loose some performance on calling it.

As for the SSE and "slice8" based implementations: we can accept them if there's evidence that they're any better than zlib implementation. But let's keep it out of this task: smaller changes have higher chances to get applied quickly.

As for the crc32 init function: I definitely don't like it. If we really need to initialize something for crc32, we can perform lazy initialization instead.

**Comment by grooverdan** [comment]
Thanks for benchmarking function pointer and ifunc calls. That's good to know. I didn't expect ifunc to be that bad.

Yes ppc64le is POWER8+ so yes its excessive.

SSE implementation was already there. "slice8" is a copy of what was in zlib and was already there (with a different crc table). I've just moved SSE around and re-factored the slice8 to handle crc32c and crc32-ieee. There should be no performance difference but I'll run tests to be sure or eliminate these changes.

I'll look at pre-generating the crc tables and using a build time check of SSE capability. Then I can make it as a static library and eliminate crc32_init.

Notes on the JIRA issue show how to write a better x86 implementation than SSE. Unfortunately I can't actually write it. Perhaps the Intel people who posted the zlib patches can (and give MariaDB Foundation a patent grant in the process).

**Comment by svoj** [comment]
Pushed 9c2215e022c325599bd1b66d1f2214529fb99a24

**Pull request closed without merging**
