### PR TITLE
MDEV-21303: Non-Linux/Non-Windows plugins to link to mariadbd now that name has been changed

### PR DESCRIPTION
**Pull request by grooverdan**
Prevent errors like on FreeBSD

[ 56%] Linking CXX shared module ha_test_sql_discovery.so
cd /usr/home/dan/build-mariadb-server-10.5/storage/test_sql_discovery && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/test_sql_discovery.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -O2 -g -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF  -shared  -o ha_test_sql_discovery.so CMakeFiles/test_sql_discovery.dir/test_sql_discovery.cc.o -lpthread ../../libservices/libmysqlservices.a -lmysqld -lpthread
/usr/bin/ld: error: unable to find library -lmysqld

Note for OSX you may need to change the target name, mysqld if you are renaming it. (untested)

### CODE REVIEW

**Comment by vaintroub** [comment]
what happens if you change 
    TARGET_LINK_LIBRARIES (${target} mysqld)
to 
  TARGET_LINK_LIBRARIES (${target} mariadbd)

Will this work? I prefer actually link whatever is needed, ideally instructing linker to force all symbols to be resolved (no-undefined). Just that Linux linker refused to handle it, thus there was exception for Linux

**Comment by grooverdan** [comment]
```
--- a/cmake/plugin.cmake
+++ b/cmake/plugin.cmake
@@ -220,8 +220,8 @@ MACRO(MYSQL_ADD_PLUGIN)
       IF(MSVC)
         ADD_DEPENDENCIES(${target} gen_mysqld_lib)
         TARGET_LINK_LIBRARIES(${target} mysqld_import_lib)
-      ELSEIF(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
-        TARGET_LINK_LIBRARIES (${target} mysqld)
+      ELSEIF(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
+        TARGET_LINK_LIBRARIES (${target} mariadbd)
```
Build
```
--- plugin/handler_socket/handlersocket.so ---
[100%] Linking CXX shared module handlersocket.so
cd /usr/home/dan/build-mariadb-server-10.5/plugin/handler_socket && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/handlersocket.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -Wno-deprecated-declarations -O2 -g -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF  -shared  -o handlersocket.so CMakeFiles/handlersocket.dir/handlersocket/database.cpp.o CMakeFiles/handlersocket.dir/handlersocket/handlersocket.cpp.o CMakeFiles/handlersocket.dir/handlersocket/hstcpsvr_worker.cpp.o CMakeFiles/handlersocket.dir/handlersocket/hstcpsvr.cpp.o -lpthread ../../libservices/libmysqlservices.a libhsclient.a -lpthread 
[100%] Built target handlersocket
--- plugin/versioning/CMakeFiles/test_versioning.dir/all ---
--- plugin/versioning/test_versioning.so ---

$  (cd /usr/home/dan/build-mariadb-server-10.5/plugin/handler_socket && cat cmake_link_script CMakeFiles/handlersocket.dir/link.txt)
cat: cmake_link_script: No such file or directory
/usr/bin/c++ -fPIC  -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -Wno-deprecated-declarations -O2 -g -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF  -shared  -o handlersocket.so CMakeFiles/handlersocket.dir/handlersocket/database.cpp.o CMakeFiles/handlersocket.dir/handlersocket/handlersocket.cpp.o CMakeFiles/handlersocket.dir/handlersocket/hstcpsvr_worker.cpp.o CMakeFiles/handlersocket.dir/handlersocket/hstcpsvr.cpp.o -lpthread ../../libservices/libmysqlservices.a libhsclient.a -lpthread 

```
So it built, but oddly no `-lmariadbd` in the output even after removing the builddir. Changing to `mariadb`  resolved to the client side library in the output `.... ./libservices/libmysqlservices.a ../../libmariadb/libmariadb/libmariadbclient.a ...`. So it works as you described, but I'm a little confused how for the moment.

**Comment by vaintroub** [comment]
CMake would use full path for TARGET_LINK_LIBRARIES, if it knows it, thus there is no -l

**Comment by vaintroub** [comment]
but yes,  little funny it does not executable to link :) Maybe it does not work for that linker.

**Comment by grooverdan** [comment]
`TARGET_LINK_LIBRARIES (${target} mariadbd)` seem to work to compile openindiana mariadb plugins ok.

**Comment by grooverdan** [comment]
updated code to how @vaintroub suggested as that works. Commit message adjusted.

**Pull request closed without merging**
