### PR TITLE
MDEV-19205: Sphinx unable to connect using a host name

### PR DESCRIPTION
**Pull request by an3l**
This patch is cherry-picked from PR #532 and added test case (see commit message).

### CODE REVIEW

**Comment by robertbindar** [comment]
Hi @an3l ! I don't see the sphinx.sphinx test enabled, can you please update the patch so that it enables the test? Also it would be nice to have sphinx.union-5539 enabled as well, although it is failing for me at the moment. If it involves a more complicated fix, we can enable it at a later point.

**Comment by an3l** [comment]
Hi @robertbindar, 
I think that `sphinx.test` shouldn't be enabled (see `MDEV-10986` for reference), right @vuvova ?
In order to make this patch I have enabled test, tested and after that again disabled it to prevent failure caused by searchd service.

**Comment by robertbindar** [comment]
It shouldn't be enabled if it's going to fail, that's for sure. But I think, given we have our attention on this issue right now, it is worth investigating a bit if fixing the test is easy or complex to do, and if it's relatively easy maybe it's worth including a fix for it here.
Starting the searchd daemon seems to happen in sphinx/suite.pm, and the daemon is synced using sleep at the moment. It might be that searchd could expose an api/signal handler/config option that could allow us to sync with the process being started or if not, we could just fall back to increasing the sleep time (not preferred).

**Comment by robertbindar** [comment]
What about something like this? When searchd is capable of returning metrics, it should be up and running (searchd --status returns 0 on success), let me know if this sounds reasonable.
```
diff --git a/storage/sphinx/mysql-test/sphinx/suite.pm b/storage/sphinx/mysql-test/sphinx/suite.pm
index 24c377d7665..5c85b84cdcf 100644
--- a/storage/sphinx/mysql-test/sphinx/suite.pm
+++ b/storage/sphinx/mysql-test/sphinx/suite.pm
@@ -23,6 +23,8 @@ return "'indexer' binary not found" unless $exe_sphinx_indexer;
 my $exe_sphinx_searchd = &locate_sphinx_binary('searchd');
 return "'searchd' binary not found" unless $exe_sphinx_searchd;
 
+my $sphinx_config= "$::opt_vardir/my_sphinx.conf";
+
 # Check for Sphinx engine
 
 return "SphinxSE not found" unless $ENV{HA_SPHINX_SO} or $::mysqld_variables{'sphinx'} eq "ON";
@@ -69,7 +71,6 @@ sub searchd_start {
   my $sphinx_data_dir= "$::opt_vardir/" . $sphinx->name();
   mkpath($sphinx_data_dir);
   my $sphinx_log= $sphinx->value('#log-error');
-  my $sphinx_config= "$::opt_vardir/my_sphinx.conf";
   my $cmd= "\"$exe_sphinx_indexer\" --config \"$sphinx_config\" test1 > \"$sphinx_log\" 2>&1";
   &::mtr_verbose("cmd: $cmd");
   system $cmd;
@@ -95,11 +96,44 @@ sub searchd_start {
   &::mtr_verbose("Started $sphinx->{proc}");
 }
 
+sub wait_exp_backoff {
+  my $timeout= shift; # Seconds
+  my $start_wait= shift; # Seconds
+  my $scale_factor= shift;
+
+  $searchd_status= "$exe_sphinx_searchd --status" .
+                   " --config $sphinx_config > /dev/null 2>&1";
+
+  my $scale= $start_wait;
+  my $total_sleep= 0;
+  while (1) {
+    my $status = system($searchd_status);
+    if (not $status) {
+      return 0;
+    }
+    if ($total_sleep >= $timeout) {
+      last;
+    }
+
+    &::mtr_milli_sleep($scale * 1000);
+    $total_sleep+= $scale;
+    $scale*= $scale_factor;
+  }
+
+  &::mtr_warning("Getting a response from searchd timed out");
+  return 1
+}
+
 sub searchd_wait {
   my ($sphinx) = @_; # My::Config::Group
 
-  return not &::sleep_until_file_created($sphinx->value('pid_file'), 20,
-                                         $sphinx->{'proc'})
+  if (not &::sleep_until_file_created($sphinx->value('pid_file'), 20,
+                                      $sphinx->{'proc'}))
+  {
+    return 1;
+  }
+
+  return wait_exp_backoff(20, 0.1, 2)
 }
```

**Comment by an3l** [comment]
Hi @robertbindar,
did you try proposed patch when no `searchd` is installed when `exe_sphinx_searchd` is not defined ?
In general I think that your this should go in different MDEV related to `MDEV-10986`.
Thanks

**Comment by robertbindar** [comment]
Hi @an3l! I haven't tested it thoroughly, it is something I proposed quickly to fill the gap between this PR and enabling the existing tests for sphinx, feel free to change any part of it that is buggy. It should work as expected when there is no searchd available because in this case the `searchd_start` callback fails and `searchd_wait` never gets called.

**Comment by robertbindar** [comment]
Hi @an3l! Any progress on this PR?

**Comment by an3l** [comment]
Pushed with 9611d7e08a9f69cd91 and fd5cd073cc5a65a1f71.

**Pull request closed without merging**
