### PR TITLE
#ifndef SOURCE_REVISION, don't compile fail

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

hit this with the build environment from #437

### CODE REVIEW

**Comment by svoj** [comment]
I'd rather have SOURCE_REVISION always defined. But let's see what @vaintroub thinks about it.

**Comment by vaintroub** [comment]
SOURCE_REVISION is always defined, in either ${CMAKE_BINARY_DIR}/include/source_revision.h or (for building from source package) in  ${CMAKE_SOURCE_DIR}/include/source_revision.h

Basically,  #include <source_revision.h> guarantees SOURCE_REVISION is defined, and yes, sometimes it will be an empty string.

**Comment by svoj** [comment]
IIUC it would've always been defined if it were ```#define```, but we have ```#cmakedefine``` there.

**Comment by vaintroub** [comment]
You're correct. I changed #cmakedefine to #define in the header file, so now it is always defined

**Comment by svoj** [comment]
Thanks!

**Comment by grooverdan** [comment]
thanks @vaintroub and @svoj. I was vaguely thinking there must have been a better way.

**Pull request closed without merging**
