### PR TITLE
MDEV-8743: fopen mode e (glibc only) to prevent galera SST scripts ac…

### PR DESCRIPTION
**Pull request by grooverdan**
…cessing server files

I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
This is probably suitable enough for a 10.0-galera backport?

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-8743

This task was added to 10.0 backlog.

Thanks,
Sergey

**Comment by svoj** [comment]
What about non-GLIBC? @vaintroub is there anything similar on Windows?

**Comment by grooverdan** [comment]
I thought Windows file opens where exclusive by default and current Windows doesn't support galera which is the main (only?) case for subprocess creation.

In a case of fopens patched here we are lucky here that 2 files here are read only, and the buffer pool dump if corrupted doesn't case data loss. The posix replacement is a ```open(.., O_CLOEXE)``` followed by a ```fdopen```.

**Comment by vaintroub** [comment]
Handles on Windows are not inherited by default.
To inherit, CreateFile needs  lpSecurityAttributes with bInheritHandle  = TRUE for this to happen

**Comment by grooverdan** [comment]
Added non-glibc path for where O_CLOEXEC isn't 0.

**Comment by janlindstrom** [comment]
Hi, comment about backporting to 10.0-galera is not clear, those files are not in 5.6 based 10.0.

**Comment by grooverdan** [comment]
There is the buf0dump.cc in 10.0 (backported maybe) but not fsp0file.cc. Sorry for the lack of clarity.

**Comment by grooverdan** [comment]
thanks @janlindstrom

**Pull request merged**
