### PR TITLE
MDEV-12911 - generate and install sysusers and tmpfiles configuration

### PR DESCRIPTION
**Pull request by eworm-de**
Using systemd we can automate creating users and directories. So
generate and install the configuration files.

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @eworm-de!

Thank you for the contribution!
A Jira task has been created to track this pull request. https://jira.mariadb.org/browse/MDEV-12911

It will be handled during the course of the next 10.1 sprint (or it may happen a bit earlier, given how we may want it into future versions.

Vicențiu

**Comment by cvicentiu** [comment]
Hi @eworm-de !

The patch looks good, however it is missing something. Look at cmake/install_layout.cmake where we make use of INSTALL_SYSTEMD_UNITDIR_{RPM||DEB}. Can you set INSTALL_SYSTEMD_SYSUSERSDIR_{RPM|DEB} and INSTALL_SYSTEMD_TMPFILESDIR_{RPM|DEB} to where these ought to go?

With those changes I believe that patch is ready to be pushed.

Thanks,
Vicențiu

**Comment by eworm-de** [comment]
Hi @cvicentiu !
Updated as requested. The Debain system I looked at did not have a `sysusers.d` directory at all. According the the documentation (`man 5 sysusers.d`) this is the correct path.
Thanks!

**Comment by eworm-de** [comment]
Any news on this one?

**Comment by cvicentiu** [comment]
Hi @eworm-de!

Sorry for taking so long on this. Other issues came up and I never got around to testing this. I have tested it now and have a patch ready with a minor addition. The FOR LOOP in install_layout.cmake needs to also iterate through SYSTEMD_SYSUSERS and SYSTEMD_TMPFILES. I've added that myself so as to not have you do the commit again for such a minor issue.

 What I don't quite know is whether systemd-sysusers should be called manually or not. When I create the .deb (or .rpm) package, the files get added to the package. When you install the package, the sysusers and tmpfiles conf files are installed correctly, however systemd-sysusers or systemd-tmpfiles commands are not run. If you run them manually, the files / users get created correctly. Is this the intention of your patch, or do you expect it to work on package installation immediately.

Regards,
Vicențiu

**Comment by eworm-de** [comment]
I am running Arch Linux here and can speak for that system only: We have a [sysusers](https://git.archlinux.org/svntogit/packages.git/tree/systemd/trunk/systemd-sysusers.hook) and [tmpfiles](https://git.archlinux.org/svntogit/packages.git/tree/systemd/trunk/systemd-tmpfiles.hook) hook for our package manager `pacman`. If a package installs and/or modifies a files matching these patterns the specified commands are run.
The package is built inside a clean chroot, so running `systemd-sysusers` and `systemd-tmpfiles` there would not have an effect on the target system. Even worse, the build is done with an unprivileged user, so this would probably fail.
I vote for not running `systemd-sysusers` and `systemd-tmpfiles` from the build system.

Anybody here familiar with packaging `.deb` or `.rpm` and can shed some light?

BTW, `systemd-sysusers` and `systemd-tmpfiles` are run on system boot, so we can be sure changes are done after a reboot.

**Comment by eworm-de** [comment]
Just found a [Wiki article about sysusers on Fedora](https://fedoraproject.org/wiki/Changes/SystemdSysusers). Looks like they have [scriptlets](https://fedoraproject.org/wiki/Packaging:Scriptlets) where `systemd-sysusers` and `systemd-tmpfiles` have to be called.

**Comment by cvicentiu** [comment]
Hi @eworm-de: I've pushed your patch with a small change (explained in the commit message) to 10.1. I believe this should be sufficient for Archlinux. For other packages, I'll spend some time separately. Anyway, 10.1.30 should have your patch in. :)

**Comment by cvicentiu** [comment]
Commit is: https://github.com/MariaDB/server/commit/7bbc6c14d1e8fcf1f4737e0a5fcf6237fe18bd23

**Pull request closed without merging**
