### PR TITLE
main.subselect* often fails on CI with ER_SUBQUERY_NO_1_ROW

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-______*

## Description

Using mysql.slow_log was a test table would generate more than one row if there was more than one row in the table.

Some by implicitly enforcing an aggregation in the subquery.

## How can this PR be tested?

its a test.
If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [X] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by ottok** [comment]
Thanks Daniel, I appreciate the bias for action to fix potential MTR failure. However, posting a pull request and immediately merging it yourself seems a bit too much bias for action. Wouldn't it be better to wait for at least one extra pair of eyes e.g. from @LinuxJedi before merging?

**Comment by grooverdan** [comment]
check the JIRA Issue, was approved.

**Comment by mariadb-RexJohnston** [comment]
I reviewed this.  Changes are consistent with MDEV-7445.

**Comment by ottok** [comment]
This was applied in Debian in https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/f7554dac59e002768847e686d58b3bad8efd7a9c and uploaded with MariaDB 1:10.11.6-2. Based on autopkgtest results at https://ci.debian.net/packages/m/mariadb/ all the new 1:10.11.6-2 CI runs are passing.

**Pull request merged**
