### PR TITLE
MDEV-21942: Correctly define libpcre2-dev dependency for 10.5 series

### PR DESCRIPTION
**Pull request by ottok**
If libpcre2 (10.x) is not defined and only the older libpcre3 (8.x)
would be available, the build would attempt to download it from the
Internet, violating many build environment restrictions.

Also update Travis-CI to reflect this change.

### CODE REVIEW

**Comment by ottok** [comment]
Seems you already did this partially. These are the remaining changes to finalize it.

**Comment by ottok** [comment]
Added extra commit to fix regressions from https://github.com/MariaDB/server/commit/fd2dc9c3fdfb73fa450db9fecd72044bb0554040, so with these changes and Daniel's recent s390x Travis-CI actually becomes green, so I urge to process this with high priority.

If Travis-CI is not green on the 10.5 branch then you are likely to get more and more regressions over time that could have been prevented since tests exist for them, but developer just ignored them since the starting point of their work was already failing.

**Comment by ottok** [comment]
Travis-CI fully passing now: 
image

I will merge this myself in a couple of days if there is no response, since having Travis-CI green is critical for the entire development workflow.

**Comment by cvicentiu** [comment]
@ottok I've merged the exec bit change in libmariadb-dev-compat.links problem from 10.3 already. I tested that so many times and yet the final commit apparently missed that. Thanks for catching it!

I'll take a look at the rest of the commits now.

**Pull request merged**
