### PR TITLE
Typo fix in sql_sequence.cc

### PR DESCRIPTION
**Pull request by waynexia**
Fixed two typos in sql_sequence.cc.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @waynexia 
Thanks for your contribution! 
Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by waynexia** [comment]
Submitted under new BSD license.

**Comment by montywi** [comment]
On Sun, Apr 14, 2019 at 5:30 PM Ruihang Xia <notifications@github.com> wrote:
>
> Fixed two typos in sql_sequence.cc.
>

Thanks, looks ok!
Anel, can you merge and push this into 10.4 ?

Regards,
Monty

**Comment by svoj** [comment]
I'd cherry-pick this to 10.3.

**Comment by an3l** [comment]
Thanks for contribution. 
Merged in `10.3` with commit  `a2335b791aa06fbf4`

**Comment by waynexia** [comment]
Appreciate it!

**Pull request closed without merging**
