### PR TITLE
Fix tests in 2020

### PR DESCRIPTION
**Pull request by bmwiedemann**
This patch allows the tests to pass in 2020-03-01.

Unfortunately, the year 2038 problem prevented me from pushing
the deadline even further into the future.

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +15 years, because that is how long I expect some software will be used in some places, but for mariadb, it even failed with +14 months

Note: I gave the patch some testing on openSUSE's mariadb-10.2.21 package.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @bmwiedemann 
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by bmwiedemann** [comment]
I am fine with submitting this code under the BSD-new license
My employer, SUSE Linux GmbH, is always encouraging upstream contributions, too.

**Comment by an3l** [comment]
Thanks

**Comment by bmwiedemann** [comment]
https://api.travis-ci.org/v3/job/485241723/log.txt  shows

```
Completed: Failed 8/1941 tests, 99.59% were successful.

Failing test(s): main.select_pkeycache main.select main.select_jcl6 main.type_float main.func_group main.func_str main.type_time_hires main.type_timestamp_hires
```

and some of these failures are more related to time granularity (e.g. the filesystem) rather than my change:

```diff
CURRENT_TEST: main.type_timestamp_hires
--- /home/travis/build/MariaDB/server/mysql-test/r/type_timestamp_hires.result	2019-01-28 08:52:45.130648446 +0000
+++ /home/travis/build/MariaDB/server/mysql-test/r/type_timestamp_hires.reject	2019-01-28 09:07:06.626850478 +0000
@@ -15,14 +15,14 @@
 0000-00-00 00:00:00.000
 2010-12-11 00:20:03.123
 2010-12-11 01:02:03.456
-2010-12-11 03:04:05.789
+2010-12-11 03:04:05.785
 2010-12-11 15:47:11.123
 select truncate(a, 6) from t1;
 truncate(a, 6)
 0.000000
 20101211002003.120000
 20101211010203.457031
-20101211030405.790000
+20101211030405.785000
 20101211154711.120000
```

There were also multiple travis jobs timing out after 2h when they had only 90% compiled.

**Comment by svoj** [comment]
Hi @bmwiedemann, your contribution is appreciated. Thanks!

According to our maintenance policy: https://mariadb.org/about/maintenance-policy/

Looks like even 5.5 will hit some of discovered issues before it goes EOL.

Will you be willing to retarget this pull request for 5.5? Alternatively I could cherry pick your patch to 5.5 and then let you re-verify if we missed something for 10.2.

**Comment by bmwiedemann** [comment]
Would be nice, if you could do the cherry-pick to 5.5 because there are 23 conflicts to resolve.

**Comment by svoj** [comment]
Thanks! I've cherry-picked your fixes to 5.5: cfe0fe1ad1f7c75102285d445c3ba8167f5b9c44
Luckily all of these were fairly easy to resolve and all `.test` files applied cleanly, which means we should have pretty much the same fixes in 10.2 as soon as they're merged.

Also I allowed myself to amend your patches and moved affected dates from the future to the past. It means these tests should pass even in gadzillon years, well, unless of course somebody reverses the flow of time.

**Pull request closed without merging**
