### PR TITLE
macos: Fix CMAKE_OSX_ARCHITECTURES when not set

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-______*

## Description

When CMAKE_OSX_ARCHITECTURES isn't set we end up with "Packaging as: mariadb-10.4.33-osx10.19-x86_64" on arm64 builders.

This is covering up some dated code in cmake/package_name.cmake on determining the MacOS name.

Based on https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html this should set before `PROJECT`.

## How can this PR be tested?

Look at "Packaging as" in MacOS builder.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [X] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by grooverdan** [comment]
[didn't help](https://buildbot.mariadb.org/#/builders/590/builds/1558/steps/4/logs/stdio)
```
-- Packaging as: mariadb-10.4.33-osx10.19-x86_64
```

**Comment by vaintroub** [comment]
> [didn't help](https://buildbot.mariadb.org/#/builders/590/builds/1558/steps/4/logs/stdio)
> 
> ```
> -- Packaging as: mariadb-10.4.33-osx10.19-x86_64
> ```

The documentation say "This variable should be set as a CACHE entry", https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html

i.e set(CMAKE_OSX_ARCHITECTURES. ... CACHE STRING "CMAKE OSX architectures"), although it might be easier to fix it in in cmake/package_name.cmake , where it assumed 64BIT means x86_64

**Comment by grooverdan** [comment]
Thanks on `CACHE`. Says to set before PROJECT hence its location. So much cmake/package_name.cmake to reorg but I haven't got a good grasp of its requirement beyond a filename, and if anyone actually uses it.

**Comment by grooverdan** [comment]
Right - as "-- Packaging as: mariadb-10.4.33-osx10.19-arm64" now.

**Pull request merged**
