### PR TITLE
MDEV-9254 - 'truncate table' make server crash in sharding&ha configuration when wrapper is oracle

### PR DESCRIPTION
**Pull request by ChengXiaoZ**

### CODE REVIEW

**Comment by ChengXiaoZ** [comment]
https://mariadb.atlassian.net/browse/MDEV-9254

**Comment by svoj** [comment]
Hi Cheng,

Thanks for your contribution. I sent notification about this pull request to Kentoku, we'll have to wait for his decision.

Thanks,
Sergey

**Comment by ChengXiaoZ** [comment]
Hi Sergey,
It's OK.
Thanks,
Cheng

**Comment by Kentoku** [comment]
Hi Cheng,
Thank you for contributing this patch.
I'm now checking but please give me more time.
Thanks,
Kentoku

**Comment by ChengXiaoZ** [comment]
Hi Kentoku
Thanks for you review.
This may be cased by an oversight,  because in all other functions 
```c++
SPIDER_CONN *conn = conns[roop_count];
spider_db_handler *dbton_hdl = dbton_handler[conn->dbton_id];
```
is used to get spider_db_handler.
for example, line 6327 in spider_db_update function of spd_db_conn.cc
https://github.com/MariaDB/server/blob/10.1/storage/spider/spd_db_conn.cc

'truncate table' make server crash when wrapper is oracle but ok when wrapper is mysql, because coincidence of value.
for example, there are two tables, myt1 and orat1.
create table myt1(A int) ENGINE = SPIDER CONNECTION='wrapper "oracle", table "T1 T2", srv "my_backend1 my_backend1"';
create table orat1(A int) ENGINE = SPIDER CONNECTION='wrapper "oracle", table "T1 T2", srv "ora_backend1 ora_backend1"';
for myt1, the memory value is 
SPIDER_SHARE.use_sql_dbton_count=1
SPIDER_SHARE.use_sql_dbton_ids[0]=0
SPIDER_SHARE.use_sql_dbton_ids[1]=0  initial value
ha_spider.dbton_handler[0] is the pointer of mysql_db_handler object
ha_spider.dbton_handler[1]=0 
for orat1, the memory value is 
SPIDER_SHARE.use_sql_dbton_count=1
SPIDER_SHARE.use_sql_dbton_ids[0]=1
SPIDER_SHARE.use_sql_dbton_ids[1]=0 initial value
ha_spider.dbton_handler[0]=0
ha_spider.dbton_handler[1] is the pointer of oracle_db_handler object

when execute codes
```c++
dbton_id = share->use_sql_dbton_ids[roop_count]; 
spider_db_handler *dbton_hdl = spider->dbton_handler[dbton_id];
```
For the first link and second link of myt1, dbton_id is 0 and can get the right dbton_handler.
For orat1, the first link's dbton_id is 1 and can get the right dbton_handler.
But the second link's  dbton_id is 0, and ha_spider.dbton_handler[0]=0, then the null point make the server crash.
Thanks,
Cheng

**Comment by svoj** [comment]
@Kentoku are there any updates on this PR?

**Comment by Kentoku** [comment]
I'm sorry for delayed.
Changes for spd_db_conn.cc are perfect! Please this patch under new BSD licence.
Please change mdev9254.test like the attached file, because this test can use default settings like other tests.
[mdev9254.zip](https://github.com/MariaDB/server/files/453931/mdev9254.zip)
Then OK to push.

Thank you for your contributing!

**Comment by svoj** [comment]
No feedback was provided for this pull request for over a month, so it is being closed. Feel free to reopen if you are able to implement requested changes.

**Pull request closed without merging**
