### PR TITLE
MDEV-22975: rocksdb: FreeBSD disable jemalloc search

### PR DESCRIPTION
**Pull request by grooverdan**
FreeBSD's inbuilt default jemalloc means its pointless
to do a package search on it. The paths are already set
by the system defaults.

Without this the build starts with:

-- Running cmake version 3.16.5
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- MariaDB 10.5.4
getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
-- Wsrep-lib version: 1.0.0
== Configuring MariaDB Connector/C
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find JeMalloc (missing: JeMalloc_LIBRARIES JeMalloc_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  storage/rocksdb/rocksdb/cmake/modules/FindJeMalloc.cmake:17 (find_package_handle_standard_args)
  storage/rocksdb/build_rocksdb.cmake:22 (find_package)
  storage/rocksdb/CMakeLists.txt:144 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/dan/build-mariadb-server-10.5/CMakeFiles/CMakeOutput.log".
See also "/home/dan/build-mariadb-server-10.5/CMakeFiles/CMakeError.log".
*** [cmake_check_build_system] Error code 1

make: stopped in /usr/home/dan/build-mariadb-server-10.5
1 error

make: stopped in /usr/home/dan/build-mariadb-server-10.5

Probably could be pushed back to 10.2 as it hasn't changed and maps to the commit 5875633c2a78.

This look ok @Sp1l ?

ATTN: @spetrunia

### CODE REVIEW

**Comment by grooverdan** [comment]
The final bit to get rockdb to compile and pass most MTR tests on FreeBSD is in the rocksdb submodule:

<pre>
mariadb-server-10.5]$ cd storage/rocksdb/rocksdb/
rocksdb]$ git diff
diff --git a/port/jemalloc_helper.h b/port/jemalloc_helper.h
index f6f72f8cb..c8c63dee0 100644
--- a/port/jemalloc_helper.h
+++ b/port/jemalloc_helper.h
@@ -30,7 +30,7 @@
 #define JEMALLOC_CXX_THROW
 #endif
 
-#if defined(OS_WIN) && defined(_MSC_VER)
+#if (defined(OS_WIN) && defined(_MSC_VER)) || defined(__FreeBSD__)
</pre>

To prevent the compile error:
<pre>
In file included from /home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/db/malloc_stats.cc:16:
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:58:19: error: redefinition of 'malloc_usable_size' as different kind of symbol
extern "C" size_t malloc_usable_size(JEMALLOC_USABLE_SIZE_CONST void*)
                  ^
/usr/include/malloc_np.h:71:8: note: previous definition is here
size_t  malloc_usable_size(const void *ptr);
        ^
In file included from /home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/db/malloc_stats.cc:16:
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:58:38: error: use of undeclared identifier 'JEMALLOC_USABLE_SIZE_CONST'
extern "C" size_t malloc_usable_size(JEMALLOC_USABLE_SIZE_CONST void*)
                                     ^
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:58:71: error: expected ';' after top level declarator
extern "C" size_t malloc_usable_size(JEMALLOC_USABLE_SIZE_CONST void*)
                                                                      ^
                                                                      ;
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:59:24: warning: declaration does not declare anything [-Wmissing-declarations]
    JEMALLOC_CXX_THROW __attribute__((__weak__));
                       ^
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:72:43: warning: comparison of function 'malloc_usable_size' not equal to a null pointer is always true [-Wtautological-pointer-compare]
         malloc_stats_print != nullptr && malloc_usable_size != nullptr;
                                          ^~~~~~~~~~~~~~~~~~    ~~~~~~~
/home/dan/mariadb-server-10.5/storage/rocksdb/rocksdb/port/jemalloc_helper.h:72:43: note: prefix with the address-of operator to silence this warning
         malloc_stats_print != nullptr && malloc_usable_size != nullptr;
                                          ^
                                          &
</pre>

**Comment by grooverdan** [comment]
Alternate version from upstream: https://github.com/facebook/rocksdb/commit/04abb2b2ddc308ab03f55ea9a1e08b62667d6e39

**Comment by an3l** [comment]
Should this be added to MDEV-12474 too?

**Comment by grooverdan** [comment]
its a fail to build rather than a test case failure that MDEV-12474 relates too. I'd suggest a new MDEV. I'm looking through a suite of rocksdb upstream fixes that might be possible/already fixed.

**Comment by an3l** [comment]
@grooverdan wrong PR, was thinking on 1598 `rocksdb.concurrent_alter` to add to MDEV-12474

**Pull request merged**
