### PR TITLE
Unix does not have ss command, replacing it with lsof

### PR DESCRIPTION
**Pull request by angeloudy**
OS like FreeBSD or Solaris do not have the command ss.

### CODE REVIEW

**Comment by grooverdan** [comment]
To avoid a uglier proliferation of greps for things lsof supports, will something like the follow work on FreeBSD/ Solaris?

`lsof -sTCP:LISTEN -i TCP:${PORT} -a -c nc -c socat -F c
`

Sample linux output:
`$ sudo lsof -sTCP:LISTEN -i TCP:22 -a -c sshd_not_exist -c sshd -F c
p5047
csshd
f3
`

**Comment by svoj** [comment]
Hi @angeloudy,

Thanks for your contribution!

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by angeloudy** [comment]
I confirm that all my contributions to the mariadb project are submitted under the BSD-new license.

**Comment by angeloudy** [comment]
@grooverdan  
It has the same output on FreeBSD. I just copied my lines from wsrep_sst_rsync.sh

**Comment by janlindstrom** [comment]
There was some issues using bash on FreeBSD and at least some Galera script was moved to use sh is that real ?

**Comment by angeloudy** [comment]
@janlindstrom 
So far I didn't find any issue with using bash on FreeBSD. But some commands work differently with GNU ones, such as find, tar

**Comment by angeloudy** [comment]
The following code removes everything in the datadir on FreeBSD because the usage of find regular expression is different.
`find $ib_home_dir $ib_log_dir $ib_undo_dir $DATA -mindepth 1  -regex $cpat  -prune  -o -exec rm -rfv {} 1>&2 \+`

**Comment by ari** [comment]
@grooverdan What's needed to get this fixed? It would be nice for FreeBSD to be fully supported by mariadb.

@janlindstrom  bash is not installed by default on FreeBSD. But if necessary, its not a problem to make it a dependency of the package. But is there a problem with just sh?

**Comment by grooverdan** [comment]
Fixed in #560 for sst_xtrabackup-v2 and will be corrected when MDEV-14030 is fixed (which plans to use the wsrep_sst_xtrabackup-v2 script). I think this can be closed for now. Thanks for the information that enabled the fix and the testing of alternatives.

@ari, @angeloudy, in the mean time can you support https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224270 getting fixed. Its rather horrible to work around and I'd rather not break FreeBSD in #556 for the mysqldump sst method.

**Pull request closed without merging**
