### PR TITLE
MDEV-16588 - MariaDB yassl AES acceleration on Arm64

### PR DESCRIPTION
**Pull request by guyuqi**
Accelerated AES with ARMv8 Crypto Extensions.
On A57 YaSSL Taocryt benchmark: got 7x performance improvement.
CXXFLAGS: -march=armv8-a+crypto

Change-Id: Ia9ca67755bb75030ba94a8cdc7555f6459978df8
Signed-off-by: Yuqi Gu <yuqi.gu@arm.com>

### CODE REVIEW

**Comment by svoj** [comment]
Hi @guyuqi,

Thanks for your contribution! It looks impressive, however we plan to remove yassl from our codebase: https://jira.mariadb.org/browse/MDEV-16475

Do you think it still makes to apply it?

Thanks,
Sergey

**Comment by guyuqi** [comment]
Hi @svoj,

Thanks for your comments!
You plan to remove yassl in 10.4 ,right?
Do you mind apply this patch to 10.3 which now also includes yassl?

BRs,
Yuqi

**Comment by svoj** [comment]
Hi @guyuqi,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-16588

This task was added to 10.3 backlog.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by guyuqi** [comment]
I've signed MCA and sent it to foundation@mariadb.org.
I submit this PR under the MCA. Thanks!

**Comment by svoj** [comment]
Hi @guyuqi 

Unfortunately your change was considered too intrusive for GA versions and given that yaSSL is getting removed we have to decline this PR.

You may consider contributing something similar to WolfSSL, which is what we're planning to switch to.

Thanks and sorry for this long delay,
Sergey

**Pull request closed without merging**
