### PR TITLE
test: innodb.innodb_mysql message changed

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by grooverdan** [comment]
Seems this was changed at some point:
<pre>
$ (cd mysql-test ; ./mtr innodb.innodb_mysql )
Logging: /home/dan/repos/mariadb-server/mysql-test/mysql-test-run.pl  innodb.innodb_mysql
vardir: /home/dan/repos/build-mariadb-server-10.2/mysql-test/var
Checking leftover processes...
Removing old var directory...
Creating var directory '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var'...
Checking supported features...
MariaDB Version 10.2.6-MariaDB
 - SSL connections supported
Collecting tests...
Installing system database...

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
innodb.innodb_mysql 'innodb'             [ fail ]
        Test ended at 2017-04-12 10:20:02

CURRENT_TEST: innodb.innodb_mysql
--- /home/dan/repos/mariadb-server/mysql-test/suite/innodb/r/innodb_mysql.result        2017-04-11 11:58:58.149580051 +1000
+++ /home/dan/repos/mariadb-server/mysql-test/suite/innodb/r/innodb_mysql.reject        2017-04-12 10:20:02.534028932 +1000
@@ -1547,7 +1547,7 @@
 set statement sql_mode = 'NO_ENGINE_SUBSTITUTION' for
 alter table t1 add index(a(1024));
 Warnings:
-Warning        1071    Specified key was too long; max key length is 767 bytes
+Note   1071    Specified key was too long; max key length is 767 bytes
 show create table t1;
 Table  Create Table
 t1     CREATE TABLE `t1` (

mysqltest: Result length mismatch

 - saving '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/log/innodb.innodb_mysql-innodb/' to '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var/log/innodb.innodb_mysql-innodb/'
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 52 seconds executing testcases

Failure: Failed 1/1 tests, 0.00% were successful.

Failing test(s): innodb.innodb_mysql

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

mysql-test-run: *** ERROR: there were failing test cases
</pre>

**Comment by grooverdan** [comment]
eventually fixed with 3849f8b2bb73ca481fd736763d72a009ca21c247

**Comment by dr-m** [comment]
Sorry, I did not notice this PR before doing my own fix. This was recently broken by MDEV-11995.

**Comment by grooverdan** [comment]
no worries. I wouldn't look in PRs for a test case failure either. I am surprised it lingered but I guess it was a busy last week. Also noted the buildbot automerge proposals means this shouldn't happen as much.

**Pull request closed without merging**
