### PR TITLE
MDEV-19204: RocksDB: use crc32c optimised version for POWER

### PR DESCRIPTION
**Pull request by grooverdan**
This copies the rocksdb submodule's CMakeLists.txt directives associated with enabling the CRC32C for rocksdb.

As both POWER8 and POWER9 cpus are on the market, the CFLAGS are checked against any existing CFLAGS before adding `-mcpu=power8` as the lowest supported POWER hardware.

While CMake tests against `ppc64` (big endian) this match ppc64le as well. Currently big endian architectures are disable due to a big endian problem.

While this is largely identical to the extra/crc32-vpmsum implementation, the rocksdb submodule doesn't allow an easy plugin of alternate implementations like this or #772.

### CODE REVIEW

**Comment by grooverdan** [comment]
I'm not patching in the submodule. RocksDB works on its own with the CMakeList.txt in the top level of the submodule. Within MariaDB this isn't used and its functionality was copied to build_rocksdb.cmake.

Yes, this is submitted under the MCA.

**Comment by grooverdan** [comment]
Please merge this. Its just a repacking of the RockDB upstream cmake as has been done for every other bit of the rocks storage engine.

**Comment by svoj** [comment]
Cherrypicked to 10.2 as 35522455e0c0d680a68609b2bb82e4321afce32f. Thanks and sorry for this delay.

**Comment by spetrunia** [comment]
(attempt at having a test for this is here: https://jira.mariadb.org/browse/MDEV-19608)

**Pull request closed without merging**
