### PR TITLE
MDEV-658: debian debug symbols require compat 9

### PR DESCRIPTION
**Pull request by grooverdan**
a one character patch with enablement :)

This is required so that the generation of dbgsyms can occur.

The meaning of the levels is here https://www.mankier.com/7/debhelper#Compatibility_Levels

The Debian manual recommends level 9 currently https://www.debian.org/doc/manuals/maint-guide/dother.en.html#compat

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-658

This task was added to 5.5 backlog, which hasn't been scheduled yet.

Thanks,
Sergey

**Comment by grooverdan** [comment]
This applies to 5.5, 10.0, and 10.1. 10.2 is already at compat 9. #380 has 10 scheduled for 10.3. I also note the debhelper man page suggests 10 instead of 9.

[~svoj] there have been two 5.5 releases since this. How are github commitments mapped to JIRA plans?

**Comment by svoj** [comment]
@grooverdan Normally I set "fix version" and priority>=major. It makes corresponding task to appear on corresponding dashboard, e.g. 5.5: https://jira.mariadb.org/secure/Dashboard.jspa?selectPageId=12200

This dashboard is reviewed weekly and normally developers pick tasks according to priority. There're many exceptions though, e.g. @ottok doesn't participate in sprints.

@ottok do you plan to work on this any time soon?

**Comment by svoj** [comment]
@grooverdan is this change actually required to fix issue described in MDEV-658? Is it going to work with all 5.5 builders?

FWICS relevant effects are:
* dh_strip compresses debugging symbol files to reduce the installed size of -dbg packages.
* dh_strip puts separated debug symbols in a location based on their build-id.

So there's no direct indication that this enables/disables debug symbols.

Also did you review other effects? Can't they brake anything?

**Comment by grooverdan** [comment]
I tested with Jessie/xenial which are beyond the supported version for 5.5 and there are no available debhelper back ports to earlier version so probably more trouble than its worth. So 5.5 is a bad target.

10.0 could be a good target. I noticed the server-core packages for 10.0 and 10.1 are about 4.2Mb compared to 10.2 at 59Mb and I haven't checked contents.

Other effects from the document between 5 and 9 are minor changes in behaviour none where harmful. I didn't notice any effects.

A 10 level would need to examine init script/systems behaviour is correct.

**Comment by vuvova** [comment]
I'll merge it into 5.5

(just checked all our debian builders should support compat=9)

**Comment by grooverdan** [comment]
thanks

**Pull request closed without merging**
