### PR TITLE
mariabackup utility, binary path implementation for Mac.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by grooverdan** [comment]
Looks good to me - library call available mac-10.5 (https://opensource.apple.com/source/xnu/xnu-2422.1.72/libsyscall/wrappers/libproc/libproc.h.auto.html)

**Comment by robertbindar** [comment]
Thanks for the patch @devnexen! You're very quickly becoming our macos guardian 🎉 
I would appreciate a lot in the future if you'd provide a shart description to the PR.

I looked at the code and it seems legit, but I fail to see what is failing for you that made you write the fix. Quickly from the code, I would guess it's either an error message that looks wrong or maybe even the tool failed to start.

**Comment by devnexen** [comment]
you are right it s not a fix but a little improvement mostly, the tool is not broken per say on mac.

**Comment by robertbindar** [comment]
Let me know when you have some spare time what the patch improves. For me for instance in 10.6, when I try to run mariabackup with no arguments, the `mysqld` instance that the tool tries to run hits a sigsegv, which is very wrong even if I pass the wrong arguments.

**Comment by devnexen** [comment]
There is indeed, even tough through the debugger it does not show. However, it s reproducible on Linux too with sanitizer.

**Comment by devnexen** [comment]
it s a casual overflow case, will try to provide a fix proposal.

**Comment by robertbindar** [comment]
Quick question before merging. I see you changed the base branch from 10.5 to 10.6. Is the bug not reproducible in mariadb 10.5?

**Comment by devnexen** [comment]
Oh I realized I rebased from 10.6 instead of 10.5 I wanted to see if eventually was fixed later on but chose the "wrong" branch. It s definitely reproducible in 10.5 as well. What I propose is after merging to backport it to 10.5 after ?

**Comment by robertbindar** [comment]
> Oh I realized I rebased from 10.6 instead of 10.5 I wanted to see if eventually was fixed later on but chose the "wrong" branch. It s definitely reproducible in 10.5 as well. What I propose is after merging to backport it to 10.5 after ?

I would love if we could add it in the smallest version possible, then it will be propagated upwards. Our upmerging processes are already huge animals and are eating immense chunks of time from senior developers, it's very recommended we respect their time and follow the usual development model so that when release comes, the number of problems is minimized.

Do you need it in 10.6 fast (meaning now)? I can totally cherry-pick it in 10.5 and push if you don't have time to rebase the PR to 10.5 yourself.

**Comment by devnexen** [comment]
Closing in favor of https://github.com/MariaDB/server/pull/1771

**Comment by robertbindar** [comment]
Pushed into 10.4 actually. The crashing bug was in 10.4 too, not in 10.2, 10.3

**Comment by devnexen** [comment]
oh you re fast ok will close the other one then

**Pull request closed without merging**
