### PR TITLE
Add HAVE_ISFINITE check to avoid warnings on OSX build

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by dr-m** [comment]
Related to this, maybe we should finally address
[MDEV-11500 Remove my_isinf() and HAVE_ISINF](https://jira.mariadb.org/browse/MDEV-11500). Does any contemporary platform actually lack the ISO/IEC 9899:1999 (C99) `isinf()` function?

**Comment by howard0su** [comment]
currently, we have #define isfinity(x) finity(x) which is fallback a C99 standard function to a deprectated one.

If we decide to use all C99 functions, we need remove this line as well.

**Comment by howard0su** [comment]
CHECK_SYMBOL_EXISTS(log2  math.h HAVE_LOG2)
 CHECK_SYMBOL_EXISTS(isnan math.h HAVE_ISNAN)
 CHECK_SYMBOL_EXISTS(rint  math.h HAVE_RINT)

these need remove as well since all these three functions are in C99.

i would vote just abandon this PR and let me clean up all these functions in a serial of PRs.

**Comment by vaintroub** [comment]
if a functionality is present on all current compilers/OSes, then checks for it can / should be removed, that's a lot better than improving checks

**Comment by svoj** [comment]
Let's start with finite/isfinite in 10.3. I can apply them and see if buildbot is satisfied with this change. The other checks lets address for 10.4. You can update this PR by force pushing into your fix_warnings branch.

I will be looking forward for PR update.

**Comment by howard0su** [comment]
sure. let me do that.

**Comment by svoj** [comment]
Hi @howard0su ,

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by howard0su** [comment]
Contribution is under BSD-new license.

**Comment by svoj** [comment]
Thanks! Merged to bb-10.3-svoj for testing. It'll appear in 10.3 soon if everything is fine.

**Pull request merged**
