### PR TITLE
Update MYSQL.USER system view by adding Slave_monitor_priv and numerous other missing permissions

### PR DESCRIPTION
**Pull request by dlenski**
In 4abb8216 ("MDEV-17658 change the structure of mysql.user table"; tagged in mariadb-10.4.1), the `MYSQL.USER` table was replaced with a view intended to contain equivalent columns, derived from the `MYSQL.GLOBAL_PRIV` table.

Subsequently, `MYSQL.USER` has not been updated at all, even as additional global privileges have been added to MariaDB.

Issues caused by this:

1) In a1e330de ("MDEV-21743 Split up SUPER privilege to smaller    privileges"; tagged in mariadb-10.5.2), the integer bitfield value of (1 << 20) was [changed from meaning `REPL_CLIENT_ACL` to `BINLOG_MONITOR_ACL`](https://github.com/MariaDB/server/commit/a1e330de5a37f88339f4a5b46231a41eb60f43d2#diff-05ae88f636371a3917b74f3880fb50fc2fc389f9e0988641d2733413317b8f59R52), while new bitfield values corresponding to finer-grained privileges were added.

   However, the `MYSQL.USER.Repl_client_priv` column was not renamed.

   For anyone who has been relying on the meaning of this column since MariaDB <10.5.2, this column now contains completely misleading information!

2) Several additional privilege bits have been added since 10.5.2 (see https://github.com/MariaDB/server/blob/5cc9cf9a05582307abefd8f3b57548945da86b1a/sql/privilege.h#L62-L70).

   A recent example:

   In 6da68049 ("MDEV-23610: Slave user can't run "SHOW SLAVE STATUS" anymore after upgrade to 10.5, mysql_user_upgrade should take care of that"; tagged in mariadb-10.5.9), the new 'SLAVE MONITOR' privilege was added with the integer bitfield value of (1 << 38).

   However, the `MYSQL.USER` system view wasn't updated to have a `Slave_monitor_priv` column. It is therefore impossible to verify if a user actually has this privilege, or any of the other privileges added in MariaDB >=10.5.2, by inspecting this view.

This patch:

* **(Addresses 1)** Renames the `MySQL.USER.Repl_client_priv` column to `Binlog_monitor_priv`, reflecting its changed purpose.
* **(Addresses 2)** Updates the creation of the `MYSQL.USER` system view to include all of the permissions added since MariaDB 10.5.2, and replaces the ascending power-of-2 integer literals with a more human-auditable form of `(1 << n)` (e.g.  `16777216` → `1 << 24`).

This patch retains the preexisting names and meanings for all of the preexisting columns of `MYSQL.USER`, with the important exception of the `Repl_client_priv` column which will no longer exist.  Because no such permission has actually existed since 10.5.2, it seems less misleading to remove this column altogether, rather than leave behind some kind of placeholder. However, this will not be 100% backwards-compatible with all existing queries on `MYSQL.USER`, which is why this patch targets the next
major release, 10.7.

All new code of the whole pull request, including one or several files that are
either new files or modified ones, are contributed under the BSD-new license. I
am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by dlenski** [comment]
One potential response to this patch is that the `MYSQL.USER` view was *intentionally* frozen as of MariaDB 10.4.1, and that users should not rely on it being updated, but instead use `MYSQL.GLOBAL_PRIV` or `SHOW GRANTS`.

A few thoughts on that:

* The intention to freeze or deprecate `MYSQL.USER` is not documented anywhere. (https://mariadb.com/kb/en/mysqluser-table does not mention any freezing or deprecation.)

   In fact `sql/privilege.h` still contains a comment indicating that `MYSQL.USER` in `mysql_system_tables.sql` must be updated whenever the privilege bitfields are updated; clearly this has been ignored since MariaDB 10.5.2.
* In the case of `MYSQL.USER.Repl_client_priv`, a subsequent change to the privilege bitfields has changed the *actual meaning* of this column totally, so that its name and [documentation](https://mariadb.com/kb/en/mysqluser-table/) are now misleading. So we cannot even say that `MYSQL.USER` has actually been frozen in terms of its meaning.
* It is difficult for end-users to replace usage of `MYSQL.USER` with `MYSQL.GLOBAL_PRIV`. Determining global user privileges from `MYSQL.GLOBAL_PRIV` means knowing the meaning of the bitfield values from `sql/privilege.h`. Understanding these values should be a developer concern, rather than an end-user concern. Discontinuing updates to `MYSQL.USER` would mean pushing the burden of knowing these values from the developers to the end-users.

    For example, a MariaDB administrator might have longstanding queries used to find MariaDB users who can create other users, or run `SHOW {MASTER,SLAVE} STATUS`:

   ```
   select count(*) from mysql.user where Create_user_priv = 'Y' or repl_client_priv='Y';
   ```

   Running this query on MariaDB 10.5.2+, the `Repl_client_priv` has a completely unexpected meaning due to (2) above. And in order to replace this with an equivalent query that uses `GLOBAL_PRIV` and gives the intended results on MariaDB 10.5.2+, the DBA would need to look at `sql/privilege.h` and find the bitfield values for `CREATE_USER_ACL` and `SLAVE_MONITOR_ACL`.

**Comment by vuvova** [comment]
The main goal of moving to json-backed `mysql.global_priv` was to never ever run `mysql_fix_privilege_tables.sql` on it. You can see in that file that the history of `mysql.user` was quite eventful — new columns were added all the time, existing columns were renamed, made longer, charsets changed here and there. This created bugs too, they had to be fixed, adding new `ALTER TABLE` lines to that file.

We didn't want to continue doing it. Ever again. Flexible json structure of `mysql.global_priv` allowed us to add new privileges, account locking and expiration and multi-authentication — all without a single `ALTER TABLE` in upgrades.

And `mysql.user` was supposed to be frozen the day it was created. For basically the same reason, to break the vicious circle of ALTER's on every upgrade. If we start updating it to accommodate new features, it'll go on forever, we'll never be able to stop.

Adding new privileges to `mysql.user` won't help existing users with existing applications, it's only for *new* applications that know of new privileges and new columns. And this is precisely what we'd like to avoid, new application using obsolete table.

Why wouldn't you use `INFORMATION_SCHEMA.USER_PRIVILEGES` table? This is the documented way of checking privileges for a user, it will always work and will always show all privileges.

**Comment by dlenski** [comment]
@markus456 wrote:

> One case where you still need the `mysql` tables is when you're using roles as they don't show up in `INFORMATION_SCHEMA.USER_PRIVILEGES`. If you use roles to define grants for users, the data stored in there is somewhat useless for determining the actual grants the user has by default.

That is a very good point. It's another reason why the `mysql.user` view really remains the only adequately succinct "_single_ source of truth" on the privileges that a user has.

**Comment by dlenski** [comment]
I am still hoping to get more review and feedback on this PR.

I'd like to summarize the key points for why I believe `mysql.user` **should be updated** despite the previous intention to deprecate it:

* Developers may have _intended_ to deprecate `mysql.user`, but this was not clearly communicated in release notes, nor updated in the documentation until [after I pointed it out](https://github.com/MariaDB/server/pull/1926#issuecomment-939110295).
* `mysql.user` currently has a very misleading column, `repl_client_priv`, which now describes the `binlog monitor` privilege rather than the `replication client` privilege (ever since a1e330d → 10.5.2)
* `mysql.user` doesn't include columns for new permissions added since 10.5.2, but there is no reason it could not; you have the code to do it right here in this PR.
* Checking/verifying the newer user-level permissions added since 10.5.2 requires a wholly different query structure:
  * Previously, a user's permissions could be verified with something like `select count(*) from mysql.user where user=? and host=? and first_priv = 'Y' and (second_priv = 'Y' or other_priv = 'Y')`.
  * Checking the new permissions added in 10.5.2+ requires `select … from information_schema.user_privileges`, which has a different structure that makes it much more complicated to `AND`/`OR` verification of multiple permissions.
  * I gave a more detailed example in [my previous comment](https://github.com/MariaDB/server/pull/1926#issuecomment-941244608).

**Comment by dlenski** [comment]
I discussed this with @montywi, who asked me to confirm that `mysqladmin` continues to work correctly with the updated version of `mysql.user`.

The answer is **yes**. I applied the changes to `mysql.user`, and verified numerous sub-commands of `mysqladmin` against it: `processlist`, `flush-user-statistics`, `flush-user-resources`, `flush-privileges`, `extended-status`, `status`, `ping`, `create db`, `drop db`, `password`, `old-password`.

For example:

```
$ build/bin/mysqladmin --socket /tmp/tmp.dt1IGrgR4v/mysql.sock processlist
+----+---------+-----------+-------+---------+------+----------+------------------+----------+
| Id | User    | Host      | db    | Command | Time | State    | Info             | Progress |
+----+---------+-----------+-------+---------+------+----------+------------------+----------+
| 3  | dlenski | localhost | mysql | Sleep   | 122  |          |                  | 0.000    |
| 7  | dlenski | localhost |       | Query   | 0    | starting | show processlist | 0.000    |
+----+---------+-----------+-------+---------+------+----------+------------------+----------+
```

**Comment by ottok** [comment]
This has been open for 9 months now. It is broken both on stable releases and also latest dev release still lacks this fix.

If you don't want to fix this as a bug, but rather as a new feature to complete the 'transition' of `mysql.user` table, do you @vuvova want this to be rebased on 10.10? Or perhaps some comments from @grooverdan ?

**Comment by dlenski** [comment]
I have just:

- Rebased on the latest `10.7`
- Added another commit to fix up the MTR results to reflect the updated `mysql.user`

If core devs would like to merge this, I'll combine the two commits. Just keeping them separate to aid in review+rebasing until it's actually ready to merge.

**Comment by dlenski** [comment]
@LinuxJedi, this is the PR I mentioned on our discussion today. Just rebased on latest 10.7.

**Comment by LinuxJedi** [comment]
> @LinuxJedi, this is the PR I mentioned on our discussion today. Just rebased on latest HEAD of 10.7 branch. (Let me know if you want it retargeted.)

Many thanks. We will definitely need this re-targeted to what will be the next major release version (the version number is currently undecided so there is no branch for it at time of writing). Something to note as well, it causes the `main.plugin_auth` test to fail due to a number of columns change, it will likely you will need to run `mtr` on this test with `--record`.

**Comment by dlenski** [comment]
@LinuxJedi, thanks, I'll fix up the tests and re-`--record` once there's a specific branch to target.

**Comment by dlenski** [comment]
@LinuxJedi, since we discussed "where to target PRs" on our call today… I would make the case for this one being a bugfix that should be applied to everything from 10.4 going forward. :grin:

**Comment by LinuxJedi** [comment]
Instead of a long I_S query can you not do something like this?:

```sql
select host, user from mysql.global_priv where (JSON_VALUE(Priv, '$.access') & 33554432) and ((JSON_VALUE(Priv, '$.access') & 16) or (JSON_VALUE(Priv, '$.access') & 32));
```

From a usability point of view I think it would be nice to have a pivot table or function to parse these numbers.

Either way, I have discussed this internally and `mysql.user` is intended to stay frozen, there more for legacy applications / usage.

The `Repl_client_priv` fix should happen probably, so my recommendation is:

1. Open that part as a new PR.
2. Consider a JIRA ticket to create a new thing which will make the `access` column in `global_priv` easier to parse.
3. If there is any better way of doing this that does not affect `mysql.user` (such as a new I_S table? I don't know), create a JIRA ticket for this to be discussed.
4. Help us improve documentation around this.

**Comment by dlenski** [comment]
> Instead of a long I_S query can you not do something like this?:
> 
> ```sql
> select host, user from mysql.global_priv where (JSON_VALUE(Priv, '$.access') & 33554432) and ((JSON_VALUE(Priv, '$.access') & 16) or (JSON_VALUE(Priv, '$.access') & 32));
> ```

That requires the user to…

1. Know that `mysql.global_priv` exists (new in 10.4.1)
1. Understand the JSON manipulating functions (new in 10.something)
1. Know the values of the privilege bitfields (undocumented and easy to mis-type)
1. Know that `mysql.user` got frozen in 10.4 (**undocumented** until [after I opened this PR](https://github.com/MariaDB/server/pull/1926#issuecomment-939143757))

There's a ton of backwards incompatibility and UX difficulty there.

_None of it is necessary_, since the `mysql.user` view can relatively easily be kept up-to-date with newer privilege bits in `global_priv`, as I've done here.
 
> From a usability point of view I think it would be nice to have a pivot table or function to parse these numbers.

`mysql.user` almost literally _is_ the pivoted version of `mysql.global_priv`.

> Either way, I have discussed this internally and `mysql.user` is intended to stay frozen, there more for legacy applications / usage.

I still do not understand this decision. What is the justification for not updating it in a fully backwards-compatible way, as I've done here?

> The `Repl_client_priv` fix should happen probably, so my recommendation is:
> 
>     1. Open that part as a new PR.
> 
>     2. Consider a JIRA ticket to create a new thing which will make the `access` column in `global_priv` easier to parse.
> 
>     3. If there is any better way of doing this that does not affect `mysql.user` (such as a new I_S table? I don't know), create a JIRA ticket for this to be discussed.
> 
>     4. Help us improve documentation around this.

That's a lot of new work that will, in my opinion, result in a much worse end-state than simply making the backwards-compatible updates to `mysql.user`, as I've done here.

**Comment by LinuxJedi** [comment]
> That requires the user to…
> 
> 1. Know that `mysql.global_priv` exists (new in 10.4.1)
> 2. Understand the JSON manipulating functions (new in 10.something)
> 3. Know the values of the privilege bitfields (undocumented and easy to mis-type)
> 4. Know that `mysql.user` got frozen in 10.4 (**undocumented** until [after I opened this PR](https://github.com/MariaDB/server/pull/1926#issuecomment-939143757))

That is all documentation issues, which absolutely should get fixes, apart from the bitfield, which should get a pivot table or function to decode.

> There's a ton of backwards incompatibility and UX difficulty there.

I don't see how freezing a table makes things backwards incompatible. If you mean tools that use `mysql.user` will need to use `global_priv` or `I_S` instead, then there is only one supported version of MariaDB where that isn't the case. That will be zero supported versions in 4 months time.

If the documentation is improved and something new exists such as a pivot table or function, then I don't see a UX issue either.

> _None of it is necessary_, since the `mysql.user` view can relatively easily be kept up-to-date with newer privilege bits in `global_priv`, as I've done here.

As Sergei mentioned, `mysql.user` is frozen. It is there for legacy usage only. The more that changes, the more complicated things get for upgrades, it is not easy to keep up to date. If you look at the upgrade script, which would need changing as well, you can see this.

> > From a usability point of view I think it would be nice to have a pivot table or function to parse these numbers.
> 
> `mysql.user` almost literally _is_ the pivoted version of `mysql.global_priv`.

Sort-of, but not quite. It is pivoted to some extent to remain compatible with legacy applications.

> > Either way, I have discussed this internally and `mysql.user` is intended to stay frozen, there more for legacy applications / usage.
> 
> I still do not understand this decision. What is the justification for not updating it in a fully backwards-compatible way, as I've done here?

I think Sergei explain it pretty well in his second comment, there really isn't much to add here. It isn't really about backwards-compatibility (whilst that is important). It adds another step in upgrades scripts (which are painful), this is the whole reason the `global_priv` table exists.

**Comment by ottok** [comment]
This was closed because MariaDB rejected the bugfix on the grounds that the mysql.user table is "frozen".

The additional feedback would require a complete rewrite of this submission. We might do that another day in another PR, but we will keep this PR here in current for for anybody who wants to have the bugfix patch applied on their build of MariaDB.

**Pull request closed without merging**
