### PR TITLE
MDEV-14639: Fix unexpected end of line at 'Normal shutdown'

### PR DESCRIPTION
**Pull request by sjmudd**
See: https://jira.mariadb.org/browse/MDEV-14639. This should remove the unwanted blank line.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @sjmudd,

Since JIRA issue is targeted for 5.5, could you resubmit this PR for 5.5 as well? Or should I cherry-pick
this patch myself?

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by sjmudd** [comment]
Hi. I'm not sure how this workflow works. My PR is against the 10.3 branch even if probably the same change can be pushed against other branches. I'm happy for this to be cherry picked to wherever makes sense.

I'll also check the licensing thing and update here once I've done that.

**Comment by sjmudd** [comment]
I confirm that I am contributing your new code of the whole pull request under the BSD-new license.

**Comment by svoj** [comment]
Ok, then I'll cherry-pick this to 5.5 and let you know when it is done.

**Comment by svoj** [comment]
Pushed cfa18e4ae11e77579ee7c577356ed7b4f874c8c7 to 5.5. Thanks!

**Pull request closed without merging**
