### PR TITLE
Utilize the INSTALL_PCDIR CMake option also for server pkgconfig file

### PR DESCRIPTION
**Pull request by FaramosCZ**
First step in MDEV-14340

### CODE REVIEW

**Comment by FaramosCZ** [comment]
Submitted under MCA

**Comment by FaramosCZ** [comment]
There is a long term problem that the pkgconfig file is considered as arch-dependent in Fedora, Debian and RHEL.

I think the propper fix should look simmilar to what's in the "libmariadb/cmake".
This PR is a quick enhancement that preserves the default behaviour, while fixing our issue.

**Comment by LaurianoElmiroDuarte** [comment]
where o i post bugs ?
thankfull

**Comment by ottok** [comment]
Thanks for your interest in MariaDB and contributing!

The commit message is quite brief. What are you trying to accomplish here? Just introduce a new variable INSTALL_PCDIR but not use it anywhere in the code base (just in your own builds)?

The fact that the file is installed in a wrong directory is a universal problem and correct handling of multi-arch files should be implemented. Adding a new build option just bloats the code in my opinion.

What do you think, should we maybe go with https://github.com/MariaDB/server/pull/597 instead?

**Comment by ottok** [comment]
I suggest this should be dismissed and #597 used to achieve the same thing instead.

**Comment by cvicentiu** [comment]
Hi @FaramosCZ !

A combination of PRs #597, and #910 were used to achieve (hopefully) the result you were looking for.

The commits for these are:

f21592c675e198ba6298748b40e5d695a17f4e5f (10.1) - slightly unrelated, fixing something within the packageconf file.
c5c1027c6eb0db9738c231731b664f9736970d98 (10.2) - Moving the packageconf file within the libdir folder. With appropriate defines during cmake, one can place the file where desired.
fd2dc9c3fdfb73fa450db9fecd72044bb0554040 (10.3) - Merging some of debian downstream packaging into MariaDB to better support multi-arch builds.

Thank you for spending time on this and I apologize for having this take so long to correct.

**Comment by cvicentiu** [comment]
And if you think that the solution that I proposed is not enough, let me know and I'd gladly consider extending it. Note that all these commits will reach 10.4 and newer versions.

**Pull request closed without merging**
