### PR TITLE
MDEV-19168: Add ssl-flush command.

### PR DESCRIPTION
**Pull request by KartikSoneji**
Re-opens #1555 

Closes #MDEV-19168

Includes tests.

### CODE REVIEW

**Comment by grooverdan** [comment]
You can't move flush error message to the top level. What about everything else in mysql_query that returns non 0, are they all going to gain an addition flush error message?

**Comment by KartikSoneji** [comment]
Hi @grooverdan 
Thanks for looking at this.

I am not sure I understand the issue.  
I moved the error printing into the `flush` function, which does not appear to be used outside `mysqladmin.cc`.
```diff
 int flush(MYSQL *mysql, const char *what)
 {
   char buf[FN_REFLEN];
   my_snprintf(buf, sizeof(buf), "flush %s%s",
               (opt_local && !sql_log_bin_off ? "local " : ""), what);
-  return mysql_query(mysql, buf);
+
+  if (mysql_query(mysql, buf))
+  {
+    my_printf_error(0, "flush %s failed; error: '%s'", error_flags, what,
+                    mysql_error(mysql));
+    return -1;
+  }
+  return 0;
 }
```

Moving the error printing into the function eliminates a lot of duplicate code like
```diff
@@ -938,173 +941,111 @@ static int execute_commands(MYSQL *mysql,int argc, char **argv)
     case ADMIN_FLUSH_LOGS:
     {
       if (flush(mysql, "logs"))
-      {
-   my_printf_error(0, "flush failed; error: '%s'", error_flags,
-           mysql_error(mysql));
    return -1;
-      }
       break;
     }
     case ADMIN_FLUSH_BINARY_LOG:
     {
       if (flush(mysql, "binary logs"))
-      {
-        my_printf_error(0, "flush failed; error: '%s'", error_flags,
-                        mysql_error(mysql));
         return -1;
-      }
       break;
     }
     case ADMIN_FLUSH_ENGINE_LOG:
     {
       if (flush(mysql, "engine logs"))
-      {
-        my_printf_error(0, "flush failed; error: '%s'", error_flags,
-                        mysql_error(mysql));
         return -1;
-      }
       break;
     }
```

**Comment by grooverdan** [comment]
My apologizes, I misread this.

**Comment by KartikSoneji** [comment]
No problem 👍

**Pull request merged**
