### PR TITLE
MDEV-11412: Backporting to 10.2 and small adjustments

### PR DESCRIPTION
**Pull request by a-novikau**
- [x] *The Jira issue number for this PR is: MDEV-11412*

## Description
As a user, I expect that a table will be fully dropped from the database when I issue a `DROP TABLE` statement, no matter of it's underlying state. However in case of absent .frm file MariaDB couldn't determine a storage engine for the table.
This problem was documented in [MDEV-11412](https://jira.mariadb.org/browse/MDEV-11412) and the fix was released in 10.5.4.

This PR is backports the fix from 10.5 to earlier 10.2.
The following commits are cherry-picked from 10.5:
- 5bcb1d65
- 346d10a9
- 4080e3ac
- dfb41fdd

In addition there is a commit adapting the code for 10.2 specifically.

## How can this PR be tested?

The most impactful change is related to `mysql_rm_table_no_locks` method. Please note that this change was already shipped with MariaDB 10.5.4 and it has not caused any known regressions so far.

A good testing scenario was previously introduced in `drop_table_force.test`. It was adjusted along with 22 other MTR tests to reflect the current state of the engine, which provides a good test coverage for this change.

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

Please note that similar patches for 10.3 and 10.4 have already been prepared. I am submitting this for 10.2 first to get feedback/acknowledgement before I submit the PRs for 10.3 and 10.4.

Since 10.3 introduces `SEQUENCE`, some code was removed from the original commits being backported to 10.2, which means the implementation as I'm suggesting cannot be directly merged to a later major version.

If MariaDB maintainers are willing to accept the change please keep that in mind and let me know what is the preferred course of action in order to get it delivered to 10.2-10.4. If you prefer, I can submit the PR for 10.4 and 10.3 so those can be merged before this 10.2 version.

## Copyright

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by a-novikau** [comment]
@montywi will you be able to review the change?
Thank you!

**Comment by a-novikau** [comment]
Hi! Can you please take a look or reassign the pull request? @montywi @cvicentiu
Thanks!

**Comment by ottok** [comment]
This was submitted in August and we haven't hade any proper review yet. @montywi mentioned on IRC yesterday that he don't want this for 10.2 but please note this in the PR:
> If MariaDB maintainers are willing to accept the change please keep that in mind and let me know what is the preferred course of action in order to get it delivered to 10.2-10.4. If you prefer, I can submit the PR for 10.4 and 10.3 so those can be merged before this 10.2 version.

Please advice on how you want to proceed with backporting MDEV-11412 to 10.4/10.3/10.2. Code already exists for all branches but progress is halted due to lack of review/guidance.

**Comment by vuvova** [comment]
This was a comparatively big and intrusive feature to implement. 10.2 is a very old and stable GA release. We generally do not want to do big changes in old GA releases to avoid destabilizing them. Many users use MariaDB 10.2 for almost five years, they clearly don't have this DROP TABLE problem with their old applications, and they wouldn't want any disruptive changes.

It's safest to say that if one wants new DROP TABLE behavior, one should upgrade to 10.5+

**Comment by ottok** [comment]
Ok, so no for 10.2 but if a patch for 10.4 is submitted with tests and
everything you could perhaps review it?

The main reason you fixed it only in 10.5+ is that you did not have
bandwidth to do it for all releases that have the bug.

But if the base work is done for you and you only have to review, it would
be great, right?

**Comment by vuvova** [comment]
The main reason it was done in 10.5 was because 10.5 was the trunk at the moment, and we generally do new features in the trunk. Not related to bandwidth.

We generally, as a rule, implement new features in the trunk and do not backport them to "oldstable" versions. Exceptions are possible, of course, for example, we've added OpenSSL 1.1 support to the trunk and then backported it — otherwise stable MariaDB versions wouldn't even compile anymore. But this does not look like one of those cases. MariaDB will not become unusable if we won't backport MDEV-11412, it'll work as before.

**Comment by montywi** [comment]
I am now working on the review of the above

**Comment by ottok** [comment]
FYI @a-novikau: @montywi notified my on Zulip that the review of this PR is in branch https://github.com/MariaDB/server/commits/10.2-force_drop - see Github compare view at https://github.com/MariaDB/server/compare/66752c02232585ef79bf2b6e302a33bac992f07d...10.2-force_drop

**Comment by grooverdan** [comment]
Based on Monty's response in MDEV-11412, closing this as won't fix.

**Pull request closed without merging**
