### PR TITLE
MDEV-17467: Tried to create a dummy to start this task

### PR DESCRIPTION
**Pull request by Weijun-H**
- [x] *The Jira issue number for this PR is: MDEV-17467*

## Description
I tried to extend a dummy function which always returns 0. But I met this error
```
CURRENT_TEST: main.func_dummy
mysqltest: At line 5: query 'SELECT DUMMY(1)' failed: <Unknown> (2013): Lost connection to server during query
```

## How can this PR be tested?
I wrote a very simple test to test this dummy, but it failed to pass.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
TODO: fill details here, if applicable, or remove the section

### CODE REVIEW

**Comment by Weijun-H** [comment]
I really want to know how to add a native function in MariaDB, could someone give me some hints about it?

**Comment by grooverdan** [comment]
An example of a simple function add cd16d6d518761d144844f9f6294744f2aa42c715

**Comment by Weijun-H** [comment]
Hi, everyone. I have a question about the aggregation function entry. I have figured out the native function mechanism, they are defined in `Item_create.cc` and use `{ { STRING_WITH_LEN("ABS") }, BUILDER(Create_func_abs)}` to define the entry . But how does MariaDB define the entry of the aggregation function and where could I find them? I have no idea about it after researching, could you give me some advice?

**Comment by grooverdan** [comment]
Going to close this. Github PRs aren't a great discussion forum. Lets stick to https://mariadb.zulipchat.com

**Pull request closed without merging**
