### PR TITLE
Remove unused French translations in Connect engine

### PR DESCRIPTION
**Pull request by anson1014**
## Description
Per discussion with Andrew Hutchings on an earlier version of this PR (see [#2224](https://github.com/MariaDB/server/pull/2224#issuecomment-1233215405)), these files are currently not being used nor compiled in MariaDB. The use of large lists of 'case' statements in these source files are also not a great way of representing translated strings. This git history can be referred to when a better translation interface can be implemented in the future.

Therefore, in order to make the encodings used in the MariaDB codebase
more consistent, these files are removed since they are not at all used.

Additional discussion regarding the implementation and justification of this PR can be seen here:

#2224 

#2188 

## How can this PR be tested?

1. These files are currently not used nor are they being compiled during the build process. Because of this, removing these files have no effect on MariaDB.

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Copyright

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by dlenski** [comment]
These French translations appears to have existed in the MariaDB repository since "time immemorial".

They're included in d7143a4160d093abecf911de4084d5dd3aa3be92, where the CONNECT engine sources were first imported into this repository from some external source.

**Comment by anson1014** [comment]
@LinuxJedi, a re-review would be much appreciated!

**Review by dlenski — APPROVED** [review]

**Review by LinuxJedi — APPROVED** [review]
Excellent, many thanks!

**Comment by dlenski** [comment]
Awesome! Less ambiguously-dead code = easier maintainability.

**Pull request merged**
