### PR TITLE
MDEV-10298: Systemd hardening

### PR DESCRIPTION
**Pull request by candrews**
Add ProtectSystem=full, NoNewPrivileges=true, PrivateDevices=true, and ProtectHome=true to the systemd units.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Craig,
 
Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-10298
 
This task was added to 10.1.16 backlog, which hasn't been scheduled yet.
 
Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.
 
The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/
 
Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
 
Thanks,
Sergey

**Comment by svoj** [comment]
@grooverdan, could you review this patch?

**Comment by knielsen** [comment]
Sergey Vojtovich <notifications@github.com> writes:

> Similar to other open source projects, the MariaDB Foundation needs to
> have shared ownership of all code that is included in the MariaDB
> distribution. The easiest way to achieve this is by submitting your
> code under the BSD-new license.
>  
> The other alternative is to sign the code contribution agreement which
> can be found here: https://mariadb.com/kb/en/mariadb/mca/

As was concluded in this mailing thread,

  https://lists.launchpad.net/maria-developers/msg09606.html

the third option is to contribute the code under GPLv2. Personally, I would
strongly recommend to contribute under GPLv2 only. There are good and
important reason why the GPL exists and why it is used by many of the most
successful free software projects. Most of the code by core developers is
contributed to the project under GPLv2 only, as is most of the major
external contributions.

Svoj, please update your "contributer request template" to mention
prominently the GPLv2 option, and use it in all future cases. eg:

-----------------------------------------------------------------------
Similar to other open source projects, the MariaDB Foundation needs to have
the right to include and re-distribute under the GPL all code that is
included in the MariaDB distribution. The easiest way to achieve this is by
submitting your code under the same license as the MariaDB source code,
GPLv2.

The other alternatives are to submit under the BSD-new license, or to sign
the code contribution agreement which can be found here:
https://mariadb.com/kb/en/mariadb/mca/. These alternatives both provide
further rights for the MariaDB Foundation and its members to use the code in
your contribution, including the rights to submit it for inclusion in Oracle
MySQL or to use it commercially in proprietary products.

Please indicate in a comment below that you are contributing your new code
of the whole pull request, including one or several files that are either
new files or modified ones, under the GPLv2 license, under the BSD-new
license, or that you have filled out the contribution agreement and sent it.
-----------------------------------------------------------------------

Thanks,

 - Kristian.

**Comment by candrews** [comment]
I don't think any nation's law would consider this to be a significant enough, or unique enough, contribution to be copyrightable. But in any case, I'll pick the bsd-new license to be able to move on :-)

**Comment by grooverdan** [comment]
Looks ok to me. The only thing to consider is which systemd version introduced each of these and how does this match to the distro package versions.

PrivateDevices - Technically innodb can run on a raw block device but I've never seen it done. For those that use it this way the user can always remove these settings by overriding it in their systemd config as documented already.

ProtectHome might have an effect if a user puts datadir on /home or similar however its override-able and I think its worth adding.

**Comment by candrews** [comment]
Regarding overrides, that's my thinking too - exceptional users can add overrides.

Regarding systemd versions... If an option is used that systemd isn't aware of, it'll just ignore it. So there's no harm if the user is using an older version of systemd that doesn't support an option specified.

**Comment by vuvova** [comment]
Will --memlock option continue to work? server does some uid juggling for it (start as root, change to mysql user, start engines, switch back to root, memlock, switch again to mysql). NoNewPrivileges won't allow that, will it?

**Comment by svoj** [comment]
We fixed that juggling to work with systemd already: https://github.com/MariaDB/server/commit/27e6fd9a596847a1a4c618d16ed43f6885dfe73a

**Comment by svoj** [comment]
Merged https://github.com/MariaDB/server/commit/53e7fcca4191c47ca48c378163bcb93ef6e632a5

**Comment by grooverdan** [comment]
In systemd we just start as mysql (https://github.com/MariaDB/server/blob/10.1/support-files/mariadb.service.in#L42) and have the capabilities for memlock added in 27e6fd9.

**Pull request closed without merging**
