### PR TITLE
Fix bash expansion issue in wsrep_sst_rsync

### PR DESCRIPTION
**Pull request by jdel**
Related to https://github.com/docker-library/mariadb/issues/126

### CODE REVIEW

**Comment by svoj** [comment]
Hi Julien,

Thanks for your contribution!

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by svoj** [comment]
Why did you change file mode? It's not supposed to be executable.

**Comment by jdel** [comment]
@svoj 

Apologies for the permission change, for some reason `git checkout -b wsrep-sst-rsync-fix` changed all permissions to 755 on my branch. This is now fixed by 4544a00.

I see that you added the 10.2 milestone, please bear in mind that 10.3 shows the same behaviour.

All code in this pull request is under BSD-new license.

**Comment by svoj** [comment]
Thanks! This will be merged to 10.3 eventually.

**Pull request merged**
