### PR TITLE
Fix RocksDB detection of ZSTD

### PR DESCRIPTION
**Pull request by ottok**
The library finder needs to have capitals in its name so that FIND_PACKAGE
will load the correct finder and actually detect that libzstd is available.

Without this change the CMake would just always silently skip ZSTD since
it would never find it.

This fixes regression from 97b563b5dbfce9dccf5a9e8204272e26d9e414a1
on branch 10.3.

Also remove QUIET from the RocksDB FIND_PACKAGE call so that it is easier
to read in build logs what libraries were detected. Also add missing
underscores to error messages.

### CODE REVIEW

**Comment by ottok** [comment]
Another related commit: https://github.com/MariaDB/server/commit/d565895bbd8e2a163be48b9bac51fccbf3949c80

I fixed this for 10.5 already 3 weeks ago in https://github.com/MariaDB/server/pull/1582 but decided to make this new PR targetting 10.3 since this regressed on stable releases and should be fixed.

**Comment by ottok** [comment]
MariaDB 10.4 in Debian had autopkgtests that detected this error:
image

This patch has now been applied in Debian. Please apply upstream. @vuvova

**Comment by vuvova** [comment]
Sorry, I've already cherry-picked your commit from #1582 into 10.3

**Comment by Neo888888** [comment]
BUG REPORT: ubuntu 18.04, apt install latest 10.5.4, 10.4.13, NO ZSTD SUPPORT!!!

**Pull request closed without merging**
