### PR TITLE
correct FSF address

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
@iangilfillan could you rebase and merge?

**Comment by grooverdan** [comment]
Why rebase? comment only changes so branch shouldn't matter and no merge conflicts.

**Comment by svoj** [comment]
"Rebase and merge" is github PR button, which does roughly rebase and push. I wonder how 10.2 version was chosen? Why not 5.5 or 10.3?

**Comment by grooverdan** [comment]
Why 10.2 - mainly was going of MDEV-14267 as a patch against 10.2. It got hit because of rpm-lint and no-one else seemed to care. 10.2 also chosen because all of the files existed at this point rather than splitting parts for earlier version (so laziness really :-) ).

**Comment by grooverdan** [comment]
Approved and not merged in 6 months.

**Pull request merged**
