### PR TITLE
MDEV-14448 - Changed mariadb-client so as to not exit upon receiving SIGINT

### PR DESCRIPTION
**Pull request by BACtaki**
Bug: https://jira.mariadb.org/browse/MDEV-14448
Windows cases need work

### CODE REVIEW

**Comment by svoj** [comment]
Hi @BACtaki,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-14448

This task was added to 10.3 backlog.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by BACtaki** [comment]
Hi @svoj , thanks for your feedback.

I am contributing code under the BSD-new license. Please let me know if you need anything else from me regarding licensing. 

Regarding the pull request, I am happy to say that I finally have a functional Windows dev environment. I will run and fix the Windows cases, if necessary, in the next iteration. I will also address the Travis check failure then.

**Comment by an3l** [comment]
Hi @BACtaki 
sorry for delay, we are now reviewing your patch.
Do you want to update this patch to support windows as well and to rebase please to latest 10.3?

**Comment by an3l** [comment]
Hi @BACtaki,
please do `git config --list` to check and rename your name and/or email. 
Currently is
```
From 35f8521daf13c0572246d37bcbcd6bc65e0c5dad Mon Sep 17 00:00:00 2001
From: Ubuntu
 <bachow@ubuntuVM.qhiapodhaaxuhksfs3tvgxgbkf.xx.internal.cloudapp.net>
Date: Sun, 15 Apr 2018 23:46:54 +0000
Subject: [PATCH] changed mysql-client so as to not exit upon receiving SIGINT,
 windows needs work
```

**Comment by an3l** [comment]
This patch is port of mysql patch which is under GPLv2 and as such I'm closing it.

**Comment by vuvova** [comment]
to be continued in #1308

**Pull request closed without merging**
