### PR TITLE
MDEV-21228: mariadb-conv man page

### PR DESCRIPTION
**Pull request by iangilfillan**

### CODE REVIEW

**Comment by an3l** [comment]
Thanks @iangilfillan

**Comment by cvicentiu** [comment]
Hi @an3l !

I think this PR needs to also update debian packaging files. Can you please put this in your TODO, try and figure out how it's done and if you need help, ping me?

**Comment by aheacon** [comment]
HI @cvicentiu, I think this is already finished with 
https://github.com/MariaDB/server/pull/1460/files#diff-7967362e5080e22514dac29f8e9de25eR18

**Comment by an3l** [comment]
Hi @cvicentiu ,
I think this is done already with https://github.com/MariaDB/server/pull/1460/files#diff-7967362e5080e22514dac29f8e9de25eR18

**Pull request merged**
