### PR TITLE
10.4 without server 20200316

### PR DESCRIPTION
**Pull request by jadenChoo**
When build&compile with -DWITHOUT_SERVER=ON option using mariadb-10.4.11, i found two error.
First is my_global.h. 
When compile hs_client/hstcpcli.cpp, "my_global.h" is not found. So i changed ./cmake/plugin.cmake to using "INCLUDE_DIRECTORIES~~" on client install mode.
Last is wsrep_sst_rsync_wan.
I knew "wsrep~~" is require to server, but copmile is failed because making symbolic link "wsrep_sst_rsync_wan". So i changed ./scripts/CMakeLists.txt. What relating to wsrep is moved to "IF(NOT WITHOUT_SERVER)"

### CODE REVIEW

**Comment by an3l** [comment]
Hi @VictorChoo,
thanks for patch. 
Please change the base of PR to `10.4` instead of `10.5`, since you have latest commit (2b3f6ab417a116d213c24ed506b2) from `10.4` at top.

**Comment by an3l** [comment]
Hi @VictorChoo,
Why have you created new PR for `10.5` ( PR #1470 ), is it better than this one? 
You should just change base of PR from `10.5` to `10.4`.

**Comment by VictorChoo** [comment]
Hi @an3l 
Just dependency. I also think it is not related, but i was afraid. So i changed 10.4->10.5 , cleared my local source, and re-push&pull request.
How i should do if it will be confirmed?

**Comment by an3l** [comment]
So you have tested on 10.4 and found the bug and raised a PR against 10.5?
Did you test on earlier versions ?

**Comment by vaintroub** [comment]
> When compile hs_client/hstcpcli.cpp, "my_global.h" is not found. 

It should not be compiling hs_client or whatever is under storage or plugin subdirectory.
Server is not compiled, means plugins should not be compiled either
Instead of changing plugin.cmake, you can do something like 

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 59444ffd1c8..157c9a9f2bc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -403,7 +403,9 @@ SET (MYSQLD_STATIC_PLUGIN_LIBS "" CACHE INTERNAL "")
 INCLUDE(mariadb_connector_c) # this does ADD_SUBDIRECTORY(libmariadb)

 # Add storage engines and plugins.
-CONFIGURE_PLUGINS()
+IF(NOT WITHOUT_SERVER)
+  CONFIGURE_PLUGINS()
+ENDIF()

 ADD_SUBDIRECTORY(include)
 ADD_SUBDIRECTORY(dbug)

**Comment by vaintroub** [comment]
@VictorChoo , and the same is true for scripts subdirectory. You do not want it  WITHOUT_SERVER, or do you? if you do not want, because there is nothing useful in there
  IF(NOT WITHOUT_SERVER)
    ADD_SUBDIRECTORY(scripts)
  ENDIF()

does help

**Comment by VictorChoo** [comment]
@an3l Correct! I tested on 10.4.11 on RHEL 7.6

**Comment by VictorChoo** [comment]
_Server is not compiled, means plugins should not be compiled either_
@vaintroub I agree with your opinion. so i changed plugins is not compiled. And i'll test your suggestion code.
And, i wanted to install just clients. I executed "cmake -DWITHOUT_SERVER=ON"

**Comment by VictorChoo** [comment]
> > When compile hs_client/hstcpcli.cpp, "my_global.h" is not found.
> 
> It should not be compiling hs_client or whatever is under storage or plugin subdirectory.
> Server is not compiled, means plugins should not be compiled either
> Instead of changing plugin.cmake, you can do something like
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 59444ffd1c8..157c9a9f2bc 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -403,7 +403,9 @@ SET (MYSQLD_STATIC_PLUGIN_LIBS "" CACHE INTERNAL "")
>  INCLUDE(mariadb_connector_c) # this does ADD_SUBDIRECTORY(libmariadb)
> 
>  # Add storage engines and plugins.
> -CONFIGURE_PLUGINS()
> +IF(NOT WITHOUT_SERVER)
> +  CONFIGURE_PLUGINS()
> +ENDIF()
> 
>  ADD_SUBDIRECTORY(include)
>  ADD_SUBDIRECTORY(dbug)
> ```

This code is cool than me! It's work very well

**Comment by an3l** [comment]
Pushed to `10.3` with 863e28ff3ed0a5859561c397cbfb492170989ddd.

**Pull request closed without merging**
