### PR TITLE
MDEV-23091: perfschema Add support for OpenBSD's getthrid() to retrie…

### PR DESCRIPTION
**Pull request by brad0**
…ve the thread id

### CODE REVIEW

**Comment by an3l** [comment]
@brad0 thanks for the patch.
@grooverdan the similar patch was pushed recently for `10.5`, `HAVE_PTHREAD_GETTHREADID_NP` fecc6caa27971bd9c049671ddedef8c334e71062, [MDEV-22621](https://jira.mariadb.org/browse/MDEV-22621) so assigning to you.

**Comment by grooverdan** [comment]
is the following for the header required?
```
#ifdef HAVE_GETTHRID
#include <unistd.h>
#endif
```

**Comment by brad0** [comment]
No. The code builds fine as is with no implicit declaration of function warnings.

**Comment by brad0** [comment]
Can this please be commited? This is still broken with 10.5.5.

**Comment by brad0** [comment]
ping.

**Comment by grooverdan** [comment]
Thanks for the PR @brad0 

Merged to be in the next 10.5 release.

**Pull request merged**
