### PR TITLE
MDEV-4537 - Update of innotop on debian/additions

### PR DESCRIPTION
**Pull request by jb-boin**
Picked last version from https://github.com/innotop
More informations : https://jira.mariadb.org/browse/MDEV-4537

### CODE REVIEW

**Comment by ottok** [comment]
I've adopted this PR as https://github.com/ottok/mariadb-10.1/commit/b4c4c5d0800fc61c3c6dcd7c3204a47ab2f7fe23 in the official Debian/Ubuntu repository.

**Comment by svoj** [comment]
@ottok so you approve this change? What kind of adoptions did you have to do?

**Comment by svoj** [comment]
Hi Jean,

Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-4537

This task was added to 10.1.22 backlog, which is planned to be handled between 2017-03-03 and 2017-03-10.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by jb-boin** [comment]
I contribute the new code of the whole pull request under the BSD-new license.

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
