### PR TITLE
MDEV-15026 - Mariadbbackup: read the same server groups

### PR DESCRIPTION
**Pull request by grooverdan**
Currently only the xtrabackup and mysqld groups are read.
Its quite possible the user has put their server options in
a different group and mariadb will grab the wrong details.

Leverage off the server load_default_groups to populate this list.
This becomes particularly important with Galera SST scripts.

Despite the description and name, defaults_group has always been
an additional group. Change its help text to reflect this.

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for you contribution! I added this task to our 10.1 queue: https://jira.mariadb.org/browse/MDEV-15026

Thanks,
Sergey

**Comment by vaintroub** [comment]
grooverdan, can you give an example where mariabackup could go wrong? I consider possibly stop reading options during backup, except [xtrabackup] ones, since server variables can be read from the server directly, with "show variables". We do this in important cases already.

**Comment by grooverdan** [comment]
Ah, i missed where the variables where read by mariabackup directly from the server. Sorry about that. I assuming it was still reading from file and 

> [mariadb-10.1]
> innodb...=something

 would be missed.

**Comment by vaintroub** [comment]
Let's close it for now.  During backup, mariabackup should read parameter from server. During prepare, it should not use other parameters than the ones in backup-my.cnf . I'd rather stay compatible to xtrabackup than to change behavior.

**Pull request closed without merging**
