### PR TITLE
MDEV-4581 / MDEV-4682 plugin - qc_info - add Query Cache flags

### PR DESCRIPTION
**Pull request by grooverdan**
Still confused why CHARACTER_SET_CLIENT  got returned as the numeric 8.

Every other test case result as expected.

I discovered this was a reimplementation of #6 so I stopped.

### CODE REVIEW

**Comment by rspadim** [comment]
hi guy :) i can help you, i did this changes
you are getting a old patch by the way, there're more 2 tables to include in query cache plugin

**Comment by rspadim** [comment]
https://mariadb.atlassian.net/secure/attachment/22421/diff_10_0_3_qc_info.cc

two tables:
QUERY_CACHE_QUERIES_TABLES    (what table a query used - usefull to get errors inside query cache code like wrong partitioning numbering information)
and
QUERY_CACHE_TABLES

**Comment by rspadim** [comment]
about #6, it include some statistics at query table, and it rename query table too

but i don't know if we should include it or not, it works without problems... but the problem is:

IMHO statistics is enabled / disabled at compile type (using the current patch), but should be nice to enable/disable at runtime

at runtime we need another strutucture just to stats, i don't know how to do this :(   (help is wellcome here)

anyway if you want to include the patch with runtime compile must be interesting turn off stats switch to production mariadb version:
"+#define HAVE_QUERY_CACHE_STATS 1"  at file config.h.cmake line 598

**Comment by vuvova** [comment]
Looks good. I've rebased it on top of 10.1 and pushed into bb-10.1-serg, will later push into 10.1

**Pull request closed without merging**
