### PR TITLE
Fix markdown headings in auth_gssapi README

### PR DESCRIPTION
**Pull request by adaugherity**
## Description
Section headings should be h2 rather than h1, and GitHub requires an intervening space to render the MarkDown.

AFAICT this is the only MarkDown file in the repo with this issue.

## How can this PR be tested?
View the file in GitHub before and after the change.  Not really suitable to automated testing.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

Not sure which to check here as it's a simple documentation fix.

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Review by grooverdan — APPROVED** [review]

**Comment by LinuxJedi** [comment]
Hi @adaugherity, thank you for this contribution. As this is a fix rather than a new feature, it should go in the oldest affected release. In this case that is 10.5. Would you like to do this rebase, or shall we do it for you?

**Comment by adaugherity** [comment]
Please go ahead and rebase to the appropriate branch.  Thanks!

Do I really need to sign the CLA for such a trivial change?

**Comment by grooverdan** [comment]
A "changes are contributed under the BSD-new license" declaration is sufficient. 10.5 as target branch.

**Review by LinuxJedi — APPROVED** [review]
Many thanks! Approved! Just need your declaration as @grooverdan mentioned and we can go ahead and merge this.

**Comment by adaugherity** [comment]
I contribute my changes under the BSD-new license.

**Pull request merged**
