### PR TITLE
MDEV-25808: Integer overflow when using PREPARE/EXECUTE on Spider

### PR DESCRIPTION
**Pull request by yongxin-xu**
- [x] *The Jira issue number for this PR is: MDEV-25808*

## Description
how to repeat:
On Spider Storage Engine:
```sql
CREATE TABLE t1 (
  `c1` bigint(20) UNSIGNED DEFAULT NULL
)ENGINE=SPIDER PARTITION BY LIST (`c1` MOD 4)
(PARTITION `pt0` VALUES IN (0)....);

insert into t1(c1) values (6800281190650363904), (17864960750176564435);

mysql> PREPARE p1 FROM 'select * FROM t1 WHERE c1 = ?';
Query OK, 0 rows affected (0.05 sec)
Statement prepared

mysql> EXECUTE p1 USING 17864960750176564435; # BUG HERE
Empty set (0.11 sec)

mysql> SELECT * FROM t1 WHERE c1 = 17864960750176564435; # CORRECT HERE
+----------------------+
| c1                   |
+----------------------+
| 17864960750176564435 |
+----------------------+
1 row in set (0.01 sec)
```

## How can this PR be tested?
The test files are included in the patch.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

This is a bug in the Spider Storage Engine that can be easily reproduced.

### CODE REVIEW

**Comment by vuvova** [comment]
Thanks. This is indeed a bug in a server. A simple test case:
```sql
prepare p1 from 'select concat(?)';
execute p1 using 17864960750176564435;
```
this prints `-581783323532987181`

Your change seems to be too complex, a simpler fix would be
```diff
--- a/sql/item.cc
+++ b/sql/item.cc
@@ -4680,7 +4680,7 @@ String *Item_param::PValue::val_str(String *str,
     str->set_real(real, NOT_FIXED_DEC, &my_charset_bin);
     return str;
   case INT_RESULT:
-    str->set(integer, &my_charset_bin);
+    str->set_int(integer, attr->unsigned_flag, &my_charset_bin);
     return str;
   case DECIMAL_RESULT:
     if (my_decimal2string(E_DEC_FATAL_ERROR, &m_decimal, 0, 0, 0, str) <= 1)
```

Note, that while this is, likely, enough for Spider, this is not enough for the server, this fixes only the case of an integer parameter in the string context.

But because all other cases are of no relevance to you, I can fix them all myself, instead of asking you to amend your patch. Is it ok?

**Comment by yongxin-xu** [comment]
@vuvova Sure, no problem.

**Comment by vuvova** [comment]
In fact. I found only one other case, integer in a real context:
```sql
prepare p1 from 'select SQRT(?)';
execute p1 using 17864960750176564435;
```

**Comment by yongxin-xu** [comment]
It looks like both `String *Item_param::PValue::val_str()` and `double Item_param::PValue::val_real() const` should deal with the `unsigned_flag`.

**Comment by vuvova** [comment]
`val_str()` already has a `Type_std_attributes *attr` that carries the unsigned flag. It's already used, for example, in `val_decimal()`.

`val_real()` doesn't have it, so I've added it in 59a29d13386

**Comment by an3l** [comment]
Pushed with https://github.com/MariaDB/server/commit/eaae13059f413647f8a406b52f212d70dca69661 to 10.3. Thanks

**Pull request closed without merging**
