### PR TITLE
MDEV-19160 JSON_DETAILED output unnecessarily verbose 

### PR DESCRIPTION
**Pull request by Weijun-H**
- [x] *The Jira issue number for this PR is: MDEV-19160*

## Description
Represents JSON in the most understandable way emphasizing nested structures.
## How can this PR be tested?
The test files locate at `func_json_detailed.test` and `func_json_detailed.result`

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Review by Weijun-H — COMMENTED** [review]
complete JSON_DETAILED based on the existing code

**Comment by LinuxJedi** [comment]
Hi @Weijun-H,

I'm attempting to assist in get pull requests that are stuck moving again. For this to be reviewed can you please rebase it against the latest development branch (currently 10.11). I can then make sure someone looks at it.

Many thanks!

**Comment by Weijun-H** [comment]
> Hi @Weijun-H,
> 
> I'm attempting to assist in get pull requests that are stuck moving again. For this to be reviewed can you please rebase it against the latest development branch (currently 10.11). I can then make sure someone looks at it.
> 
> Many thanks!

Hi @LinuxJedi , do you mean to move the implementation to the current version (10.11)?

**Comment by Weijun-H** [comment]
> Hi @Weijun-H,
> 
> I'm attempting to assist in get pull requests that are stuck moving again. For this to be reviewed can you please rebase it against the latest development branch (currently 10.11). I can then make sure someone looks at it.
> 
> Many thanks!

I have rebased the code to 10.11 now.

**Pull request closed without merging**
