### PR TITLE
MDEV-19755: Switch Perl DBI scripts from DBD::mysql to DBD::MariaDB driver

### PR DESCRIPTION
**Pull request by pali**
Perl DBD::MariaDB driver is available CPAN and is already used in
production environment.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @pali,
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by pali** [comment]
BSD-new license is fine for me.

**Comment by vaintroub** [comment]
Why would that be a good idea?

**Comment by pali** [comment]
Hi @vaintroub! DBD::mysql has broken Unicode support and their older versions are incompatible with MariaDB client 10.2+. DBD::MariaDB is there with Unicode support and fixes which were not possible to do in DBD::mysql. Also it supports MariaDB 10.4.

**Comment by vaintroub** [comment]
I dunno, our statement in the past was  that we are compatible with popular drivers that work with MySQL.
I'm not sure this means that we should switch away from popular Perl driver, because if we stop working with it , perhaps it would be harder to notice, if there are no tests for it.

**Comment by pali** [comment]
DBD-MariaDB is also mentioned in MariaDB documentation: https://mariadb.com/kb/en/library/perl-dbi/

**Comment by grooverdan** [comment]
@dveeden are you aware of these character set issues?

**Comment by pali** [comment]
Done!

**Comment by robertbindar** [comment]
Merged with 5cc2096f93b7f130b36f8bc0fc43440db9a848e4. Thanks!

**Comment by pali** [comment]
Great!

Could you also update links on https://mariadb.com/kb/en/library/perl-dbi/ "Documentation" and "DBD-MariaDB driver" to points to up-to-date version? Currently they refer to the version 1.00, but new versions were released.

"Documentation" to always last version has URI https://metacpan.org/pod/DBD::MariaDB and
"DBD-MariaDB driver" has (unversioned) URI https://metacpan.org/release/DBD-MariaDB

**Comment by robertbindar** [comment]
Done! https://mariadb.com/kb/en/library/perl-dbi/ Many thanks!

**Pull request closed without merging**
