### PR TITLE
Misc Travis-CI fixes, including making it faster and run less but more relevant jobs

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by grooverdan** [comment]
#1469 fixes s390x. Reverting without even pinging someone to fix it is a bit rude.

**Comment by ottok** [comment]
Yes, https://github.com/MariaDB/server/pull/1469 fixes s390x builds. Good!

Also https://github.com/MariaDB/server/pull/1467 needs to be merged first so that the deb builds work in this branch.

I reverted the old changes because both the .travis-ci.yml itself looked like a mess and the commit messages also looked bad (two after each other, the second fixing the first that was a mess to start with), so I got the impression that it the whole thing is a mess and the path to better quality required reverting. Yes, it is a bit rude and I apologize, but breaking the CI is not only rude but critically endangering the quality of the code base, and it already deteriorated as we witnessed in this short time as people started overlooking the failures as they seemed permanent (and thus missed the new failures).

**Comment by grooverdan** [comment]
A review /merge process need to highlight the benefits of swashing commits. Thanks for getting the CI green again, its a good goal, and hopefully its status as such will encourage basics corrections in case of failure. I just repinged some s390 folks about the WolfSSL issue.

**Comment by ottok** [comment]
You mean squashing? All these commits are atomic and server their own function. Any one of those can be reverted independently if it turns out they were bad.

**Comment by ottok** [comment]
I am considering rebasing and fine tuning some of this commits in this PR, and anyway #1467 needs to go in 10.5 first. Please share your review comments here but don't merge this yet.

**Comment by ottok** [comment]
#1467 needs to go in 10.5 first, after that I have to completely rewrite this PR unfortunately.. but the ideas in here will still be implemented, just in a different form

**Comment by cvicentiu** [comment]
@ottok #1467 is in, feel free to rework this commit and I'll review it as soon as it's done.

**Comment by ottok** [comment]
OK, this is now ready for review and merge @vladbogo 
image

**Comment by ottok** [comment]
Total run-time seems to depend wildly on general Travis-CI load:
image

**Comment by ottok** [comment]
Current 10.5 branch execution time is 10h hours:
image

I recommend prioritizing merging this so the build time drops 50%.

**Pull request merged**
