### PR TITLE
MDEV-22010: mtr search for mariadbd first

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @grooverdan, can you please rebase on the latest 10.5 and check failing tests and update them (some are `shutdown`, `mysqld--help-aria`)?

**Comment by vuvova** [comment]
This is part of https://jira.mariadb.org/browse/MDEV-22010 (not MDEV-21303)

**Comment by an3l** [comment]
Thanks @grooverdan .

**Comment by grooverdan** [comment]
Thanks for the merge

**Comment by grooverdan** [comment]
To cleanup the warnings #1493 is needed.

Rather important as the previous killed a far too many BB builds
http://buildbot.askmonty.org/buildbot/grid?category=main&branch=10.5

**Pull request merged**
