### PR TITLE
Systemd notify only - no socket activation

### PR DESCRIPTION
**Pull request by grooverdan**
@svoj 

TODO: more testing on packaging

is fc0e419 too dodgy as work around for http://public.kitware.com/Bug/view.php?id=14782. I could manipulate settings to avoid this using distro version.

changed OPTIONS to EXTRA_ARGS to be closer to compatible to percona systemd script
 ( https://github.com/percona/percona-xtradb-cluster/blob/5.6/build-ps/rpm/mysql@.service )

### CODE REVIEW

**Comment by svoj** [comment]
I merged everything but CPackRPM workaround to https://github.com/MariaDB/server/tree/bb-systemd. Also I adjusted a couple of things.

What are the other options to workaround CPackRPM bug?

**Comment by grooverdan** [comment]
> What are the other options to workaround CPackRPM bug?

install it as a non @ filename and rename it in a post install script

Could install a separate mariadb_bootstrap.service - will be different from Percona and means user customisation will affect the main server service and not the bootstrap.

remove the multi instance version (and hence mariadb@bootstrap). 

probably distributing the cmakeRPM of the earliest supported cmake (2.8) version would of been better.

**Comment by svoj** [comment]
From the above options anything but distributing CMakeRPM is acceptable. If Percona has such file, how did it workaround this issue?

Why mariadb-bootstrap.conf is installed as wsrep-new-cluster.conf in debian scripts and as it's original name otherwise?

**Comment by svoj** [comment]
Why SYSTEMD_SYSTEM_CONFDIR is unused?

**Comment by grooverdan** [comment]
Percona seems to rely on spec files:
* https://github.com/percona/percona-xtradb-cluster/blob/5.6/build-ps/percona-xtradb-cluster.spec#L675

I'll get an error to generate if building with a broken cpackRPM and systemd enabled.

Will clean up the consistencies with Debian too.

**Comment by svoj** [comment]
@grooverdan, please note that I continue development of systemd in bb-systemd, it has quite a few fixes already. Also I rebase and adjust commits and do git push --force now and then.

**Comment by grooverdan** [comment]
ack. I'll just did a merge. A fairly heavy modification of the debian packaging hit 10.1 that I've merged. Have set up VMs to test packaging more. Will keep pushing here as I fix stuff.

**Comment by grooverdan** [comment]
all merged

**Pull request closed without merging**
