### PR TITLE
sql_statistics - initialize all of io_cache

### PR DESCRIPTION
**Pull request by grooverdan**
Other members apart from buffer of the io_cache
where not initialized. Use bzero to init them all.

Found by Coverity (id 1409633)

I submit this under the MCA.

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @grooverdan!

Thanks for the contribution.

I've reviewed the patch and there is no reason to even initialize the buffer to NULL in the first place. All the initializing happens during the init call, which for this class always happens after construction. If you want, you can submit a pull request that deletes the row entirely and I'll merge that :)

Thanks,
Vicentiu

**Comment by svoj** [comment]
I believe ```my_b_clear()``` in ```Stat_table_write_iter``` should stay. At least until ```rowid_buf``` is allocated before ```open_cached_file()```.

```my_b_clear()``` in ```Stat_table_write_iter::cleanup()``` seem to be excessive: ```close_cached_file()/end_io_cache()``` does this.

But I don't see any point in initialisation of other members of io_cache. FWICS all relevant code is guarded by my_b_inited().

**Comment by grooverdan** [comment]
So it seems nothing much was actually required.

I've done a bit of a rebase to skip the while loops if the init fails. This previously would of happened if open_cached_file succeeded.

Overall the change is not that important. So close if its too hard.

A MTR is running here https://app.codeship.com/projects/217781/builds/26809734?pipeline=374868c1-c92c-4306-ac72-c309838339dd.

**Comment by svoj** [comment]
This is kind of what I meant semantically. I'd simplify syntax though.

But I'm not sure regarding cleanup() removal. It allows to release resources earlier, which is good.

I leave final decision up to @cvicentiu.

**Comment by grooverdan** [comment]
The cleanup/destructor needed to happen before the table close hence the nested (though original cleanup function was probably easier to follow).

MTR --big-test succeeded and appoligies for link, didn't realise contents weren't public.

**Comment by svoj** [comment]
We discussed this issue with @cvicentiu recently. One of alternative options that we came up with was removing ```Stat_table_write_iter```. As a replacement we should implement much simpler ```Stat_table``` method.

But I wonder if @spetrunia had any other potential use cases for this iterator?

**Comment by grooverdan** [comment]
not required. initialization complete via human static analysis.

**Pull request closed without merging**
