### PR TITLE
MDEV-22023 Update man pages titles to say MariaDB instead of MySQL

### PR DESCRIPTION
**Pull request by PhysicsTing**
## Description
When reading the man page of e.g. 'mysql' on a system with MariaDB installed one would actually see the man page of 'mariadb'. However the man page had no indication of the page being for 'mariadb', which was confusing for users.

Fix this by updating the man page title lines to use mariadb-* instead of mysql* for MariaDB binaries that are drop-in replacements for MySQL equivalents, indicating that the commands are actually of the MariaDB version.

In long term, all the commands in man pages should be replaced by their MariaDB counterparts. Update the title lines as a start, and only those that exist as symlinks to their MariaDB counterparts.

Before:

    man mariadb-upgrade | head -n 1
    MYSQL_UPGRADE(1) ...

After:

    man mariadb-upgrade | head -n 1
    MARIADB-UPGRADE(1) ...

## How can this PR be tested?
Only man pages are changed so it is not amenable to test automation. However mtr main suite still runs and passes. Also man pages are read using man tool to verify that the outputs are as expected.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
Target 10.5 which was when that MariaDB names became default.

## Copyright
All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by grooverdan** [comment]
Thanks @PhysicsTing. It seems we've got out of date in updating the major version in the headers too.

@iangilfillan I'd be ok in moving this back to 10.6. What do you think?

**Comment by grooverdan** [comment]
We're going to push this back to 10.5 after the release which was when that MariaDB names became default.

**Comment by PhysicsTing** [comment]
Hi @grooverdan. Thanks for taking a look. Just to confirm, should I re-base and target my PR against 10.5, or do you plan to accept it as is and then back port it to 10.5?

**Comment by grooverdan** [comment]
That would be appreciated. So desired actions:
* A rebase to 10.5
* Edit the major version in the man page titles to 10.5 (and I'll deal with the changes as I merge up).
* I'm not a big fan of changing dates on man page headers unless we actually change the content so please leave these unchanged.
* Including the MDEV in your commit message.
* and repush (branch name will need to be the same, despite the misleading branchname),
* and re-target (editing target branch in pr title to 10.5) would be appreciated.

**Comment by PhysicsTing** [comment]
Thank you @grooverdan for the clarifying the details. I have re-pushed the changes and updated the PR to target 10.5.

**Review by dlenski — APPROVED** [review]

**Pull request merged**
