### PR TITLE
Typo Errors Fixed like essensially->essentially

### PR DESCRIPTION
**Pull request by rajat123456**
Here I am contributing my new code of the whole pull request, including one modified file with 1 commit, under the BSD-new license .

### CODE REVIEW

**Comment by svoj** [comment]
@rajat123456 

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by svoj** [comment]
Note that #525 was submitted against 10.2, while this PR is submitted against 10.3. Hope that's fine, I don't have branch preference.

**Comment by rajat123456** [comment]
Yes, sure it is submitted against 10.3

**Comment by rajat123456** [comment]
@svoj which BSD License, either BSD 2-clause or the  BSD 3-clause?

**Comment by rajat123456** [comment]
Ok, fine got it, it's BSD 3-clause :)

**Comment by svoj** [comment]
BSD-new is 3-clause

**Comment by rajat123456** [comment]
Yup, I have created the license

**Comment by svoj** [comment]
No-no, please remove that last commit. You just need to state it here in a comment.

**Comment by svoj** [comment]
Like in #523.

**Comment by rajat123456** [comment]
Here I am contributing my new code of the whole pull request, including one modified file with 1 commit, under the BSD-new license .

**Comment by rajat123456** [comment]
Stated above

**Comment by svoj** [comment]
Pushed 7a66e0ab8f52f3bd32850463daa05f9a2401e6b1. Thanks!

**Pull request closed without merging**
