### PR TITLE
MDEV-30843: Add Extended descriptions to compat packages

### PR DESCRIPTION
**Pull request by illuusio**
- [x] *The Jira issue number for this PR is: MDEV-30843*

## Description
Currently Debian package: `mariadb-client-compat` and `mariadb-server-compat` are missing Extended description which leads to Lintian error:
 * extended-description-is-empty

Commit orders Description to same as rest of the Debian control file does.

Commit also fix Debian Lintian error:
 * obsolete-relation-form-in-source

## How can this PR be tested?
Build with `debian/autobake-debs.sh` and run `lintian *.deb`. There should not be:
 * E: mariadb-client-compat: extended-description-is-empty
 * E: mariadb-server-compat: extended-description-is-empty
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-client-compat) Conflicts mariadb-client (< 11.0.0) [debian/control:563]
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-client-compat) Conflicts mariadb-client-core (< 11.0.0) [debian/control:563]
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-client-compat) Conflicts mariadb-server (< 11.0.0) [debian/control:563]
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-client-compat) Conflicts mariadb-server-core (< 11.0.0) [debian/control:563]
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-server-compat) Conflicts mariadb-server (< 11.0.0) [debian/control:857]
 * E: mariadb source: obsolete-relation-form-in-source (in section for mariadb-server-compat) Conflicts mariadb-server-core (< 11.0.0) [debian/control:857]

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*

## Backward compatibility
Should not affect make more compatible with Debian packaging rules

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

### CODE REVIEW

**Review by ottok — APPROVED** [review]
Looks good to me!

Do you have a link to the Salsa CI run of this commit, did it improve or regress?

**Comment by illuusio** [comment]
> Looks good to me!
> 
> Do you have a link to the Salsa CI run of this commit, did it improve or regress?

Didn't have time this week to fetch it in Salsa. I'll do it and post link to run. Tested manually and remove all the Lintian problems besides that changelog thing.

**Comment by ottok** [comment]
> > Looks good to me!
> > Do you have a link to the Salsa CI run of this commit, did it improve or regress?
> 
> Didn't have time this week to fetch it in Salsa. I'll do it and post link to run. Tested manually and remove all the Lintian problems besides that changelog thing.

Why do you need time to do that? The same `git push` here can go to your Salsa fork without any additional work.

What was the URL of your MariaDB fork on Salsa? What does `git remote -v` show on your local machine you run `git push` on? I can help you with the exact commands on how to push two multiple remotes.

**Comment by grooverdan** [comment]
https://salsa.debian.org/grooverdan/mariadb-server/-/pipelines/524488 "mariadb-10.3 with Buster backports upgrade job: undefined need: build buster-backports"

**Comment by illuusio** [comment]
> https://salsa.debian.org/grooverdan/mariadb-server/-/pipelines/524488 "mariadb-10.3 with Buster backports upgrade job: undefined need: build buster-backports"

I've been fixing this Salsa-CI build thing and will PR soon.

**Pull request merged**
