### PR TITLE
MDEV-16937 Strict SQL with system versioned tables causes issues

### PR DESCRIPTION
**Pull request by midenok**
Vers SQL: respect system fields in NO_ZERO_DATE mode.

This is the subject for refactoring in tempesta-tech/mariadb#379

This code is submitted under the BSD-new license.

### CODE REVIEW

**Comment by midenok** [comment]
[Buildbots passed](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.3-MDEV-16937)

**Comment by vuvova** [comment]
Here I'd rather go towards having VERS_SYS fields more like generated columns. They **are** generated columns from the user point of view, they are generated, technically. The only difference — they are `NOT NULL` while other generated columns are always nullable, for now. That and VERS_SYS fields always have `field->vcol_info == NULL`. 

Fixing this would be a separate task.  But for now I'd fix this bug not by allowing invalid defaults for VERS_SYS columns, but by adding the check where vcols have it. That is:
```
--- a/sql/field.cc
+++ b/sql/field.cc
@@ -11001,7 +11001,7 @@ Column_definition::Column_definition(THD *thd, Field *o>
 
     - The column didn't have a default expression
   */
-  if (!(flags & (NO_DEFAULT_VALUE_FLAG | BLOB_FLAG)) &&
+  if (!(flags & (NO_DEFAULT_VALUE_FLAG | BLOB_FLAG | VERS_SYSTEM_FIELD)) &&
       old_field->ptr != NULL && orig_field != NULL)
   {
     if (orig_field->unireg_check != Field::NEXT_NUMBER)
```
here vcols are always nullable, so VERS_SYSTEM_FIELD needs a separate check. And also I'd set NO_DEFAULT_VALUE_FLAG for them, and that'll avoid all checks for the default value.

I'm afraid the flag has to be set when reading the frm, to take care of already existing tables:
```
--- a/sql/table.cc
+++ b/sql/table.cc
@@ -2015,9 +2015,9 @@ int TABLE_SHARE::init_from_binary_frm_image(THD *thd, boo>
     if (versioned)
     {
       if (i == row_start_field)
-        flags|= VERS_SYS_START_FLAG;
+        flags|= VERS_SYS_START_FLAG | NO_DEFAULT_VALUE_FLAG;
       else if (i == row_end_field)
-        flags|= VERS_SYS_END_FLAG;
+        flags|= VERS_SYS_END_FLAG | NO_DEFAULT_VALUE_FLAG;
 
       if (flags & VERS_SYSTEM_FIELD)
       {
```
Something like that.

**Comment by midenok** [comment]
@vuvova I don't think it's good idea because there are expressions like:

```sql
insert into t1(x, y, sys_start) values (7, 7001, DEFAULT);
```

It looks natural to me to implement sys fields values via Item_default_value.

Nonetheless I tried to do like you said. The patch became longer. The old one resides [here](https://github.com/tempesta-tech/mariadb/tree/midenok/old/tt-10.3-MDEV-16937).

**Comment by midenok** [comment]
Moved to `bb-10.4-midenok`.

**Pull request closed without merging**
