### PR TITLE
Fix a case of `unused-but-set-variable`

### PR DESCRIPTION
**Pull request by tgross35**
- [ ] *The Jira issue number for this PR is: MDEV-______*

## Description

The `unused-but-set-variable` warning is raised on MacOS from the `posix_fadvise` standin macro, since offset is often otherwise unused. Add a cast to absorb this warning.

## How can this PR be tested?

Compile files such as `ds_tmpfile.cc` with `-Wunused-but-set-variable`

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by grooverdan** [comment]
seems odd that offset is special. Note the other macro:
```
storage/innobase/row/row0merge.cc:# define posix_fadvise(fd, offset, len, advice) /* nothing */
```

Please target 10.4

**Comment by tgross35** [comment]
Agreed, it is weird that this shows up and can't be flag disabled. I think it's just the one variable that doesn't have a use otherwise - `fd` and `len` are used to access the file and `advice` expands to nothing, but it seems like we only use `offset` for this purpose.

Seems like use in `row0merge.cc` is mostly gated but the one from `common.h` isn't?

Changed the base, still doesn't build fully but at least it doesn't get stuck on this.

**Comment by LinuxJedi** [comment]
Hi @tgross35, unfortunately this has missed the boat for 10.4. It will need rebasing against 10.5 for us to approve it. Would you like to do it? Or should we do it?

**Comment by tgross35** [comment]
Sure, I reapplied it.

**Review by LinuxJedi — APPROVED** [review]
Many thanks, looks good to me.

**Pull request merged**
