### PR TITLE
MDEV-14207: mysql innodb_gis test fixes

### PR DESCRIPTION
**Pull request by grooverdan**
@janlindstrom - missed a file

Copied straight from MySQL.

used by:
$ git grep -l  have_innodb_zip.inc
mysql-test/suite/innodb_gis/t/rtree_compress.test
mysql-test/suite/innodb_gis/t/rtree_compress2.test
mysql-test/suite/innodb_gis/t/rtree_purge.test

### CODE REVIEW

**Comment by svoj** [comment]
Thanks!

I wonder if this should be assigned to @dr-m instead?

**Comment by dr-m** [comment]
Thank you for noticing this error. I think that it should be
```sql
--source include/innodb_page_size_small.inc
```
In that way, all applicable page sizes 4k, 8k, 16k will be covered by the innodb_page_size_small.combinations.
Apparently these tests did not fail on the normal MariaDB buildbot, because they require `--big-test`.

**Comment by grooverdan** [comment]
rtree_compress2 segfaults as per MDEV-14227. 

Using debug build rtree_purge and rtree_compress seem to pass (at least on a couple of runs of mtr):

innodb_gis.rtree_purge '4k,innodb'       w7 [ skipped ]  Test requires InnoDB with not 4k Page size.
innodb_gis.rtree_compress '16k,innodb'   w3 [ pass ]  11915
innodb_gis.rtree_compress '8k,innodb'    w6 [ pass ]  12315
innodb_gis.rtree_compress '4k,innodb'    w4 [ pass ]  14886
innodb_gis.rtree_purge '16k,innodb'      w1 [ pass ]  212994
innodb_gis.rtree_purge '8k,innodb'       w2 [ pass ]  245348

**Comment by grooverdan** [comment]
rebased and updated unstable-tests accordingly. I've noted your intent in MDEV-140207 to scale down these tests. Hope this is still useful.

**Comment by dr-m** [comment]
Thanks, this could still be useful. Unfortunately I do not have time right now to fix the tests.
Hopefully I will be able to revisit this in a few weeks.

**Comment by dr-m** [comment]
I fixed most of the tests today; see commit 8dc77a72ea38ca2d7e16468916bedb7ce2779e7f. The remaining disabled tests are mostly due to the geospatial functions behaving differently between MySQL and MariaDB.
I think that @holyfoot should evaluate them.

**Comment by grooverdan** [comment]
ok.

**Pull request closed without merging**
