### PR TITLE
fix some clang warnings

### PR DESCRIPTION
**Pull request by kevgs**

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @kevgs !

Thanks for the pull request. Can you confirm that you are submitting this under MCA or BSD license?

I was looking into fixing those warnings myself so I'll review your patch soon. Some of these may make it into 5.5.

Vicențiu

**Comment by kevgs** [comment]
Hi @cvicentiu 

I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by kevgs** [comment]
Also removing warnings like this:
```
/mariadb/include/maria.h:369:44: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
```

**Comment by kevgs** [comment]
Rebased to current `10.3`.

**Comment by svoj** [comment]
Some reasons on deprecating `register` explained here: https://stackoverflow.com/questions/20618008/replacement-for-deprecated-register-keyword-c-11

**Comment by dr-m** [comment]
Thank you for the contribution. I did most part of it manually, and then cherry-picked your remaining changes. Initially I wanted to make the `#define reg1` and so on no-op, but then I realized that the `register` keyword may continue to have some value in C, and some of MariaDB is still written in and compiled as C.
I applied this to 10.2 in commit 8346acaf807587da751fdded5eb87fd72f5268a5.

**Comment by dr-m** [comment]
Actually, I realize that I did not merge commit 4e3411c187eb42614e099afefb5f220037b2fa46. It does not apply cleanly to 10.3 even after merging the `register` keyword removal from 10.2.
@kevgs maybe you would want to resubmit that one?

**Pull request closed without merging**
