### PR TITLE
MDEV-27036: re-enable my_json_writer-t unit test

### PR DESCRIPTION
**Pull request by SergMariaDB**
- [x] *The Jira issue number for this PR is: MDEV-27036*

## Description
my_json_writer-t unit test
## How can this PR be tested?
test

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by an3l** [comment]
Hi @SergMariaDB, is this patch pushed, since jira item is closed?

**Comment by ohhmm** [comment]
Hi @an3l,
I also 100% sure about this change but I guess someone may have a concern.
It waiting for review before push.

**Comment by spetrunia** [comment]
Suggesting an alternative patch which is much smaller 
https://gist.github.com/spetrunia/c3c4be9ef32abbafbe7542fcbdaf012b

**Comment by grooverdan** [comment]
Appears resolved in jira with 2021-12-20 commits

**Pull request closed without merging**
