### PR TITLE
MDEV-30789 Adding initial Georgian translation

### PR DESCRIPTION
**Pull request by EkaterinePapava**
## Description

Adding initial translation of messages for Georgian language

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to
behave as intended. Consult the documentation on
["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).
In many cases, this will be as simple as modifying one .test and one .result
file in the mysql-test/ subdirectory. Without automated tests, future regressions
in the expected behavior can't be automatically detected and verified.

If the changes are not amenable to automated testing, please explain why not and
carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [x] This is a new feature and the PR is based against the latest MariaDB development branch
- [ ] This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced

## Backward compatibility
TODO: fill details here, if applicable, or remove the section

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

### CODE REVIEW

**Comment by ottok** [comment]
Hi!

Changes looks correct to me, looking good!

Please squash commits, there is no need to spread this across 4 separate
commits, and then force push to update this PR without creating new ones.

The PR template text does mostly not apply here, no MDEV nor MTR is needed.
You can just delete the unrelated parts from the PR description.

**Comment by NorwayFun** [comment]
Is it OK now?

**Comment by EkaterinePapava** [comment]
Is it OK now?

**Comment by ottok** [comment]
Yes, I can see you successfully squashed the commits into one.

You can view how your raw patch would look like if applied on top of
MariaDB sources by viewing url
https://patch-diff.githubusercontent.com/raw/MariaDB/server/pull/2524.patch

**Comment by grooverdan** [comment]
Thanks @EkaterinePapava. I needed to add a few extra things to get it to build but that is pushed here now.

Did you want to add a full Georgian locale with a section like https://github.com/MariaDB/server/blob/11.0/sql/sql_locale.cc#L500-L534 ?

The meaning of the fields is: https://github.com/MariaDB/server/blob/11.0/sql/sql_locale.h#L28-L65 . The number will be 26 (the one after `hi_IN`).

If you are still having difficulty with git I recommend creating a new branch `git checkout -b georgian_locale 922fcc6a0e3fe4fee4e1e4942b11bd25fadac97a` and making the changes in a separate pull request. I can do small fixups like did here to make it ready.

Thank you very much for your contribution.

**Comment by EkaterinePapava** [comment]
Hello,
Thanks.
Several questions, though:
in sql_locale.cc language code will be ka_GE, which is right one for Georgian, not ka_geo. Is it ok?
I see N26 language slot is taken by Croatian. Or did you mean "increment highest number by one"?

**Comment by grooverdan** [comment]
> Hello, Thanks. Several questions, though: in sql_locale.cc language code will be ka_GE, which is right one for Georgian,

opps, yes.

> not ka_geo. Is it ok? 

> I see N26 language slot is taken by Croatian. Or did you mean "increment highest number by one"?

yep

**Comment by LinuxJedi** [comment]
Tagging related PR #2527

**Comment by LinuxJedi** [comment]
Buildbot failure is:

```
/home/buildbot/amd64-centos-7-rpm-autobake/build/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX/sql/sql_table.cc: In function 'bool mysql_write_frm(ALTER_PARTITION_PARAM_TYPE*, uint)':
/home/buildbot/amd64-centos-7-rpm-autobake/build/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX/sql/sql_table.cc:846:53: warning: statement has no effect [-Wunused-value]
     ERROR_INJECT("alter_partition_after_create_frm");
                                                     ^
```

I don't think this is related to your change,

**Comment by LinuxJedi** [comment]
Excellent work :)

**Pull request merged**
