### PR TITLE
MDEV-15503 - mtr: fix --strace

### PR DESCRIPTION
**Pull request by grooverdan**
was quite broken for out-of-tree builds, --mem and --parallel.

strace-client needs to behave like the valgrind client.

I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
FYI @elenst

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-15503

This task was added to 10.3 backlog.

Thanks,
Sergey

**Comment by grooverdan** [comment]
more comprehensively fixed and accurately documented the strace mtr options.

**Comment by an3l** [comment]
Hi @grooverdan,
pushed to `5.5` with small variations regarding the review with commit 866e5c250e27e3.
Thanks for contribution!

**Pull request closed without merging**
