### PR TITLE
Minor fixes to Debian packaging in 10.5

### PR DESCRIPTION
**Pull request by ottok**
Fixes:
- https://jira.mariadb.org/browse/MDEV-17367
- https://jira.mariadb.org/browse/MDEV-14918

### CODE REVIEW

**Comment by spetrunia** [comment]
The fix for MDEV-14918 is ok.
I don't see anything wrong with MDEV-17367, but I'm less of an expert in the area

**Comment by spetrunia** [comment]
@ottok , re the MDEV-17367 fix:

I am looking through  `mysql_install_db` and besides `my_print_defaults` it also uses these .sql files:

```
# Set up paths to SQL scripts required for bootstrap
fill_help_tables="$srcpkgdatadir/fill_help_tables.sql"
create_system_tables="$srcpkgdatadir/mysql_system_tables.sql"
create_system_tables2="$srcpkgdatadir/mysql_performance_tables.sql"
fill_system_tables="$srcpkgdatadir/mysql_system_tables_data.sql"
maria_add_gis_sp="$buildpkgdatadir/maria_add_gis_sp_bootstrap.sql"
mysql_test_db="$srcpkgdatadir/mysql_test_db.sql"

for f in "$fill_help_tables" "$create_system_tables" "$create_system_tables2" "$fill_system_tables" "$maria_add_gis_sp" "$mysql_test_db"
do
  if test ! -f "$f"
  then
    cannot_find_file "$f"
    exit 1
  fi
done
```
but the files are in the mariadb-server package?  Should they be moved here as well, or should mysql_install_db moved there instead?  (I admit I dont see the reason why there is a distinction between "server" and "server-core" packages).

**Comment by ottok** [comment]
The server-core package should be the stand-alone server which people can run in minimal setups, e.g. manually starting/stopping and other scenarios. The full server package includes systemd files and other stuff. This setup has been inherited from MySQL packaging 15 years ago, I don't know if people really run the server-core.

I will move those other *.sql files to -core as well then..

**Comment by ottok** [comment]
Tests on Travis-CI seem to fail on an unrelated MTR error:
```
main.thread_pool_info                    w1 [ fail ]
        Test ended at 2020-02-25 08:54:48
CURRENT_TEST: main.thread_pool_info
mysqltest: At line 30: query 'FLUSH THREAD_POOL_STATS' failed: 2013: Lost connection to MySQL server during query
The result from queries just before the failure was:
< snip >
DESC INFORMATION_SCHEMA.THREAD_POOL_STATS;
Field	Type	Null	Key	Default	Extra
GROUP_ID	int(6)	NO		0	
THREAD_CREATIONS	bigint(19)	NO		0	
THREAD_CREATIONS_DUE_TO_STALL	bigint(19)	NO		0	
WAKES	bigint(19)	NO		0	
WAKES_DUE_TO_STALL	bigint(19)	NO		0	
THROTTLES	bigint(19)	NO		0	
STALLS	bigint(19)	NO		0	
POLLS_BY_LISTENER	bigint(19)	NO		0	
POLLS_BY_WORKER	bigint(19)	NO		0	
DEQUEUES_BY_LISTENER	bigint(19)	NO		0	
DEQUEUES_BY_WORKER	bigint(19)	NO		0	
SELECT SUM(DEQUEUES_BY_LISTENER+DEQUEUES_BY_WORKER) > 0 FROM INFORMATION_SCHEMA.THREAD_POOL_STATS;
SUM(DEQUEUES_BY_LISTENER+DEQUEUES_BY_WORKER) > 0
1
SELECT SUM(POLLS_BY_LISTENER+POLLS_BY_WORKER) > 0 FROM INFORMATION_SCHEMA.THREAD_POOL_STATS;
SUM(POLLS_BY_LISTENER+POLLS_BY_WORKER) > 0
1
FLUSH THREAD_POOL_STATS;
More results from queries before failure can be found in /home/travis/build/MariaDB/server/mysql-test/var/1/log/thread_pool_info.log
```

This failure already existed in Travis-CI before this PR (I wonder why is it even allowed to merge commits that break the CI?).

**Comment by ottok** [comment]
It should be OK to merge this branch now.

**Comment by ottok** [comment]
Rebased on master. Will push once CI passes.

**Pull request merged**
