### PR TITLE
Link against libatomic on platforms missing 64-bit atomics

### PR DESCRIPTION
**Pull request by glaubitz**
Some architectures require linking against libatomic for using 64-bit atomic operations like __atomic_load_8. Due to a bug in gcc, linking against libatomic is not happening automatically when using C11 code.

See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358

### CODE REVIEW

**Comment by glaubitz** [comment]
I hereby declare that I am submitting my contributions to the MariaDB project under the BSD-new license.

**Comment by glaubitz** [comment]
I have updated both my PRs to make the cmake code more consistent (capitalization of the statements).

**Comment by glaubitz** [comment]
Hi! Could someone have another look at this? Thanks!

**Comment by glaubitz** [comment]
@vaintroub I actually checked which components required linking against ```libatomic```. None of the cases where I am linking is optional.

As for testing whether the linking is necessary on a specific platform, I actually do that in the test "HAVE_ATOMIC_ADD_FETCH".

**Comment by vaintroub** [comment]
@glaubitz  : I would not like libatomic to be spread around multiple CMakeLists.txt. If this is a system library, which is unfortunately not added by GCC, then it just needs to link with mysys. Eventually gcc will be fixed, and removing libatomic would also be easier, if it is in one place, not spread around.

As for you CMake test, you need to add more comments really, because GCC atomics are meant to be intrinsics, and added by compiler without needed to link LIBATOMIC. So your HAVE_LIBATOMIC can as well be named NEED_GCC_C11_LIBATOMIC_LINK_WORKAROUND.

**Comment by glaubitz** [comment]
Ok, I'll look into it. I'll force-push an updated version over the weekend.

**Comment by svoj** [comment]
Let's continue discussion in #979. It will get merged to 10.4 anyway, so this one is not needed.

**Pull request closed without merging**
