### PR TITLE
MDEV-9288: Use POWER8 accelerated crc32

### PR DESCRIPTION
**Pull request by grooverdan**
- Make accelerated checksum available to InnoDB and XtraDB.
 - Fall back to slice-by-eight if not available. The mode used is printed on startup.
 - Will only build on POWER systems at the moment until CMakeLists are modified
   to only add the crc32_power8/ files when building on POWER.

running MySQL-5.7 unittest/gunit/innodb/ut0crc32-t

Before:

1..2
Using software crc32 implementation, CPU is little-endian
ok 1
Using software crc32 implementation, CPU is little-endian
    normal CRC32: real    0.148006 sec
    normal CRC32: user    0.148000 sec
    normal CRC32: sys     0.000000 sec
big endian CRC32: real    0.144293 sec
big endian CRC32: user    0.144000 sec
big endian CRC32: sys     0.000000 sec
ok 2

After:

1..2
Using POWER8 crc32 implementation, CPU is little-endian
ok 1
Using POWER8 crc32 implementation, CPU is little-endian
    normal CRC32: real    0.008097 sec
    normal CRC32: user    0.008000 sec
    normal CRC32: sys     0.000000 sec
big endian CRC32: real    0.147043 sec
big endian CRC32: user    0.144000 sec
big endian CRC32: sys     0.000000 sec
ok 2

Author CRC32 ASM code: Anton Blanchard <anton@au.ibm.com>
ref: https://github.com/antonblanchard/crc32-vpmsum

Signed-off-by: Daniel Black <daniel.black@au.ibm.com>

Submitted under the MCA.

### CODE REVIEW

**Comment by janlindstrom** [comment]
Hi Daniel,

Thanks for your contribution! JIRA task just for the record: https://mariadb.atlassian.net/browse/MDEV-9288

Meanwhile could you check the following addendum and let us know if you want to sign MCA or you just Ok about contributing under the BSD-new license terms?

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

**Comment by grooverdan** [comment]
MCA has been signed. Otto acknowledged it the other day.

**Comment by grooverdan** [comment]
@janlindstrom  thanks.

@vaintroub I did try to look for a CMake way, something along the lines ofinclude the ASM only for the power target in some way? I was trying to prevent breaking cross compiler set ups (which I haven't really tested). Any CMake tips/constructs to handle such a case would be appreciated. I'll definitely clean this up with guidance.

**Comment by grooverdan** [comment]
Ok found the following constructs. I'll get another PR organised.
<pre>
+IF(CMAKE_SYSTEM_NAME MATCHES "ppc64le")
+  enable_language(ASM)
+  LIST(APPEND MYSYS_SOURCES
+      crc32_power8/crc32.S
+      crc32_power8/crc32_wrapper.c)
+ENDIF()
</pre>

**Comment by janlindstrom** [comment]
Is this really so that it does not work with ppc64be ?

**Comment by vaintroub** [comment]
Yup, CMAKE_SYSTEM_NAME seems the correct construct. Thanks!

**Pull request merged**
