### PR TITLE
MDEV-19211: Fix mysqld_safe --dry-run

### PR DESCRIPTION
**Pull request by FaramosCZ**

### CODE REVIEW

**Comment by FaramosCZ** [comment]
Submitted under MCA

**Comment by FaramosCZ** [comment]
Fixes error message:
/usr/bin/mysqld_safe: line 932: return: can only `return' from a function or sourced script

Please note that with the error above, the server *will* start - which is exactly opposite of what "--dry-run" tries to achieve

**Comment by FaramosCZ** [comment]
If the original "return" is desired (even though the ugly error message), I suggest putting "set -e" before it and "set +e" after it, so it will exit the script anyway.

**Comment by grooverdan** [comment]
Hmm. The original purpose of `--dry-run` was https://github.com/MariaDB/server/blob/10.4/scripts/mariadb-service-convert as a script to take `[mysqld_safe]` params and create a systemd service file override.

Apologies for stuffing up the raw call of mysqld_safe (which really wasn't mean to be called with --dry-run).

**Comment by svoj** [comment]
Which means we can't use `exit` unconditionally?

**Comment by FaramosCZ** [comment]
The option is not mentioned in the man page.
The "mysqld_safe --help" says:
  --dry-run                  Simulate the start to detect errors but don't start


I'm fine with leaving as it is, with only documenting better the purpose.
In other case, I'd go with the "set -e" variant I metioned if the "exit" is not acceptable.

**Comment by cvicentiu** [comment]
@FaramosCZ Thanks for suggesting this fix.

I found a more stable approach and implemented it in 10.1.

6a7d51b1cb338081aa111f3ec774aaf4d90c994b

**Pull request closed without merging**
