### PR TITLE
[Ubuntu] Cannot stop mysqld process

### PR DESCRIPTION
**Pull request by cweiland**
'log_end_msg 1' stop the stopping process at this point when mysqladmin cannot stop properly

### CODE REVIEW

**Comment by svoj** [comment]
@ottok could you review this PR? Alternative option might be to call ```log_end_msg 0```.

**Comment by ottok** [comment]
Hello!

Thanks for the pull request and potential fix.

However, I don't feel comfortable in merging this change when I don't know what error it is supposed to fix. Can you please describe a bit what the error was and why this change is a good way to fix it?

The description does not have to be long. A screenshot or copy-paste from terminal is also good, as long as context (Ubuntu version, MariaDB package version etc) is also visible.

**Comment by ottok** [comment]
@cweiland Please supply some more information.

**Comment by ottok** [comment]
@cweiland We didn't get any furher information from you so I am closing this PR now. Feel free to open a new PR later when/if you have the chance to document the purpose of it properly.

**Pull request closed without merging**
