### PR TITLE
Update wsrep-lib to have OSX compilation fixes

### PR DESCRIPTION
**Pull request by temeo**

### CODE REVIEW

**Comment by temeo** [comment]
It seems to allow changing base branch only.

**Comment by janlindstrom** [comment]
10.4 is fine now.

**Comment by svoj** [comment]
I see, an alternative is to force push correct changes to `10.4-test-pr` if you don't need it otherwise.

**Comment by temeo** [comment]
The intention was to open this PR against Codership fork for testing purposes, but I messed up when selecting the repository.

However, the fix for the compilation issue in this PR is real one, feel free to take it in if it suits your needs.

Sorry about the noise.

**Pull request merged**
