### PR TITLE
my_thread: Use unsigned long long for storing pthread IDs

### PR DESCRIPTION
**Pull request by niacat**
This is a fix for operating systems that have pthread_t defined
as a pointer and use the default pthread_self() mechanism for
identifying threads. More specifically, this is a build fix
for NetBSD.

Any changes I submit are freely available under the new BSD
license.

Signed-off-by: Nia Alarie <nia@NetBSD.org>

### CODE REVIEW

**Comment by grooverdan** [comment]
@niacat, why have you chosen `uintptr_t` here? https://man.netbsd.org/NetBSD-9.2/pthread_self.3 indicates a pthread_t is returned. I'm just assuming a pointer type compile fails elsewhere.

Also note this breaks the other platforms in CI that don't have uintptr_t, only intptr_t.

Notably MySQL use a [unsigned long long](https://github.com/mysql/mysql-server/commit/15f1d8f0f677#diff-29287fb350a4a032bb32c09e700b4be5daaf8e0394545199f4d8b8658858b12eR39). Given this just ends up being uses as an unsigned long long type [here](https://github.com/MariaDB/server/blob/10.5/storage/perfschema/table_threads.cc#L307), does an unsigned long long work for you?

If so can you use this and rebase this pull request against 10.5.

**Comment by grooverdan** [comment]
@vuvova do you remember a reason why you used uint32 in https://github.com/MariaDB/server/commit/0ea717f51a152afdb3791195c4a25ee0baa2faac#diff-7bc54e6497f177eadda15a593a6147598e8bea3fc4991fbc0d89927edd3717f9R11 when you imported this?

**Comment by niacat** [comment]
@grooverdan `uintptr_t` seemed like the natural choice to preserve the signedness of the existing type while fitting a pointer type. On NetBSD pthread_t is defined as `typedef struct __pthread_st *pthread_t;`. I'm happy with unsigned long long too and will update the PR.

**Comment by grooverdan** [comment]
Ah, Windows, that explains uint32. Leave it with me, I'll get something that satisfies all OSes.
```
C:\projects\server\storage\perfschema\pfs_instr.cc(532,41): warning C4244: '=': conversion from 'my_thread_os_id_t' to 'uint32', possible loss of data [C:\projects\server\win_build\storage\perfschema\perfschema.vcxproj]
```

**Comment by grooverdan** [comment]
@niacat I ended up going back to your `uintptr_t` for the NetBSD HAVE_INTEGER_PTHREAD_SELF case and left other OSes to their native type. If you could just sanity check this  https://github.com/MariaDB/server/commits/bb-10.5-danielblack-perfschema-thread_os_t-type-netbsd that would be appreciated.

**Comment by niacat** [comment]
@grooverdan This looks good, but I do need the return value of pthread_self cast to uintptr_t for this to compile cleanly.

**Comment by grooverdan** [comment]
Thanks @niacat for the pull request. A fix as previously described has been merged and will be in the next 10.5 release.

**Pull request closed without merging**
