### PR TITLE
Apple Silicon is a 64-bit platform

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by lonnylot** [comment]
@an3l Is there any ETA on the 10.6 release? Would be great to get this running on my new Mac...

**Comment by lonnylot** [comment]
Or perhaps the better question is if we can get this in a 10.5 patch.

**Comment by an3l** [comment]
Hi @lonnylot please take a look into PR #1743, there is a similar change.

**Comment by lonnylot** [comment]
Hi @an3l - I don't actually have the knowledge to review it. If you'd like I can build it and run the test suite on my M1.

**Comment by robertbindar** [comment]
Hey @fxcoudert and @lonnylot! Thanks for submitting this patch and showing interest in making MariaDB available on the new M1 platforms :-) :tada: 

@fxcoudert is this patch fixing a compile error on your M1? No description was provided so I'm assuming that's the most likely motivation for the patch.

@lonnylot I'm not sure what's an accurate timeline for a 10.6 release, but 10.5.9 is coming in the next few days and most probably we can still catch this release with this M1-support patches.

Got a quick question for you too if you don't mind, I asked the same thing in #1743 (my m1 mac is on its way and our CI m1 machine is also on its way so no real way currently to test ourselves these patches or how MariaDB in general is working on this platform, thus the need to listen feedback from as many community members as possible), is the server building fine except this compile error on your machines?

Also if any of you is willing to punch the clock and try running the test suites via MTR on M1s and attach the output (if any tests fail), I would be extremely grateful :heart:

**Comment by lonnylot** [comment]
@robertbindar Sure - I'll set it up later today.

**Comment by robertbindar** [comment]
That sounds amazing! Many thanks for the help

**Comment by robertbindar** [comment]
Merged in 10.5! Many thanks @fxcoudert and sorry for the delay.

**Pull request closed without merging**
