### PR TITLE
MDEV-23519: Assigning original column name just before packet gets formed to be sent to client using mysql protocol

### PR DESCRIPTION
**Pull request by ashwin-kayyoor**
- [x] *The Jira issue number for this PR is: MDEV-23519*

## Description
MySQL protocol packet captured at client 10.4 is having "Original name" parameter using the alias name instead of the original column name which you can see 10.2 is showing up properly.

Fix in this PR solves this problem by assigning original name correctly.

## How can this PR be tested?
Test case using mysql_client_test is included with this PR.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

I am submitting this bug fix under BSD New 3 Clause License.

### CODE REVIEW

**Comment by sanja-byelkin** [comment]
The fix chacks if "original name" exists then compare it with name (without length involved!!!) and reassign if differ.

Why just do not take "original name" if exists and "name" otherwise?

**Comment by sanja-byelkin** [comment]
The other note is that in the test we shoud not delete table "if exists" before creation but unconditionally drop at at the end of the test.

So I will wait a bit if the author will fix the 2 problems if no I will fix it by myself

**Comment by ashwin-kayyoor** [comment]
@sanja-byelkin I have made the suggested changes. Please review.

**Comment by montywi** [comment]
Why did MariaDB 10.2 give the correct name?
What changed in MariaDB 10.4 and why cannot we go revert to use the original code?

**Comment by vuvova** [comment]
A bug fix must be accompanied with a test case. And a test case must fail without the bug fix and must succeed with a bug fix.

This is not the case here, the test case succeeds with and without bug fix. And `test_bug21635()` fails with a fix.

**Comment by montywi** [comment]
Thanks for all the work on this!
I was able to repeat the issue with a simple test case. When investigating why things changed between 10.3 and 10.4, I noticed that one function wrongly copies the alias value instead of the column name.
Fixing that fixed the issue (as far as I can see).
You can find the fix in bb-10.4-monty, soon to be pushed to 10.4 (assuming review and QA are ok)

**Pull request closed without merging**
