### PR TITLE
MDEV-7258 support TokuDB read free replication

### PR DESCRIPTION
**Pull request by prohaska7**
Add handler API for RFR.
Update RFR tests.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Rich,

Thanks for your contribution. JIRA task just for the record: https://jira.mariadb.org/browse/MDEV-7258

This task was added to 10.0.28 backlog, which is planned to be handled between 2016-10-06 and 2016-10-13.

Thanks,
Sergey

**Comment by jocel1** [comment]
Hi Sergey,

Any chance to have this merged ? :)

Thanks!
  Jocelyn

**Comment by svoj** [comment]
@jocel1, according to @vuvova this task was postponed due to high inflow of 10.1 critical issues. All I can say so far is: stay tuned. This should be merged to MariaDB some day eventually.

**Comment by atopiler** [comment]
Any updates on this by chance now that we're almost in version 10.3?

**Comment by starinacool** [comment]
Is there any information on merging this into 10.1, 10.2 or 10.3?

**Comment by vuvova** [comment]
It's not merged yet. It somewhat depends on our RocksDB integration, because RocksDB engine needs read free replication too, and we want a feature that works for both engines, to avoid reimplementing it later.

**Comment by jocel1** [comment]
Hi @vuvova 

@prohaska patch was a quite generic implementation and could have been used directly by RockDB if it was merged earlier, or I'm missing something?

**Pull request closed without merging**
