### PR TITLE
MDEV-30205 Move /usr/share/mysql to /usr/share/mariadb

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-30205*

## Description

These are mainly internal files so is a low impact change.

The few scripts/mysql*sql where renames to mariadb_* prefix on the name.

mysql-test renamed to mariadb-test in the final packages.

## How can this PR be tested?

```
$ podman run -ti --rm ubuntu:20.04 
root@5ce193aeebd9:/#  apt-get update && apt-get install -y ca-certificates
root@5ce193aeebd9:/# echo "deb [trusted=yes] https://ci.mariadb.org/31091/amd64-ubuntu-2004-deb-autobake/debs ./" >>/etc/apt/sources.list
root@5ce193aeebd9:/# 
root@5ce193aeebd9:/# apt-get update
root@5ce193aeebd9:/# apt-get install mariadb-test
root@5ce193aeebd9:/#  cd /usr/share/mariadb/
root@5ce193aeebd9:/usr/share/mariadb# ls -la
total 3656
drwxr-xr-x. 30 root root    4096 Dec 21 06:11 .
drwxr-xr-x.  1 root root    4096 Dec 21 06:11 ..
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 bulgarian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 charsets
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 chinese
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 czech
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 danish
-rwxr-xr-x.  1 root root    3015 Dec 21 05:29 debian-start.inc.sh
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 dutch
-rwxr-xr-x.  1 root root      27 Dec 21 05:29 echo_stderr
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 english
-rw-r--r--.  1 root root  718421 Dec 21 05:29 errmsg-utf8.txt
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 estonian
-rw-r--r--.  1 root root 2165918 Dec 21 05:29 fill_help_tables.sql
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 french
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 german
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 greek
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 hindi
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 hungarian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 italian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 japanese
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 korean
-rw-r--r--.  1 root root    1683 Dec 21 05:43 maria_add_gis_sp_bootstrap.sql
drwxr-xr-x.  9 root root    4096 Dec 21 06:11 mariadb-test
-rw-r--r--.  1 root root    1955 Dec 21 05:29 mariadb_performance_tables.sql
-rw-r--r--.  1 root root  619228 Dec 21 05:43 mariadb_sys_schema.sql
-rw-r--r--.  1 root root   30040 Dec 21 05:29 mariadb_system_tables.sql
-rw-r--r--.  1 root root    3159 Dec 21 05:29 mariadb_system_tables_data.sql
-rw-r--r--.  1 root root   10413 Dec 21 05:29 mariadb_test_data_timezone.sql
-rw-r--r--.  1 root root    1775 Dec 21 05:29 mariadb_test_db.sql
-rwxr-xr-x.  1 root root    6928 Dec 21 05:43 mini-benchmark
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 norwegian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 norwegian-ny
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 polish
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 portuguese
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 romanian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 russian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 serbian
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 slovak
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 spanish
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 swedish
drwxr-xr-x.  2 root root    4096 Dec 21 06:11 ukrainian
-rw-r--r--.  1 root root    3474 Dec 21 05:43 wsrep.cnf
-rwxr-xr-x.  1 root root    4979 Dec 21 05:43 wsrep_notify
root@5ce193aeebd9:/usr/share/mariadb# cd mariadb-test/
root@5ce193aeebd9:/usr/share/mariadb/mariadb-test# ./mtr --parallel=auto --suite=main
Logging: ./mtr  --parallel=auto --suite=main
VS config: 
vardir: /usr/share/mariadb/mariadb-test/var
Checking leftover processes...
Removing old var directory...
Creating var directory '/usr/share/mariadb/mariadb-test/var'...
Checking supported features...
Can't exec "patch": No such file or directory at ./mtr line 1855.
MariaDB Version 11.0.0-MariaDB-1:11.0.0+maria~ubu2004
 - SSL connections supported
Using suites: main
Collecting tests...
Installing system database...
Using parallel: 8

==============================================================================

TEST                                  WORKER RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[4] Using MTR_BUILD_THREAD 301, with reserved ports 16020..16039
worker[3] Using MTR_BUILD_THREAD 302, with reserved ports 16040..16059
worker[2] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
worker[1] Using MTR_BUILD_THREAD 303, with reserved ports 16060..16079
worker[5] Using MTR_BUILD_THREAD 304, with reserved ports 16080..16099
worker[6] Using MTR_BUILD_THREAD 305, with reserved ports 16100..16119
worker[7] Using MTR_BUILD_THREAD 306, with reserved ports 16120..16139
worker[8] Using MTR_BUILD_THREAD 307, with reserved ports 16140..16159
worker[1] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
worker[6] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
main.alter_table-big                     worker[8] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
[ skipped ]  Test needs --big-test
...
main.create_or_replace2                  [ skipped ]  Requires debug build
worker[3] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
worker[4] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
worker[2] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
worker[7] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
main.connect-abstract                    w1 [ skipped ]  Need Linux
main.bind_multiple_addresses_resolution  w2 [ pass ]     17
main.bind_address_resolution             w7 [ pass ]     21
main.ipv4_and_ipv6                       w8 [ pass ]    106
main.ipv6                                w4 [ pass ]    153
main.mysqlbinlog_row_minimal             w2 [ pass ]     64
main.ipv4_as_ipv6                        w3 [ pass ]    306
main.ctype_cp932_binlog_row              w8 [ pass ]     45
main.long_unique_bugs 'innodb'           w7 [ pass ]     83
main.mysqlbinlog-innodb 'innodb'         w4 [ pass ]     12
main.partition_innodb_stmt 'innodb'      w2 [ pass ]      7
main.mysqlbinlog_row_compressed          w8 [ pass ]     45
main.session_tracker_last_gtid 'innodb'  w3 [ pass ]      4
main.partition_binlog_stmt               w8 [ pass ]     17
main.mysqlbinlog_stmt_compressed         w2 [ pass ]     41
main.ctype_filesystem                    w8 [ pass ]      1
main.set_statement_notembedded_binlog    w2 [ pass ]      6
main.lock_tables_lost_commit 'innodb'    w3 [ pass ]      6
main.mysqlbinlog                         w4 [ pass ]    293
...
root@62167db98943:/# mkdir /tmp/x; mariadb-install-db --no-defaults --datadir=/tmp/x
Installing MariaDB/MySQL system tables in '/tmp/x' ...
OK

```

[salsa pipeline](https://salsa.debian.org/grooverdan/mariadb-server/-/pipelines/473479).

## Backward compatibility

Hopefully minimized. A small number of users might access database initialization SQL files, translation, or mtr tests. Those users will be able to see the difference quite easily.

### CODE REVIEW

**Comment by ottok** [comment]
If you merge #2396 to get Salsa-CI up to 10.11, and then maybe @illuusio or @fauust can create the additional 11.0 upgrade scenario test on the 11.0 branch, which after this and other similar PRs can more easily be tested with proper CI support.

**Comment by illuusio** [comment]
This one needs heavy testing but at last there is mostly mariadb and not mysql

**Comment by ottok** [comment]
I pushed this branch to https://salsa.debian.org/otto/mariadb-server/-/pipelines/512586 to get Debian Salsa-CI results. I did not spot any regressions due to this change, so this should be fine to merge! (Unfortunately there are a lot of regressions due to other issues - for 10.6 branch I already fixed everything in January in #2424, but that was not approved/merged, and since there have been changes that have regressed 10.7+ branches more, so the value of Salsa-CI for upstream has gone down. It will need a new round of attention to get fixed, along with all packaging fixes that it detected.)

Note to self: I used commands
```
git remote add -t bb-10.11-MDEV-30205-usr-share-mariadb grooverdan https://github.com/grooverdan/mariadb-server.git
git fetch grooverdan
git checkout bb-10.11-MDEV-30205-usr-share-mariadb
git push -u otto
```

**Comment by illuusio** [comment]
It seems to pass most of test but those systemd or SysV-init stuff seems to need some love. Meaning upgrades from 10.2-10.6 which are failing or are they fixed in: PR #2424

**Pull request merged**
