### PR TITLE
Fix submodule url of wolfssl and libmarias3

### PR DESCRIPTION
**Pull request by lingbin**

### CODE REVIEW

**Comment by an3l** [comment]
Hi @lingbin,
thanks for contribution.
Why not to update `libmariadb` submodule ?

**Comment by svoj** [comment]
Are there any problems with original urls?

**Comment by an3l** [comment]
Hi @svoj,
original urls can be resolved too, so far as I tested, although the exact url is `wolfSSL/` instead of `WolfSSl/`, as proposed in patch.
Probably contribution was since urls are `.gitmodules` to have `.git` suffix and be unique, right @lingbin  ?
I suppose this cannot harm our buildbot.

**Comment by lingbin** [comment]
Thank you for your review.

This problem was discovered when I tried to compile with source code. Downloading submoudle always failed, so I checked the .gitmodule file and changed it to the address provided on the github page of the module (green button, "**clone or download**")

I don't know the exact reason, When running on my machine, there will be a difference similar to the following

```
$ git clone https://github.com/WolfSSL/wolfssl
Cloning into 'wolfssl'...
fatal: repository 'https://github.com/WolfSSL/wolfssl/' not found

# Run successfully with the '.git' suffix
$ git clone https://github.com/wolfSSL/wolfssl.git
Cloning into 'wolfssl'...
remote: Counting objects: 71239, done.
remote: Compressing objects: 100% (18004/18004), done.
remote: Total 71239 (delta 52504), reused 71239 (delta 52504)
Receiving objects: 100% (71239/71239), 86.21 MiB | 30.13 MiB/s, done.
Resolving deltas: 100% (52504/52504), done.
```

Probably because the server I am using is accessing github through the **nginx proxy**. sorry I can't verify it by modifying the configuration, because there are many people using this machine at the same time.

One possible clue is on my macbook that does not require a .git suffix

**Comment by an3l** [comment]
Hi @lingbin,
can you please try compiling from source code using [getting-started-tutorial](https://mariadb.org/get-involved/getting-started-for-developers/get-code-build-test/) without your patch?
Are there any differences?
Thanks

**Comment by svoj** [comment]
@lingbin did you get this with all submodules or only wolfssl? There was a letter case typo in wolfssl and it looks like github repo names are case sensitive: https://help.github.com/en/articles/error-repository-not-found

**Comment by an3l** [comment]
Hi,
I have tested `wolfssl` without/with your patch on `10.4` which has same submodules in `.gitmodules`:
```
cat .gitmodules 
[submodule "libmariadb"]
	path = libmariadb
	url = https://github.com/MariaDB/mariadb-connector-c
[submodule "storage/rocksdb/rocksdb"]
	path = storage/rocksdb/rocksdb
	url = https://github.com/facebook/rocksdb.git
[submodule "wsrep-lib"]
	path = wsrep-lib
	url = https://github.com/codership/wsrep-lib.git
	branch = master
[submodule "extra/wolfssl/wolfssl"]
	path = extra/wolfssl/wolfssl
	url = https://github.com/WolfSSL/wolfssl
```

So after fetching repo and running `git submodule` we don't get `wolfssl`:
```zsh
anel@ubuntu:~/workspace/mariadb/server$ git submodule
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb ((null))
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb ((null))
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib ((null))
```
In order to use it use `git submodule init`:
```zsh
anel@ubuntu:~/workspace/mariadb/server$ git submodule init
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) registered for path 'extra/wolfssl/wolfssl'
anel@ubuntu:~/workspace/mariadb/server$ git submodule
 21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl ((null))
+16533b475df07683c994210cb41cb7fd685f413e libmariadb (v3.0.2-317-g16533b4)
+7259e28d915af72dd0cd6d055ab966644d83dd68 storage/rocksdb/rocksdb (v5.8-1670-g7259e28d9)
+eba8a8f35d11cb4cc21f3caaf2cc584553b8a568 wsrep-lib (remotes/origin/HEAD)
```
After that update submodule:
```bash
anel@ubuntu:~/workspace/mariadb/server$ git submodule update 
Cloning into '/home/anel/workspace/mariadb/server/extra/wolfssl/wolfssl'...
Submodule path 'extra/wolfssl/wolfssl': checked out '21f2beca9f320199fcea4a96df3e19967804144b'
Submodule path 'libmariadb': checked out 'c098613d289ed88fc53286e98add28ae9f2d8b46'
Submodule path 'storage/rocksdb/rocksdb': checked out '926f3a78a64b327475ee6c60b6c8ab4f34253204'
Submodule path 'wsrep-lib': checked out 'e9dafb73734d71ab55078b34748e54f139aec827'
```
and double check again:
```bash
anel@ubuntu:~/workspace/mariadb/server$ git submodule
 21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl (v4.0.0-stable)
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (heads/master)
```
In order to remove it use:
```bash
anel@ubuntu:~/workspace/mariadb/server$ git submodule deinit extra/wolfssl/wolfssl
Cleared directory 'extra/wolfssl/wolfssl'
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) unregistered for path 'extra/wolfssl/wolfssl'

anel@ubuntu:~/workspace/mariadb/server$ git submodule
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (heads/master)
```
I applied your change and seems like ok too, but I would say that we should use case sensitive url (with/without `.git` suffix), `submodule` will handle it for us.
```bash
submodule "extra/wolfssl/wolfssl"]
	path = extra/wolfssl/wolfssl
	url = https://github.com/wolfSSL/wolfssl.git

anel@ubuntu:~/workspace/mariadb/server$ git submodule
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (heads/master)

anel@ubuntu:~/workspace/mariadb/server$ git submodule init
Submodule 'extra/wolfssl/wolfssl' (https://github.com/wolfSSL/wolfssl.git) registered for path 'extra/wolfssl/wolfssl'

anel@ubuntu:~/workspace/mariadb/server$ git submodule update 
Submodule path 'extra/wolfssl/wolfssl': checked out '21f2beca9f320199fcea4a96df3e19967804144b'

anel@ubuntu:~/workspace/mariadb/server$ git submodule
 21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl (v4.0.0-stable)
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (heads/master)

anel@ubuntu:~/workspace/mariadb/server$ ls .git/modules/extra/
wolfssl

anel@ubuntu:~/workspace/mariadb/server$ git submodule deinit extra/wolfssl/wolfssl
fatal: Please stage your changes to .gitmodules or stash them to proceed
fatal: Submodule work tree 'extra/wolfssl/wolfssl' contains local modifications; use '-f' to discard them

anel@ubuntu:~/workspace/mariadb/server$ git submodule deinit -f extra/wolfssl/wolfssl
Cleared directory 'extra/wolfssl/wolfssl'
Submodule 'extra/wolfssl/wolfssl' (https://github.com/wolfSSL/wolfssl.git) unregistered for path 'extra/wolfssl/wolfssl'

anel@ubuntu:~/workspace/mariadb/server$ git submodule 
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (heads/master)


```

**Comment by lingbin** [comment]
Hi, thanks for your reply.
I tried it again on my server(CentOS 6.3), using the correct spelling( `wolfSSL/wolfssl`), without the `.git` suffix, it is OK.
```
git clone https://github.com/wolfSSL/wolfssl
Cloning into 'wolfssl'...
warning: redirecting to https://github.com/wolfSSL/wolfssl.git/
remote: Counting objects: 71269, done.
remote: Compressing objects: 100% (19597/19597), done.
remote: Total 71269 (delta 51898), reused 70312 (delta 50941)
Receiving objects: 100% (71269/71269), 98.95 MiB | 22.67 MiB/s, done.
Resolving deltas: 100% (51898/51898), done.

$ git --version
git version 2.16.2
```
So this is really a matter of letter case.

Another test, on the mac OS, is ok even with `WolfSSL`
```
lingbin@baidudeMacBook-Pro:~/src/tmp $ git clone https://github.com/WolfSSL/wolfssl
Cloning into 'wolfssl'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 71269 (delta 2), reused 4 (delta 1), pack-reused 71258
Receiving objects: 100% (71269/71269), 86.43 MiB | 854.00 KiB/s, done.
Resolving deltas: 100% (52522/52522), done.

lingbin@baidudeMacBook-Pro:~/src/tmp $ git --version
git version 2.20.1 (Apple Git-117)
```
So the behavior may be slightly different on different OS or on different git version.

In order to avoid hidden problems, I feel that it is better to use the way github suggested：https://help.github.com/en/articles/cloning-a-repository, using both **the correct spelling** and **the .git suffix**. Do you agree? @an3l @svoj 

There is still a problem that needs help, I don't know why this PR will hurts the `buildbot`, I don't know how to fix the problem.

**Comment by an3l** [comment]
Hi @lingbin,
I agree in general about correct spelling and .git suffix.
Did you try suggested approach using `git submodule` from mariadb server?

**Comment by lingbin** [comment]
hi @an3l 

Do you mean that executing `git submodule update` before executing the `cmake` command?

I cloned a new repository and then executed `git submodule update` with no output.
Then I continue to do `cmake` and the result is the same

```
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) registered for path 'extra/wolfssl/wolfssl'
Submodule 'libmariadb' (https://github.com/MariaDB/mariadb-connector-c) registered for path 'libmariadb'
Submodule 'storage/maria/libmarias3' (https://github.com/mariadb-corporation/libmarias3) registered for path 'storage/maria/libmarias3'
Submodule 'storage/rocksdb/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'storage/rocksdb/rocksdb'
Submodule 'wsrep-lib' (https://github.com/codership/wsrep-lib.git) registered for path 'wsrep-lib'
Cloning into '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl'...
fatal: repository 'https://github.com/WolfSSL/wolfssl/' not found
fatal: clone of 'https://github.com/WolfSSL/wolfssl' into submodule path '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl' failed
Failed to clone 'extra/wolfssl/wolfssl'. Retry scheduled
Cloning into '/home/ssd1/lingbin/tmp/server/libmariadb'...
...
```

**Comment by an3l** [comment]
Did you try to run `git submodule init` before `git submodule update` ?

**Comment by lingbin** [comment]
Hi @an3l , it is the same error
```
$ git clone https://github.com/lingbin/server.git
...

$ git submodule init
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) registered for path 'extra/wolfssl/wolfssl'
Submodule 'libmariadb' (https://github.com/MariaDB/mariadb-connector-c) registered for path 'libmariadb'
Submodule 'storage/maria/libmarias3' (https://github.com/mariadb-corporation/libmarias3) registered for path 'storage/maria/libmarias3'
Submodule 'storage/rocksdb/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'storage/rocksdb/rocksdb'
Submodule 'wsrep-lib' (https://github.com/codership/wsrep-lib.git) registered for path 'wsrep-lib'

$ git submodule update
Cloning into '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl'...
fatal: repository 'https://github.com/WolfSSL/wolfssl/' not found
fatal: clone of 'https://github.com/WolfSSL/wolfssl' into submodule path '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl' failed
Failed to clone 'extra/wolfssl/wolfssl'. Retry scheduled
Cloning into '/home/ssd1/lingbin/tmp/server/libmariadb'...
```

**Comment by svoj** [comment]
@lingbin could you retarget this PR for 10.4? No need to create new one, just cherry-pick your change to 10.4 and force push to `fix_submodule_url` branch. Otherwise I agree.

**Comment by an3l** [comment]
These are exactly the steps I did, 
@lingbin although your patch will be applied, can we go one more iteration to confirm we are doing right with current configuration? 

```
$ git clone https://github.com/lingbin/server.git
```
```
$ git submodule
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
-c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb
-e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a storage/maria/libmarias3
-926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb
-e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib
```
```
$ cmake . -DCMAKE_BUILD_TYPE=debug

-- Packaging as: mariadb-10.5.0-Linux-x86_64
-- Updating submodules
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) registered for path 'extra/wolfssl/wolfssl'
Submodule 'libmariadb' (https://github.com/MariaDB/mariadb-connector-c) registered for path 'libmariadb'
Submodule 'storage/maria/libmarias3' (https://github.com/mariadb-corporation/libmarias3) registered for path 'storage/maria/libmarias3'
Submodule 'storage/rocksdb/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'storage/rocksdb/rocksdb'
Submodule 'wsrep-lib' (https://github.com/codership/wsrep-lib.git) registered for path 'wsrep-lib'
Cloning into '/home/anel/workspace/server/extra/wolfssl/wolfssl'...
Cloning into '/home/anel/workspace/server/libmariadb'...
Cloning into '/home/anel/workspace/server/storage/maria/libmarias3'...
Cloning into '/home/anel/workspace/server/storage/rocksdb/rocksdb'...
Cloning into '/home/anel/workspace/server/wsrep-lib'...
Submodule path 'extra/wolfssl/wolfssl': checked out '21f2beca9f320199fcea4a96df3e19967804144b'
Submodule path 'libmariadb': checked out 'c098613d289ed88fc53286e98add28ae9f2d8b46'
Submodule path 'storage/maria/libmarias3': checked out 'e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a'
Submodule path 'storage/rocksdb/rocksdb': checked out '926f3a78a64b327475ee6c60b6c8ab4f34253204'
Submodule path 'wsrep-lib': checked out 'e9dafb73734d71ab55078b34748e54f139aec827'
Submodule 'wsrep-API/v26' (https://github.com/codership/wsrep-API.git) registered for path 'wsrep-lib/wsrep-API/v26'
Cloning into '/home/anel/workspace/server/wsrep-lib/wsrep-API/v26'...
Submodule path 'wsrep-lib/wsrep-API/v26': checked out '75a5f452f2ba07b0f4a3a9a94825fccc71b27398'
```
```
$ git submodule
 21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl (v4.0.0-stable)
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a storage/maria/libmarias3 (libmarias3-3.1.0-2-ge4b7d2f)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (remotes/origin/revert-encryption-37-ge9dafb7)
```

**Comment by lingbin** [comment]
Hi @svoj 
Because there is no `libmarias3` submodule on the `10.4` branch, direct cherry-pick will fail. Should I submit a new PR to 10.4?


Hi @an3l 
yes, I tried it again, my result is below
```
# step 1
git clone https://github.com/lingbin/server.git
...

$ cat .gitmodules
[submodule "libmariadb"]
        path = libmariadb
        url = https://github.com/MariaDB/mariadb-connector-c
[submodule "storage/rocksdb/rocksdb"]
        path = storage/rocksdb/rocksdb
        url = https://github.com/facebook/rocksdb.git
[submodule "wsrep-lib"]
        path = wsrep-lib
        url = https://github.com/codership/wsrep-lib.git
        branch = master
[submodule "extra/wolfssl/wolfssl"]
        path = extra/wolfssl/wolfssl
        url = https://github.com/WolfSSL/wolfssl
[submodule "storage/maria/libmarias3"]
        path = storage/maria/libmarias3
        url = https://github.com/mariadb-corporation/libmarias3

# step 2
$ git submodule
-21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl
-c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb
-e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a storage/maria/libmarias3
-926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb
-e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib

# step 3
$ cmake . -DCMAKE_BUILD_TYPE=debug
...
-- Packaging as: mariadb-10.5.0-Linux-x86_64
-- Updating submodules
Submodule 'extra/wolfssl/wolfssl' (https://github.com/WolfSSL/wolfssl) registered for path 'extra/wolfssl/wolfssl'
Submodule 'libmariadb' (https://github.com/MariaDB/mariadb-connector-c) registered for path 'libmariadb'
Submodule 'storage/maria/libmarias3' (https://github.com/mariadb-corporation/libmarias3) registered for path 'storage/maria/libmarias3'
Submodule 'storage/rocksdb/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'storage/rocksdb/rocksdb'
Submodule 'wsrep-lib' (https://github.com/codership/wsrep-lib.git) registered for path 'wsrep-lib'
Cloning into '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl'...
fatal: repository 'https://github.com/WolfSSL/wolfssl/' not found
fatal: clone of 'https://github.com/WolfSSL/wolfssl' into submodule path '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl' failed
Failed to clone 'extra/wolfssl/wolfssl'. Retry scheduled
Cloning into '/home/ssd1/lingbin/tmp/server/libmariadb'...
warning: redirecting to https://github.com/MariaDB/mariadb-connector-c.git/
Cloning into '/home/ssd1/lingbin/tmp/server/storage/maria/libmarias3'...
warning: redirecting to https://github.com/mariadb-corporation/libmarias3.git/
Cloning into '/home/ssd1/lingbin/tmp/server/storage/rocksdb/rocksdb'...
Cloning into '/home/ssd1/lingbin/tmp/server/wsrep-lib'...
Cloning into '/home/ssd1/lingbin/tmp/server/extra/wolfssl/wolfssl'...
Submodule path 'extra/wolfssl/wolfssl': checked out '21f2beca9f320199fcea4a96df3e19967804144b'
Submodule path 'libmariadb': checked out 'c098613d289ed88fc53286e98add28ae9f2d8b46'
Submodule path 'storage/maria/libmarias3': checked out 'e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a'
Submodule path 'storage/rocksdb/rocksdb': checked out '926f3a78a64b327475ee6c60b6c8ab4f34253204'
Submodule path 'wsrep-lib': checked out 'e9dafb73734d71ab55078b34748e54f139aec827'
Submodule 'wsrep-API/v26' (https://github.com/codership/wsrep-API.git) registered for path 'wsrep-lib/wsrep-API/v26'
Cloning into '/home/ssd1/lingbin/tmp/server/wsrep-lib/wsrep-API/v26'...
Submodule path 'wsrep-lib/wsrep-API/v26': checked out '75a5f452f2ba07b0f4a3a9a94825fccc71b27398'
Submodule path 'extra/wolfssl/wolfssl': checked out '21f2beca9f320199fcea4a96df3e19967804144b'
-- Performing Test HAVE_VISIBILITY_HIDDEN
...

# step 4
$ git submodule
 21f2beca9f320199fcea4a96df3e19967804144b extra/wolfssl/wolfssl (v4.0.0-stable)
 c098613d289ed88fc53286e98add28ae9f2d8b46 libmariadb (v3.0.2-453-gc098613)
 e4b7d2ffdbf9db3bdd26af0d6a8cc0ed3980571a storage/maria/libmarias3 (libmarias3-3.1.0-2-ge4b7d2f)
 926f3a78a64b327475ee6c60b6c8ab4f34253204 storage/rocksdb/rocksdb (v5.8-791-g926f3a78a)
 e9dafb73734d71ab55078b34748e54f139aec827 wsrep-lib (remotes/origin/revert-encryption-37-ge9dafb7)
```
There are two points to note, 
1. Although the first prompt `fatal: repository 'https://github.com/WolfSSL/wolfssl/' not found`, but in the end it automatically retryed and succeeded.
2. For `libmariadb` and `libmarias3` with correct spelling but without the `.git` suffix, the corresponding warning prompt(`warning: redirecting to https://github.com/MariaDB/mariadb-connector-c.git/
`), which is redirecting to the url with `.git` suffix.

**Comment by svoj** [comment]
Thanks! No need to do anything extra, I'll get this backported myself.

**Pull request merged**
