### PR TITLE
MDEV-7384 Add --persistent option for mysqlcheck

### PR DESCRIPTION
**Pull request by grooverdan**
10.0 has an "analyze table .. persistent for all" syntax. This adds
--persistent to mysqlcheck(mysqlanalyize) to perform this extended
analyze table option.

From MDEV-7384

### CODE REVIEW

**Comment by grooverdan** [comment]
I submit this under BSD-new license

**Comment by svoj** [comment]
@grooverdan, PR#38 seem to be about the same issue. Should we close one of these?

**Comment by grooverdan** [comment]
it was targeting a different branch. close which ever one you're not going to use.

**Comment by cvicentiu** [comment]
Commited your code with test cases in 3b9423fda2612a463e9f3af5750234ccf2667545

Thank you for the contribution!

**Pull request closed without merging**
