### PR TITLE
MDEV-27033: Remove version suffix from Debian packages

### PR DESCRIPTION
**Pull request by illuusio**
- [x] *The Jira issue number for this PR is: MDEV-27033*

## Description
Remove version suffix from Debian packages (for example mariadb-server-10.8)
because installing suffixed package removes older version
of package even if it's suffixed (for example mariadb-server-10.7)

This make also Debian package management easier in future MariaDB
version iterations because there is no need for stacking
Conlicts/Breaks/Replaces-parameters in every new major release

## How can this PR be tested?
Launch Debian or Ubuntu instance. Run `debian/autobake-deb.sh` script to build deb packages and install created packages over the current Debian or Ubuntu packages

This can be autotested but should be make sure in Buildbot instances that it uses correct version system.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*

## Backward compatibility
All the older control file Breaks, Conflict and Replaces are in place so it will work as suffixed version and remove older versions. There also comparability Provides with suffix. Metapackage for server and client is removed as it's not needed anymore

### CODE REVIEW

**Comment by ottok** [comment]
I have been thinking about doing this change as well. Nice that you did it now. I will review this as soon as I have time.

**Comment by cvicentiu** [comment]
@illuusio Thanks for the work done on this. Couple of comments:

PR related:
1. Why did we have suffixed versions before? This one is also probably for @ottok. Is there anything that relied on suffixed package names that we are missing?

Process related:
2. Remember that force-pushing to a PR branch invokes the whole CI process. Doing it in quick succession (4 times in the span of an hour) invokes 4 builds. This is not a good use of our testing resources. Please make an effort to avoid pushes that require "minor tweaks". Think through the patch properly, then only push for CI testing once.

3. It looks like *you* are working on this MDEV, however in JIRA it is assigned to @grooverdan, which makes it confusing who is the person actually working. If *you* are working on the MDEV, assign it to yourself and mark it as "IN PROGRESS". Afterwards, assign to the reviewer and mark it as "IN REVIEW". Once review is done, reassign to yourself and mark it as in progress when you start working on the review comments.

Logging hours spent also will help us in measuring how well we are doing with estimates vs actual time spent so please try and do that as well.

**Comment by illuusio** [comment]
> * Remember that force-pushing to a PR branch invokes the whole CI process. Doing it in quick succession, 4 times in the span of an hour, invokes 4 builds. This is not a good use of our testing resources. Please make an effort to avoid pushes that require "minor tweaks". Think through the patch properly, then only push for CI testing once.
> 
> * It looks like _you_ are working on this MDEV, however in JIRA it is assigned to @grooverdan, which makes it confusing who is the person actually working. If _you_ are working on the MDEV, assign it to yourself and mark it as "IN PROGRESS". Afterwards, assign to the reviewer and mark it as "IN REVIEW". Once review is done, reassign to yourself and mark it as in progress when you start working on the review comments.

Ok I'll take these notes. Is there somewhere documentation about this or it just how it goes?

**Comment by illuusio** [comment]
> 1. Why did we have suffixed versions before? This one is also probably for @ottok. Is there anything that relied on suffixed package names that we are missing?

If I understood correctly it was first place because Ubuntu wanted to have 2 separated version supported MariaDB but I think @ottok can shed light on this as you said.

**Comment by vuvova** [comment]
I was told (many years ago) that the logic was

- the user can install mariadb-server and then it'll upgrade as needed, following whatever in the repo, from 10.2 to 10.3, 10.4, 10.5, etc.
- alternatively the user can install mariadb-server-10.3 (for example) and then it'll upgrade within the 10.3 series, but will never jump automatically to 10.4.

So yes, if you remove version suffixes you will remove a feature.
But I don't know if this feature is really needed, RPMs seem to live fine without it.

**Comment by illuusio** [comment]
> * the user can install mariadb-server and then it'll upgrade as needed, following whatever in the repo, from 10.2 to 10.3, 10.4, 10.5, etc.

Actually no. If you read `debian/control` mariadb-server-10.8 (original branch) there is Conflict, Replace and Suggest you will note that all the other older versions are removed from system even when suffixed package is installed. Same goes if you install `mariadb-server` meta package every old one is removed.

> * alternatively the user can install mariadb-server-10.3 (for example) and then it'll upgrade within the 10.3 series, but will never jump automatically to 10.4.

Future is here and if we believe Container (Docker/Podman) is what most people install and use then this scenario gets more and more out of scope. Every Debian version has newer version of MariaDB so  without adding MariaDB official version repository of for example 10.3 to keep using 10.3 if new Debian wants to install 10.4 anyway.

All the other Distros (Redhat, Fedora, Arch and SUSE) have survive without this from the beginning and if something is wanted to keep suffixed it's library package but then it's efficient to use  same pattern as everyone else (only when it break rise a number in package and share object) not tied with release or branch.

Otherwise this can be closed and then there Replace, Suggests and Conflicts has to removed or altered and then tested that if user really have two separated version everything related (for example systemd scripts) does not overlap each other.

I understand totally enterprise admins and users which want to use same version until sun sets over it as said RPM does not have suffix and there is not big fuss about it.

**Comment by ottok** [comment]
> I was told (many years ago) that the logic was
> 
> * the user can install mariadb-server and then it'll upgrade as needed, following whatever in the repo, from 10.2 to 10.3, 10.4, 10.5, etc.
> * alternatively the user can install mariadb-server-10.3 (for example) and then it'll upgrade within the 10.3 series, but will never jump automatically to 10.4.
> 
> So yes, if you remove version suffixes you will remove a feature. But I don't know if this feature is really needed, RPMs seem to live fine without it.

This is the same I've heard, and it applies for MySQL/MariaDB packaging in Debian at least since MySQL 5.5, but probably older as well.

@illuusio's reply mixes up co-installability. This setup does not allow co-installation of multiple MariaDB versions, it only facilitates pinning down the MariaDB installation to a certain version to prevent upgrades.

None the less, I don't think this feature has had much use, and I am in favor of dropping versions from packages names completely.

To test this with Salsa-CI I just triggered builds:
* baseline for 10.8: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/333799
* change: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/333797

**Comment by grooverdan** [comment]
Ok, it looks like the dependencies of plugins needs to be a bit more accurate and the other introduced salsa regressions, but otherwise the concept is sound. Looking forward to the result.

**Comment by illuusio** [comment]
> To test this with Salsa-CI I just triggered builds:
> 
>     * baseline for 10.8: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/333799
> 
>     * change: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/333797

I looked Salsa-CI outputs and there Replaces/Breaks missing in missing-breaks which should be sorted out.  It seems Lintian warnings should be cleaned up to make sure false-positives could be spotted more easily (but that is for another PR) also lz4 smoke test is not working which should be sorted out.

**Comment by ottok** [comment]
Seems there are several regressions on 10.8 already on baseline now: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/338174 (and thus e.g. the lz4 failure is from the mariadb-plugin-provider-* change and not from this PR).

**Comment by illuusio** [comment]
> Seems there are several regressions on 10.8 already on baseline now: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/338174 (and thus e.g. the lz4 failure is from the mariadb-plugin-provider-* change and not from this PR).

Should these be ironed out with another PR before going further with this as then 'real' regressions could be spotted.

**Comment by ottok** [comment]
> > Seems there are several regressions on 10.8 already on baseline now: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/338174 (and thus e.g. the lz4 failure is from the mariadb-plugin-provider-* change and not from this PR).
> 
> Should these be ironed out with another PR before going further with this as then 'real' regressions could be spotted.

Yes, as fixing regressions caused by other commits is out of scope of this PR and should do in other PRs. This PR itself should ideally be tested against a green CI and verified that it stays green.

**Comment by grooverdan** [comment]
@illuusio I think you can do a PR against salsa to get the change tested, and when it don't regress, submit that patch here with a link to the test. 10.8 release is getting prepared so this is the very last of the 10.8 chance.

**Comment by ottok** [comment]
@illuusio If you have any PRs here about fixing upstream version of [salsa-ci.yml](https://github.com/MariaDB/server/blob/10.5/debian/salsa-ci.yml), feel free to mark me as reviewer. You should start by fixing the one on the 10.5 branch, so that the basic stuff works again (it refressed some months ago) and then wait for 10.5 to be merged upwards, and fix the remaining stuff per branch.

**Comment by illuusio** [comment]
> @illuusio If you have any PRs here about fixing upstream version of [salsa-ci.yml](https://github.com/MariaDB/server/blob/10.5/debian/salsa-ci.yml), feel free to mark me as reviewer. You should start by fixing the one on the 10.5 branch, so that the basic stuff works again (it refressed some months ago) and then wait for 10.5 to be merged upwards, and fix the remaining stuff per branch.

There is some but problem is most of them is Lintian error and for example: `library-not-linked-against-libc` can't do nothing about it as for example `provider_bzip2.so` does not have any symbols from libc so it's false-positive which should be upstreamed to Lintian like Octave plugins are handled but that is long way before it's fixed and `version-substvar-for-external-package` is kind of problematic as it needs to remove some package deps to make it do away but I assume they are correct and they are there for some reason.

All the others where fixed until something breaked `main.group_min_max` test in autopkg and in break test blaming that `mariadb.pc` is conflicting but it should not I have to find why..

**Comment by ottok** [comment]
Working to fix salsa-ci.yml for [10.5](https://github.com/MariaDB/server/pull/2038) and [10.6](https://github.com/MariaDB/server/pull/2039). Once the 10.6 version has been merged upwards, you can take over and tweak it for 10.7/8/9 compatibility and then continue with this PR.

**Comment by illuusio** [comment]
This one is now on target and I'll fix those merge problems

**Review by ottok — COMMENTED** [review]
Looks good!

**Review by ottok — COMMENTED** [review]
Looks good!

**Comment by illuusio** [comment]
Last build for this on Salsa-CI and 10.9 is: https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/368232

**Comment by illuusio** [comment]
Noticed that Columnstore was not correctly handled. Now it's fixed and another BB run should be done.

**Pull request merged**
