### PR TITLE
MDEV-23051: riscv64 fails build (atomics)

### PR DESCRIPTION
**Pull request by grooverdan**
riscv64 fails to build because the use
of #include <atomic> needs to link with -latomic.

per https://github.com/riscv/riscv-gnu-toolchain/issues/183#issuecomment-253721765

@cpaelzer can you try this as a mariadb fix. I'm trying a bit more blind here because I can't complete a mariadb cross compile like I did on RocksDB. This is also why the RocksDB cmake patch doesn't work on mariadb, mariadb copied the rocksDB cmake logic to build_rocksdb.cmake

### CODE REVIEW

**Comment by cpaelzer** [comment]
@grooverdan thanks for the patch, it seems to work [here}(https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/4128/+build/19536778) - the build isn't complete yet but passed the stage it formerly crashed.

**Comment by grooverdan** [comment]
Thanks @cpaelzer completed successfully and did the complete build of rocksdb. Needs debian/ubuntu arch tagging in your build to complete the package coming out, but as far as upstream here in debian/control mariadb-plugin-rocksdb is still marked for all architectures.

@xnox  MariaDB fix here.

**Comment by grooverdan** [comment]
Yes, that would be a better approach, though would probably need to compile check again with the libs added to ensure that's the right resolution.

I don't have a complete cross compile setup for riscv64 and would rather not blind test this too much. Can we take the good over perfect as the launchpad tests where based on the commit as is? I haven't see other arches require atomic libs so this really might be just risc.

**Comment by grooverdan** [comment]
Constraining to the target arch to limit adverse secondary effects in a stable branch.

**Pull request merged**
