### PR TITLE
MDEV-33460 select '123' 'x'; unexpected result

### PR DESCRIPTION
**Pull request by DaveGosselin-MariaDB**
Queries that select concatenated constant strings now have colname and value that match.  For example,
  SELECT '123' 'x';
will return a result where the column name and value both are '123x'.

### CODE REVIEW

**Comment by grooverdan** [comment]
Looks good so far. One more test case:

```
MariaDB [(none)]> set sql_mode=EMPTY_STRING_IS_NULL
    -> ;
Query OK, 0 rows affected (0.000 sec)

MariaDB [(none)]> select '';
+------+
| NULL |
+------+
| NULL |
+------+
1 row in set (0.000 sec)

MariaDB [(none)]> select '' 'chicken';
+---------+
| chicken |
+---------+
| chicken |
+---------+
1 row in set (0.000 sec)

MariaDB [(none)]> select '' 'chicken' 'dog';
+------------+
| chicken    |
+------------+
| chickendog |
+------------+
1 row in set (0.000 sec)
```

Needs correction in `Item_null::make_string_literal_concat` I suspect. As Item_basic_constant is virtual, this appears to be the last of `make_string_literal_concat` that needs addressing.

Any reason not to fix earlier 10.4/10.5/10.6?

**Comment by DaveGosselin-MariaDB** [comment]
> MariaDB [(none)]> set sql_mode=EMPTY_STRING_IS_NULL
>     -> ;
> Query OK, 0 rows affected (0.000 sec)
> MariaDB [(none)]> select '' 'chicken' 'dog';
> +------------+
> | chicken    |
> +------------+
> | chickendog |
> +------------+
> 1 row in set (0.000 sec)
> ```

Great catch @grooverdan I did not know about this option for `sql_mode`.  I will fix.

> Any reason not to fix earlier 10.4/10.5/10.6?

I think I found this in 11.4 because that's where I was working on another feature.  I don't have any problem delivering to an earlier release instead.  IIRC 10.5 is now the earliest we should deliver to, yes?

**Comment by grooverdan** [comment]
afaik 10.4 isn't fully closed, there was an ambiguity about when it was its last release. So this could go 10.4 or 10.5. I'd probably go 10.5.

**Comment by DaveGosselin-MariaDB** [comment]
@grooverdan are you certain that you applied my patch?  When I test both `10.5` and `11.4` with my patch as it is, I get the expected correct results:

```
$ ./mariadb-build/sql/mariadbd  --version
./mariadb-build/sql/mariadbd  Ver 11.4.2-MariaDB-debug for Linux on aarch64 (Source distribution)
$ git log -1
commit d81d9c45f21915dc3bd989435c5db164a76d2fc7 (HEAD -> 11.4-mdev-33460, origin/11.4-mdev-33460)
Author: Dave Gosselin <dave.gosselin@mariadb.com>
Date:   Wed Mar 13 16:56:37 2024 -0400

    MDEV-33460 select '123' 'x'; unexpected result

    Queries that select concatenated constant strings now have
    colname and value that match.  For example,
      SELECT '123' 'x';
    will return a result where the column name and value both
    are '123x'.
$ mariaclient
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 11.4.2-MariaDB-debug Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [test]> set sql_mode=EMPTY_STRING_IS_NULL;
Query OK, 0 rows affected (0.001 sec)

MariaDB [test]> select @@sql_mode;
+----------------------+
| @@sql_mode           |
+----------------------+
| EMPTY_STRING_IS_NULL |
+----------------------+
1 row in set (0.002 sec)

MariaDB [test]> select '';
+------+
| NULL |
+------+
| NULL |
+------+
1 row in set (0.002 sec)

MariaDB [test]> select '' 'chicken';
+---------+
| chicken |
+---------+
| chicken |
+---------+
1 row in set (0.002 sec)

MariaDB [test]> select '' 'chicken' 'dog';
+------------+
| chickendog |
+------------+
| chickendog |
+------------+
1 row in set (0.001 sec)
```

**Review by grooverdan — APPROVED** [review]

**Pull request merged**
