### PR TITLE
MDEV-9046 - Updated build dependency list

### PR DESCRIPTION
**Pull request by darkain**
Both the pkg-config and libxml2-dev packages are required to build MariaDB 10.1 on Debian 8.2

### CODE REVIEW

**Comment by svoj** [comment]
Hi Vince,

thanks for you contribution. JIRA task has been created to track this pull request: https://mariadb.atlassian.net/browse/MDEV-9046

This task was added to 10.1.9 backlog, which is planned to be handled between 2015-10-27 and 2015-11-17.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by darkain** [comment]
MCA has been sent in

**Comment by ottok** [comment]
Thanks @darkain for your time to look into this issue.

Could you please provide a little bit of additional motivation why these to dependencies are required, what uses them and what is the symptom if they are not present?

I've build 10.1 on Debian 8 (Jessie) without these dependencies in the past and have not noticed any problems (e.g. log at http://labs.seravo.fi/~otto/mariadb-repo/mariadb-jessie-amd64/mariadb-10.1_10.1.0_amd64.build-a88f03a-pbuilder.log)

**Comment by svoj** [comment]
@darkain, could you comment on @ottok's question? Otherwise we'll have to close this PR as no feedback was provided.

**Comment by svoj** [comment]
Closing as no feedback was provided. Feel free to reopen this issue.

**Pull request closed without merging**
