### PR TITLE
MDEV-27038 Custom configuration file procedure does not work with Doc…

### PR DESCRIPTION
**Pull request by grooverdan**
…ker Desktop for Windows 10+

- [x] *The Jira issue number for this PR is: MDEV-______*

## Description

Docker when mounting a configuration file into a Windows exposes the file with permission 0777. These world writable files are ignored by by MariaDB.
ref; https://docs.docker.com/desktop/troubleshoot/overview/#volumes

Add the access check such that filesystem RO or immutable file is counted as sufficient protection on the file.

## How can this PR be tested?

Test:
$ mkdir /tmp/src
$ vi /tmp/src/my.cnf
$ chmod 666 /tmp/src/my.cnf
$ mkdir /tmp/dst
$ sudo mount --bind /tmp/src /tmp/dst -o ro
$ ls -la /tmp/dst
total 4
drwxr-xr-x.  2 dan  dan   60 Jun 15 15:12 .
drwxrwxrwt. 25 root root 660 Jun 15 15:13 ..
-rw-rw-rw-.  1 dan  dan   10 Jun 15 15:12 my.cnf
$ mount | grep dst
tmpfs on /tmp/dst type tmpfs (ro,seclabel,nr_inodes=1048576,inode64)

strace client/mariadb --defaults-file=/tmp/dst/my.cnf

newfstatat(AT_FDCWD, "/tmp/dst/my.cnf", {st_mode=S_IFREG|0666, st_size=10, ...}, 0) = 0
access("/tmp/dst/my.cnf", W_OK)         = -1 EROFS (Read-only file system)
openat(AT_FDCWD, "/tmp/dst/my.cnf", O_RDONLY|O_CLOEXEC) = 3

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ X ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ X ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by grooverdan** [comment]
This should pop out as a testable container `quay.io/mariadb-foundation/mariadb-devel:10.4-MDEV-27038-ro-mounts-pkgtest` in a few hrs.

**Review by LinuxJedi — DISMISSED** [review]
Good call, I think this could be useful for immutable OSes which appear to be popping up as well.

**Comment by LinuxJedi** [comment]
Got rid of my original approval because I think the comment could be adjusted and there are some scenarios discussed that could need testing.

**Comment by grooverdan** [comment]
Re-read the comment request, and I'm missing the point of what was wrong with it. Expanded comment significantly.

Completed Windows test successfully. Made the `access` a narrowly scoped exception on EROFS/EPERM rather than any error. Other errors are handing in statfs/open.

@gremo as this is a fix for your SO question, can you test the container quay.io/mariadb-foundation/mariadb-devel:10.4-MDEV-27038-ro-mounts-pkgtest in your scenario to see if RO volume mounts work as expected.

**Comment by gremo** [comment]
@grooverdan same mount, using `quay.io/mariadb-foundation/mariadb-devel:10.4-MDEV-27038-ro-mounts-pkgtest` as `image` no errors shown, right permissions for `80-app.cnf`:

```
# ls -la /etc/mysql/mariadb.conf.d/
total 40
drwxr-xr-x 1 root root 4096 Jun 16 12:40 .
drwxr-xr-x 1 root root 4096 Jun  9 23:30 ..
-rw-r--r-- 1 root root   46 Jun  9 23:30 05-skipcache.cnf
-rw-r--r-- 1 root root  575 Jun  5 19:14 50-client.cnf
-rw-r--r-- 1 root root  231 Jun  5 19:14 50-mysql-clients.cnf
-rw-r--r-- 1 root root  927 Jun  5 19:14 50-mysqld_safe.cnf
-rw-r--r-- 1 root root 3584 Jun  9 23:30 50-server.cnf
-rw-r--r-- 1 root root  570 Jun  5 19:14 60-galera.cnf
-rw-r--r-- 1 root root  167 Jun 14 16:39 80-app.cnf
drwxr-xr-x 2 root root 4096 Jun  9 23:30 99-enable-encryption.cnf.preset
```

**Comment by grooverdan** [comment]
> @grooverdan same mount, using `quay.io/mariadb-foundation/mariadb-devel:10.4-MDEV-27038-ro-mounts-pkgtest` as `image` no errors shown, right permissions for `80-app.cnf`:

Thanks for testing. I never actually changed the permissions on the `80-app.cnf` file, only accepted the read-only filesystem status. As its showing a change in permission from 777 its looks like your test is different this time and not demonstrating the original problem is solved.

**Comment by gremo** [comment]
I'll double  check and re-do the test @grooverdan

**Comment by LinuxJedi** [comment]
> Re-read the comment request, and I'm missing the point of what was wrong with it. Expanded comment significantly.

The problem with the comment is changing from this:
```
      Ignore world-writable regular files.
      This is mainly done to protect us to not read a file created by
      the mysqld server, but the check is still valid in most context. 
```
To this:
```
      Ignore world-writable regular files (exceptions apply).
      This is mainly done to protect us to not read a file that may be
      modified by anyone.
```

I think the original comment is more correct there, it doesn't protect us against a file that may be modified by anyone. Only files that may be modified by MariaDB Server. This only checks if MariaDB Server can write, not other users / processes (which would be extremely difficult to do).

**Comment by grooverdan** [comment]
> I think the original comment is more correct there, it doesn't protect us against a file that may be modified by anyone. 

`(stat_info.st_mode & S_IWOTH)` - so write permission by others is the base criteria.

> Only files that may be modified by MariaDB Server. This only checks if MariaDB Server can write

`access(name, W_OK) == 0` is just acting as a shortcut not to check `errno` if its not set.

`errno == EACCESS`, aka user cannot write, still ends up inside the if condition "Warning: World-writable config file".

So the W_OK `access` check is only checking that `EROFS`/`EPERM` aren't set, on the assumption that those failures are for everyone.

>, not other users / processes (which would be extremely difficult to do).

Correct, the base `(stat_info.st_mode & S_IWOTH)` that is checked, can be limited further by any LSM (or non Linux restriction) that we can't check.

So with this, how should it be worded?

```
      Ignore world-writable regular files (exceptions apply).
      This is done to protect us to not read a file that may be
      modified by anyone.

     The modified by anyone isn't checking beyond world-writable files, read only filesystems, or immutable files. Other Linux Security Modules or other additional operating system protections may prevent the modification of the file, even though the file has world writeable permissions. These cannot be checked, so we assume the worst.

    Read only filesystems and immutable files are checked from the current user's access level, and its assumed other users will encounter the same errors.
```

**Comment by gremo** [comment]
Ok @grooverdan sorry for the mistake, at least for me, the errors is still there. I've removed and recreated the containers/volumes etc. just to be sure.

```txt
2023-06-23 16:42:38 Warning: World-writable config file '/etc/mysql/mariadb.conf.d/80-app.cnf' is ignored
2023-06-23 16:42:38 2023-06-23 16:42:38 0 [Note] Starting MariaDB 10.11.4-MariaDB-1:10.11.4+maria~ubu2204 source revision 4e2b93dffef2414a11ca5edc8d215f57ee5010e5 as process 1
```

Immagine 2023-06-23 164409

```shell
# ls -la /etc/mysql/mariadb.conf.d/
# ls -la /etc/mysql/mariadb.conf.d/
total 40
drwxr-xr-x 1 root root 4096 Jun 23 16:42 .
drwxr-xr-x 1 root root 4096 Jun 16 05:08 ..
-rw-r--r-- 1 root root   46 Jun 16 05:08 05-skipcache.cnf
-rw-r--r-- 1 root root  575 Jun  5 19:14 50-client.cnf
-rw-r--r-- 1 root root  231 Jun  5 19:14 50-mysql-clients.cnf
-rw-r--r-- 1 root root  927 Jun  5 19:14 50-mysqld_safe.cnf
-rw-r--r-- 1 root root 3584 Jun 16 05:08 50-server.cnf
-rw-r--r-- 1 root root  570 Jun  5 19:14 60-galera.cnf
-rwxrwxrwx 1 root root  167 Jun 20 21:01 80-app.cnf
drwxr-xr-x 2 root root 4096 Jun 16 05:08 99-enable-encryption.cnf.preset
```

**Comment by grooverdan** [comment]
The reading of world-writable files is there for read-only volumes of the configuration files.

**Review by LinuxJedi — APPROVED** [review]

**Pull request merged**
