### PR TITLE
MDEV-17076: Allow negative number for --max-save-* options for no saving

### PR DESCRIPTION
**Pull request by shinnok**

### CODE REVIEW

**Comment by grooverdan** [comment]
what value does having negative   max-save-{datadir|core} provide?

**Comment by shinnok** [comment]
When testing in memory with `--mem` in a normal bare-bone Buildbot worker, MTR can leave behind as much as 3G (or even more with --big) in my tests, not to count for coredumps. This is because the var/ and coredumps are not properly cleaned up and they accrue in the shared memory, thus exhausting it in a short while resulting in failure for further MTR invocations.

Having this feature, allows one to clear up after every invocation, but logs are still preserved by Buildbot of course.

NB: This is a partial fix for the actual problem I'm facing, `./mtr --mem --parallel n` also creates n directories in `./var` with leftovers after completion too, in addition to what already ends up in `./var/log`.

**Comment by grooverdan** [comment]
I see, designing around the poor choice of 0 being unlimited made in distant past.

Can't we just pay back the software debt by changing defaults to X large number and making 0 mean 0? There may be a couple of instances of `--max-save-core=0` / `--max-save-datadir=0` wanting to be unlimited however, I think if they really wanted cores they'll quickly find cores/datadirs missing, and that the API is changed, and they can use a saner large number instead.

Preserving poor choices by adding more poor usability options, like "negative means 0", is just adding to software debt.

Surely a small break in the command line API of a test script runner is acceptable.

**Comment by an3l** [comment]
Closed with PR #1633

**Pull request closed without merging**
