### PR TITLE
support row based replication, read and write of MySQL 5.7.x JSON binary

### PR DESCRIPTION
**Pull request by Dieken**
See https://mariadb.com/kb/en/library/json-data-type/#replicating-json-data-between-mysql-and-mariadb.

I would like to use temporal table feature in a MariaDB slave that replicates from a MySQL 5.7.x master,  it's a pity MariaDB doesn't support row based replication of MySQL JSON column.

I meant to add some tests, but this requires a MySQL server running, I'm not sure how to fit MariaDB's test framework if there is any.

### CODE REVIEW

**Comment by an3l** [comment]
Hi @Dieken ,
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.
Thanks,
Anel

**Comment by Dieken** [comment]
I have already signed the CLA yesterday to choose contribution agreement, the cla-assistant.io web site also shows I signed it,  but the comment above still shows "CLA not signed yet".   Click "recheck" doesn't work.

**Comment by Dieken** [comment]
The initial purpose was to support row based replication of JSON binary,  I just added capabilities to directly read and write MySQL tables including JSON binary columns,  so I don't have to do  mysqldump to initialize my MariaDB server.

**Comment by Dieken** [comment]
@an3l  any feedback to the patch?

**Comment by cvicentiu** [comment]
Hi @Dieken !

This is a very interesting patch. We have already worked on something very similar to allow MariaDB to upgrade from MySQL 5.7 tables with JSON. See https://jira.mariadb.org/browse/MDEV-18323

There are a few things we need to fix with your patch and we are not sure if we really want to do replication this exact way, yet. It is very likely to be done.

We had a few vacation days between devs responsible for this, but expect some progress in the next couple of weeks. We'll get back to you once we have pushed our work and work with you to merge the remaining logic from your PR.

Sorry for having this take a bit more time.

**Comment by Dieken** [comment]
@cvicentiu   Thanks for your information, very glad to know MariaDB team are working on this area!

I checked the JIRA issue,  I feel it's better to still allow drop-in replacement, don't have to do mysql_upgrade and even a rewrite on mysql 5.7 ibd files,  of course, users can do an explicit slow mysql_upgrade.

My patch implemented these features:

1. replicate from mysql 5.7:  this isn't covered by the JIRA issue,  I strongly suggest MariaDB supports this,  so that many people can safely try MariaDB as slave while still use Oracle MySQL as master.

Currently my patch dynamically converts binary json to text json on replication, so that MariaDB json functions  work on the MariaDB slave.

2. in-place read MySQL 5.7 ibd files containing JSON binary.

The JSON binary is also dynamically converted to text, so that MariaDB json functions still work.  With this feature I don't have to do slow "insert select" to convert table for read-only query.

3.  in-place update MySQL 5.7 ibd files containing JSON binary.

The JSON binary column is updated to text JSON,   my patch can read binary json and text json too,  this is transparent to users,  but the updated ibd files can't be read by Oracle MySQL any more.  This is nice to have feature.

I did a drop-in replacement to a production Oracle MySQL 5.7 slave,   mysql_check failed on two kinds of tables:  (1) with full text index  (2) with generated columns.    The first failure is known,  the second is possibly related to [my change](https://github.com/MariaDB/server/pull/1364/files#diff-9c172977fe0505bac353b9289a2ab1d5L2143),  I haven't got time to double check that.

**Comment by an3l** [comment]
Hi @Dieken the patch for MDEV-18323, related to MYSQL_JSON  was pushed to 10.5. 
Can you please rebase this PR to 10.5 and create subsequent changes related to replication only, followed by some test case ?

**Comment by an3l** [comment]
Closing this PR as there is a patch for MDEV-18323.
Thanks

**Pull request closed without merging**
