### PR TITLE
MDEV-27965: MariaDB needs at least libfmt version 7.0

### PR DESCRIPTION
**Pull request by illuusio**
- [x] *The Jira issue number for this PR is: MDEV-27965*

## Description
Add requirement in Debian control file for libfmt 7.0 which is needed for building MariaDB

## How can this PR be tested?
Try to build package without libfmt-dev >= 7.0.0 and it should fail

See Salsa-CI run:
https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/360727

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
As you need newer libfmt there is needed attention in `autobake.sh`.

### CODE REVIEW

**Comment by grooverdan** [comment]
pushing to 10.9 as new dependency.

Could push to 10.8 as not GA yet, but will need it to pass protected branches tests, but at the moment they don't have libfmt installed.

**Comment by ottok** [comment]
Change looks good. It might be worthwhile to mention in commit message what exactly in MariaDB needs libfmt (what fails to build if it is missing?) and that it is available in Debian 10 "Bullseye" onwards and Ubuntu 21.04 "Hirsute" onwards, as the debian/control file does not properly support inline comments, so git blame is the only way to check why dependencies were added.

**Comment by grooverdan** [comment]
Nothing failed to build as the cmake pulls down the libfmt version and bundles it in. So how do you do an optional dependency?

Updated 831cdcd532ae5a906e1c8fc0313668a9cd3d568b to show the SFORMAT implementation reference.

**Review by ottok — APPROVED** [review]
https://github.com/MariaDB/server/commit/831cdcd532ae5a906e1c8fc0313668a9cd3d568b looks good and approving it (note that it wasn't pushed on the PR yet)

**Comment by grooverdan** [comment]
merged in 13b97880bd8f6901225a1f8d6ff2eb6ba9303ceb with autobake changes.

Thanks @illuusio for code and thanks @ottok for review.

**Pull request closed without merging**
