### PR TITLE
MDEV-9209 - scripts: Do not prepend the prefix to absolute paths

### PR DESCRIPTION
**Pull request by olesalscheider**

### CODE REVIEW

**Comment by grooverdan** [comment]
why is this important? What behaviour will break with this change?

**Comment by olesalscheider** [comment]
The INSTALL_* variables can be absolute or relative to the prefix path. The current code only handles the case where they are relative. With the patch, the old behaviour is used as long as they are relative, but it fixes the case when they are absolute.

This is important for Exherbo since we have to use absolute paths because of our file system layout. Exherbo has /usr/share for arch-independent files and /usr/$ARCH/{bin,include,lib,libexec} for arch-dependent files, so that files for multiple architectures can be installed in parallel.

**Comment by svoj** [comment]
Hi Niels,

thanks for your contribution! I just wonder why the following didn't work for you?

cmake -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_BINDIR=$ARCH/bin -DINSTALL_LIBDIR=$ARCH/lib ...

Another option is to add your layout to cmake/install_layout.cmake.

Thanks,
Sergey

**Comment by olesalscheider** [comment]
Hi Sergey,

this seems to work, too. Therefore, I would not mind if this is considered the only supported way.

But in this case it would probably be a good idea to warn when an absolute path is passed. Because currently everything works except for the scripts that fail (and require debugging to find the cause).

**Comment by svoj** [comment]
Hi Niels,

this has been discussed with developers and it was considered a bug. Most probably we'll have to implement it differently, but in case we'll reuse your code:

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

JIRA task has been created to track this pull request: https://mariadb.atlassian.net/browse/MDEV-9209
This task was added to 10.1.10 backlog, which is planned to be handled between 2015-12-15 and 2015-12-22.

Thanks,
Sergey

**Comment by olesalscheider** [comment]
I contribute the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by svoj** [comment]
Pushed https://github.com/MariaDB/server/commit/c597ed01112c2f6549c59e6548d4ff53803487df

Please note that it still won't generate correct mysql_install_db for STANDALONE layout. Feel free to contribute Exherbo layout (see cmake/install_layout.cmake for details).

**Pull request closed without merging**
