### PR TITLE
MDEV-21108: Add option for setting install paths of groonga storage engine

### PR DESCRIPTION
**Pull request by ljavorsk**
Include gronnga and groonga-normalizer-mysql install path

Reason for this patch is, that the installed files from mariadb-server conflicts with the original files of groonga package when installed.
The PR created after issue: https://jira.mariadb.org/browse/MDEV-21108
This problem is occurring since 10.3.12 (not included) version of mariadb-server.
The options used during building the package are:
-DGRN_DATA_DIR=share/mariadb-server/groonga
-DGROONGA_NORMALIZER_MYSQL_PROJECT_NAME=mariadb-server/groonga-normalizer-mysql

### CODE REVIEW

**Comment by an3l** [comment]
Hi @ljavorsk ,
Thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below, or update your PR comment, that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by ljavorsk** [comment]
I'm contributing my PR under the BSD-new licence

**Comment by an3l** [comment]
If the problem is starting with `10.3` can you please edit this PR for `10.3` branch?

**Comment by ljavorsk** [comment]
Okay, and it will be updated on later releases too?

**Comment by an3l** [comment]
Yes, eventually, after merging it will find it's way on the latest release.

**Comment by ljavorsk** [comment]
This will be at 10.3 branch

**Pull request closed without merging**
