### PR TITLE
MDEV-15183: prevent building WSREP without INNODB

### PR DESCRIPTION
**Pull request by saur0n**
Fix for https://jira.mariadb.org/browse/MDEV-15183

### CODE REVIEW

**Comment by janlindstrom** [comment]
Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Jan

**Comment by saur0n** [comment]
Hereby I agree to submit this patch (and all subsequent patches to this repository) under the BSD-new license.

**Comment by janlindstrom** [comment]
Does it build if WITH_XTRADB_STORAGE_ENGINE is defined ?

**Comment by janlindstrom** [comment]
Fixed to 10.2 on commit 8db54f1ad55fad7396fb51850c7266352785ed6c
Author: Sauron <git@sauron.cf>
Date:   Fri Feb 2 20:12:23 2018 +0300

    Prevent building WSREP without INNODB

**Pull request closed without merging**
