### PR TITLE
Added -j option to dpkg-buildpackage to speed up build

### PR DESCRIPTION
**Pull request by rasmushoj**

### CODE REVIEW

**Comment by ottok** [comment]
The rules file already defines that both debhelper and cmake/make will be run in parallel automatically. I doubt this change had any effect on anything. See https://github.com/MariaDB/server/blob/10.3/debian/rules#L19-L27

Did you test it? In what kind of setup?

Also, it seems you did 3 identical pull requests in succession. Please don't do that.. but I am sure you know how fixes are done on old branches and then merged upwards. Why did you choose to do many pull requests?

**Comment by ottok** [comment]
Also, the PR must be green. Now it is failing in many ways: https://travis-ci.org/MariaDB/server/builds/411242617

I would be really stupid to merge it if it has known failures. You should rebase the change on the last commit that was green and see that your commit stays green and you do not cause a regression. If your commit is based on a already failed commit, you cannot spot a regression.

Unfortunartely you have to go back two weeks in the 10.4 branch to find green:

image

We really need to get protected branches that do not allow direct pushes unless the commit id is green in Github's memory. This kind of waste of developer time on working on already failed trees is stupid.

Ping @svoj @shinnok @cvicentiu

**Comment by ottok** [comment]
OK, indeed the default build without any envs set will run only one thread and with this change its all-in.
image

This should be made in a way that it honors the existing envs if set. For example in the .travis.yml it is defined `env DEB_BUILD_OPTIONS="parallel=4" debian/autobake-deb.sh;`

Maybe check first `if echo DEB_BUILDOPTIONS | grep parallel` first and then extend BUILDPACKAGE_FLAGS with -j$(nproc)?

**Comment by shinnok** [comment]
@ottok The original problem that I and @rasmushoj  encountered here is that even though I specify this in buildbot config:
```
267     env={'MTR_MEM':'/tmp','DEB_BUILD_OPTIONS':util.Interpolate('parallel=%(kw:jobs)s', jobs=util.Property('jobs', default='$(getconf _NPROCESSORS_ONLN)'))}))
```
Which translates into:
```
DEB_BUILD_OPTIONS=parallel=2
```
As you can see on this build:
http://buildbot.mariadb.org/#/builders/8/builds/52/steps/6/logs/stdio

The deb build system doesn't pass the -j somehow all the way to the make command. I've also inspected the docker instance manually and indeed, only one build thread is used. Googling a little bit doesn't yield that we're doing anything wrong and that this is the way that parallel deb build is supposed to be specified. 
https://www.debian.org/doc/debian-policy/ch-source.html#s-debianrules-options
https://askubuntu.com/questions/337093/how-to-run-parallel-make-with-debuild

I'm against hardcoding -j $(nproc) in there, since that might not be desired in certain use cases, like the BB Docker builds where I can't limit per thread instance access so I'm fine-tunning the number of -j's passed for each build manually so that the individual build machines don't get bogged down.

@ottok what you can do to help here, is investigate on your end if DEB_BUILD_OPTIONS does work as expected on your machine (without manual -j) and then come up with suggestions why it might not work in the BB Docker case which I can investigate on my own. 

I think also Travis is affected by this, it explains why deb-autobake takes 3x as much time as the other builds even after properly enabling ccache for all targets:
https://travis-ci.org/MariaDB/server/builds/412327774

(the extra file copying that goes in this case shouldn't 3x the build time)

**Comment by ottok** [comment]
DEB_BUILD_OPTIONS works well for me. Here is the Docker command I use:
```
export DEB_BUILD_OPTIONS="parallel=8 nocheck"
docker run -it -v "${PWD}/buildout":/tmp/build -v "${PWD}/ccache":/var/cache/ccache \
       -v "${PWD}/$PKG":/tmp/build/source -w /tmp/build/source -e BUILDPACKAGE_FLAGS='-b' \
       -e DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS" -e CCACHE_DIR=/var/cache/ccache \
       --user=1001 registry.gitlab.com/mariadb/mariadb.org-build-containers:mariadb-10.4-debian-sid-build-env \
       debian/autobake-deb.sh | tee autobake-deb.build
```

And when it runs I can see in my htop all my cores running 100%.

**Comment by ottok** [comment]
Note there are small differences in debian/rules in different branches, with 10.3 and 10.4 being the most up-to-date and best versions:

```
(10.4) $ git diff HEAD..10.3 debian/rules | grep MAKEFLAGS
(10.4) $ git diff HEAD..10.2 debian/rules | grep MAKEFLAGS
-    MAKEFLAGS += -j$(NUMJOBS)
+    MAKEFLAGS += -j $(NUMJOBS)
-    CMAKEFLAGS += -DWITHOUT_ROCKSDB=true
     CMAKEFLAGS += -DWITHOUT_TOKUDB=true
-    CMAKEFLAGS += -DWITH_JEMALLOC=no
 MAKEFLAGS += VERBOSE=1
 	    $(CMAKEFLAGS) \
(10.4) $ git diff HEAD..10.1 debian/rules | grep MAKEFLAGS
-    MAKEFLAGS += -j$(NUMJOBS)
-    CMAKEFLAGS += -DWITHOUT_ROCKSDB=true
-    CMAKEFLAGS += -DWITHOUT_TOKUDB=true
-    CMAKEFLAGS += -DWITH_JEMALLOC=no
-MAKEFLAGS += VERBOSE=1
-	    $(CMAKEFLAGS) \
+	cd $(builddir) && $(MAKE) $(MAKE_J) $(AM_EXTRA_MAKEFLAGS)
```

**Pull request closed without merging**
