### PR TITLE
MDEV-8551 mroonga compilation with clang++ correction

### PR DESCRIPTION
**Pull request by grooverdan**
As per: https://github.com/Homebrew/homebrew/pull/42233

### CODE REVIEW

**Comment by ChasonTang** [comment]
i have a issue after add the patch,it give a message below
```
CMake Error at storage/mroonga/vendor/groonga/CMakeLists.txt:171 (check_cxxflag):
  Unknown CMake command "check_cxxflag".
```
however when i delete the patch and then add
```
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_C_COMPILER_ID STREQUAL "Clang")
  MY_CHECK_AND_SET_COMPILER_FLAG("-fexceptions")
endif()
```
it work.can you help me?

**Comment by grooverdan** [comment]
Thanks for testing.  I can't remember what prompted my use of check_cxxflag - seems to be part of the autoconfigure.

Rather than a string comparison for clang does the following work for you?
<pre>
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANGCXX)
  MY_CHECK_AND_SET_COMPILER_FLAG("-fexceptions")
endif()
</pre>

**Comment by ChasonTang** [comment]
yeah. it work.

**Comment by ChasonTang** [comment]
yeah. it work.

**Comment by grooverdan** [comment]
not sure why you added CMAKE_COMPILER_IS_GNUCXX. updated PR as per latest homebrew (https://github.com/Homebrew/homebrew/pull/43793):

Thanks for testing

**Comment by grooverdan** [comment]
<pre>
export CC=clang CXX=clang++
rm storage/oqgraph/CMakeLists.txt
rm storage/tokudb/CMakeLists.txt
cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DWITHOUT_TOKUDB_STORAGE_ENGINE=1  -DWITHOUT_OQGRAPH=ON  .
 make -j9
Scanning dependencies of target abi_check
Scanning dependencies of target INFO_BIN
Scanning dependencies of target INFO_SRC
[  0%] Built target INFO_SRC
Scanning dependencies of target strings
Scanning dependencies of target gen_lex_hash
[  0%] Building C object strings/CMakeFiles/strings.dir/bchange.c.o
[  0%] Building CXX object sql/CMakeFiles/gen_lex_hash.dir/gen_lex_hash.cc.o
Scanning dependencies of target mytap
[  0%] Building C object unittest/mytap/CMakeFiles/mytap.dir/tap.c.o
Scanning dependencies of target mysqlservices
[  0%] Building C object libservices/CMakeFiles/mysqlservices.dir/my_snprintf_service.c.o
Scanning dependencies of target readline
[  0%] Building C object extra/readline/CMakeFiles/readline.dir/readline.c.o
Scanning dependencies of target wsrep
[  0%] Building C object wsrep/CMakeFiles/wsrep.dir/wsrep_gtid.c.o
Scanning dependencies of target vio
[  0%] Building C object vio/CMakeFiles/vio.dir/vio.c.o
[  0%] Built target INFO_BIN
[  0%] Building C object vio/CMakeFiles/vio.dir/viosocket.c.o
[  0%] Building C object wsrep/CMakeFiles/wsrep.dir/wsrep_uuid.c.o
[  0%] Building C object wsrep/CMakeFiles/wsrep.dir/wsrep_loader.c.o
[  0%] Building C object libservices/CMakeFiles/mysqlservices.dir/thd_alloc_service.c.o
...
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_field_normalizer.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_encoding.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_parameters_parser.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_condition_converter.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_database_manager.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_lock.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_time_converter.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_database_repairer.cpp.o
[100%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_value_decoder.cpp.o
[100%] Linking CXX shared module ha_mroonga.so
[100%] Built target mroonga
</pre>

**Comment by vuvova** [comment]
Fixed in MDEV-8551

**Pull request closed without merging**
