### PR TITLE
Misc Debian packaging fixes

### PR DESCRIPTION
**Pull request by ottok**
See commits.

### CODE REVIEW

**Comment by ottok** [comment]
# Quality assurance

image

## Travis-CI

All green

## Salsa-CI

All green at https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/212146 thanks to changes in this PR:
image

## Buildbot

No more failures at http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-lintian-and-missing-breaks&category=main&category=experimental than on main 10.5 branch, but hard to be certains as the main 10.5 is so broken to begin with..

image

**Comment by vuvova** [comment]
I think it's conceptually wrong, `mariadb-client-core-10.5` cannot possibly **replace** `mariadb-client-5.5`, it replaces `mariadb-client-core-5.5`. Or, for example, there's no way `mariadb-test` **replaces** `mariadb-server-5.5` — the former doesn't even include the `mysqld` executable. I understand that these packages **conflict**, but they don't **replace**.

**Comment by vuvova** [comment]
It's annoying that your `control` file sorting tool puts `mariadb-server-10.1` (for example) *before* `mariadb-server-5.5`.
This is, I suppose, unavoidable, and we'll have to live with it. But, please, mention this "unnatural" sort order in the commit comment and the reason for it. Otherwise someone might reorder lines "naturally" again.

**Comment by vuvova** [comment]
could you show an example (like, link to a package file), that requires using versioned Breaks/Replaces on `mysql-client-5.5` in the 10.5 branch? I would expect that any version of `mysql-client-5.5` will start from 5.5, so it'll always be less than any version of 10.5, so specifying explicitly `(<< ${source:Version})` is redundant

**Comment by ottok** [comment]
> I think it's conceptually wrong, `mariadb-client-core-10.5` cannot possibly **replace** `mariadb-client-5.5`, it replaces `mariadb-client-core-5.5`. Or, for example, there's no way `mariadb-test` **replaces** `mariadb-server-5.5` — the former doesn't even include the `mysqld` executable. I understand that these packages **conflict**, but they don't **replace**.

It does not mean the whole package replaces the other contains files that replace files of the other.

But yes, I can test if using _conflicts_ here would work as well.

> It's annoying that your control file sorting tool puts mariadb-server-10.1 (for example) before mariadb-server-5.5.
> This is, I suppose, unavoidable, and we'll have to live with it. But, please, mention this "unnatural" sort order in the commit comment and the reason for it. Otherwise someone might reorder lines "naturally" again.

This PR/commits don't sort anything new, sorting happens only due to reverting another commit. The commits that have done sorting do state it clearly that they use the Debian tool `wrap-and-sort -av`. See e.g. e7c7f5c1bbac9a081775a1dc50088ae1e32e2a8d

> could you show an example (like, link to a package file), that requires using versioned Breaks/Replaces on mysql-client-5.5 in the 10.5 branch? I would expect that any version of mysql-client-5.5 will start from 5.5, so it'll always be less than any version of 10.5, so specifying explicitly (<< ${source:Version}) is redundant

I'll double check this.

**Comment by ottok** [comment]
@vuvova Changes you suggested work and PR now updated to include them.

**Comment by ottok** [comment]
Some tests fail on this but is intentional:
```
++ diff -U1000 /home/buildbot/ldd.old /home/buildbot/ldd.new
++ grep -E '^[-+]|^ ='
--- /home/buildbot/ldd.old	2021-02-11 19:53:33.264487717 -0500
+++ /home/buildbot/ldd.new	2021-02-11 19:57:00.108974843 -0500
 === /usr/sbin/mysqld
 === /usr/bin/mysql
+	libbsd.so.0 => /lib/i386-linux-gnu/libbsd.so.0 
+	libedit.so.2 => /lib/i386-linux-gnu/libedit.so.2 
-	libreadline.so.5 => /lib/i386-linux-gnu/libreadline.so.5 
```

**Comment by ottok** [comment]
Merging this soon since @vuvova did not re-review in a month and I think it is an important fix. Also it makes the Salsa-CI for branch 10.5 all green:
image

I still have a Bionic upgrade issue now to solve from the 5.7.30 version specifically, which Serg's original change addressed but I did not yet figure out what exactly caused this and what exactly is needed to avoid this (I don't want to make too extensive changes)


On old buildbot kvm-deb-bionic-amd64 and kvm-deb-bionic-ppc64le to fail on step upgrade1 with:
http://buildbot.askmonty.org/buildbot/builders/kvm-deb-bionic-amd64/builds/6999/steps/upgrade1/logs/stdio

```
ii  mysql-client-5.7                      5.7.30-0ubuntu0.18.04.1             amd64        MySQL database client binaries
ii  mysql-client-core-5.7                 5.7.30-0ubuntu0.18.04.1             amd64        MySQL database core client binaries
ii  mysql-common                          5.8+1.0.4                           all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                          5.7.30-0ubuntu0.18.04.1             all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.7                      5.7.30-0ubuntu0.18.04.1             amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.7                 5.7.30-0ubuntu0.18.04.1             amd64        MySQL database server binaries
...
+ sudo sh -c 'DEBIAN_FRONTEND=noninteractive MYSQLD_STARTUP_TIMEOUT=180 apt-get install --allow-unauthenticated -y mariadb-server mariadb-client libmariadbclient18'
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-10.5 (>= 1:10.5.10+maria~bionic) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

In Docker:
```
root@00754e33f16b:/build# dpkg -l | grep -iE 'maria|mysql|galera'
ii  mysql-client-5.7           5.7.30-0ubuntu0.18.04.1             amd64        MySQL database client binaries
ii  mysql-client-core-5.7      5.7.30-0ubuntu0.18.04.1             amd64        MySQL database core client binaries
ii  mysql-common               5.8+1.0.4                           all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server               5.7.30-0ubuntu0.18.04.1             all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.7           5.7.30-0ubuntu0.18.04.1             amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.7      5.7.30-0ubuntu0.18.04.1             amd64        MySQL database server binaries
root@00754e33f16b:/build# apt install mariadb-server mariadb-client libmariadbclient18
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-client : Depends: mariadb-client-10.5 (>= 1:10.5.10+maria~bionic) but it is not going to be installed
 mariadb-server : Depends: mariadb-server-10.5 (>= 1:10.5.10+maria~bionic) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@00754e33f16b:/build# head -n 1 /etc/apt/sources.list
deb [trusted=yes] file:/build/mariadb-bionic/ ./
```

**Comment by ottok** [comment]
All green now at http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-lintian-and-missing-breaks&category=main&category=experimental and https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/242563 - merging this now.

**Comment by grooverdan** [comment]
Thanks @ottok

**Pull request merged**
