### PR TITLE
MDEV-19756 - Removing obsolete register keyword

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @devnexen !

Any reason why this only covers connect storage engine and not even all its files?

Because we are not the primary maintainers of connect engine (@Buggynours is), I'd rather have his opinion if he is ok with this. Code wise, it should not be a problem. Compilers now should be able to optimize this better than we could, but changing this code involves potential merge conflicts during the next merge that we do with connect storage engine. In this case, I'd much rather have @Buggynours integrate it.

**Comment by devnexen** [comment]
Was not discriminating on purpose :-) I just did not notice them the other day :-)

**Comment by Buggynours** [comment]
I didn't know these keyword was obsolete. No problem to remove them. AMF I can do it myself.

**Comment by cvicentiu** [comment]
@devnexen Alright, removing looks more complete now.

To make life easier for everyone, I propose the following:
Force push on your branch a commit that *only touches* Connect storage engine. Clear anything else.

@Buggynours will chery-pick your commit into his tree. @devnexen, your code will become part of MariaDB Server when we update connect storage engine for the next release.

The rest of the server is a bit trickier when it comes to changing such code, due to merges from MySQL. There are places where we are purposefully not changing code so it makes merging from upstream MySQL easier. I suggest we stick to Connect for the time being.

We can clean up everything in 10.5, soon.

**Pull request merged**
