### PR TITLE
MDEV-14531 - 10.3 fused madd ppc64

### PR DESCRIPTION
**Pull request by grooverdan**
From #303, roundings aren't required when -ffp-contract=off is used. This. This is enabled on ppc64 and not x86_64 based on tests. Extensive discussion https://github.com/mysql/mysql-server/pull/158.

FYI @akopytov.

My contributions are under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
Pro: So cross architecture migration should give the same same answer now.
Con: Stored floats could give a different answer after this change compared to how they where previously calculated.

So what are the other outstanding questions that need to be answered here?

Obviously its a significant change hence targeting 10.3. I think the pro still outweighs the con and could be handled in a release notes.

**Comment by svoj** [comment]
On the one hand I like stable results, on the other hand I like optimisations.
I wonder if these functions are actually supposed to return stable results or does standard allow some divergence?

Assigning to @vuvova to decide.

**Comment by vuvova** [comment]
I'd agree that disabling fused multiply add is arguably "more correct".

Two thoughts: why would you bother with floating_point.cmake byte fiddling, instead of always using `-ffp-contract=off` if it's available?

And, user override, if one specifies `-ffp-contract=on` in `CMAKE_CXX_FLAGS`, what will win? What is put later on the command line?

**Comment by grooverdan** [comment]
byte fiddling - I was just assuming that this would validate it actually makes a difference before using it.

`cmake -DCMAKE_CXX_FLAGS=-ffp-contract=fast` - looses as the  -ffp-contract=off  is last:
<pre>
cd /home/danielgb/build-mariadb-server-10.3/storage/innobase && /usr/bin/c++   -DBTR_CUR_ADAPT -DBTR_CUR_HASH_ADAPT -DCOMPILER_HINTS -DHAVE_BZIP2=1 -DHAVE_C99_INITIALIZERS -DHAVE_CONFIG_H -DHAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE=1 -DHAVE_IB_LINUX_FUTEX=1 -DHAVE_LIBNUMA=1 -DHAVE_LZ4=1 -DHAVE_LZ4_COMPRESS_DEFAULT=1 -DHAVE_LZMA=1 -DHAVE_NANOSLEEP=1 -DHAVE_POSIX_MEMALIGN -DHAVE_SCHED_GETCPU=1 -DHAVE_SNAPPY=1 -DHAVE_SYSTEMD -DLINUX_NATIVE_AIO=1 -DMUTEX_EVENT -D_FILE_OFFSET_BITS=64 -I/home/danielgb/build-mariadb-server-10.3/include -I/home/danielgb/mariadb-server-10.3/storage/innobase/include -I/home/danielgb/mariadb-server-10.3/storage/innobase/handler -I/home/danielgb/mariadb-server-10.3/libbinlogevents/include -I/home/danielgb/mariadb-server-10.3/include -I/home/danielgb/mariadb-server-10.3/sql -I/home/danielgb/build-mariadb-server-10.3/pcre -I/home/danielgb/mariadb-server-10.3/pcre  -ffp-contract=fast -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -DWITH_INNODB_DISALLOW_WRITES -fno-rtti -g -DENABLED_DEBUG_SYNC -ggdb3 -DSAFE_MUTEX -DSAFEMALLOC -Wall -Wextra -Wformat-security -Wno-init-self -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Wvla -Wwrite-strings -DUNIV_DEBUG   -DUNIV_LINUX -D_GNU_SOURCE=1  -fvisibility=hidden -ffp-contract=off -o CMakeFiles/innobase.dir/gis/gis0geo.cc.o -c /home/danielgb/mariadb-server-10.3/storage/innobase/gis/gis0geo.cc
</pre>

<pre>
 make VERBOSE=1 CXXFLAGS=-ffp-contract=fast 
</pre>
`-ffp-contract=fast`  didn't show up in output

In both cases the gis, gis-precise, and suite=innodb_gis(--big-tests) tests passed in Debug and non-debug builds.

**Comment by vuvova** [comment]
Thanks. I'll apply it without byte fiddling, under condition "if `-ffp-contract=off`is supported by the compiler and `-ffp-contract` is not present in compiler options`". Sounds ok?

**Comment by grooverdan** [comment]
>  Sounds ok?

yes

**Comment by vuvova** [comment]
thanks. pushed (into bb-10.3-serg now, in 10.3 later this week)

**Comment by grooverdan** [comment]
thanks @vuvova

**Pull request closed without merging**
