### PR TITLE
[perf] parallel init rollback segments

### PR DESCRIPTION
**Pull request by justfortaste**

### CODE REVIEW

**Comment by vaintroub** [comment]
- Do not introduce new single-purpose threads, we removed most threads in 10. .use tpool::task instead.
Look like srv_thread_pool->submit_task() is used, it will cut a contribution by some factors.
- Do not introduce new parameters either, unless necessary.  Is it necessary? Which number makes sense?

**Comment by dr-m** [comment]
If I understand correctly, this aims to speed up the database startup. Could you please show the actual impact of this with a test case?

I think that something like this could make more difference after [MDEV-14481 Execute InnoDB crash recovery in the background](https://jira.mariadb.org/browse/MDEV-14481) has been implemented. Normally, if there are lots of undo logs, there should also be many redo log records to process. Currently, the startup would wait for the page flush of the redo log recovery, and the bottleneck should be the I/O, not the single-threaded `trx_rseg_mem_restore()` execution that happens concurrently with the redo log recovery.

**Comment by robertbindar** [comment]
Hey @justfortaste, thanks for the contribution! There is still feedback needed from you regarding practical testing to prove the change actually improves startup time. I will close the PR for now, but if you're still willing to continue working on this, please feel free to open a new PR and address Marko's and Wlad's initial concerns.

**Comment by dr-m** [comment]
I see that a similar feature was included in MySQL 8.0.26: https://bugs.mysql.com/bug.php?id=101658
mysql/mysql-server@08c30638d22f29361c696d90af4107983b699b51

**Comment by justfortaste** [comment]
> 

It's also contribution from our Tencent TXSQL team.

**Pull request closed without merging**
