### PR TITLE
MDEV-12064 - Bug#18411494 WRONG COMPARSION ON BIG DECIMAL VALUES

### PR DESCRIPTION
**Pull request by weisslj**
This is a bugfix for https://bugs.mysql.com/bug.php?id=72056, solved in MySQL 5.7 but not MariaDB. I cherry picked commit https://github.com/mysql/mysql-server/commit/1cf3489ba42df1f29c1f3e269443254087505166 by Tor Didriksen. I asked the author if he is OK with the transplantation of the patch, but received no answer.

### CODE REVIEW

**Comment by grooverdan** [comment]
As a released MySQL fix, as opposed to a patch in the bugs.mysql.com, it is available under GPL-2 for merging and hence no author permission is required. Using git commit --author=".."  is good to identify and credit the original author however.

**Comment by svoj** [comment]
Note that in mysql-5.7 there were 4 follow-up patches fixing regressions after original fix.

**Comment by svoj** [comment]
Hi Johannes,

Thanks for your contribution. JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-12064

This task was added to 10.1.22 backlog, which is planned to be handled between 2017-02-25 and 2017-03-03.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Note: you only need to confirm license for changes done on your behalf. Original MySQL code is GPL2,

Thanks,
Sergey

**Comment by weisslj** [comment]
@svoj Thanks! I have looked at all of the four other commits, but mysql/mysql-server@38621ef and mysql/mysql-server@3327f7b (when combined) just add two test cases that are not directly related to this bug (they pass even without this fix), and mysql/mysql-server@478aa0d fixes negative zero returns from decimal comparisons (which is a separate bug) and mysql/mysql-server@bea174f adds more test cases for the negative zero bug. They contain a fair amount of code restructuring etc. which is not necessary to the fix. I will open a new PR for the negative zero issue.

**Comment by weisslj** [comment]
I sent a scan of the signed MCA to `f o u n d a t i o n [at] m a r i a d b (dot) o r g`.

**Comment by svoj** [comment]
@weisslj MCA received, thanks!

**Comment by weisslj** [comment]
I tested the negative-zero patches more thoroughly and I can not confidently open a PR for them. As far as I see it the bug here is resolved by this patch.

**Comment by holyfoot** [comment]
Thanks, weisslj, everybody.

**Pull request merged**
