### PR TITLE
Add Upstart job to debian packaging, based on Ubuntu MySQL job

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by grooverdan** [comment]
10.1 has systemd scripts now. Is this still needed?

**Comment by svoj** [comment]
@ottok, what's your thinking? Now that we have systemd and SysV init support, is it still worth adding upstart support to MariaDB?

**Comment by ottok** [comment]
The files is copied from http://anonscm.debian.org/cgit/pkg-mysql/mysql-5.6.git/tree/debian/mysql-server-5.6.mysql.upstart and I don't see any obivious flaws in it. The second commit about not blocking shutdown seems a bit odd, do we not want to block shutdown to secure the mysqld process has enough time to shutdown cleanly?

The benefits of introducing an upstart script at this moment are quite small and potentially any problems in it will have affect negatively a large pool of users, and we would need to spend a lot of time testing the upstrart script if the PR is accepted, and the PR itself does not do anything to assure that all upgrade/start/stop scenarios will work.

I would vote against accepting this at the time and rather focus efforts on systemd script testing/improvements and review/accept all systemd related contributions.

**Comment by svoj** [comment]
Most distributions that have used upstart before seem to have been migrated to systemd. User base of upstart seem to drop rapidly. I tend to agree with @ottok that maintaining upstart script doesn't sound reasonable these days.

Said the above, I'm closing this PR. Feel free to reopen it if you still believe upstart script is worth it.

**Pull request closed without merging**
