### PR TITLE
Remove unnecessary whitespace in mysqldump

### PR DESCRIPTION
**Pull request by staabm**
- [x] *The Jira issue number for this PR is: MDEV-33583*

## Description

before this PR when mysqldump was used to create `INSERT` or `REPLACE` statements with additional table-options, one unnecessary space was written to the dump for each `INSERT` or `REPLACE`

before this PR:
```
INSERT  IGNORE INTO `test033` VALUES (1,'test test test');
```
_note the 2 spaces between `INSERT` and `IGNORE`_

after this PR:
```
INSERT IGNORE INTO `test033` VALUES (1,'test test test');
```

motivation: when dumping databases without additional compression, this results in one unnecessary byte per row in dump-files which wastes disc space or creates unnecessay network traffic. my thesis is, because compressing dumps requires an additional manual step (as its not used per default), there will be a lot of db dumps beeing exported without compression - and these will benefit.

at the scale mariadb is used, this can easily add up. lets make sure we don't waste our planets resources :).

## Release Notes
-

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

not sure whether this should be considered a bugfix or a feature request

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by grooverdan** [comment]
The test cases `main.mysqldump` `main.mysqldump-system` need to be re-recorded to take into account changes. `msql-test/mtr --record main.mysqldump main.mysqldump-system` and add the result file to the commit.

**Comment by staabm** [comment]
thank you for the comment. I am no C developer and need to ask a few dumb questions - sorry for that.

to run the suggested command, I think I need to build mariadb on my m1 mac (running sonoma 14.3.1)  before.

taken from https://mariadb.org/get-involved/getting-started-for-developers/get-code-build-test/ https://mariadb.com/kb/en/Build_Environment_Setup_for_Mac/ ... running `cmake ../server -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=/usr/local/openssl` currently leads to a bison error

```
...
-- Looking for getmntent
-- Looking for getmntent - not found
-- Looking for setmntent
-- Looking for setmntent - not found
-- Looking for getmntinfo
-- Looking for getmntinfo - found
-- Looking for include file sys/mntent.h
-- Looking for include file sys/mntent.h - not found
-- Performing Test HAVE_GETMNTINFO_TAKES_statvfs
-- Performing Test HAVE_GETMNTINFO_TAKES_statvfs - Failed
-- Found BZip2: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/libbz2.tbd (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found LZ4: /opt/homebrew/lib/liblz4.dylib (found suitable version "1.9.4", minimum required is "1.6")
-- Looking for lzma_auto_decoder in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_auto_decoder in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd - found
-- Looking for lzma_easy_encoder in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_easy_encoder in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd - found
-- Looking for lzma_lzma_preset in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_lzma_preset in /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd - found
-- Found LibLZMA: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/liblzma.tbd (found version "5.6.0")
-- Found LZO: /opt/homebrew/lib/liblzo2.dylib
-- Could NOT find Snappy (missing: SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIRS)
-- Looking for event.h
-- Looking for event.h - not found
-- Could NOT find BISON: Found unsuitable version "2.3", but required is at least "2.4" (found /usr/bin/bison)
-- Performing Test have_CXX__Wno_unused_but_set_variable
-- Performing Test have_CXX__Wno_unused_but_set_variable - Success
CMake Error at sql/CMakeLists.txt:390 (MESSAGE):
  Bison (GNU parser generator) is required to build MySQL.Please install
  bison.
```

I am not sure how to proceed from here.

thank you

**Comment by staabm** [comment]
I will try https://stackoverflow.com/a/35161881 later today

**Comment by tonychen2001** [comment]
Hi @staabm, here's a good guide on how to build mariadb with Docker. This is what I'm currently using and it works well. It also guides you on how to run the MTRs.

https://optimizedbyotto.com/post/quick-builds-and-rebuilds-of-mariadb-with-docker/

**Comment by tonychen2001** [comment]
This change seems more like a bug fix and should probably be targeted onto `10.5`

**Review by LinuxJedi — APPROVED** [review]
Thanks for adding the test recordings.

**Comment by staabm** [comment]
Thabks for pushing it forward. Really appreciate it

**Review by cvicentiu — APPROVED** [review]
LGTM

**Pull request merged**
