### PR TITLE
Markdown README for a prettier github representation

### PR DESCRIPTION
**Pull request by grooverdan**
Mainly adds a pretty travis link on the front page of github.

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
@iangilfillan, could you review this PR?

**Comment by svoj** [comment]
I'm taking this PR since nobody responded in reasonable time.

I'm generally fine with this README.md, but it is github specific thing. I suggest we keep original README and not install README.md.

**Comment by vuvova** [comment]
There is no `README`, this patch renames it to `README.md`. I think it doesn't matter much what to install, markdown is fairly invisible for human readers, `README.md` looks no less readable than the original `README`

**Comment by nirbhayc** [comment]
Why rename in first place? Does github not render README unless its .md (even if its uses proper markdown) ?

**Comment by grooverdan** [comment]
Correct, needs to be .md for github to render it. Same file as README here https://github.com/grooverdan/mariadb-server/tree/10.2-README.txt-markdown (rendered).

**Comment by svoj** [comment]
Merged as is according to @vuvova comment.

**Comment by grooverdan** [comment]
thank you all.

**Pull request merged**
