### PR TITLE
MDEV-27809 Spider: remove #ifdef SPIDER_I_S_USE_SHOW_FOR_COLUMN

### PR DESCRIPTION
**Pull request by chansuke**
- [x] *The Jira issue number for this PR is: MDEV-27809

## Description
https://jira.mariadb.org/browse/MDEV-27809

Remove `SPIDER_I_S_USE_SHOW_FOR_COLUMN`.

## How can this PR be tested?
Success to run existing test cases.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Review by nayuta-yanagisawa — CHANGES_REQUESTED** [review]
Hi, @chansuke. Thank you for your pull request again.

I believe the fix is not compilable. In fact, the Windows CI fails. I think we have to delete all the code between `#else` and `#endif`. Anyway, It would be great if you could compile the server locally and check if the tests for Spider pass. Thank you in advance.

Note that, at the pull request creation, Spider is only compiled in the Windows CI. Once a maintainer pushes the branch named `bb-*`, all the CIs, including expensive ones, will be invoked.

**Comment by chansuke** [comment]
@nayuta-yanagisawa I appreciate your feedback and really sorry about my incomplete PR. I did a clean build and found the problem. I will revert this and commit again.

**Review by nayuta-yanagisawa — CHANGES_REQUESTED** [review]
@chansuke The change for MDEV-27809 looks good to me. However, I cannot approve the pull request because it also includes a commit for [MDEV-28795](https://jira.mariadb.org/browse/MDEV-28795). Please create one pull request per issue.

**Comment by nayuta-yanagisawa** [comment]
I'd suggest cherry-picking https://github.com/MariaDB/server/pull/2165/commits/2ee4de14f9950cca6c97ee9b4305bd7a3160fae1 to the clean 10.10 HEAD and force-pushing to the pull request branch.

**Review by nayuta-yanagisawa — APPROVED** [review]

**Pull request merged**
