### PR TITLE
fix issues with concurrent CTAS in 10.0-galera

### PR DESCRIPTION
**Pull request by aweits**
Nirbhay/All,

    Not quite sure if these modifications are 100%
   correct. Some of these issues are also present upstream in the
   mysql-wsrep code. These commits were against the 10.0-galera branch
   in GIT. I've included one of your 5.5 commits so this should work
   out-of-the-box.

### CODE REVIEW

**Comment by nirbhayc** [comment]
I have created https://mariadb.atlassian.net/browse/MDEV-8260 to get this patch reviewed and merged into 5.5/10.0 galera branches.

**Comment by nirbhayc** [comment]
https://github.com/MariaDB/server/commit/fc716dc5a5abd6997310256a1f846e39ea5bf312

**Comment by nirbhayc** [comment]
Hi @aweits!

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

**Comment by aweits** [comment]
Nirbhay Choubey <notifications@github.com> writes:

> Please indicate in a comment below that you are contributing your new
> code of the whole pull request, including one or several files that
> are either new files or modified ones, under the BSD-new license or
> that you have filled out the contribution agreement and sent it.

Pull #57 is therefore contributed under the terms of the BSD-new
license.

Thanks,

Andy

-- 
Andrew W. Elble
aweits@discipline.rit.edu
Infrastructure Engineer, Communications Technical Lead
Rochester Institute of Technology
PGP: BFAD 8461 4CCF DC95 DA2C B0EB 965B 082E 863E C912

**Pull request closed without merging**
