### PR TITLE
MDEV-19837 and MDEV-19816: Change some comments

### PR DESCRIPTION
**Pull request by myguyy**

### CODE REVIEW

**Comment by myguyy** [comment]
@an3l

**Comment by an3l** [comment]
Thanks @myguyy,
we need a license for each patch/PR. 
Please indicate in a comment below, or update your PR comment that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it, or have signed CLA.

**Comment by myguyy** [comment]
I've signed the CLA

**Comment by an3l** [comment]
Merged with 4e89fdb9d8e88607.
Thanks!

**Pull request closed without merging**
