### PR TITLE
MDEV-10752 - travis:  Correct -j in debian/build + for travis jobs=3

### PR DESCRIPTION
**Pull request by grooverdan**
Timings:

parallel=4 https://travis-ci.org/grooverdan/mariadb-server/builds/155215821
parallel=3 https://travis-ci.org/grooverdan/mariadb-server/builds/155215969
parallel=2 https://travis-ci.org/grooverdan/mariadb-server/builds/155215975

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
@grooverdan, thanks for your contribution!

@ottok, could you handle this PR?

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-10752

This task was added to 10.2.3 backlog, which is planned to be handled between 2016-09-22 and 2016-09-29.

Thanks,
Sergey

**Comment by ottok** [comment]
Why do you want to remove MAKEFLAGS? Does Travis have any guarantee on how many CPUs are availble per build, is it wise to have a fixed count instead of a dynamic value?

**Comment by grooverdan** [comment]
By passing MAKEFLAGS and putting a -j {numjobs} on the command line, you end up with errors like https://travis-ci.org/MariaDB/server#L1613 which means there is effectively no parallel build.

**Comment by grooverdan** [comment]
I'm fairly sure there is no guarantees and that even the number is quite overcommited on their build environment. Autodetection will result in 2 which would result in time exceeding 50 mins (or close to it looking at the small sample of results so far).

**Comment by grooverdan** [comment]
Still broken - https://travis-ci.org/MariaDB/server/builds/167364162#L2225 -> There is no parallel build while MAKEFLAGS is set (https://github.com/MariaDB/server/blob/10.2/debian/rules#L36) and -jX is passed to make (https://github.com/MariaDB/server/blob/10.2/debian/rules#L82).

This is slowing down the build.

Suggest using --output-sync=recurse (or =target) https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html to make it easier to parse on the output.

**Comment by svoj** [comment]
@grooverdan, could you update this PR? It has merge conflicts now.

**Comment by svoj** [comment]
Merged c35b8c46b404d035e54a23d667da5dff6502fc2e

**Pull request closed without merging**
