### PR TITLE
MDEV-17088: Provide tools to encode/decode mysql-encoded file system …

### PR DESCRIPTION
**Pull request by tsasaki609**
Hi,

I finished task MDEV-17088.
https://jira.mariadb.org/browse/MDEV-17088

There should be no problem if it is a basic use case.

Thanks,
Takashi

### CODE REVIEW

**Comment by an3l** [comment]
Can we have test case when error is raised (invalid option)?

**Comment by tsasaki609** [comment]
@an3l That's right. Is it like this?

**Comment by drrtuy** [comment]
@tsasaki69

Could you replace maliadb with mariadb in the code.

**Comment by vaintroub** [comment]
And please not link to sql library . It will take ages to link.

**Comment by tsasaki609** [comment]
@drrtuy Oops, that is a typo. I fixed it.

@vaintroub I am not familiar with CMake. If there is a better way to implement without linking to sql library, would you please tell me in detail?

**Comment by vaintroub** [comment]
@tsasaki609  : It is not about CMake, it is about linking.

First, you do not need tablename_to_filename(), thus you do not need to link with sql

Second, yu basically need 
`uint strconvert(CHARSET_INFO *from_cs, const char *from, size_t from_length,
                CHARSET_INFO *to_cs, char *to, size_t to_length, uint *errors)`


which is in sql for no good reason. I think it should be moved to strings library instead, and then you can link with strings library , which is much smaller.   and then your executable would link much faster them e.g mysqld, but if you link with sql, your practically link with the whole server.

**Comment by tsasaki609** [comment]
@vaintroub I understand. I'll try.

**Comment by tsasaki609** [comment]
I moved strconvert() from sql to strings, and linked with strings.

**Comment by vaintroub** [comment]
I think @abarkov should look over it, but still 2 things from me

-  The name is misleading. myls does not do anything like ls. I have no great suggestions for something like that, but even filename_to_tablename is better. hopefully @abarkov  or someone else can come up with a better suggestion

- You seem to assume you get UTF8 in argv, and can write UTF8 to stdout with "puts", and it would be displayed fine. This might be case on some OS, but not on others. On Windows, you never get UTF8 argv parameters in main(), and mysqltest's --exec does not work with UTF8 on Windows (it does everywhere else though), I had to fix a couple of tests in the recent past.

 I do not have suggestion on how to fix that, just pointing out potential problems, I'd leave suggestions to anyone who'd do proper review.

**Comment by abarkov** [comment]
The new tool should probably detect the client character set from the OS environment, like other tools do, e.g. "mysql".

and use this character set instead of system_charset_info when converting from/to my_charset_filename.

**Comment by abarkov** [comment]
Another option is to use the C library functions mbtowc() and wctomb(), instead of MariaDB version, to read/put characters from/to the local character set.

See "man mbtowc" and "man wctomb".

**Comment by tsasaki609** [comment]
@vaintroub @abarkov Thanks for the review.
I understand that there is a character set problem. I'll fix it.

**Comment by tsasaki609** [comment]
I fixed charset issue like other tools.

>The name is misleading. 

I thought about the tool name.
The prefix of the tool name is "mysql", so the name is
"mysql_tablename_to_filename".
But this is too long.
A simple tool name is "mysqlttof".
What do you think?

**Comment by abarkov** [comment]
It looks very good.

I have one idea. What the tool actually does: it converts from one character set to another character set. Instead of limiting it to convert from/to "filename" only, why not to extend it to handle all character sets. It would be very useful for other purposes.

Can we do the following:
1. Rename to mysql-conv
2. Change it to be compatible with iconv (see "man iconv"):
- read data from stdin, or from a file (if a file name is specified)
- add options -f and -t
?

So, for example, to read all table names in a MariaDB directory, one would do:

ls *.frm | mysql-conv -f filename -t utf8

**Comment by abarkov** [comment]
Hi Takashi,


On 01/28/2019 02:53 AM, Takashi Sasaki wrote:
> Hi @abarkov <https://github.com/abarkov> ,
> 
>     ls *.frm | mysql-conv -f filename -t utf8
> 
> I have a question.
> "." is mapped as "@002e" on the filename character set.
> But "ls *.frm" output contains ".", it is unexpected input for
> "filename" encoding and can't decode.


FRM file name is a mixture of encoded and non-encoded parts.


If you do:

CREATE TABLE `t1.x` (a INT);

It will create this FRM file:

t1@002ex.frm


Notice, the first dot was encoded as @002e.
This dot is a part of the table name.


The second dot is a separator between the encoded table name
and the file extension "frm" and it's written literally
(without encoding).


To properly convert the table name, one needs to extract
the encoded table name part from the file name.


We have a "replace" tool as a part of MariaDB distribution,
so one can do like this;

ls *.frm|replace ".frm" ""

and pipe its output to mysql-conv.


> 
> |$ echo "abc.frm" | sed s/\\./@002e/ |./client/mysql-conv -t utf8 -f
> filename abc?frm |
> 
> If we want the correct result, we need to edit and input as follows, for
> example.
> 
> |$ echo "abc.frm" | sed s/\\./@002e/ |./client/mysql-conv -t utf8 -f
> filename abc.frm |
> 
> But this method can not be done unless user is familiar with the
> internal implementation.
> Should we automatically escape "." to "@002e" in "filename" encoding cases?
> (maybe "/" too)
> 
> Or is it OK to exit with returning the error status code?


I think we can also add a flag similar to iconv's "-c".

So mysql-conv can reject unknown input byte sequences by default,
or (when the flag is set) replace unknown input byte sequences to
question marks.

So with this flag set, even if one does not use "replace", it will just
replace unexpected dots to question marks.

What do you think?

**Comment by tsasaki609** [comment]
Hi @abarkov  ,

>We have a "replace" tool as a part of MariaDB distribution,

Oh I see. I did not know that the "replace" tool exists, but it is very useful.
```
$ echo "abc.frm" | replace ".frm" "" | ./client/mysql-conv -t utf8 -f filename
abc
```


>I think we can also add a flag similar to iconv's "-c".

I think your opinion is very valid.
I will add the "-c" option to the tool.

**Comment by tsasaki609** [comment]
I added the "-c" option, but a few of error occurred in CI test.
ex. https://travis-ci.org/MariaDB/server/jobs/498689826#L4149

Since I feel that it does not relate to this PR, I will wait for a while until it gets fixed... 🤔

**Comment by abarkov** [comment]
Hi Takashi,


On 03/03/2019 09:03 AM, Takashi Sasaki wrote:
> I added the "-c" option, but a few of error occurred in CI test.
> ex. https://travis-ci.org/MariaDB/server/jobs/498689826#L4149
> 
> Since I feel that it does not relate to this PR, I will wait for a while
> until it gets fixed... 🤔

thanks for the update.

**Comment by dr-m** [comment]
I think that the tool name should start with `mariadb` in order to be aligned with [MDEV-17591 Create MariaDB named commands](https://jira.mariadb.org/browse/MDEV-17591).

**Comment by abarkov** [comment]
Marko,


On 03/04/2019 02:23 PM, Marko Mäkelä wrote:
> I think that the tool name should start with |mariadb| in order to be
> aligned with MDEV-17591 Create MariaDB named commands
> <https://jira.mariadb.org/browse/MDEV-17591>.

From my understanding, the exact naming convention for MariaDB tools
is not decided yet. So let it start with "mysql" for now.
We'll rename it together with all other tools.

**Comment by tsasaki609** [comment]
Hi,
CI tests passed but all buildbots has been waiting.
What should I do?

**Comment by abarkov** [comment]
Hi Takashi,
I'm sorry for the delay.
I have made some minor cleanups and pushed  the patch to 10.5:
https://github.com/MariaDB/server/commit/4ad083cd64852b0bf22d5c211767f006a501ce39
Thank you very much for your contribution!

**Pull request closed without merging**
