### PR TITLE
MDEV-18019, MDEV-18135: Renew test OpenSSL certs at level 3 security

### PR DESCRIPTION
**Pull request by ottok**
Future-proof the certs and upgrade them to level 3.

Also touch attribute file to fix errors like:
```
lib/generate-ssh-certs.sh
...
  Can't open ./demoCA/index.txt.attr for reading,
  No such file or directory
  140553384993216:error:02001002:system library:  fopen:No such file or directory:../crypto/bio/bss_file.c:72:  fopen('./demoCA/index.txt.attr','r')
  140553384993216:error:2006D080:BIO routines:  BIO_new_file:no such file:../crypto/bio/bss_file.c:79:  Check that the request matches the signature
```

### CODE REVIEW

**Comment by ottok** [comment]
Is it fine if I merge this on 10.6?

**Comment by ottok** [comment]
Rebased on 10.6 as this PR is almost 1 year old now, and it is better merged on 10.6 now.

**Comment by ericherman** [comment]
MDEV links:
* [MDEV-18019 Default test certificate key too small, incompatible with OpenSSL 1.1.0]( https://jira.mariadb.org/browse/MDEV-18019)
* [MDEV-18135 binlog_encryption.encrypted_slave, main.pool_of_threads and connect tests fail in buildbot with SSL error](https://jira.mariadb.org/browse/MDEV-18135)

**Comment by ericherman** [comment]
Since we're changing from RSA:2048 to RSA:3072, why not jump up to RSA:4096 here?

**Comment by ottok** [comment]
> Since we're changing from RSA:2048 to RSA:3072, why not jump up to RSA:4096 here?

OK, I'll do a test run with RSA:4096.

Anything else beyond that?

**Comment by ericherman** [comment]
Nothing more from me. It looks fine as far as I can tell, though I don't know this domain deeply.

Can anyone articulate a concern that would suggest holding on the merge? @vuvova ? @cvicentiu ?

**Comment by vuvova** [comment]
Is it an issue to be fixed at all? mtr forces openssl security level to 1, it was done in [MDEV-21965](https://jira.mariadb.org/browse/MDEV-21965). Works fine on Ubuntu Focal and OpenSSL 1.1.1.

**Comment by ottok** [comment]
Updated to RSA:4096, otherwise no changes. Certs are still dated on Monty's birthday :)

I will proceed to merge this on 10.6 myself unless CI systems show new regressions (that have not been visible since April 2020).

**Comment by ottok** [comment]
> Is it an issue to be fixed at all? mtr forces openssl security level to 1, it was done in [MDEV-21965](https://jira.mariadb.org/browse/MDEV-21965). Works fine on Ubuntu Focal and OpenSSL 1.1.1.

This fixes the fact that the OpenSSL cert key sizes are too small and are incompatible with the key size requirements in latest OpenSSL versions. It does not fix an acute issue, as you already did partial fixes in spring 2019 and spring 2020 (while unaware or ignoring the work I already did). By making the key size RSA:4096 as @ericherman the keys are additionally future-proof.

The commit message explains this and the MDEVs are referenced. This also fixes minor issues in the script that generates the certs. Actually, I fixed this issue in Debian originally already in December 2018: https://salsa.debian.org/mariadb-team/mariadb-10.3/commit/8da43c2e32b0730a3d813b1a637d72574205a16d

Then in spring 2019 you did some of the exact same changes in 0636637e37a4471ae2ef44b4932c6dcb4d9a77cf and 9c60535f867678e65ade1258ca10b7d2ee2bdc53. This PR has remaining changes to make those complete. After this there should not be any need to touch the certs for a many years.

**Pull request merged**
