### PR TITLE
Adding -j option to dpkg-buildpackage. Value taken from DEB_BUILD_OPT…

### PR DESCRIPTION
**Pull request by rasmushoj**
…IONS' parallel and if it's not defined use nproc

@shinnok please review

### CODE REVIEW

**Comment by shinnok** [comment]
@rasmushoj Not sure if we should further investigate why specifying `DEB_BUILD_OPTIONS="parallel=8"` is not enough on BB and just go with this; @ottok said in PR #836 that it worked just fine on his personal machine..

**Comment by shinnok** [comment]
@ottok we need to resolve this, currently -j$(nproc) is bringing down performance for all the other BB builders running on the same docker instance.

**Comment by ottok** [comment]
-j is already in the debian/rules file, and it follows whatever parallel=x you've set in DEB_BUILD_OPTIONS. I don't see why you need this new way of defining it?

**Comment by ottok** [comment]
As a side note, the git commit subject and message are not along usual standards for writing them and my eyes hurt a bit ;)

My git commit tips at https://www.slideshare.net/ottokekalainen/git-best-practices-2016/#17

**Comment by ottok** [comment]
Oh, this PR is for the 5.5 branch where we have an age-old debian/rules file with the contents:
```
MAKE_J = -j$(shell if [ -f /proc/cpuinfo ] ; then grep -c processor.* /proc/cpuinfo ; else echo 1 ; fi)
ifeq (${MAKE_J}, -j0)
  MAKE_J = -j1
endif
```

The modern version (since 10.2) is

**Comment by ottok** [comment]
@rasmushoj I have two questions in my review commits above. Can you please reply something to them?

**Comment by ottok** [comment]
@rasmushoj I have two questions in my review commits above. Can you please reply something to them?

**Comment by rasmushoj** [comment]
I'll close this as unnecessary since it was done against 5.5. In newer MariaDB versions the build parallelism works.

**Pull request closed without merging**
