### PR TITLE
MDEV-23915 ER_KILL_DENIED_ERROR not passed a thread id

### PR DESCRIPTION
**Pull request by grooverdan**
The 10.5 test error main.grant_kill showed up a incorrect
thread id on a big endian architecture.

The cause of this is the sql_kill_user function assumed the
error was ER_OUT_OF_RESOURCES, when the the actual error was
ER_KILL_DENIED_ERROR. ER_KILL_DENIED_ERROR as an error message
requires a thread id to be passed as unsigned long, however a
user/host was passed.

ER_OUT_OF_RESOURCES doesn't even take a user/host, despite
the optimistic comment. We remove this being passed as an
argument to the function so that when MDEV-21978 is implemented
one less compiler format warning is generated (which would
have caught this error sooner).

Thanks Otto for reporting and Marko for analysis.

- [x] *The Jira issue number for this PR is: MDEV-MDEV-23915*

## Description

Correct the ER_KILL_DENIED_ERROR to actually include the thread id expected in the error message

## How can this PR be tested?

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 9
Server version: 10.2.44-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select sleep(50);
```

Second monitor:
```
MariaDB [(none)]> \s
--------------
client/mysql  Ver 15.1 Distrib 10.2.44-MariaDB, for Linux (x86_64) using readline 5.1

Connection id:		10
Current database:	
Current user:		dan@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server:			MariaDB
Server version:		10.2.44-MariaDB Source distribution
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	latin1
Conn.  characterset:	latin1
UNIX socket:		/tmp/build-mariadb-server-10.2_second.sock
Uptime:			27 sec

Threads: 7  Questions: 8  Slow queries: 0  Opens: 18  Flush tables: 1  Open tables: 11  Queries per second avg: 0.296
--------------

MariaDB [(none)]> kill 9
    -> ;
ERROR 1095 (HY000): You are not owner of thread 9
```

galera.galera_kill_applier updated to reference the thread id. Later version per MDEV have main.grant_kill.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ X ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility

Users may be shocked to see an error that references a thread id.

### CODE REVIEW

**Comment by ottok** [comment]
I backported this to 10.6 in Debian and it worked so far on both Launchpad and official Debian builders. Thanks!
https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d8b6f1399697c701ae769c8055c57d762f44e50a

**Review by ottok — APPROVED** [review]

**Comment by ottok** [comment]
Weirdly arch *powerpc* only fails now with:

```
main.grant_kill                          w10 [ fail ]
        Test ended at 2022-03-11 17:19:58

CURRENT_TEST: main.grant_kill
--- /<<PKGBUILDDIR>>/mysql-test/main/grant_kill.result	2022-02-10 20:07:03.000000000 +0000
+++ /<<PKGBUILDDIR>>/mysql-test/main/grant_kill.reject	2022-03-11 17:19:58.158444112 +0000
@@ -20,7 +20,7 @@
 foo
 root
 KILL ID;
-ERROR HY000: You are not owner of thread ID
+ERROR HY000: You are not owner of thread 0
 disconnect foo;
 disconnect bar;
 connection default;

mysqltest: Result length mismatch
```

Full log: https://buildd.debian.org/status/fetch.php?pkg=mariadb-10.6&arch=powerpc&ver=1%3A10.6.7-3&stamp=1647019335&raw=0
Build overview of 1:10.6.7-3: https://buildd.debian.org/status/package.php?p=mariadb-10.6

**Comment by grooverdan** [comment]
@ottok thanks. Appears I only implemented one of Marko's suggestions. The other one added now.

**Comment by montywi** [comment]
Looked at both patches. Both good, with very good clear commit messages.
ok to push

**Review by montywi — APPROVED** [review]

**Review by montywi — APPROVED** [review]

**Pull request merged**
