### PR TITLE
Fix typo in components for WITHOUT_SERVER

### PR DESCRIPTION
**Pull request by Sp1l**
- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
The cmake WITHOUT_SERVER option excludes a non-existent component `SuportFiles` (note: single "p").
Assuming this is a typo, component `SupportFiles` (note: double "p") does exist .

## Release Notes
WITHOUT_SERVER fixed to exclude SupportFiles components.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by Sp1l** [comment]
Need to check again, only want to add a single character typo fix, not 281 commits!

**Comment by grooverdan** [comment]
You just need 10.5 as the target branch rather than 11.5.

**Review by grooverdan — APPROVED** [review]
All good :-)

**Comment by grooverdan** [comment]
Thanks @Sp1l .

**Pull request merged**
