### PR TITLE
MDEV-27246  Implement a method to add IPs to allowlist for Galera Cluster node addresses that can make SST/IST requests

### PR DESCRIPTION
**Pull request by mkaruza**
- [x] *The Jira issue number for this PR is: MDEV-27246*

## Description
Introduced allowlist functionality to secure galera cluster from unwanted connections

## How can this PR be tested?
MTR test is provided

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by mkaruza** [comment]
Depends on changes after https://github.com/MariaDB/server/pull/1959

**Comment by dlenski** [comment]
What does `ment 425` or `MENT-425` refer to? This is a dead link: https://jira.mariadb.org/MENT-425

**Comment by vuvova** [comment]
Sorry, it's an invalid link to a private project that shouldn't have been used here. The correct link is https://jira.mariadb.org/browse/MDEV-27246

**Comment by janlindstrom** [comment]
Merged to 10.10

**Pull request closed without merging**
