### PR TITLE
MDEV-11204: SHOW SLAVE HOSTS should show connection name

### PR DESCRIPTION
**Pull request by markus456**
Since the client host can be extracted from the network connection, it can
always be printed. This makes it easier to find out where a slave is
replicating from. It could also be used to automatically discover slaves
that are replicating from a master.

### CODE REVIEW

**Comment by markus456** [comment]
I submit the code under the BSD-new license.

**Comment by an3l** [comment]
Hi @markus456 ,
I suppose this patch is related to `MDEV-11204`?

**Comment by markus456** [comment]
Looks like it is, I didn't know there was an existing issue for it.

**Comment by markus456** [comment]
Updated test results and rebased on top of 10.5.

**Comment by robertbindar** [comment]
Thanks a lot @markus456! `thd` is not there anymore, the code around your patch was refactored in 10.5, sorry for not pointing this out (`this` should work just fine instead). Also you'll have to look for strmake in the global namespace, ::strmake.

**Comment by markus456** [comment]
My bad, it was stupid of me to assume the code would work as-is in 10.5. I'll fix that ASAP.

**Comment by robertbindar** [comment]
Merged with 0d5d8d2e7a1debece188f355ecd7b0984ef8d171. Thanks @markus456!

**Pull request closed without merging**
