### PR TITLE
MDEV-9167: COLUMN_CHECK fails on valid decimal data

### PR DESCRIPTION
**Pull request by adamchainz**
Check now allows zero length decimals too.

[MDEV-9167](https://mariadb.atlassian.net/browse/MDEV-9167)

I'm on Mac OS X and can't get compile to complete, so this is untested, I simply re-hashed 9a3ff0789fbf6c0ea627415c90ae5487449f433b which fixed a similar issue.

### CODE REVIEW

**Comment by svoj** [comment]
Hi Adam,

thanks for you contribution. This task was added to 10.1.10 backlog, which is planned to be handled between 2015-12-15 and 2015-12-22.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by adamchainz** [comment]
Thnaks. I've submitted the contribution agreement by email so I'm covered now and in the future.

**Comment by adamchainz** [comment]
I have now successfully compiled the 10.1 branch with this patch and run `dyncol.test` with the new test - it fails before the changes to `ma_dyncol.c` and succeeds afterwards.

**Comment by sanja-byelkin** [comment]
Thank you a lot for bug reporting and fixing! I moved it to 10.0 version because it fixes the patch in it.

**Comment by adamchainz** [comment]
:+1:

**Comment by sanja-byelkin** [comment]
it is pushed as revision 71eee693b2ffadaf3d3ae9f68d5a723d9e4b503a

**Comment by adamchainz** [comment]
Awesome

**Pull request closed without merging**
