### PR TITLE
MDEV-24767 Update sql_join_cache.cc

### PR DESCRIPTION
**Pull request by cstarc**
fix hash key order error

### CODE REVIEW

**Comment by grooverdan** [comment]
Hi, I see you've replaced #1750 with this one. The JIRA entry for MDEV-24767 lists 10.2 (and higher versions) as the fixed version. Would you just like to make a pull request against 10.2. Changes are merged from the lowest version all the way to the highest version. You only need to do a PR against the lowest version.

Thank you very much for the bug report and the fix.

**Comment by cstarc** [comment]
> 
> 
> Hi, I see you've replaced #1750 with this one. The JIRA entry for MDEV-24767 lists 10.2 (and higher versions) as the fixed version. Would you just like to make a pull request against 10.2. Changes are merged from the lowest version all the way to the highest version. You only need to do a PR against the lowest version.
> 
> Thank you very much for the bug report and the fix.

ok

**Comment by cstarc** [comment]
I find 5.5 is the lowest version in The JIRA entry for MDEV-24767. so I merge into it.  is it enough?

**Comment by grooverdan** [comment]
This commit is now merge and part of 8f7a6cde580298116b50b144984f996dc6af60ae.

Thanks for the contribution.

**Pull request closed without merging**
