### PR TITLE
MDEV-14672 Minor upgrade fails on xenial due to missing unixODBC (case-sensitive)

### PR DESCRIPTION
**Pull request by fauust**
Package dependency case problem (unixodbc):
https://jira.mariadb.org/browse/MDEV-14672
Add travis build files.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @fauust,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-14672

This task was added to 10.0 backlog.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by fauust** [comment]
Hi Sergey,

Sergey Vojtovich <notifications@github.com>,
26/04/2018 - 00:32:21 (-0700):

> The other alternative is to sign the code contribution agreement which can be
> found here: [3]https://mariadb.com/kb/en/mariadb/mca/
I have signed and sent the MCA on 07-Jan-2018.

> Please indicate in a comment below that you are contributing your new code of
> the whole pull request, including one or several files that are either new
> files or modified ones, under the BSD-new license or that you have filled out
> the contribution agreement and sent it.
I am.

Regards,

Faustin

**Comment by ottok** [comment]
Please clean up the PR. Now it contains unnecessary changes to the Travis configs.

Note that this was fixed for 10.2 and 10.3 in commit https://github.com/MariaDB/server/commit/0a970083342b4d43afda901a77186236974926f5, but I guess this commit cannot easily be backported to 10.1 and 10.0 as it also contains lot's of other changes as well.

**Comment by fauust** [comment]
@ottok done.

**Pull request merged**
