### PR TITLE
MDEV-25294 signal handler display coredump pattern on mac

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by robertbindar** [comment]
There it is, another one, amazing! 🎉 
I'll take a look at this beginning of next week, sorry for the eventual delay.

What was missing/not working before your patch, how does your patch fixes this? Please add a comment with this info so that I can review it as fast as possible on Monday.

**Comment by devnexen** [comment]
that s fine next week no rush :-)

**Comment by robertbindar** [comment]
Cool!
Let me explain why I asked again for a more detailed explanation of the PR for the second time, because I have a feeling I'm being annoying 😆  and I want to offer you the reasoning behind this.

Because MariaDB is quite a complex project (no really?! :-) ), there are very little changes that I or any other reviewer is very familiar with a particular segment of code that a contributor touches. Even if the reviewer was, at some point, familiar with the piece of code a patch touches, there is a high chance the reviewer doesn't currently remember it well enough now, or at least to the level of details required to offer a good, comprehensive review (i.e. because the code is big and the work is very scattered across it, so not that many chances that one can specialise in a particular component or smtg; you understand something now, but after 6 months of working on some other parts, oops!, you have rampup time again).

Now that we've acknowledged the causes of people's amnesia around here, it's important to notice that in order for us to minimise the chances of breaking something (especially something that might be of critical importance to other users), the reviewer needs to:
1. If the contribution is a bug fix
* understand what was broken, why the contributor was motivated to submit a patch
* understand how the patch fixes the issue, e.g. how output changed, how the behaviour of some component changed
* read the code of the patch and the code around it, try to understand it
* decide if the architecture is fine, styling consistency is followed, performance is preserved/improved
* pull the commits, replicate the issue locally, test stuff manually to validate the effectiveness of the patch
* think about potential side-effects, think how the patch might affect other platforms
* think if there might be backward-compatibility implications
* rely on buildbots to validate pontential side-effects theories that you discovered in the two steps above (but this takes time too as buildbots are not as fast as you might desire)
2. If the contribution is a feature implementation
* to be continued (maybe in a blog post, MD file or something like that)

Each of the steps above has a time toll that the reviewer (and the project, and other contributors that wait for reviews, etc) needs to pay. The more information a contributor provides about the patch, the smaller this toll is. The contributor is happier because the PR is reviewed faster, the reviewer is happier because more PRs can be solved per unit of time, other contributors are happier because they wait less for their PRs, the community is happier because their project gets better faster.
From another perspective, it's kind of crappy to expect more from a contributor than a free patch, on their time expense, that fixes a problem in your project, again for free, you can't be more grateful than that 🙇 , so I don't know what to say, I guess everybody needs to meet in the middle for the sake of the community.

In the near future this explanation will be summarised in a GitHub PR template and a guideline document to help contributors guide themselves through the process, but until then, I hope this explanation will be helpful to others too, especially now that GSoC season is coming and a new batch of contributors is expected ❤️

**Comment by ericherman** [comment]
A pull request template is a very good idea.

**Comment by devnexen** [comment]
@robertbindar any other changes requested ? :)

**Comment by robertbindar** [comment]
Hey @devnexen, i promised Monday, but it's now almost Saturday, sorry for this, I will look at this over the weekend.

**Comment by robertbindar** [comment]
Hey @devnexen! Sorry again for the delay, I promise it won't happen too often :D Patch looks good to me, but I would like to see this rebased on top of 10.2 as it is most probably reproducible in there too (code in the core output function is almost identical in this regard afaik 10.2-10.5).

Once we have the PR rebased, I should be able to merge it no problem.
Thanks again for the patience :-)

**Comment by devnexen** [comment]
too much of conflicts thus I did this PR https://github.com/MariaDB/server/pull/1794 :-)

**Pull request closed without merging**
