### PR TITLE
Working on MCOL-4944: QueryStats Doesn't Automatically Work When Turned On - used to in CS 1.2.5

### PR DESCRIPTION
**Pull request by SergMariaDB**
- [x] *The Jira issue number for this PR is: MCOL-4944*

## Description
TODO:
 solve systemd detection related issues for Fedora-based distros.
 Fix and enable ColumnStore tests to run with its test suite and to be included in common tests run.
 add new test-case for MCOL-4944

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to
behave as intended. Consult the documentation on
["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).
In many cases, this will be as simple as modifying one `.test` and one `.result`
file in the `mysql-test/` subdirectory. Without _automated_ tests, future regressions
in the expected behavior can't be automatically detected and verified.

If the changes are not amenable to automated testing, please explain why not and
carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by drrtuy** [comment]
I don't see any correlation b/w the issue and this patch. Moreover the scope of the issue doesn't include MDB repo at all.

**Comment by SergMariaDB** [comment]
These are unrelated. 
I tried to run ColumnStore tests: two warnings appears and the only test in the server ColumnStore test suite is failing and show two warnings.
Warnings are fixed in this patch.
Tests fail fix requires deeper investigation. 
To run ColumnStore native tests I must build & install the ColumnStore systemd service.
The systemd detection currently has a set of compatibility problems on Fedora-based distros.
This patch-set has one patch to set one systemd compatibility detection issue: header detection.
The way @grooverdan made it first worked well.
Now it is a bit broken.
So for me it is like a blocker because the proper way to start is to add test for the relevant issue.
And neither OS I currently possess allow me to build ColumnStore properly for this.

I would concentrate on proper integration of ColumnStore tests into the server test system.
Presumably it is as easy as running ColumnStore service process together with mariadbd process for tests.
I also would run the ColumnStore native tests suite directly from the server. 
For this additional ColumnStore  test data downloadable separately should be included somehow via CmakeFetchContent for example or into the repo.

Thanks. Good luck.

**Comment by drrtuy** [comment]
JFYI @SergMariaDB MTR tests works now. [Here](https://ci.columnstore.mariadb.net/mariadb-corporation/mariadb-columnstore-engine/3583/3/9) is the example of a relevant CI pipeline output. We have a list of distros MCS support and Fedora doesn't belong to this list(The same CI link lists distros MCS supports). However @abarkov was able to even run multiple MCS instances on the same Fedora node.
MCS and Server team has an unspoken agreement MCS has as small server code footprint as possible to reduce the effect of a potential mistakes introduced by MCS team. 
These are reasons why I think this patch is irrelevant to the original issue.

**Comment by grooverdan** [comment]
Closing based on above comment.

**Pull request closed without merging**
