### PR TITLE
Fix build failure on CentOS for MariaDB official CI

### PR DESCRIPTION
**Pull request by guyuqi**
From: https://github.com/MariaDB/server/pull/772#issuecomment-500394103
The patch is to fix CentOs build failure on Arm64.

The Arm gcc version in CentOS 7 is 4.8.2 (released in Mar 2013).
But Arm added the support for 'arm_acle.h' in gcc 5.1 (released in Jun 2014).
And there are also some bugs in Arm gcc 4.8.

The patch is to detect  whether GCC version is greater than 5.1 or not.
If not, Arm64 crc32c optimization will be skipped.

P.S. The cmake version should be greater than 3.7.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @guyuqi,

Looks good. It means ARM crc32 optimisations are not going to be available for clang and other compilers?

Thanks,
Sergey

**Comment by guyuqi** [comment]
@svoj 
Mentioned from official doc: [ARM C Language Extensions 2.1](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0053d/IHI0053D_acle_2_1.pdf), ` ACLE` is supported by `ARMCC`and `GCC`.
For free opensource world, we just add GCC support here.

**Comment by svoj** [comment]
@guyuqi good. Could you confirm this PR is under MCA or BSD-new?

**Comment by guyuqi** [comment]
I submit this PR under the MCA. Thanks!

**Comment by svoj** [comment]
Thanks!

**Pull request merged**
