### PR TITLE
MDEV-8140 - spd_db_oracle.cc fail to compile

### PR DESCRIPTION
**Pull request by ChengXiaoZ**
https://mariadb.atlassian.net/browse/MDEV-8140

### CODE REVIEW

**Comment by ChengXiaoZ** [comment]
the bug is not fixed.

**Comment by ChengXiaoZ** [comment]
the bug is not fixed.

**Comment by svoj** [comment]
Hi Cheng,

thanks for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by ChengXiaoZ** [comment]
Hi Sergey,
My contribution of this pull request ,including one or several files that are either new files or modified ones, is submitted under the BSD-new license.
Thanks,
Sergey

**Comment by svoj** [comment]
Merged.

**Pull request closed without merging**
