### PR TITLE
MDEV-23892: Fix riscv64 build failure by linking correctly with pthread

### PR DESCRIPTION
**Pull request by ottok**
Link with -pthread instead of -lpthread, and do that for all architectures.

Contributors:
Aurelien Jarno <aurelien@aurel32.net>

This has been used in Debian for about a month with 10.5.8 without issues and it fixed all the remaining riscv64 issues.

Merging this would allow us to drop the downstream patch at https://salsa.debian.org/mariadb-team/mariadb-10.5/-/blob/master/debian/patches/riscv64-link-pthread.patch

### CODE REVIEW

**Comment by ottok** [comment]
Before:
riscv64 fails to build: https://launchpadlibrarian.net/511949501/buildlog_ubuntu-focal-riscv64.mariadb-10.5_1%3A10.5.0~ubuntu20.04.1~1608323829.a1974d1991f+ok.10.5_BUILDING.txt.gz

After:
riscv64 build passes but now fails on test suite failures: https://launchpadlibrarian.net/512326996/buildlog_ubuntu-focal-riscv64.mariadb-10.5_1%3A10.5.0~ubuntu20.04.1~1608492466.1e061559eae+ok.10.5.riscv64_BUILDING.txt.gz

Despite not being perfect yet this is progress and should be merged.

No regressions in the other builds:
image

**Comment by ottok** [comment]
Remaining test failures:
- https://jira.mariadb.org/browse/MDEV-24456
- https://jira.mariadb.org/browse/MDEV-24457

**Comment by ottok** [comment]
# Quality assurance

## Travs-CI

No new regressions. There is one frequent failure until https://github.com/MariaDB/server/pull/1681 is merged.

## Buildbot

Lots of failures, but I don't see any new ones compared to main 10.5 branch:

http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-riscv64&category=main&category=experimental
image

**Comment by grooverdan** [comment]
Thanks for pulling this one together, seems applicable to AIX too.

**Comment by ottok** [comment]
@cvicentiu Is this OK to merge? It is your original code, I think you should finalize this.

**Comment by grooverdan** [comment]
Pushed to 10.5, and then after looking at MDEV-23892, to 10.3.
Thanks.

**Comment by ottok** [comment]
Accepted without changed and merged in de746304c98.

(Documenting this so at least I myself see that it was accepted and not rejected despite the PR itself being in a rejected state.)

**Comment by grooverdan** [comment]
Yep, I'm putting `Closes: #1717` in commit messages so there is a link like above my previous comment.

Technically its a closed issue rather than rejected, however I think we can start putting some label indicating successful import into the code base. I'll chat to the team.

**Comment by ottok** [comment]
Don't waste energy on doing extra things, such as extra labels. Just merge
the PR.

If it is not in a mergeable state, simply ask contributor to finalize it,
and then merge it.

>

**Comment by grooverdan** [comment]
With protect branches the rebase and merge option isn't available if the destination branch has moved on (hence me jumping on a few PRs really quickly).

The "merge" option adds a merge commit to the PR, but does trigger the latest build. It looked, though apparently it wasn't the case, that the available rebase and merge option after that would be merging a second merge commit.

 It wasn't obvious that it could be done, but now I know it is, I'll try to do this.

**Pull request closed without merging**
