### PR TITLE
MDEV-17028 Fix glitches with systemd sysusers and tmpfiles

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by cvicentiu** [comment]
Hi @eworm-de !

Thank you for the contribution. There's a few problems with Debian releases using systemd-sysusers and systemd-tmpfiles. We don't want to break a stable version and we ended up disabling your previous systemd contribution for debian builds. I may have to merge this to 10.2 (or even 10.3) instead of 10.1. I'll look more into this and see how we can help you with it. I assume this helps Archlinux packaging the most, right?

Vicențiu

**Comment by eworm-de** [comment]
Hi @cvicentiu !

I am from the ArchLinux folks, yes. But this is supposed to be as generic as possible. Anyway, if you disable this for Debian builds there is no impact by further changes, no?
I do not think there is any reason not to merge this in 10.1. IMHO its better to fix some glitches than to have something half ready. You can still disable the code for specific systems (as you did for Debian).
Let me know if you think changes are required.

Chris

**Comment by grooverdan** [comment]
Fedora/Redhat affected https://src.fedoraproject.org/cgit/rpms/mariadb.git/commit/?id=0f8f4c807c8038be33a65ea3464b73a67228a4a2

Pushing the first commit to stable is recommended as its location isn't conflicting or dependant on anything else.

FYI @FaramosCZ

I totally endorse the second commit in contributing to not needing root premissions aren't needed for the mariadb.service (MDEV-14707). I haven't found a Debian equivalent on ensuring this directory exists with the right permission (like it does for rundir https://github.com/MariaDB/server/blob/10.3/cmake/systemd.cmake#L59). Not needed by Fedora https://src.fedoraproject.org/cgit/rpms/mariadb.git/tree/mysql.tmpfiles.d.in but probably not harmful.

**Comment by eworm-de** [comment]
Any news on this one? It's waiting for more than half a year now.

**Comment by ottok** [comment]
@fauust Do you have some systemd insights here?

**Comment by eworm-de** [comment]
BTW, this also applies to 10.3 and 10.4 branches. As things move on... Does it make sense to send a pull request for either of both?

**Comment by eworm-de** [comment]
I replaced the on-the-fly-modifications with proper patches, so this is in Arch Linux package now:
[0002-systemd-sysusers-tmpfiles.patch](https://git.archlinux.org/svntogit/packages.git/plain/trunk/0002-systemd-sysusers-tmpfiles.patch?h=packages/mariadb)

**Comment by fauust** [comment]
Hi @eworm-de, sorry for the delay in responding!
Can you explain me briefly what this patch is supposed to resolve? Sorry but I can't find any pointer here...

**Comment by eworm-de** [comment]
Hey @fauust, thanks for looking at this!

Sure I can give some details. The discussion does not have them, but commit messages do:

```
Use descriptive file names for sysusers and tmpfiles configuration

These files were installed to:

${INSTALL_SYSTEMD_SYSUSERSDIR}/sysusers.conf
${INSTALL_SYSTEMD_TMPFILESDIR}/tmpfiles.conf

Instead rename the files to more descriptive file names 'mariadb.conf'.
```
The file content for `sysusers.conf` and `tmpfiles.conf` is ok, but file names are not. The file name should reflect the package name, so `mariadb.conf` for both file (in different directories) is fine.

```
Make systemd-tmpfiles create MYSQL_DATADIR

This is a no-op if the directory exists, but makes sure it is created by
systemd-tmpfiles with proper permissions otherwise.

This solves packaging issues when the user MYSQLD_USER is created by
systemd-sysusers and uid is not known in advance.
```
Currently the mariadb package for Arch Linux does not ship the data directory directly. Instead it is created with correct ownerstip and permission by `systemd-tmpfiles`. As written this is a no-op when the directory exists.

I hope that helps, let me know if you need more details.

**Comment by fauust** [comment]
Thank you @eworm-de, build is OK on my platform.

I found these on Jira:
https://jira.mariadb.org/browse/MDEV-15052
https://jira.mariadb.org/browse/MDEV-15543
https://jira.mariadb.org/browse/MDEV-17028

**Comment by fauust** [comment]
@eworm-de do you have any test protocol that you could share with me so I can test this deeper?
Or an issue that is resolved by this patch?

As this applies to all version, I would then suggest to first merge this on 10.4 branch that is in beta and then to backport on stables versions.

**Comment by eworm-de** [comment]
I think I do not have any extra protocol or documentation.

The change in first commit should be pretty obvious: If another package tries to install files named `sysusers.conf` and `tmpfiles.conf` you will see conflicts... From `man` `tmpfiles.d`:
```
Each configuration file shall be named in the style of package.conf or package-part.conf.
```

The second commit is supposed to ease packaging. When creating the user with `systemd-sysusers` it is allowed to have dynamic uid (as current `sysusers.conf` uses). You have three ways to go:

* Create the user `mysql` with a fixed and hardcoded uid, then ship the directory with hardcoded uid.
* Create the user with dynamic uid from `systemd-sysusers`, then adjust the permissions for data directory from post-install script.
* Drop the line in tmpfiles configuration and let `systemd-tmpfiles` do the job.

I think the third option is what we want.

**Comment by eworm-de** [comment]
This is where Arch Linux package switched from creating user from post install script to systemd-sysusers. We still used hardcoded uid back then:
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/mariadb&id=9d34a461c5eb4569952d5dd8c9ec046db59c5d14

With 7bbc6c14d1e8fcf1f4737e0a5fcf6237fe18bd23 being merged we switched to dynamic uids and extended `tmpfiles.conf` to create the data directory:
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/mariadb&id=5c8a22e1e0d9a8dbebb3cddd5ffdf847c7fdcd3c

**Comment by grooverdan** [comment]
Searching the [debian bugs](https://groups.google.com/forum/#!searchin/linux.debian.bugs.dist/tmpfiles.d%7Csort:date) (since search packages for tmpfiles.d is limited), the convention is always to use the packagename.conf as a filename. There's nothing particularly unstable about this change.

**Comment by fauust** [comment]
@grooverdan, yes I get to the same conclusion yesterday after looking at various Debian systems, first commit is clearly OK.
@eworm-de, do you have any idea of what is going to happen in the case of an upgrade? We might end up with same lines in two files (sysusers.conf and mariadb.conf)?

**Comment by eworm-de** [comment]
@fauust, `systemd-sysusers` (and `systemd-tmpfiles`) is run on any system boot. It applies the rules from configuration files and does nothing if everything is in place. Same for identical files: Second file will be no-op as first one did the job (if any).

(But hey, we install packages with package managers, no? There will be no duplicate files with same line. :-)

**Comment by fauust** [comment]
> @fauust, `systemd-sysusers` (and `systemd-tmpfiles`) is run on any system boot. It applies the rules from configuration files and does nothing if everything is in place. Same for identical files: Second file will be no-op as first one did the job (if any).

OK, perfect.

> (But hey, we install packages with package managers, no? There will be no duplicate files with same line. :-)

Well in the case of Debian this is even more true because theses files are removed:
https://salsa.debian.org/mariadb-team/mariadb-10.1/blob/master/debian/rules#L147

After a discussion with @cvicentiu this morning this should be merged 
> into the earliest version that is valid.
> That way, when merges happen, the patch gets incorporated automatically.

**Comment by eworm-de** [comment]
Now that version 10.3.13 and 10.4.3 have been released... Possibly it's a good time to merge this and related pull requests (#510, #1137, #1143)?

**Comment by hgxl64** [comment]
I don't think this PR is right. While I don't have a problem with the part about renaming the systemd config files, I severely doubt that creating the datadir is a job for systemd. Actually even creating the MYSQL_USER is not a job for systemd.
The systemd-tmpfiles service is for creating volatile directories and files. The datadir however is not volatile, quite the contrary. On top of that: just creating the datadir will not make the server start. It needs to be initialized (mysql_install_db) as well. This logic and actions belong into the installer. Since the MYSQL_USER must exist before the datadir can be created, this belongs into the installer as well. Actually this is how RPM and DEB packages do this, using the post-installation hooks.
The creation of MYSQL_UNIX_DIR by systemd however is correct. This directory is indeed volatile and may reside on a non-persistent file system.
So please explain why you believe, that non-temporary directories and users should be created by systemd.

**Comment by grooverdan** [comment]
@hgxl64 can you merge the first commit for now then? Which would enable #605 to me be merged after removing the tmpfiles bit from debian/not-installed. And #528.

**Comment by cvicentiu** [comment]
Hi @eworm-de !
As discussed in this PR, I have decided to accept the first commit, but not the second one. I took a long time to think about this and investigated how Debian packaging handles it. They use a post-install script and do not rely on sysusers or tmpfiles at all.

We need to find a better solution for the problem that your commit was trying to fix, so as to follow appropriate conventions for systemd-tmpfiles.

Either way, renaming the files is a good first step.

Patch is here:
https://github.com/MariaDB/server/commit/b472bc2eba017b3286dc7110f1c2ce3a039e6ac7

**Pull request closed without merging**
