### PR TITLE
Use cmake timestamp macro

### PR DESCRIPTION
**Pull request by bmwiedemann**
Without this patch it is hard to build mariadb packages
that do not differ between builds.

See https://reproducible-builds.org/ for why this matters.

With this patch, it is possible, because recent cmake versions
honor the SOURCE_DATE_EPOCH environment variable.

Note: if requiring cmake-2.8.11 is not yet an option,
another approach could be taken via
https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal#CMake

I contribute this change under the BSD-new license.

### CODE REVIEW

**Comment by svoj** [comment]
Thanks for your contribution!

CMake 2.8.11 is almost 5 years old, however we still have builders with older cmake building 10.2 (some even have cmake 2.7).

What if do something like
```
IF (CMAKE_VERSION VERSION_GREATER 3.8.10)
  STRING(TIMESTAMP TMP_DATE "+%Y-%m-%d %H:%M:%S" UTC)
ELSEIF (WIN32)
...
```

This will make reproducible builds on recent platforms, while keeping it compilable on older platforms.

**Comment by vuvova** [comment]
I'd say, just don't include INFO_BIN into the "reproducible build" set. Ignore it, delete it, whatever. Binaries are reproducible, as far as I know.

**Comment by bmwiedemann** [comment]
adapted to svoi's suggestion. dropping the `INFO_BIN` file would be another way, but I did not know if it is used for something at runtime.

**Comment by vuvova** [comment]
it's not used for anything at runtime

**Comment by svoj** [comment]
Independently of alternative solution suggested by @vuvova, I like ```STRING(TIMESTAMP UTC)```. It looks much cleaner than what we have. Writing UTC time looks nice too, after all time zone is not included.

@bmwiedemann I wonder if dropping ```INFO_BIN``` is easy/acceptable for whatever you're trying to achieve?

**Comment by bmwiedemann** [comment]
I submitted https://build.opensuse.org/request/show/536714 for dropping INFO_BIN from our package and it was accepted, so it is good for us.

**Comment by svoj** [comment]
Closing as alternative solution was acceptable, there's seem to be no point to bother with this code. Thanks!

**Pull request closed without merging**
