### PR TITLE
MDEV-11350 - fix build and some warnings

### PR DESCRIPTION
**Pull request by kevgs**
Patch is self explanatory. NFC
Used clang version 3.8.1

### CODE REVIEW

**Comment by svoj** [comment]
Hi kevgs,

Thanks for your contribution. JIRA task has been created to track this pull request: https://jira.mariadb.org/browse/MDEV-11350

This task was added to 10.2.4 backlog, which is planned to be handled between 2016-12-15 and 2016-12-22.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Sergey

**Comment by kevgs** [comment]
Hello. Thanks for your answer.

I'm contributing this new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by dr-m** [comment]
Thanks for the patch! With the exception of XtraDB (see below), it looks OK to me.
Coincidentally, I fixed some of these warnings in 10.1 and 10.2. Can you please resolve the conflict (it is white space only).
Also, at your discretion, you could revert the white-space changes after resolving the conflicts.
In XtraDB, after the conflict resolution, there is only one non-whitespace change, in ha_innodb.cc, and that one should be reverted. While it is removing a compilation error, the correct fix would be different. MariaDB 10.2 does not currently build XtraDB. We would fix this error later if we re-enable XtraDB in 10.2.

**Comment by dr-m** [comment]
I did the merge myself. I omitted some changes that require further review, and I ensured that we are actually always passing this!=NULL to one member function:
```diff
120a121,133
> diff --git a/sql/records.cc b/sql/records.cc
> index e7a4ab8..b8abb48 100644
> --- a/sql/records.cc
> +++ b/sql/records.cc
> @@ -69,7 +69,7 @@ static int rr_index_desc(READ_RECORD *info);
>  bool init_read_record_idx(READ_RECORD *info, THD *thd, TABLE *table,
>                            bool print_error, uint idx, bool reverse)
>  {
> -  int error;
> +  int error= 0;
>    DBUG_ENTER("init_read_record_idx");
>  
>    empty_record(table);
164,187c177,189
< diff --git a/sql/sql_partition.cc b/sql/sql_partition.cc
< index 324eef0..a2bc500 100644
< --- a/sql/sql_partition.cc
< +++ b/sql/sql_partition.cc
< @@ -6649,7 +6649,8 @@ void handle_alter_part_error(ALTER_PARTITION_PARAM_TYPE *lpt,
<        }
<      }
<      /* Ensure the share is destroyed and reopened. */
< -    part_info= lpt->part_info->get_clone(thd);
< +    if (part_info)
< +      part_info= part_info->get_clone(thd);
<      close_all_tables_for_name(thd, table->s, HA_EXTRA_NOT_USED, NULL);
<    }
<    else
< @@ -6667,7 +6668,8 @@ void handle_alter_part_error(ALTER_PARTITION_PARAM_TYPE *lpt,
<        the table cache.
<      */
<      mysql_lock_remove(thd, thd->lock, table);
< -    part_info= lpt->part_info->get_clone(thd);
< +    if (part_info)
< +      part_info= part_info->get_clone(thd);
<      close_thread_table(thd, &thd->open_tables);
<      lpt->table_list->table= NULL;
<    }
---
> diff --git a/sql/sql_class.cc b/sql/sql_class.cc
> index 8fabc8f..3eeeda5 100644
> --- a/sql/sql_class.cc
> +++ b/sql/sql_class.cc
> @@ -2093,7 +2093,7 @@ bool THD::notify_shared_lock(MDL_context_owner *ctx_in_use,
>          if (!thd_table->needs_reopen())
>          {
>            signalled|= mysql_lock_abort_for_thread(this, thd_table);
> -          if (this && WSREP(this) && wsrep_thd_is_BF(this, FALSE))
> +          if (WSREP(this) && wsrep_thd_is_BF(this, FALSE))
>            {
>              WSREP_DEBUG("remove_table_from_cache: %llu",
>                          (unsigned long long) this->real_id);
```

**Comment by kevgs** [comment]
Thanks a lot for reviewing and merging!

One question. How it is possible to pass a `NULL` as `this` to method?

**Comment by dr-m** [comment]
Invoking a member function on a `NULL` object pointer is not valid or well-formed modern C++, but it used to work in the past. For example, in `handle_alter_part_error()`, it is possible for `lpt->part_info` to be `NULL`. Without my fix, we would invoke `lpt->part_info->get_clone(thd)` without ensuring that the object is not `NULL`. With my fix, we skip the call if `part_info` (which had been assigned from `lpt->part_info` earlier in the function) is `NULL`.
Note: Error handling is tricky for rare errors. It could be that we would end up always having a non-`NULL` pointer when running tests. I have not looked at the code coverage. Unit testing or fault-injection testing could be needed to exercise the logic.

**Comment by kevgs** [comment]
Thanks for clarification.

**Pull request merged**
