### PR TITLE
Deb: Move my_print_defaults to MariaDB client core package

### PR DESCRIPTION
**Pull request by ottok**
The my_print_default is required by mytop which is also in the MariaDB
client package, which in turn requires the client core package.
This way it is ensured my_print_deafult is always available when mytop
is installed.

The my_print_defaults is also required by the server logrotate files
and mysqld_safe script etc, but this change is fine, since the server
core package always depends on the MariaDB client core package anyway
and they are both installed on server installations.

Related: https://github.com/MariaDB/server/pull/1566

### CODE REVIEW

**Comment by ottok** [comment]
# CI resutls

* Buildbot OK at http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5-my_print_defaults&category=main&category=experimental

* Salsa-CI OK at https://salsa.debian.org/mariadb-team/mariadb-server/pipelines/143662

Waiting for buildbot.mariadb.org and Travis-CI to run.

**Comment by grooverdan** [comment]
From the staging tree of FreeBSD this seems to be not just a Debian goal - https://github.com/Sp1l/ports/blob/master/databases/mariadb105-server/files/patch-extra_CMakeLists.txt

**Comment by ottok** [comment]
@an3l What is the status here? This has been open for over a month.

**Comment by an3l** [comment]
@ottok it was vacation, will take a look asap.

**Comment by ottok** [comment]
Ping @an3l 

This missed the 10.5.5 release now..

**Comment by an3l** [comment]
Hi @ottok, yes your patch is confirmed also by Serg.
But it is going in batch with other patches from 
[bb-10.5-anel-MDEV-22552](https://github.com/MariaDB/server/commits/bb-10.5-anel-MDEV-22552) see [MDEV-22552](https://jira.mariadb.org/browse/MDEV-22552), which are still in review.

**Comment by an3l** [comment]
@ottok  can you please rebase this on the latest 10.5?

**Comment by ottok** [comment]
This will be obsoleted by https://github.com/MariaDB/server/pull/1782

**Comment by grooverdan** [comment]
ok

**Pull request closed without merging**
