### PR TITLE
MDEV-27664 Spider:remove #ifdef SPIDER_SQL_CACHE_IS_IN_LEX

### PR DESCRIPTION
**Pull request by Kaiton7**
- [x] *The Jira issue number for this PR is: MDEV-27664*

## Description
Remove unnecessary #ifdefs and dead code in Spider.

SPIDER_SQL_CACHE_IS_IN_LEX has been removed.

## How can this PR be tested?
No modification of test cases.
Remove dead code to make sure it passes the existing test cases.
## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

### CODE REVIEW

**Comment by Kaiton7** [comment]
@nayuta-yanagisawa 
The fix is in, please review this pull request.

**Comment by nayuta-yanagisawa** [comment]
@Kaiton7 Hi! Thank you for your pull request. Could you sign CLA following the comment of CLAAssistant?

**Review by nayuta-yanagisawa — APPROVED** [review]

**Comment by Kaiton7** [comment]
@nayuta-yanagisawa 
Thank you!! I've signed the CLA.

**Comment by Kaiton7** [comment]
@nayuta-yanagisawa 
Thank you for your review. This is my first commit to the MariaDB server.
I have a question. I would be very grateful if you could respond to the question below. 
Is there any way (or tool) to test effectively in git-bisect? 
For example, the option to test only a part of the test using this option``--do-test=PREFIX or REGEX``, or parallel test in multi instances.
If there is a component that only requires some testing to be carried out, could you please let us know?

It takes 15 minutes for testing all test cases in my environment below.
I've checked these tweets.
About git-bisect
https://twitter.com/NayutaYanagisaw/status/1487116558283411461?s=20&t=ujncznDKkbjWEEpctCAUkA
About recommend computer specs.
https://twitter.com/NayutaYanagisaw/status/1492712745485352962?s=20&t=0xy_eVRNYEQPMWvYX5-8Aw

OS
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

CPU 
```
$ sudo lshw -class processor
  *-cpu                     
       description: CPU
       product: AMD Ryzen 5 3600 6-Core Processor
       vendor: Advanced Micro Devices [AMD]
       physical id: 14
       bus info: cpu@0
       version: AMD Ryzen 5 3600 6-Core Processor
       serial: Unknown
       slot: AM4
       size: 2195MHz
       capacity: 4200MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca cpufreq
       configuration: cores=6 enabledcores=6 threads=12
```
Disk
```
$ sudo parted -l
Model: ADATA SX8200PNP (nvme)
Disk /dev/nvme0n1: 512GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End    Size   File system  Name                  Flags
 1      1049kB  538MB  537MB  fat32        EFI System Partition  boot, esp
 2      538MB   512GB  512GB  ext4
```

Memory
```
$ cat /proc/meminfo
MemTotal:       32806904 kB
MemFree:         1000688 kB
MemAvailable:   16236700 kB
Buffers:          338144 kB
Cached:         15778604 kB
SwapCached:         1456 kB
Active:         19813024 kB
Inactive:        9554928 kB
Active(anon):   12518424 kB
Inactive(anon):  2755816 kB
Active(file):    7294600 kB
Inactive(file):  6799112 kB
Unevictable:       13076 kB
Mlocked:           13076 kB
SwapTotal:       2097148 kB
SwapFree:        2074576 kB
Dirty:              2460 kB
Writeback:             0 kB
AnonPages:      13263720 kB
Mapped:          1851080 kB
Shmem:           2049884 kB
KReclaimable:    1606076 kB
Slab:            1965944 kB
SReclaimable:    1606076 kB
SUnreclaim:       359868 kB
KernelStack:       44528 kB
PageTables:       132892 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    18500600 kB
Committed_AS:   46399060 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      111488 kB
VmallocChunk:          0 kB
Percpu:            44928 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:     1435320 kB
DirectMap2M:    27854848 kB
DirectMap1G:     5242880 kB
```

**Comment by nayuta-yanagisawa** [comment]
@Kaiton7 We use `git-bisect` for finding the first bad commit, which introduced a certain bug to the repository. So, you don't need to run all the test cases in the `git-bisect` test script. Please check my blog post (sorry in Japanese) for more detailed instructions. https://nayuta-yanagisawa.hatenablog.com/entry/learning-mysql-mariadb-debugging-by-example

**Comment by nayuta-yanagisawa** [comment]
I expect that parallelizing git-bisect on a single machine doesn't help because, for MariaDB Server, the compilation time is dominant. However, I think a few hours for git-bisect is acceptable.

**Comment by Kaiton7** [comment]
Thank you for your advice. Surely only certain test cases should be tried. I'll try it later. 
And I found that build certainly seems to have a greater impact than the test.
But for a few hours, it seems okay for me. Thank you!!!
I've checked your post. It is helpful for me.

**Pull request merged**
