### PR TITLE
defaults-groups-suffix in print_defaults

### PR DESCRIPTION
**Pull request by grooverdan**
Also clarify the default options, if present, must be part of the first arguments.

I submit this under the MCA.

### CODE REVIEW

**Comment by grooverdan** [comment]
@svoj, unassigned PR that got missed and pushed back to page 2.

Really simple change to help text as those that call print_defaults also use the library for command line and option parsing.

**Comment by svoj** [comment]
It's not missed. I did a few attempts to review this PR without any luck. I'd like to verify your claim (not that I don't trust you, but I rather don't like to merge things that I don't fully understand).

Stay tuned.

**Comment by svoj** [comment]
I haven't tested, it is just how I understand this code...

Previously this statement was true indeed and all of these options were only accepted if they were given as first argument. This has changed in 68b4d7b74 so that:
- `--print-defaults` and `--no-defaults` are still required to be first argument
- `--defaults-file`, `--defaults-extra-file` and `--defaults-group-suffix` can appear anywhere in command line. If some option is given multiple times first occurrence is being used.

Said the above, adding `--defaults-group-suffix` is nice, but adding "only" makes this statement even more misleading.

And: did you run tests? ;)

**Comment by grooverdan** [comment]
Seem point about "only' being misleading. Reworded and placed a separatioin between the `--print-defaults` and `--no-defaults`

Other options can't appear anywhere:
<pre>
$ client/mysql --user=bob  --defaults-group-suffix=.group
client/mysql: unknown variable 'defaults-group-suffix=.group'
$ client/mysql --user=bob  --defaults-file=/etc/my.cnf
client/mysql: unknown variable 'defaults-file=/etc/my.cnf'
<pre>

I tested around making sure multiple clients recognised defaults-group-suffix in preparation for the systemd multi service changes but its too long ago to remember what else I tested.

Did a few basic tests that I put in the commit message.

**Comment by svoj** [comment]
Thanks! You're right: the other three options can be specified only before all other options. But they're not mutually exclusive.

**Comment by grooverdan** [comment]
Thanks.

**Pull request merged**
