### PR TITLE
Fix for MDEV-18276, typo in error message + all other occurrences of …

### PR DESCRIPTION
**Pull request by chriscalender**
Fix for MDEV-18276, typo in error message + all other occurrences of "refering".

### CODE REVIEW

**Comment by an3l** [comment]
Hi @chriscalender 
I would just suggest you to change this line too:
`sql/sql_parse.cc `
`6674:    /* check if these are refering to temporary tables */ `

**Comment by chriscalender** [comment]
Hi @an3l !

Thank you for the suggestion.  However, I am not seeing that misspelling in 10.3 source.  I also checked 10.4 source.  And the bug only lists 10.3 and 10.4 for "Fix Versions".  Further, I did not see it in 5.5 source either.  I've downloaded all fresh code tonight.  Do you know what I might be missing as to why I do not see this?

**Comment by an3l** [comment]
Hi @chriscalender 
look it is in `10.3` https://github.com/MariaDB/server/blob/10.3/sql/sql_parse.cc#L6674
Try to fetch upstream first and after that do git rebase, so 
`git checkout MDEV-18276` (this is your local branch as branch from `10.3`), 
`git fetch upstream`
`git rebase upstream/10.3` (now you should have as a last commit `Fix for MDEV-18276, typo in error message + all other occurrences of refering` and all other updated history of `10.3`)
After this you should see this line :).

**Comment by chriscalender** [comment]
I received errors when trying that last command above:

c:\wpafb\hangar18\10.3\server>git rebase upstream/10.3
fatal: Needed a single revision
invalid upstream 'upstream/10.3'

So I edited the file through github and that last fix is here:

https://github.com/MariaDB/server/pull/1163

Thank you again for the advice! :)

**Comment by svoj** [comment]
Thanks! Cherry-picked to 5.5 d8b7e76c37ae53255880370d68244608230dbc53 and 10.2 2d6e627a9f5f5d901dc02161d4cca8a6e72c0116

**Pull request closed without merging**
