### PR TITLE
MDEV-23494: unify and modernise mysql_install db

### PR DESCRIPTION
**Pull request by grooverdan**
mysql_install_db has come with a number of fixed features that are undesirable in modern installations where frequent installs happens.

Over time some of these have been expanded slowly in later MariaDB versions. For projects like dbdeployer and the docker library this creates a pain with a single initialization script needing to account for variants of feature that mysql_install_db should provide.

As such, and now including packaging there are number of restarts of mysqld just to initialize it how it is required.

The approach here has been to backport a few features, add options to make explict root host/password, and provide a file descriptor that can be passed to mysqld to finish its initialization.

This is a first draft. Some more testing on portability and testing for closed file descriptors is required.

I'd like your feedback on if I've missed anything that would make it easier for you.

Feedback please especially pinging @datacharmer, @ottok, @tianon, @yosifkit, @Sp1l  , @FaramosCZ

### CODE REVIEW

**Comment by datacharmer** [comment]
Thanks for involving me in this proceedings.
I would like to know what is going to change  for the database initialization with this proposal.

Right now, dbdeployer generates two main methods of initialization:

(MySQL 5.7+)
```
$HOME/opt/mysql/8.0.20/bin/mysqld \
    --no-defaults \
    --user=$USER \
    --basedir=$BASEDIR \
    --datadir=$DATADIR \
    --tmpdir=$SBDIR/tmp \
    --initialize-insecure
```

(MariaDB and MySQL up to 5.6)
```
$HOME/opt/mysql/ma10.5.4/scripts/mysql_install_db \
    --no-defaults \
    --user=$USER \
    --basedir=$BASEDIR \
    --datadir=$DATADIR \
    --tmpdir=$SBDIR/tmp \
    --auth-root-authentication-method=normal
```

What would the new procedure look like?
Will the above command still work?
Is there a plan to make the initialization similar to MySQL 5.7+?

**Comment by grooverdan** [comment]
There's no move away from mysql_install_db. Existing compatibility will be preserved. By backporting the functionality perhaps any version dependent things like https://github.com/datacharmer/dbdeployer/pull/68 (though `--auth-root-socket-user` was there for local users) might not need as much version checking (like [docker library version checking](https://github.com/docker-library/mariadb/blob/master/docker-entrypoint.sh#L154)).

Perhaps the file descriptor 3 could be use to script some replication initialization of db users.

Notes on the input file descriptor 3 (that should be expanded in real help). This was partially written around docker library requirements of creating users (and debian packaging does similar things) so this is made more flexible so the following could be used in initialization:
```
FLUSH PRIVILEGES;
CREATE USER ...;
CREATE DATABASE...
```

Its still running in a bootstrap mode so I'll need to check what `execute immediate`/ prepared statement restrictions apply.

I've also obviously added timezone initialization as an option in IO friendly way.

Is there anything around the `mysql_install_db` that you don't like?

**Comment by datacharmer** [comment]
> Is there anything around the mysql_install_db that you don't like?

My biggest concern with it was that there used to be very little automated testing about this script, and thus I was the first one to get a bug when I tried a new version of MySQL/MariaDB with MySQL-Sandbox first and dbdeployer later.

Apart from that, the only issue is that I need to maintain two initialization methods for dbdeployer. However, since I introduced the `capabilities` library, fine tuning the bootstrap has become a lot easier.

**Comment by grooverdan** [comment]
Another entry point to look at:
https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L247

**Comment by grooverdan** [comment]
@datacharmer , long time since your comment - however I was listening, https://github.com/MariaDB/server/commit/b4c302c6fe04f0177b36d30c1985c7f4133d1250 is the beginning of it.

I'm going to close this for now. I'm keeping the concepts, just making a more minimal change to 10.2 onwards supported by a mtr tests for mysql_install_db.

**Pull request closed without merging**
