### PR TITLE
MDEV-30482 libmariadb3 - debian/libmariadb3.symbols not updated

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-30482*

## Description

Add missing symbols and their introduced C/C version.

@ottok  see you added this in #2778. Some of our version number differ. I didn't look down to 3.1 so your introduced version of this is likely more accurate.

Is it a FYI field in the debian packaging?

## How can this PR be tested?

deb-autobake tests (check output, won't fail I think)

## Basing the PR against the correct MariaDB version
- [X] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [X] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by ottok** [comment]
This looks correct, thanks!

I will try to debug why buildbot does not fail on builds *before* this commit as clearly the actual ABI and expected ABI has a mismatch (before this change).

**Comment by grooverdan** [comment]
I think debian being lenient of symbols added and then just assuming the package name is the version added for ease of update.

if you're not worried about the version added part of the symbol file being potentially a version or two incorrect as it was hard too look up.

I'll double check after some sleep we came to the right ABI version as that probably matters most. Sorry for the dup - long flight without internet

**Comment by ottok** [comment]
I checked the buildlog from *this PR* at https://buildbot.mariadb.org/#/builders/148/builds/26707 - it does indeed fail on the step that checks ABI tracking:

```
	dpkg-gensymbols -plibmariadb3 -Idebian/libmariadb3.symbols -Pdebian/libmariadb3 -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb.so.3 -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/caching_sha2_password.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/client_ed25519.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/dialog.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/mysql_clear_password.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/sha256_password.so
dpkg-gensymbols: warning: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: error: some symbols or patterns disappeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libmariadb3/DEBIAN/symbols doesn't match completely debian/libmariadb3.symbols
--- debian/libmariadb3.symbols (libmariadb3_1:10.10.7+maria~deb10_amd64)
+++ dpkg-gensymbolsxpHEcI	2023-10-08 15:43:46.262539903 +0000
@@ -1,7 +1,8 @@
 libmariadb.so.3 libmariadb3 #MINVER#
 * Build-Depends-Package: libmariadb-dev
  libmariadb_3@libmariadb_3 3.0.0
- libmariadb_3_3_5@libmariadb_3 3.3.5
+#MISSING: 1:10.10.7+maria~deb10# libmariadb_3_3_5@libmariadb_3 3.3.5
+ libmariadb_3_3_5@libmariadb_3_3_5 1:10.10.7+maria~deb10
  libmariadbclient_18@libmariadbclient_18 3.0.0
  libmysqlclient_18@libmysqlclient_18 3.0.0
  ma_pvio_register_callback@libmariadb_3 3.0.0
	mv debian/.debhelper/generated/libmariadb3/triggers.new debian/.debhelper/generated/libmariadb3/triggers
	rm -f debian/libmariadb3-compat/DEBIAN/shlibs
	rm -f debian/libmariadbclient18/DEBIAN/shlibs
	rm -f debian/libmysqlclient18/DEBIAN/shlibs
	rm -f debian/libmariadbd19/DEBIAN/shlibs
	echo "libmariadbd 19 libmariadbd19" >> debian/libmariadbd19/DEBIAN/shlibs
	chmod 0644 -- debian/libmariadbd19/DEBIAN/shlibs
	mv debian/.debhelper/generated/libmariadbd19/triggers.new debian/.debhelper/generated/libmariadbd19/triggers
	rm -f debian/libmariadbd-dev/DEBIAN/shlibs
	rm -f debian/mysql-common/DEBIAN/shlibs
	rm -f debian/mariadb-common/DEBIAN/shlibs
	rm -f debian/mariadb-client-core/DEBIAN/shlibs
	rm -f debian/mariadb-client/DEBIAN/shlibs
	rm -f debian/mariadb-server-core/DEBIAN/shlibs
	rm -f debian/mariadb-server/DEBIAN/shlibs
	rm -f debian/mariadb-backup/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-connect/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-s3/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-rocksdb/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-oqgraph/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-mroonga/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-spider/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-gssapi-server/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-gssapi-client/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-cracklib-password-check/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-hashicorp-key-management/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-provider-bzip2/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-provider-lz4/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-provider-lzma/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-provider-lzo/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-provider-snappy/DEBIAN/shlibs
	rm -f debian/mariadb-test/DEBIAN/shlibs
	rm -f debian/mariadb-test-data/DEBIAN/shlibs
	rm -f debian/mariadb-plugin-columnstore/DEBIAN/shlibs
dh_makeshlibs: failing due to earlier errors
make: *** [debian/rules:221: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
program finished with exit code 2
elapsedTime=3038.920827
```

I checked the mainline 11.3 builds for latest commit at https://buildbot.mariadb.org/#/builders/148/builds/26603 and it reveals:

```
	dpkg-gensymbols -plibmariadb3 -Idebian/libmariadb3.symbols -Pdebian/libmariadb3 -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb.so.3 -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/caching_sha2_password.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/client_ed25519.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/dialog.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/mysql_clear_password.so -edebian/libmariadb3/usr/lib/x86_64-linux-gnu/libmariadb3/plugin/sha256_password.so
dpkg-gensymbols: warning: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libmariadb3/DEBIAN/symbols doesn't match completely debian/libmariadb3.symbols
--- debian/libmariadb3.symbols (libmariadb3_1:11.3.0+maria~deb10_amd64)
+++ dpkg-gensymbolseaMbLb	2023-10-04 09:33:20.704167359 +0000
@@ -1,6 +1,7 @@
 libmariadb.so.3 libmariadb3 #MINVER#
 * Build-Depends-Package: libmariadb-dev
  libmariadb_3@libmariadb_3 3.0.0
+ libmariadb_3_3_5@libmariadb_3_3_5 1:11.3.0+maria~deb10
  libmariadbclient_18@libmariadbclient_18 3.0.0
  libmysqlclient_18@libmysqlclient_18 3.0.0
  ma_pvio_register_callback@libmariadb_3 3.0.0
@@ -8,6 +9,7 @@
  mariadb_connection@libmariadb_3 3.0.0
  mariadb_convert_string@libmariadb_3 3.0.0
  mariadb_deinitialize_ssl@libmariadb_3 3.0.0
+ mariadb_field_attr@libmariadb_3 1:11.3.0+maria~deb10
  mariadb_free_rpl_event@libmariadb_3 3.1.0
  mariadb_get_charset_by_name@libmariadb_3 3.0.0
  mariadb_get_charset_by_nr@libmariadb_3 3.0.0
@@ -15,8 +17,12 @@
  mariadb_get_infov@libmariadb_3 3.0.0
  mariadb_reconnect@libmariadb_3 3.0.0
  mariadb_rpl_close@libmariadb_3 3.1.0
+ mariadb_rpl_errno@libmariadb_3_3_5 1:11.3.0+maria~deb10
+ mariadb_rpl_error@libmariadb_3_3_5 1:11.3.0+maria~deb10
+ mariadb_rpl_extract_rows@libmariadb_3_3_5 1:11.3.0+maria~deb10
  mariadb_rpl_fetch@libmariadb_3 3.1.0
  mariadb_rpl_get_optionsv@libmariadb_3 3.1.0
+ mariadb_rpl_init_ex@libmariadb_3 1:11.3.0+maria~deb10
  mariadb_rpl_open@libmariadb_3 3.1.0
  mariadb_rpl_optionsv@libmariadb_3 3.1.0
  mariadb_stmt_execute_direct@libmariadb_3 3.0.0
```

However it is not failing. Maybe something on buildbot is fiddling with [DPKG_GENSYMBOLS_CHECK_LEVEL](https://manpages.debian.org/bookworm/dpkg-dev/dpkg-gensymbols.1.en.html) to prevent it from failing the build.

**Comment by grooverdan** [comment]
thanks for exaction and check level reference.

**Comment by grooverdan** [comment]
this is now fixed with `libmariadb_3_3_5@libmariadb_3_3_5`. Seems the appended version is entirely informational.

**Comment by ottok** [comment]
You probably want to have as commit title "MDEV-30482: Add missing symbols and their introduced C/C version" and rebase instead of having merge commits in a merge request.

I checked https://buildbot.mariadb.org/#builders/148/builds/27096 and `dpkg-gensymbols` no longer complains so this should be good. Ideally there would also be something that forces [dpkg-gensymbols](https://manpages.debian.org/bookworm/dpkg-dev/dpkg-gensymbols.1.en.html) to fail in the future is it again detects mismatches in the ABI.

**Comment by grooverdan** [comment]
the merges are from the update branch and get removed when merged. The original commit is further up.

https://github.com/MariaDB/buildbot/pull/197 is ready to enforce this.

Acceptable?

**Comment by LinuxJedi** [comment]
Note that 10.10 is end of life, so we cannot merge. Might want to move this to 10.11.

**Pull request merged**
