### PR TITLE
MDEV-8743: ib_logfile0 Use O_CLOEXEC so galera SST scripts don't get fd

### PR DESCRIPTION
**Pull request by grooverdan**
I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-8743

This task was added to 10.0 backlog.

Thanks,
Sergey

**Comment by grooverdan** [comment]
thanks @janlindstrom

**Comment by janlindstrom** [comment]
Can you sled light on other similar PRs, there is even one for 5.5-galera that is the first release, should I merge all of these or only 5.5-galera one and when it is automatically merged it will cover rest of cases up to 10.3?

**Comment by grooverdan** [comment]
I've split the functionality up to where the functionality was introduced. Each PR doesn't have an overlap so each does need to be merged. There should only be a small amount of easily resolvable conflict moving up as `::open` is changed to `open` and that sort of thing.

**Pull request merged**
