### PR TITLE
MDEV-12346 - Remove dated my-{size}.cnf files

### PR DESCRIPTION
**Pull request by grooverdan**
The dates on the these files shows they are very dated.

Following the sentiments of MDEV-9882 the default values are quite decent so lets remove this old stuff.

will need referenced removed from KB like https://mariadb.com/kb/en/mariadb/mysqld-configuration-files-and-groups/ and perhaps a example that doesn't reference version 5.3

### CODE REVIEW

**Comment by svoj** [comment]
Hi Daniel,

Thanks for your contribution. Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-12346

This task was added to 10.2 backlog, which hasn't been scheduled yet.

Thanks,
Sergey

**Comment by svoj** [comment]
I assume it was approved by @vuvova in MDEV-12346. I'll better retarget this for 10.3.

**Comment by grooverdan** [comment]
I'm not sure the compatibility of stable releases rule is broken by keeping a 10.2 target.

**Comment by svoj** [comment]
Merged to 10.3 7fee164faf8fce7be4ebe322d2178efd3d075eae

**Comment by grooverdan** [comment]
Thanks

**Pull request closed without merging**
