### PR TITLE
MDEV-10814: Coredumps to exclude query cache

### PR DESCRIPTION
**Pull request by grooverdan**
i submit this under the mca

### CODE REVIEW

**Comment by svoj** [comment]
@sanja-byelkin we have this small QC change. Do you need jira task to handle it or can you review it instantly?

**Comment by sanja-byelkin** [comment]
I do not understand why QC should be excluded from memory dump? If something happened there it is the way to investigate.

**Comment by grooverdan** [comment]
Its just a core dump size reduction mechanism, the other large part was large pages of innodb buffers in #364. While the QC is comparatively smaller its usually fairly uninteresting from a debugging point of view.

**Comment by grooverdan** [comment]
Like innodb, this will still dump for the Debug builds.

**Comment by dr-m** [comment]
@sanja-byelkin FYI, I merged the InnoDB part of this (omit the buffer pool, redo log buffers and some other large allocations from core dumps) to MariaDB 10.3.5 in commit 7bfe33ee286b89eda1eb885762bf9281236bcf58.
I sometimes do depend on the buffer pool contents in core dumps for debugging. The core dump reduction does not happen in debug builds. In release builds, you can attach `gdb` and `call buf_madvise_do_dump()` to re-include the buffer pool before the core is dumped.

**Comment by grooverdan** [comment]
thanks @sanja-byelkin. made it before the year anniversary.

**Pull request merged**
