### PR TITLE
MDEV-14330: tokudb and mysqltest manpages to right packages

### PR DESCRIPTION
**Pull request by grooverdan**
I tested the test package contains it.

Had trouble creating a tokudb-engine package for some reason.

I submit this under the MCA.

### CODE REVIEW

**Comment by svoj** [comment]
Hi @grooverdan, thanks for your contribution!

@iangilfillan please review! Please also double check target version.

**Comment by svoj** [comment]
I'd probably move those under `storage/tokudb/man`.

**Comment by grooverdan** [comment]
> I'd probably move those under storage/tokudb/man.

Fair call, and for the time being man/ is the only location that installs man pages.

Its unclear if you want this changed before a merge.

**Comment by cvicentiu** [comment]
Hi @grooverdan !

This patch was merged in two steps. Man pages for mysqltest were corrected in 10.1 with https://github.com/MariaDB/server/commit/5271d43648957141b55159958b66fd635d80ac85

Tokudb manpages were moved to storage/tokudb/man and corrected with:
https://github.com/MariaDB/server/commit/07e34cddb66da2e9e4ab5bdd8d52d1a72c2d2e8e

**Pull request closed without merging**
