### PR TITLE
Add my_global.h header to plugins to provide HAVE_ALLOCA_H for service_encryption.h

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by LinuxJedi — CHANGES_REQUESTED** [review]
I've discussed this one internally and we are not sure this is the right approach.

Stepping back I think a better solution would be to modify `service_encryption.h` so that `alloca` isn't used. Instead use `malloc` / `free` with proper error handling.

**Comment by brad0** [comment]
> I've discussed this one internally and we are not sure this is the right approach.
> 
> Stepping back I think a better solution would be to modify `service_encryption.h` so that `alloca` isn't used. Instead use `malloc` / `free` with proper error handling.

Well if that is possible that would be much more preferable.

**Comment by vuvova** [comment]
Using `<my_global.h>` in plugins is definitely wrong. This header is full of server specific dependencies and idiosyncrasies accumulated over >20 years of history. Plugins generally shouldn't need or depend on it.

alloca is much faster than malloc/free, so it's preferable for cases when it works. And OpenBSD has alloca, as far as I can see, what are you trying to fix here?

**Comment by brad0** [comment]
> alloca is much faster than malloc/free, so it's preferable for cases when it works. And OpenBSD has alloca, as far as I can see, what are you trying to fix here?

It wasn't about OpenBSD. It was about fixing the build with AIX, since HAVE_ALLOCA_H needs to be passed down.

**Comment by grooverdan** [comment]
I think we can do a smaller `config.h.cmake` for plugin/service headers if they need them.

**Comment by brad0** [comment]
> I think we can do a smaller `config.h.cmake` for plugin/service headers if they need them.

That's all I am trying to do with this diff. The minimal to have HAVE_ALLOCA_H passed down, but not all of the other stuff.

**Comment by grooverdan** [comment]
Don't worry, we'll so something Monday. Enjoy your weekend.

**Comment by grooverdan** [comment]
Pushed [bb-10.3-danielblack-alloca_h_service-pkgtest](https://buildbot.mariadb.org/#/grid?branch=bb-10.3-danielblack-alloca_h_service-pkgtest) as alternative to test.

Tested package of header:
```
/tmp/t 
$ tar -axf /home/dan/repos/build-mariadb-server-10.3/mariadb-10.3.37-linux-x86_64-Development.tar.xz
$ more ./include/mysql/server/service_encryption.h
....
#else
#include <stdlib.h>
#define HAVE_ALLOCA_H 1
#ifdef HAVE_ALLOCA_H
```

**Comment by grooverdan** [comment]
aix tested:
```
mdborg@p8-aix1-mariadb:[/home/mdborg/build-mariadb-server-10.8]cmake .
CMake Warning (dev) at CMakeLists.txt:30 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Running cmake version 3.16.0
-- MariaDB 10.8.6
-- Updating submodules
getconf: specified variable is not valid on this system
-- Wsrep-lib version: 1.0.0
== Configuring MariaDB Connector/C
-- Could NOT find ZSTD (missing: ZSTD_LIBRARIES ZSTD_INCLUDE_DIRS) 
-- SYSTEM_LIBS: -lld;m;-lld;m;/usr/lib/libssl.a;/usr/lib/libcrypto.a;/usr/lib/libz.a
-- Mroonga doesn't support on big-endian
-- Could NOT find BZip2 (missing: BZIP2_INCLUDE_DIR) 
-- Could NOT find LZO (missing: LZO_LIBRARIES LZO_INCLUDE_DIRS) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mdborg/build-mariadb-server-10.8

mdborg@p8-aix1-mariadb:[/home/mdborg/build-mariadb-server-10.8]make VERBOSE=1 auth_gssapi
..
[ 92%] Linking CXX shared module auth_gssapi
cd /home/mdborg/build-mariadb-server-10.8/plugin/auth_gssapi && /opt/freeware/bin/cmake -E cmake_link_script CMakeFiles/auth_gssapi.dir/link.txt --verbose=1
"/opt/freeware/share/cmake-3.16/Modules/Platform/AIX/ExportImportList" -o CMakeFiles/auth_gssapi.dir/objects.exp CMakeFiles/auth_gssapi.dir/server_plugin.cc.o CMakeFiles/auth_gssapi.dir/gssapi_server.cc.o CMakeFiles/auth_gssapi.dir/gssapi_errmsg.cc.o
/opt/freeware/bin/g++-10 -fPIC -Wl,-bE:CMakeFiles/auth_gssapi.dir/objects.exp  -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -maix64 -pthread -mcmodel=large -pie -fPIC -O2 -g -DNDEBUG -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -DDBUG_OFF -Wall -Wenum-compare -Wextra -Wmissing-braces -Wno-format-truncation -Wno-init-self -Wno-nonnull-compare -Wno-unused-parameter -Woverloaded-virtual -Wnon-virtual-dtor -Wvla -Wwrite-strings -Wl,-bE:/home/mdborg/mariadb-server-10.8/libservices/mysqlservices_aix.def -shared -Wl,-bnoipath -o auth_gssapi.so CMakeFiles/auth_gssapi.dir/server_plugin.cc.o CMakeFiles/auth_gssapi.dir/gssapi_server.cc.o CMakeFiles/auth_gssapi.dir/gssapi_errmsg.cc.o  -Wl,-blibpath:/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/10:/opt/freeware/lib:/usr/lib:/lib ../../libservices/libmysqlservices.a -lpthreads -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err 
strip -e -X32_64 auth_gssapi.so
make[3]: Leaving directory '/home/mdborg/build-mariadb-server-10.8'
[100%] Built target auth_gssapi

mdborg@p8-aix1-mariadb:[/home/mdborg/build-mariadb-server-10.8] grep ALLOCA *
CMakeCache.txt:HAVE_ALLOCA_H:INTERNAL=1
CMakeCache.txt:HAVE_POSIX_FALLOCATE:INTERNAL=1
```

**Comment by brad0** [comment]
If you don't want my_global.h in plugins then I would revert .. https://github.com/MariaDB/server/pull/2288

But change
```#elif !defined(__FreeBSD__) && !defined(__NetBSD__) && !defined(__OpenBSD__) && !defined(__DragonFly__)```
to
```#elif defined(HAVE_ALLOCA_H)```

Revert the cracklib_password_check.c part of https://github.com/MariaDB/server/pull/2289 and change the alloca.h header to
```
#include <stdlib.h>
#ifdef HAVE_ALLOCA_H
#include <alloca.h>
#endif
```

To me there should be some minimal header for plugins to do this.

**Comment by grooverdan** [comment]
Yep, I see what you mean. Both plugins use `alloca` so relying on existing headers to define it is fragile.
hashicorp will get it from `mysql/plugin_encryption.h`.

cracklib, given the number of 1k (`STRINGSIZE`) allocations [cracklib entrypoint `FascistCheckUser` down to `Gtry`](https://github.com/cracklib/cracklib/blob/c66d74fc38e1632726da8230714bf62f6128e212/src/lib/fascist.c#L514) does to compare the `username@host` (to the password, so `username` passes?) the fast smaller allocation of `alloca` looks odd).

**Comment by grooverdan** [comment]
forward handled to #2567.

noted about #2288 revert, which might need ^ merged up.

**Pull request closed without merging**
