### PR TITLE
Misc Debian packaging fixes

### PR DESCRIPTION
**Pull request by ottok**
See commits.

### CODE REVIEW

**Comment by ottok** [comment]
This is ready for review and merging.

CI on old buildbot passes OK:
image
http://buildbot.askmonty.org/buildbot/grid?branch=ok-10.5&category=main&category=experimental

Cannot run Salsa-CI as ColumnStore breaks it.

**Comment by ottok** [comment]
Buildbots pass OK.

Travis-CI is OK:
image

Salsa-CI is OK if ColumnStore builds are temporairly disabled:
image

**Comment by ottok** [comment]
[buildbot.mariadb.org debian-9](https://buildbot.mariadb.org/#builders/22/builds/5682) fails with some buildbot related thing, not a real regressions:
```
Completed: All 4821 tests were successful.
852 tests were skipped, 206 by the test itself.

command timed out: 7200 seconds without output running [b'sh', b'-c', b'cd mysql-test && exec perl mysql-test-run.pl --verbose-restart --force --retry=3 --max-save-core=1 --max-save-datadir=1 --max-test-fail=20 --mem --parallel=$(expr 7 \\* 2)'], attempting to kill
SIGKILL failed to kill process
using fake rc=-1
program finished with exit code -1
remoteFailed: [Failure instance: Traceback from remote host -- builtins.RuntimeError: SIGKILL failed to kill process
```

**Comment by ottok** [comment]
Rebased, fixed python dependency conflict. Ready to merge again. @drrtuy

**Comment by ottok** [comment]
Rebased on latest 10.5.

**Comment by ottok** [comment]
@robertbindar This has now been open for 18 days and it stalls other works since already fixes issues still pop up on the 10.5 branch making it harder to build/test/review further improvements. I cannot work e.g. on MDEV-14622 before this is merged.

**Comment by grooverdan** [comment]
While a certain amount of whitespace/spelling fixes can be accepted in a PR, this is excessive. The risk of merge conflicts in error messages and tests is increased as more complex aspects like c034cc6 need closer examination.

Can you please separate this into:
* whitespace + spelling and rebased
* single commit - Deb: On upgrades, stop both mysqld and mariadbd for backwards compat c034cc6
* rest of packaging changes (that I on first look though seem ok).

**Comment by ottok** [comment]
Thanks for the comments @grooverdan! I threw away the whitespace fixes, they are not that relevant and should not stall merging this one. The server stopping with both mysql and mariadb names is a critical bugfix and should go in ASAP as everybody upgrading from pre-10.5.4 will suffer from it.

**Comment by grooverdan** [comment]
Thanks @ottok. That was significantly easier to review. Looking forwards to further improvements.

**Pull request merged**
