### PR TITLE
MDEV-20053: set @sbindir@ for scripts

### PR DESCRIPTION
**Pull request by eworm-de**
- [x] *The Jira issue number for this PR is: MDEV-20053*

## Description
The script `galera_recovery` has a borked path, as `@sbindir@` is not set correctly.

## Release Notes
Fix the path to `mariadbd` executable in `galera_recovery`.

## How can this PR be tested?
All galera functionality should continue to work as expected without regressions.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by eworm-de** [comment]
Not sure about the correct branch... The jira issue lists 10.4, but that is no longer supported I think. Let me know if you want this to be rebased on whatever. This one (11.2) is the oldest that I care about atm.

**Comment by grooverdan** [comment]
10.5 would be good. Thanks.

**Comment by eworm-de** [comment]
Rebased and ticked the corresponding check mark.

**Review by grooverdan — APPROVED** [review]

**Comment by anson1014** [comment]
Nice catch!

**Review by anson1014 — APPROVED** [review]

**Comment by eworm-de** [comment]
So... Anybody wants to press the merge button?

**Pull request merged**
