### PR TITLE
MDEV-34754 packaging prep for oracular

### PR DESCRIPTION
**Pull request by grooverdan**
- [x] *The Jira issue number for this PR is: MDEV-______*

## Description

Once deb-autobake.sh knows about oracular the BB dependencies can be worked out.

## Release Notes

nothing yet, will be included in release notes once Oracular is released

## How can this PR be tested?

Once merged, a retrigger https://github.com/MariaDB/buildbot/actions/runs/10380263529/job/28739795984?pr=540 should build the worker required.
## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the latest MariaDB development branch.*
- [X] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by illuusio** [comment]
Is there Noble builder available?

**Comment by grooverdan** [comment]
chicken/egg problem - this is required first. - then the worker can pull the dependencies https://github.com/MariaDB/buildbot/pull/540

But for now, assuming the latest is ok.

**Comment by illuusio** [comment]
Ok I'll test with docker with oraculus snapshot.

**Comment by illuusio** [comment]
Patch itself works as expected but compiling fails so got to dig on that.

**Comment by illuusio** [comment]
This LGTM

**Pull request merged**
