### PR TITLE
MDEV-17386 cmake: fix ucontext detection

### PR DESCRIPTION
**Pull request by bkuhls**
On some archs uclibc does not provide the ucontext structure despite
providing ucontext.h, for details see
https://git.buildroot.net/buildroot/commit/?id=f1cbfeea95e6287c7a666aafc182ffa318eff262

This patch improves the detection of ucontext by making sure that
HAVE_UCONTEXT_H is only set when makecontext() was found.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>

### CODE REVIEW

**Comment by an3l** [comment]
Hi @bkuhls,

Thanks for your contribution.
Corresponding JIRA task: https://jira.mariadb.org/browse/MDEV-17386

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license (to update existing PR or to add a new comment bellow).

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Anel

**Comment by bkuhls** [comment]
I here by contribute the commit in this pull request under the BSD-new license terms.

**Comment by svoj** [comment]
Hi @bkuhls,

Could you elaborate how your patch works? I can't immediately see any functional difference compared to original code. That is both version would emit `HAVE_UCONTEXT_H` only if `makecontext` exists. Or do I miss something?

Thanks,
Sergey

**Comment by svoj** [comment]
Gosh, you're right! But then I'd prefer to have this fixed in 10.1. Either you resubmit, or I cherry-pick this change.

**Comment by bkuhls** [comment]
Patch for 10.1: https://github.com/MariaDB/server/pull/885

**Comment by bkuhls** [comment]
> But then I'd prefer to have this fixed in 10.1.

Hi, I am not familiar with the development flow of the project so I would like to ask whether this patch will make it into 10.3, 10.4 and/or master branch?
The reason for the question is whether the buildroot project needs to keep the patch for 10.3
https://git.buildroot.net/buildroot/tree/package/mariadb/0002-cmake-fix-ucontext-detection.patch
in its local tree for a longer period of time.

**Comment by an3l** [comment]
Hi, yes it will be merged on 10.3,10.4.

**Pull request closed without merging**
