### PR TITLE
MDEV-8553: Impossible where for a!=a, a<a, a>a

### PR DESCRIPTION
**Pull request by grooverdan**
As it turns out this is quite simple.

This tests an already retrieved value of eq_cmp_result to a constant. This is done under the condition that `a.f(a)` where f is a comparison operator (only these return `eq_cmp_result()) != Item::COND_OK`).

I submit this under the MCA.

### CODE REVIEW

**Comment by igorbabaev** [comment]
I applied the published patch to 10.4
Here's what I 
got:
MariaDB [test]> EXPLAIN SELECT * FROM t1 WHERE a<a;+------+-------------+-------+------+---------------+------+---------+------+------+------------------+
| id   | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra            |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------+
|    1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Impossible WHERE |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------+
MariaDB [test]> EXPLAIN SELECT * FROM t3 WHERE a<a+1;
+------+-------------+-------+------+---------------+------+---------+------+------+------------------+
| id   | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra            |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------+
|    1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Impossible WHERE |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------+

**Comment by grooverdan** [comment]
Odd, I'm getting 'Using where; Using index' for `a<a+1`. Does the type of `a` matter?
<pre>
SELECT VERSION();
VERSION()
10.4.1-MariaDB-log
CREATE TABLE t1 (a TINYINT NOT NULL, KEY(a));
INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
EXPLAIN SELECT * FROM t1 WHERE a!=a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	NULL	NULL	NULL	NULL	NULL	NULL	NULL	Impossible WHERE
EXPLAIN SELECT * FROM t1 WHERE a>a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	NULL	NULL	NULL	NULL	NULL	NULL	NULL	Impossible WHERE
EXPLAIN SELECT * FROM t1 WHERE a<a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	NULL	NULL	NULL	NULL	NULL	NULL	NULL	Impossible WHERE
EXPLAIN SELECT * FROM t1 WHERE a<a+0;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using where; Using index
EXPLAIN SELECT * FROM t1 WHERE a<a*2;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using where; Using index
EXPLAIN SELECT * FROM t1 WHERE a<a+1;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using where; Using index
EXPLAIN SELECT * FROM t1 WHERE NOT a=a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	NULL	NULL	NULL	NULL	NULL	NULL	NULL	Impossible WHERE
EXPLAIN SELECT * FROM t1 WHERE a=a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using index
EXPLAIN SELECT * FROM t1 WHERE a>=a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using index
EXPLAIN SELECT * FROM t1 WHERE a<=a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using index
EXPLAIN SELECT * FROM t1 WHERE a LIKE a;
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	NULL	a	1	NULL	5	Using where; Using index
<pre>

**Comment by igorbabaev** [comment]
Sorry, my mistake: misapplied the patch. Corrected and got:
MariaDB [test]> EXPLAIN SELECT * FROM t3 WHERE a<a+1;
+------+-------------+-------+-------+---------------+------+---------+------+-----
| id   | select_type | table | type  | possible_keys | key  | key_len | ref  | rows
+------+-------------+-------+-------+---------------+------+---------+------+-----
|    1 | SIMPLE      | t3    | index | NULL          | a    | 2       | NULL |    5
+------+-------------+-------+-------+---------------+------+---------+------+-----

Still  don't understand why 
return new (thd->mem_root) Item_bool(thd, false);
is needed.
Why   
    if (*cond_value == Item::COND_FALSE)
      return (COND*) 0;
is not enough?
(It would be almost in full accordance with MySQL code. The only difference would be the order of this check with the previous one)

**Comment by igorbabaev** [comment]
Ok I was of too good opinion on the MySQL code:
mysql> CREATE TABLE t1 (a TINYINT, KEY(a));
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
Query OK, 5 rows affected (0.05 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> EXPLAIN SELECT * FROM t1 WHERE a<a;
+----+-------------+-------+------------+-------+---------------+------+---------+------+------+----------+--------------------------+
| id | select_type | table | partitions | type  | possible_keys | key  | key_len | ref  | rows | filtered | Extra                    |
+----+-------------+-------+------------+-------+---------------+------+---------+------+------+----------+--------------------------+
|  1 | SIMPLE      | t1    | NULL       | index | NULL          | a    | 2       | NULL |    5 |    33.33 | Using where; Using index |
+----+-------------+-------+------------+-------+---------------+------+---------+------+------+----------+--------------------------+
As we can see the above query it behaves itself exactly as MariaDB does (no NOT NULL for 'a'  matters here).
Yout patch actually adds new optimization for both MariaDB and MySQL code (with a proper adjustment for MySQL) 
Please prepare comprehensive and full tests for this optimization and describe what it actually adds
I still would prefer something like this
if (cond_value == Item::COND_FALSE OR
   (!args[0]->maybe_null || functype() == Item_func::EQUAL_FUNC)
return (COND *) 0;

**Pull request closed without merging**
