### PR TITLE
MDEV-21140: make galera_recovery.sh work with fs.protected_regular = 1

### PR DESCRIPTION
**Pull request by patrakov**

### CODE REVIEW

**Comment by patrakov** [comment]
The build failures are there because I force-pushed without waiting, in order to fix the commit message.

**Comment by eworm-de** [comment]
Ha, I've wanted to merge this a long time ago in #1137...
Can we get the commit into 10.4, please?

**Comment by doka-ua** [comment]
Hi colleagues, any plans to backport it to 10.3? Ubuntu 20 will come with MariaDB 10.3 and fs.regular_protected = 1 by default (systemd 244), so by default Galera cluster will not work under Ubuntu 20.

**Comment by janlindstrom** [comment]
Merged to 10.1 on 241ac3f4873007cced7b547837f311da5c1261ce

**Pull request merged**
