### PR TITLE
MDEV-19837 Fix spelling mistake in comment

### PR DESCRIPTION
**Pull request by myguyy**

### CODE REVIEW

**Comment by an3l** [comment]
Hi @myguyy,
thanks for your contribution.
Can you please just rebase this patch, as well as PR#1375 for `5.5` as stated in jira?
Also I would suggest you to change name and mail
`git commit --amend --author="foo bar<foo@bar.org>"`
currently it is
```
From: myguyy <49013940+myguyy@users.noreply.github.com>
```

**Comment by myguyy** [comment]
Should I open a new PR for 5.5 instead?

**Comment by an3l** [comment]
No please, no need to open new PR. 
It should go something like this:
```
git checkout 5.5
git checkout -b myguy5.5 #create new branch on 5.5
git cherry-pick c2370ecf8b8a2c4eba # use PR1374
git cherry-pick 474618c05990992b0d9e570ca # use PR1375, there should be no errors
git rebase -i HEAD~2 # pick first, squash/or fixup last one
git push origin myguy5.5:10.5 -f # let's say we will use only this PR
```

**Comment by myguyy** [comment]
Oh whoops, I already opened a new PR. So sorry

**Pull request closed without merging**
