### PR TITLE
MDEV-11619: correct mtr to handle mtr --mem testcase1

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by dr-m** [comment]
Did I understand correctly that this change would make the option `--mem` work as it used to? That is, the only way to override the default directory path `/dev/shm` is to specify `--mem=directory` in a single argument? If so, I very much support this change.

**Comment by elenst** [comment]
@grooverdan , sorry, that's not enough. Try for example `perl ./mtr --mem plugin` on a release-like installation, where we actually have the `plugin` dir. And in general, it depends too much on not having a directory with the given name.

**Comment by grooverdan** [comment]
ouch, didn't know about the dir passed to mtr. Whether --mem=X is specified vs --mem X is hidden in the perl option processing libraries as both of these are parsed the same way by giving opt_mem the value.

**Comment by elenst** [comment]
@grooverdan , so, do we agree on returning to a pure flag and only handling the problem with `MTR_MEM` being ignored when `--mem` flag is present?

**Comment by grooverdan** [comment]
@elenst I haven't managed to find an incantation of `./mtr plugindir` that runs a plugin's test. If I did the testing of {plugindir}/mysql-test or {plugindir}/mysql-test/t or {plugindir}/mysql-test/t/*.test might be sufficient.

Tried:
<pre>
./mtr  metadata_lock_info
mysql-test-run: *** ERROR: Could not find 'metadata_lock_info' in
./mtr ../../mariadb-server/plugin/metadata_lock_info
mysql-test-run: *** ERROR: Illegal format of test name: ../../mariadb-server/plugin/metadata_lock_info
./mtr ../../mariadb-server/plugin/metadata_lock_info/t
mysql-test-run: *** ERROR: Illegal format of test name: ../../mariadb-server/plugin/metadata_lock_info/t
</pre>

In an installed version:
<pre>
$ pwd
/usr/local/mariadb-10.0/mysql-test
$ find plugin/metadata_lock_info -ls
    35314      4 drwxrwxr-x   3  root     root         4096 Feb 24 10:13 plugin/metadata_lock_info
    35315      4 drwxrwxr-x   4  root     root         4096 Feb 24 10:13 plugin/metadata_lock_info/metadata_lock_info
    35322      4 drwxrwxr-x   2  root     root         4096 Feb 24 10:13 plugin/metadata_lock_info/metadata_lock_info/r
    35325      4 -rw-rw-r--   1  root     root          652 Oct 11 10:30 plugin/metadata_lock_info/metadata_lock_info/r/table_metadata_lock.result
    35324      4 -rw-rw-r--   1  root     root          622 Oct 11 10:30 plugin/metadata_lock_info/metadata_lock_info/r/global_read_lock.result
    35323      4 -rw-rw-r--   1  root     root          659 Oct 11 10:30 plugin/metadata_lock_info/metadata_lock_info/r/user_lock.result
    35317      4 drwxrwxr-x   2  root     root         4096 Feb 24 10:13 plugin/metadata_lock_info/metadata_lock_info/t
    35318      4 -rw-rw-r--   1  root     root          399 Oct 11 10:30 plugin/metadata_lock_info/metadata_lock_info/t/global_read_lock.test
    35319      4 -rw-rw-r--   1  root     root          397 Aug 31 08:49 plugin/metadata_lock_info/metadata_lock_info/t/user_lock.test
    35320      4 -rw-rw-r--   1  root     root          427 Aug 31 08:49 plugin/metadata_lock_info/metadata_lock_info/t/table_metadata_lock.test
    35316      4 -rw-rw-r--   1  root     root           68 Aug 31 08:49 plugin/metadata_lock_info/metadata_lock_info/suite.opt
    35321      4 -rw-rw-r--   1  root     root          228 Aug 31 08:49 plugin/metadata_lock_info/metadata_lock_info/suite.pm
$ ./mtr plugin/meta_lock_info
mysql-test-run: *** ERROR: Could not find 'plugin/meta_lock_info'
./mtr plugin/metadata_lock_info/metadata_lock_info
mysql-test-run: *** ERROR: Could not find 'plugin/metadata_lock_info/metadata_lock_info'
</pre>

**Comment by elenst** [comment]
@grooverdan , when i said `perl ./mysql-test-run.pl --mem plugin`, I meant it literally, as `plugin`, not as `<plugin_name>`. There is a directory `plugin` in a release installation (as you can see yourself), and there is the test `plugin` in the `main` suite. So, after your change an attempt to run the test this way will make MTR to check for existence of `plugin` folder, which does exist, and thus it will wrongly assume that it's an argument of `--mem`. 

I suppose there is a technical possibility to hardcode it as an exception, but it becomes rather dirty, unreliable (as there might be more such coincidences in future) and, importantly, it seems pointless, because letting `--mem` to accept an optional value is not a part of the original fix, but an extension to provide the level of flexibility which is hardly ever needed. If one wants a specific path, there is `MTR_MEM` to set, if they want it to be chosen from default locations, it's already happening; the necessity to override MTR_MEM with a command-line option appears to be artificial, I can't really imagine the scenario when it would be really needed, can you suggest one?

**Comment by grooverdan** [comment]
Of course. Sorry.

The case I was trying to fix was the ignoring of the MTR_MEM value with --mem as below (which as you indicate doesn't need --mem to take an argument). The reason was so that travis can be fixed without waiting for @ottok to approve debian/* changes or for Travis to fix travis-ci/travis-ci/issues/7062 so the default shm is writeable.

<pre>
(cd mysql-test; MTR_MEM=/run/user/1000/  ./mtr --mem )
Logging: /home/dan/repos/mariadb-server/mysql-test/mysql-test-run.pl  --mem
vardir: /home/dan/repos/build-mariadb-server-10.2/mysql-test/var
Checking leftover processes...
Removing old var directory...
Creating var directory '/home/dan/repos/build-mariadb-server-10.2/mysql-test/var'...
 - symlinking 'var' to '/dev/shm/var_auto_IZih'
</pre>

I'll add a "plugin" exception to this PR and add another one removing the optional mem argument. Take which every one suits you.

**Comment by elenst** [comment]
Thank you. I'll take PR #320 , only there are a couple more lines to remove.

**Comment by grooverdan** [comment]
ack. Appreciate your help. Fixed #320 as requested.

**Pull request closed without merging**
