### PR TITLE
wsrep scripts fixes for working on OpenBSD

### PR DESCRIPTION
**Pull request by brad0**
- [ ] *The Jira issue number for this PR is: MDEV-______*

## Description
Fixes for working on OpenBSD.

## How can this PR be tested?

Issues were found via trying to utilize the script on OpenBSD and things not working due to differences in command operation.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by brad0** [comment]
Ping.

**Comment by grooverdan** [comment]
So what is being pushed to stderr for `hostname` and `tar` on OpenBSD?

**Comment by brad0** [comment]
```
fubar$ tar --help | grep -qw -F -- '--transform'
tar: unknown option -- -
usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
           [blocking-factor | archive | replstr] [-C directory] [-I file]
           [file ...]
       tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
           [-C directory] [-f archive] [-I file] [-s replstr] [file ...]

fubar$ tar --help 2>/dev/null | grep -qw -F -- '--transform'

fubar$ tar --version | grep -qw -E '^bsdtar'
tar: unknown option -- -
usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
           [blocking-factor | archive | replstr] [-C directory] [-I file]
           [file ...]
       tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
           [-C directory] [-f archive] [-I file] [-s replstr] [file ...]

fubar$ tar --version 2>/dev/null | grep -qw -E '^bsdtar'

fubar$ hostname -s
fubar

fubar$ hostname -f
hostname: unknown option -- f
usage: hostname [-s] [name-of-host]
fubar$ hostname -f 2>/dev/null
```

**Review by grooverdan — APPROVED** [review]

**Comment by brad0** [comment]
Ping.

**Pull request merged**
