### PR TITLE
MDEV-13549 Fix and re-enable test galera.MW-286

### PR DESCRIPTION
**Pull request by sciascid**

### CODE REVIEW

**Comment by sciascid** [comment]
The pull request makes the following changes:
* Re-enables test MW-286
* Minor fix in wsrep_thd_set_conflict_state to avoid spurious deadlock errors (see details in commit message)
* Fix "Wrong usage of mutex 'LOCK_wsrep_thd' and 'LOCK_thd_kill"

**Comment by janlindstrom** [comment]
Thank you for your contribution.

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Jan

**Comment by sciascid** [comment]
The changes in this pull request are contributed under the BSD-new license.

**Comment by sciascid** [comment]
I added an additional commit to the pull request to re-enable a few more tests, which I realized where also subject to the same "wrong usage of mutex" error.

**Pull request merged**
